export type {
  OperationEraAuditResult,
  OperationEraCandidate,
  OperationEraChipModel,
  OperationEraContentHook,
  OperationEraContentWeightHints,
  OperationEraContext,
  OperationEraDefinition,
  OperationEraEventFamilySignal,
  OperationEraFocusDomain,
  OperationEraId,
  OperationEraNonTerminalGuardResult,
  OperationEraPresentationModel,
  OperationEraCadence,
  OperationEraStatus,
  OperationEraTone,
  OperationEraUnlockAxis,
} from './operationEraTypes';

export {
  OPERATION_ERA_CADENCE_LABELS,
  OPERATION_ERA_CADENCES,
  OPERATION_ERA_CONTENT_HOOK_LABELS,
  OPERATION_ERA_CONTENT_HOOKS,
  OPERATION_ERA_FOCUS_DOMAIN_LABELS,
  OPERATION_ERA_FOCUS_DOMAINS,
  OPERATION_ERA_FORBIDDEN_COPY_TERMS,
  OPERATION_ERA_IS_TERMINAL_GAME_STATE,
  OPERATION_ERA_MAX_VISIBLE_CANDIDATES,
  OPERATION_ERA_MAX_VISIBLE_CHIPS,
  OPERATION_ERA_MIN_DAY_VISIBILITY,
  OPERATION_ERA_PILOT_MAX_DAY,
  OPERATION_ERA_PLAYER_COPY_RULES,
  OPERATION_ERA_REQUIRED_PERMISSION_IDS,
  OPERATION_ERA_SAFE_FALLBACK_SCORE,
  OPERATION_ERA_SCORE_RANGE,
  OPERATION_ERA_STATUS_LABELS,
  OPERATION_ERA_STATUSES,
} from './operationEraConstants';

export { OPERATION_ERA_CATALOG, getOperationEraCatalogEntry } from './operationEraCatalog';

export {
  assertOperationEraIsNonTerminal,
  buildOperationEraCandidate,
  buildOperationEraCandidates,
  buildOperationEraFallbackCandidate,
  calculateOperationEraReadinessScore,
  calculateOperationEraRelevanceScore,
  clampOperationEraScore,
  getOperationEraContentWeightHints,
  getOperationEraDefinition,
  getOperationEraDefinitions,
  getOperationEraDefinitionsByContentHook,
  getOperationEraDefinitionsByFocusDomain,
  getRecommendedOperationEras,
  resolveOperationEraStatus,
  shouldShowOperationEraPreview,
} from './operationEraModel';

export {
  buildOperationEraCadenceLabel,
  buildOperationEraCompactLine,
  buildOperationEraEmptyState,
  buildOperationEraFocusChips,
  buildOperationEraHookChips,
  buildOperationEraNonTerminalDisclaimer,
  buildOperationEraPresentationModel,
  buildOperationEraRecommendationLine,
  buildOperationEraReviewLine,
  buildOperationEraStatusLabel,
  buildOperationEraSummaryLine,
  buildOperationEraUnlockLine,
  collectOperationEraPlayerFacingCopy,
  operationEraCopyContainsForbiddenTerms,
} from './operationEraPresentation';
