import type { OperationEraDefinition } from './operationEraTypes';

export const OPERATION_ERA_CATALOG: readonly OperationEraDefinition[] = [
  {
    id: 'core_city_operations',
    title: 'Temel Şehir Operasyonları',
    shortLabel: 'Temel Operasyon',
    description:
      'Pilot sonrası açık uçlu ana operasyonu stabilize eden temel şehir operasyon dönemi.',
    flavorLine: 'Günlük operasyon ritmini güçlendirir; kariyer devam eder.',
    cadence: 'milestone_based',
    focusDomains: ['core_operations', 'operation_efficiency'],
    unlockAxes: ['rank_permission', 'authority', 'xp'],
    contentHooks: ['event_family', 'district_operation', 'report_review'],
    requiredPermissionId: 'operation_era_preview',
    minDay: 8,
    relatedEventFamilyDomains: ['generic_operation', 'district_balance', 'operation_era'],
    relatedDistrictOperationKinds: ['visible_service', 'resource_balance', 'operation_era_special'],
    relatedMapLayerIds: ['operation_era', 'event_family_signal'],
    relatedTeamSpecializationIds: ['field_response_team_core'],
    relatedVehicleMaintenanceKinds: ['preventive_check'],
    relatedContainerUpgradeKinds: ['capacity_rebalance'],
    isFutureOnly: false,
    playerFacingPriority: 95,
    tone: 'neutral',
    iconKey: 'business-outline',
  },
  {
    id: 'route_maintenance_era',
    title: 'Rota ve Bakım Dönemi',
    shortLabel: 'Rota / Bakım',
    description:
      'Araç rotası, bakım penceresi ve saha akışını öne çıkaran operasyon teması.',
    flavorLine: 'Rota baskısı ve bakım disiplinini aynı dönem odağına taşır.',
    cadence: 'weekly_theme',
    focusDomains: ['vehicle_route', 'operation_efficiency'],
    unlockAxes: ['rank_permission', 'resource_stability', 'map_layer'],
    contentHooks: [
      'active_task_route',
      'team_specialization',
      'vehicle_maintenance',
      'map_layer',
    ],
    requiredPermissionId: 'operation_era_preview',
    minDay: 8,
    relatedEventFamilyDomains: ['vehicle_route', 'resource_recovery', 'operation_era'],
    relatedDistrictOperationKinds: ['route_discipline', 'resource_balance'],
    relatedMapLayerIds: ['resource_pressure', 'active_task_route', 'operation_era'],
    relatedTeamSpecializationIds: [
      'technical_team_preventive_maintenance',
      'route_support_team_core',
    ],
    relatedVehicleMaintenanceKinds: [
      'route_load_rebalance',
      'preventive_check',
      'operation_era_maintenance',
    ],
    relatedContainerUpgradeKinds: ['transit_flow_support'],
    isFutureOnly: false,
    playerFacingPriority: 88,
    tone: 'strategic',
    iconKey: 'car-outline',
  },
  {
    id: 'container_network_era',
    title: 'Konteyner Ağı Gelişim Dönemi',
    shortLabel: 'Konteyner Ağı',
    description:
      'Mahalle temizlik baskısı ve konteyner ağı geliştirmesini odaklayan operasyon teması.',
    flavorLine: 'Konteyner ağı sinyalleri bu dönemde daha görünür hale gelir.',
    cadence: 'content_pack',
    focusDomains: ['container_network', 'district_trust'],
    unlockAxes: ['rank_permission', 'district_trust', 'map_layer'],
    contentHooks: ['container_network', 'district_operation', 'event_family', 'map_layer'],
    requiredPermissionId: 'container_network_upgrade_preview',
    minDay: 8,
    relatedEventFamilyDomains: ['container', 'resource_recovery', 'district_balance'],
    relatedDistrictOperationKinds: ['container_network', 'environmental_care'],
    relatedMapLayerIds: ['resource_pressure', 'district_trust', 'operation_era'],
    relatedTeamSpecializationIds: ['container_network_unit', 'technical_team_preventive_maintenance'],
    relatedVehicleMaintenanceKinds: ['preventive_check'],
    relatedContainerUpgradeKinds: [
      'visible_clean_point',
      'capacity_rebalance',
      'operation_era_upgrade',
      'environmental_sensitivity_point',
    ],
    isFutureOnly: false,
    playerFacingPriority: 86,
    tone: 'positive',
    iconKey: 'trash-outline',
  },
  {
    id: 'district_trust_era',
    title: 'Mahalle Güveni Dönemi',
    shortLabel: 'Mahalle Güveni',
    description:
      'Mahalle güveni, sosyal nabız ve görünür hizmet operasyonlarını öne çıkaran dönem.',
    flavorLine: 'Güven trendleri ve sosyal sinyaller bu dönemin ana odağıdır.',
    cadence: 'biweekly_theme',
    focusDomains: ['district_trust', 'social_pulse'],
    unlockAxes: ['district_trust', 'rank_permission', 'map_layer'],
    contentHooks: ['district_trust', 'social_pulse', 'district_operation', 'advisor_note'],
    requiredPermissionId: 'district_trust_preview',
    minDay: 8,
    relatedEventFamilyDomains: ['social', 'district_balance', 'resource_recovery'],
    relatedDistrictOperationKinds: ['public_trust', 'visible_service', 'district_memory_response'],
    relatedMapLayerIds: ['district_trust', 'district_memory', 'social_pulse', 'operation_era'],
    relatedTeamSpecializationIds: ['public_communication_team_core'],
    relatedVehicleMaintenanceKinds: ['preventive_check'],
    relatedContainerUpgradeKinds: ['visible_clean_point', 'school_residential_order'],
    isFutureOnly: false,
    playerFacingPriority: 84,
    tone: 'positive',
    iconKey: 'heart-outline',
  },
  {
    id: 'crisis_recovery_era',
    title: 'Kriz Hazırlığı ve Toparlanma Dönemi',
    shortLabel: 'Kriz / Toparlanma',
    description:
      'Kriz eşiği, toparlanma operasyonları ve ekip hazırlığını birleştiren operasyon teması.',
    flavorLine: 'Kriz sinyalleri yükseldiğinde toparlanma odağı netleşir; kariyer sürer.',
    cadence: 'milestone_based',
    focusDomains: ['crisis_recovery', 'personnel_team'],
    unlockAxes: ['crisis_control', 'rank_permission', 'resource_stability'],
    contentHooks: [
      'district_operation',
      'team_specialization',
      'vehicle_maintenance',
      'report_review',
    ],
    requiredPermissionId: 'operation_era_preview',
    minDay: 8,
    relatedEventFamilyDomains: ['crisis_adjacent', 'resource_recovery', 'personnel'],
    relatedDistrictOperationKinds: ['crisis_prevention', 'recovery_focus'],
    relatedMapLayerIds: ['crisis_watch', 'operation_era', 'active_task_route'],
    relatedTeamSpecializationIds: ['crisis_support_team_core', 'technical_team_preventive_maintenance'],
    relatedVehicleMaintenanceKinds: ['emergency_stabilization', 'operation_era_maintenance'],
    relatedContainerUpgradeKinds: ['recovery_cleanup_focus'],
    isFutureOnly: false,
    playerFacingPriority: 82,
    tone: 'crisis_watch',
    iconKey: 'shield-outline',
  },
  {
    id: 'city_growth_preview_era',
    title: 'Şehir Gelişimi Hazırlığı',
    shortLabel: 'Şehir Gelişimi',
    description:
      'City Development System için ileride açılacak şehir gelişimi operasyon teması önizlemesi.',
    flavorLine: 'Uzun vadeli şehir gelişimi bu dönemde hazırlık odağı olarak izlenir.',
    cadence: 'future_live_ops',
    focusDomains: ['city_development', 'content_expansion'],
    unlockAxes: ['future_system', 'content_pack', 'map_layer'],
    contentHooks: ['city_development', 'map_layer', 'container_network', 'district_operation'],
    requiredPermissionId: 'city_development_preview',
    minDay: 12,
    relatedEventFamilyDomains: ['authority_milestone', 'operation_era', 'district_balance'],
    relatedDistrictOperationKinds: ['operation_era_special', 'visible_service'],
    relatedMapLayerIds: ['city_development', 'operation_era', 'district_trust'],
    relatedTeamSpecializationIds: ['field_response_team_core'],
    relatedVehicleMaintenanceKinds: ['future_upgrade'],
    relatedContainerUpgradeKinds: ['future_smart_network', 'operation_era_upgrade'],
    isFutureOnly: true,
    playerFacingPriority: 70,
    tone: 'growth',
    iconKey: 'trending-up-outline',
  },
  {
    id: 'social_pulse_era',
    title: 'Sosyal Nabız Dönemi',
    shortLabel: 'Sosyal Nabız',
    description:
      'Sosyal nabız, mahalle güveni ve danışman notlarını öne çıkaran operasyon teması.',
    flavorLine: 'Sosyal sinyaller bu dönemde operasyon gündemini şekillendirir.',
    cadence: 'weekly_theme',
    focusDomains: ['social_pulse', 'district_trust'],
    unlockAxes: ['rank_permission', 'district_trust'],
    contentHooks: ['social_pulse', 'event_family', 'advisor_note', 'report_review'],
    requiredPermissionId: 'operation_era_preview',
    minDay: 8,
    relatedEventFamilyDomains: ['social', 'district_balance'],
    relatedDistrictOperationKinds: ['public_trust', 'visible_service'],
    relatedMapLayerIds: ['social_pulse', 'district_trust', 'operation_era'],
    relatedTeamSpecializationIds: ['public_communication_team_core'],
    relatedVehicleMaintenanceKinds: ['preventive_check'],
    relatedContainerUpgradeKinds: ['visible_clean_point'],
    isFutureOnly: false,
    playerFacingPriority: 80,
    tone: 'watch',
    iconKey: 'chatbubbles-outline',
  },
] as const;

const DEFINITIONS_BY_ID = new Map(
  OPERATION_ERA_CATALOG.map((definition) => [definition.id, definition]),
);

export function getOperationEraCatalogEntry(id: string): OperationEraDefinition | undefined {
  return DEFINITIONS_BY_ID.get(id);
}
