import type {
  CreviaOperationEraPreviewDefinition,
  CreviaOperationEraPreviewKind,
} from './operationEraRuntimePreviewTypes';

export const OPERATION_ERA_RUNTIME_PREVIEW_PILOT_MAX_DAY = 7;
export const OPERATION_ERA_RUNTIME_PREVIEW_MIN_DAY = 8;
export const OPERATION_ERA_RUNTIME_PREVIEW_COMPACT_COPY_MAX = 72;
export const OPERATION_ERA_RUNTIME_PREVIEW_MOBILE_COPY_MAX = 96;

export const OPERATION_ERA_RUNTIME_PREVIEW_FORBIDDEN_COPY_TERMS: readonly string[] = [
  'sezon finali',
  '14 gün bitti',
  'oyun sonu',
  'premium',
  'satın al',
  'satin al',
  'kilitli',
  'paywall',
  'panik',
  'alarm',
  'çöktü',
  'coktu',
  'başarısız',
  'basarisiz',
  'haftalık canlı etkinlik başladı',
  'canlı etkinlik başladı',
  'gerçek zamanlı takip',
  'canlı gps',
] as const;

export const OPERATION_ERA_RUNTIME_PREVIEW_PANIC_TERMS: readonly string[] = [
  'panik',
  'alarm',
  'kriz patladı',
  'çöktü',
  'felaket',
  'kontrol kaybedildi',
] as const;

export const OPERATION_ERA_RUNTIME_PREVIEW_SCORE_WEIGHTS = {
  routePressure: 22,
  containerPressure: 22,
  socialTrustPressure: 20,
  crisisWatch: 20,
  resourceFatigue: 18,
  districtOperationAction: 12,
  recentImprovement: 14,
  activeRoute: 10,
  storyChainBias: 8,
  contentPackCoverage: 6,
  postPilotCareer: 10,
  freshnessPenalty: 18,
  fallbackBase: 8,
} as const;

export const OPERATION_ERA_CONTENT_PACK_IDS = {
  districtPackOne: 'district_pack_one',
  vehicleRoutePackOne: 'vehicle_route_pack_one',
  containerEnvironmentPackOne: 'container_environment_pack_one',
  socialTrustPackOne: 'social_trust_pack_one',
  crisisAdjacentPackOne: 'crisis_adjacent_pack_one',
} as const;

export const OPERATION_ERA_RUNTIME_PREVIEW_KINDS: readonly CreviaOperationEraPreviewKind[] = [
  'route_efficiency_era',
  'container_recovery_era',
  'social_trust_era',
  'crisis_prevention_era',
  'district_development_era',
  'resource_balance_era',
  'visible_service_era',
  'open_operation_career_era',
] as const;

export const OPERATION_ERA_RUNTIME_PREVIEW_DEFINITIONS: Record<
  CreviaOperationEraPreviewKind,
  CreviaOperationEraPreviewDefinition
> = {
  route_efficiency_era: {
    kind: 'route_efficiency_era',
    label: 'Rota Verimliliği Dönemi',
    shortLabel: 'Rota Verimliliği',
    tone: 'gold',
    relatedDomains: ['vehicle_route', 'personnel', 'resource_pressure'],
    relatedDistricts: ['sanayi', 'istasyon'],
    relatedContentPacks: [OPERATION_ERA_CONTENT_PACK_IDS.vehicleRoutePackOne],
    recommendedMapLayerFocus: 'operation',
    recommendedAdvisorFocus: 'route_tempo',
    recommendedStoryChainKinds: ['route_pressure_chain', 'operation_followup_chain'],
    recommendedVariantBias: ['carry_over', 'resource_fatigue', 'improved'],
    reportIntent: 'Gün sonu rota temposu ve araç dengesi takip teması olarak okunur.',
    hubIntent: 'Bugünkü ana yön: rota verimliliği ve saha akış dengesi.',
    profileIntent: 'Açık uçlu kariyerde rota verimliliği dönemi izleniyor.',
    mapIntent: 'Seçili mahallede rota baskısı için kısa takip teması.',
    maxCopyLength: OPERATION_ERA_RUNTIME_PREVIEW_MOBILE_COPY_MAX,
    forbiddenTerms: OPERATION_ERA_RUNTIME_PREVIEW_FORBIDDEN_COPY_TERMS,
  },
  container_recovery_era: {
    kind: 'container_recovery_era',
    label: 'Konteyner Toparlanma Dönemi',
    shortLabel: 'Konteyner Toparlanma',
    tone: 'mint',
    relatedDomains: ['container_network', 'container', 'recovery'],
    relatedDistricts: ['cumhuriyet', 'yesilvadi'],
    relatedContentPacks: [OPERATION_ERA_CONTENT_PACK_IDS.containerEnvironmentPackOne],
    recommendedMapLayerFocus: 'memory',
    recommendedAdvisorFocus: 'container_recovery',
    recommendedStoryChainKinds: ['container_recovery_chain', 'district_recovery_chain'],
    recommendedVariantBias: ['recovery', 'carry_over', 'comeback'],
    reportIntent: 'Konteyner ağı toparlanması gün sonunda takip teması olarak yansır.',
    hubIntent: 'Dönemsel operasyon odağı: konteyner ağı toparlanma penceresi.',
    profileIntent: 'Kariyer vitrininde konteyner toparlanma teması görünür.',
    mapIntent: 'Mahallede konteyner izi için sakin toparlanma teması.',
    maxCopyLength: OPERATION_ERA_RUNTIME_PREVIEW_MOBILE_COPY_MAX,
    forbiddenTerms: OPERATION_ERA_RUNTIME_PREVIEW_FORBIDDEN_COPY_TERMS,
  },
  social_trust_era: {
    kind: 'social_trust_era',
    label: 'Sosyal Güven Onarım Dönemi',
    shortLabel: 'Güven Onarımı',
    tone: 'teal',
    relatedDomains: ['social_trust', 'district_trust', 'social'],
    relatedDistricts: ['cumhuriyet', 'merkez'],
    relatedContentPacks: [OPERATION_ERA_CONTENT_PACK_IDS.socialTrustPackOne],
    recommendedMapLayerFocus: 'trust',
    recommendedAdvisorFocus: 'social_trust',
    recommendedStoryChainKinds: ['social_trust_chain', 'visible_service_chain'],
    recommendedVariantBias: ['recovery', 'district_trust', 'reward'],
    reportIntent: 'Sosyal güven onarımı gün sonu raporunda takip teması olarak kalır.',
    hubIntent: 'Bugünkü ana yön: sosyal güven onarımı ve görünür cevap.',
    profileIntent: 'Açık uçlu kariyerde güven onarım dönemi öne çıkar.',
    mapIntent: 'Mahalle güveni için sakin onarım takip teması.',
    maxCopyLength: OPERATION_ERA_RUNTIME_PREVIEW_MOBILE_COPY_MAX,
    forbiddenTerms: OPERATION_ERA_RUNTIME_PREVIEW_FORBIDDEN_COPY_TERMS,
  },
  crisis_prevention_era: {
    kind: 'crisis_prevention_era',
    label: 'Kriz Önleyici Takip Dönemi',
    shortLabel: 'Önleyici Takip',
    tone: 'watch',
    relatedDomains: ['crisis_adjacent', 'crisis_watch', 'prevention'],
    relatedDistricts: ['sanayi', 'istasyon'],
    relatedContentPacks: [OPERATION_ERA_CONTENT_PACK_IDS.crisisAdjacentPackOne],
    recommendedMapLayerFocus: 'operation',
    recommendedAdvisorFocus: 'crisis_watch',
    recommendedStoryChainKinds: ['crisis_watch_chain', 'operation_followup_chain'],
    recommendedVariantBias: ['crisis_adjacent', 'improved', 'recovery'],
    reportIntent: 'Önleyici takip penceresi gün sonunda sakin biçimde not edilir.',
    hubIntent: 'Şehir operasyon ritmi: kriz önleyici takip teması aktif.',
    profileIntent: 'Kariyer vitrininde önleyici takip dönemi görünür.',
    mapIntent: 'Kritik mahallede önleyici takip penceresi teması.',
    maxCopyLength: OPERATION_ERA_RUNTIME_PREVIEW_MOBILE_COPY_MAX,
    forbiddenTerms: OPERATION_ERA_RUNTIME_PREVIEW_FORBIDDEN_COPY_TERMS,
  },
  district_development_era: {
    kind: 'district_development_era',
    label: 'Mahalle Gelişim Dönemi',
    shortLabel: 'Mahalle Gelişimi',
    tone: 'recovery',
    relatedDomains: ['district_memory', 'recovery', 'city_development'],
    relatedDistricts: ['merkez', 'yesilvadi', 'cumhuriyet'],
    relatedContentPacks: [OPERATION_ERA_CONTENT_PACK_IDS.districtPackOne],
    recommendedMapLayerFocus: 'memory',
    recommendedAdvisorFocus: 'district_growth',
    recommendedStoryChainKinds: ['district_recovery_chain', 'visible_service_chain'],
    recommendedVariantBias: ['recovery', 'comeback', 'reward'],
    reportIntent: 'Mahalle gelişim izi gün sonunda takip teması olarak okunur.',
    hubIntent: 'Dönemsel operasyon odağı: mahalle gelişim ve toparlanma.',
    profileIntent: 'Açık uçlu kariyerde mahalle gelişim teması izleniyor.',
    mapIntent: 'Mahalle gelişim izi için kısa takip teması.',
    maxCopyLength: OPERATION_ERA_RUNTIME_PREVIEW_MOBILE_COPY_MAX,
    forbiddenTerms: OPERATION_ERA_RUNTIME_PREVIEW_FORBIDDEN_COPY_TERMS,
  },
  resource_balance_era: {
    kind: 'resource_balance_era',
    label: 'Kaynak Dengeleme Dönemi',
    shortLabel: 'Kaynak Dengesi',
    tone: 'gold',
    relatedDomains: ['resource_pressure', 'resource_fatigue', 'personnel'],
    relatedDistricts: ['sanayi', 'istasyon', 'merkez'],
    relatedContentPacks: [
      OPERATION_ERA_CONTENT_PACK_IDS.vehicleRoutePackOne,
      OPERATION_ERA_CONTENT_PACK_IDS.districtPackOne,
    ],
    recommendedMapLayerFocus: 'operation',
    recommendedAdvisorFocus: 'resource_balance',
    recommendedStoryChainKinds: ['resource_fatigue_chain', 'route_pressure_chain'],
    recommendedVariantBias: ['resource_fatigue', 'carry_over', 'comeback'],
    reportIntent: 'Kaynak dengesi gün sonunda şehir operasyon ritmi olarak yansır.',
    hubIntent: 'Bugünkü ana yön: kaynak dengeleme ve ekip temposu.',
    profileIntent: 'Kariyer vitrininde kaynak dengeleme dönemi görünür.',
    mapIntent: 'Kaynak baskısı için sakin denge takip teması.',
    maxCopyLength: OPERATION_ERA_RUNTIME_PREVIEW_MOBILE_COPY_MAX,
    forbiddenTerms: OPERATION_ERA_RUNTIME_PREVIEW_FORBIDDEN_COPY_TERMS,
  },
  visible_service_era: {
    kind: 'visible_service_era',
    label: 'Görünür Hizmet Dönemi',
    shortLabel: 'Görünür Hizmet',
    tone: 'teal',
    relatedDomains: ['visible_service', 'district_trust', 'operation_era'],
    relatedDistricts: ['merkez'],
    relatedContentPacks: [
      OPERATION_ERA_CONTENT_PACK_IDS.districtPackOne,
      OPERATION_ERA_CONTENT_PACK_IDS.socialTrustPackOne,
    ],
    recommendedMapLayerFocus: 'trust',
    recommendedAdvisorFocus: 'visible_service',
    recommendedStoryChainKinds: ['visible_service_chain', 'social_trust_chain'],
    recommendedVariantBias: ['improved', 'reward', 'district_trust'],
    reportIntent: 'Görünür hizmet teması gün sonunda olumlu takip notu bırakır.',
    hubIntent: 'Dönemsel operasyon odağı: görünür hizmet ve vatandaş algısı.',
    profileIntent: 'Açık uçlu kariyerde görünür hizmet dönemi öne çıkar.',
    mapIntent: 'Görünür hizmet izi için kısa takip teması.',
    maxCopyLength: OPERATION_ERA_RUNTIME_PREVIEW_MOBILE_COPY_MAX,
    forbiddenTerms: OPERATION_ERA_RUNTIME_PREVIEW_FORBIDDEN_COPY_TERMS,
  },
  open_operation_career_era: {
    kind: 'open_operation_career_era',
    label: 'Açık Uçlu Operasyon Kariyeri',
    shortLabel: 'Ana Operasyon',
    tone: 'neutral',
    relatedDomains: ['core_operations', 'operation_era', 'district_balance'],
    relatedDistricts: ['merkez', 'cumhuriyet', 'sanayi', 'istasyon', 'yesilvadi'],
    relatedContentPacks: Object.values(OPERATION_ERA_CONTENT_PACK_IDS),
    recommendedMapLayerFocus: 'base',
    recommendedAdvisorFocus: 'career_rhythm',
    recommendedStoryChainKinds: ['operation_followup_chain'],
    recommendedVariantBias: ['carry_over', 'improved', 'recovery'],
    reportIntent: 'Açık uçlu operasyon kariyeri gün sonunda genel takip teması olarak kalır.',
    hubIntent: 'Şehir operasyon ritmi: açık uçlu ana operasyon kariyeri devam ediyor.',
    profileIntent: 'Profil vitrininde açık uçlu operasyon kariyeri teması görünür.',
    mapIntent: 'Genel operasyon teması için kısa takip notu.',
    maxCopyLength: OPERATION_ERA_RUNTIME_PREVIEW_MOBILE_COPY_MAX,
    forbiddenTerms: OPERATION_ERA_RUNTIME_PREVIEW_FORBIDDEN_COPY_TERMS,
  },
};

export function getOperationEraRuntimePreviewDefinition(
  kind: CreviaOperationEraPreviewKind,
): CreviaOperationEraPreviewDefinition {
  return OPERATION_ERA_RUNTIME_PREVIEW_DEFINITIONS[kind];
}
