import type { EventCard, EventDecision } from '@/core/models/EventCard';
import type { Neighborhood } from '@/core/models/Neighborhood';

/** Ucuz / hızlı / kalıcı karar şablonu */
function decisions(
  slow: Omit<EventDecision, 'id' | 'style'> & { id: string },
  fast: Omit<EventDecision, 'id' | 'style'> & { id: string },
  permanent: Omit<EventDecision, 'id' | 'style'> & { id: string },
): EventDecision[] {
  return [
    { ...slow, style: 'balanced' },
    { ...fast, style: 'bold', recommended: true },
    { ...permanent, style: 'cautious' },
  ];
}

export const DAY1_NEIGHBORHOODS: Neighborhood[] = [
  {
    id: 'merkez',
    name: 'Merkez Mahallesi',
    cleanliness: 58,
    trust: 52,
    longTermNeglect: 38,
  },
  {
    id: 'pazar',
    name: 'Pazar Yeri Bölgesi',
    cleanliness: 52,
    trust: 48,
    longTermNeglect: 42,
  },
  {
    id: 'yesilpark',
    name: 'Yeşilpark Mahallesi',
    cleanliness: 60,
    trust: 55,
    longTermNeglect: 35,
  },
  {
    id: 'sanayi',
    name: 'Sanayi Çevresi',
    cleanliness: 48,
    trust: 45,
    longTermNeglect: 48,
  },
  {
    id: 'yeni-konut',
    name: 'Yeni Konutlar',
    cleanliness: 55,
    trust: 50,
    longTermNeglect: 40,
  },
];

export const DAY1_ACTIVE_EVENT_IDS = [
  'container-overflow',
  'trash-collection-delay',
  'park-trash-buildup',
] as const;

export const DAY1_EVENT_POOL: EventCard[] = [
  {
    id: 'container-overflow',
    title: 'Konteyner Taşması',
    category: 'Temizlik',
    riskLevel: 'high',
    district: 'Merkez Mahallesi',
    neighborhoodId: 'merkez',
    contextTag: 'Acil müdahale',
    urgencyHours: 2,
    delayHint: true,
    filterTags: ['urgent', 'crisis'],
    description:
      'Ana cadde üzerindeki konteyner taştı. Yoğun yaya trafiği ve görünürlük yüksek.',
    previewEffects: {
      publicSatisfaction: -8,
      risk: 12,
      xp: 20,
      budget: -8500,
    },
    decisions: decisions(
      {
        id: 'container-route',
        title: 'Normal rotaya ekle',
        description: 'Maliyet düşük; çözüm gecikebilir, tekrar şikayet riski var.',
        effects: {
          publicSatisfaction: 4,
          budget: -1500,
          morale: -2,
          risk: 5,
          xp: 8,
        },
      },
      {
        id: 'container-crew',
        title: 'Ek temizlik ekibi gönder',
        description: 'Hızlı müdahale; bütçe ve personel yükü artar.',
        effects: {
          publicSatisfaction: 12,
          budget: -8000,
          morale: -5,
          risk: -12,
          xp: 15,
        },
        costs: { staffHours: 8, vehicleUsage: 1 },
      },
      {
        id: 'container-plan',
        title: 'Konteyner ve dezenfeksiyon planı',
        description: 'Kalıcı çözüm; bütçe yüksek, mahalle güveni güçlenir.',
        effects: {
          publicSatisfaction: 10,
          budget: -12000,
          morale: -2,
          risk: -18,
          trust: 8,
          cleanliness: 10,
          xp: 12,
        },
        costs: { budget: 12000, staffHours: 4 },
      },
    ),
  },
  {
    id: 'trash-collection-delay',
    title: 'Çöp Toplama Gecikmesi',
    category: 'Temizlik',
    riskLevel: 'high',
    district: 'Pazar Yeri Bölgesi',
    neighborhoodId: 'pazar',
    contextTag: 'Vatandaş şikayeti',
    urgencyHours: 4,
    filterTags: ['urgent'],
    description: 'Pazar sonrası atık birikimi şikayetlere dönüştü. Görünürlük yüksek.',
    previewEffects: { publicSatisfaction: -6, risk: 10, xp: 18 },
    decisions: decisions(
      {
        id: 'delay-next-route',
        title: 'Sonraki planlı rotada topla',
        description: 'Bütçe korunur; memnuniyet sınırlı artar, risk sürer.',
        effects: {
          publicSatisfaction: 2,
          budget: -800,
          morale: 1,
          risk: 6,
          xp: 6,
        },
      },
      {
        id: 'delay-extra-run',
        title: 'Ek sefer düzenle',
        description: 'Aynı gün ek araç; hızlı toparlanma, maliyet artar.',
        effects: {
          publicSatisfaction: 10,
          budget: -5500,
          morale: -4,
          risk: -10,
          xp: 14,
        },
        costs: { vehicleUsage: 2, staffHours: 6 },
      },
      {
        id: 'delay-bins',
        title: 'Geçici ek konteyner noktası',
        description: 'Kalıcı kapasite artışı; kurulum maliyeti yüksek.',
        effects: {
          publicSatisfaction: 8,
          budget: -9000,
          morale: -1,
          risk: -14,
          cleanliness: 8,
          trust: 6,
          xp: 11,
        },
      },
    ),
  },
  {
    id: 'park-trash-buildup',
    title: 'Park İçi Çöp Birikimi',
    category: 'Temizlik',
    riskLevel: 'medium',
    district: 'Yeşilpark Mahallesi',
    neighborhoodId: 'yesilpark',
    contextTag: 'Saha bildirimi',
    urgencyHours: 6,
    filterTags: ['urgent'],
    description: 'Park girişinde çöp yığınları oluştu. Aile kullanımı yoğun.',
    previewEffects: { publicSatisfaction: -5, risk: 6, xp: 14 },
    decisions: decisions(
      {
        id: 'park-volunteer',
        title: 'Gönüllü destekle topla',
        description: 'Düşük maliyet; sonuç orta, tekrar riski kalır.',
        effects: {
          publicSatisfaction: 5,
          budget: -500,
          morale: 2,
          risk: 2,
          xp: 7,
        },
      },
      {
        id: 'park-crew',
        title: 'Saha ekibi yönlendir',
        description: 'Hızlı temizlik; personel yorulur.',
        effects: {
          publicSatisfaction: 9,
          budget: -3500,
          morale: -3,
          risk: -8,
          xp: 12,
        },
        costs: { staffHours: 5 },
      },
      {
        id: 'park-recycle',
        title: 'Ayrıştırma noktası kur',
        description: 'Uzun vadeli düzen; yatırım maliyeti yüksek.',
        effects: {
          publicSatisfaction: 7,
          budget: -7500,
          morale: -1,
          risk: -12,
          cleanliness: 9,
          trust: 5,
          xp: 10,
        },
      },
    ),
  },
  {
    id: 'market-litter',
    title: 'Pazar Yeri Kirliliği',
    category: 'Temizlik',
    riskLevel: 'medium',
    district: 'Pazar Yeri Bölgesi',
    neighborhoodId: 'pazar',
    contextTag: 'Haftalık yoğunluk',
    urgencyHours: 8,
    description: 'Pazar kalıntıları caddeye taştı. Esnaflar tepki gösteriyor.',
    previewEffects: { publicSatisfaction: -4, risk: 5, xp: 12 },
    decisions: decisions(
      {
        id: 'market-sweep-later',
        title: 'Akşam planlı süpürme',
        description: 'Maliyet düşük; sabah şikayetleri sürebilir.',
        effects: {
          publicSatisfaction: 3,
          budget: -1200,
          morale: 0,
          risk: 4,
          xp: 6,
        },
      },
      {
        id: 'market-morning',
        title: 'Sabah erken ek ekip',
        description: 'Görünürlük yüksek bölgede hızlı temizlik.',
        effects: {
          publicSatisfaction: 8,
          budget: -4000,
          morale: -3,
          risk: -6,
          xp: 11,
        },
      },
      {
        id: 'market-bins',
        title: 'Ek pazar konteynerleri',
        description: 'Kapasite artışı; kurulum ve bakım maliyeti.',
        effects: {
          publicSatisfaction: 6,
          budget: -8500,
          morale: -1,
          risk: -10,
          cleanliness: 7,
          trust: 4,
          xp: 9,
        },
      },
    ),
  },
  {
    id: 'odor-complaint',
    title: 'Koku Şikayeti',
    category: 'Temizlik',
    riskLevel: 'high',
    district: 'Sanayi Çevresi',
    neighborhoodId: 'sanayi',
    contextTag: 'Sağlık riski',
    urgencyHours: 5,
    filterTags: ['crisis'],
    description: 'Atık birikiminden koku şikayetleri arttı. Basın ilgisi olası.',
    previewEffects: { publicSatisfaction: -7, risk: 11, xp: 16 },
    decisions: decisions(
      {
        id: 'odor-vent',
        title: 'Havalandırma ve kısmi toplama',
        description: 'Geçici rahatlama; sorun kısmen kalır.',
        effects: {
          publicSatisfaction: 4,
          budget: -2000,
          morale: -2,
          risk: 3,
          xp: 7,
        },
      },
      {
        id: 'odor-flush',
        title: 'Dezenfeksiyon ekibi',
        description: 'Hızlı etki; kimyasal ve iş gücü maliyeti.',
        effects: {
          publicSatisfaction: 11,
          budget: -6000,
          morale: -4,
          risk: -11,
          xp: 13,
        },
      },
      {
        id: 'odor-contract',
        title: 'Firma ile temizlik sözleşmesi',
        description: 'Kalıcı hizmet; yüksek bütçe, risk düşer.',
        effects: {
          publicSatisfaction: 9,
          budget: -11000,
          morale: 0,
          risk: -16,
          trust: 6,
          xp: 10,
        },
      },
    ),
  },
  {
    id: 'missing-container',
    title: 'Konteyner Eksikliği',
    category: 'Temizlik',
    riskLevel: 'medium',
    district: 'Yeni Konutlar',
    neighborhoodId: 'yeni-konut',
    contextTag: 'Kapasite',
    urgencyHours: 10,
    description: 'Yeni konut hattında yeterli konteyner yok. Düzensiz döküm var.',
    previewEffects: { publicSatisfaction: -3, risk: 5, xp: 10 },
    decisions: decisions(
      {
        id: 'missing-wait',
        title: 'Mevcut rotayı sürdür',
        description: 'Maliyet minimum; şikayet devam edebilir.',
        effects: {
          publicSatisfaction: 1,
          budget: -500,
          morale: 1,
          risk: 5,
          xp: 5,
        },
      },
      {
        id: 'missing-deliver',
        title: 'Geçici konteyner getir',
        description: 'Hızlı kapasite; lojistik maliyeti.',
        effects: {
          publicSatisfaction: 7,
          budget: -4500,
          morale: -2,
          risk: -7,
          xp: 10,
        },
      },
      {
        id: 'missing-install',
        title: 'Kalıcı konteyner altyapısı',
        description: 'Yatırım yüksek; uzun vadeli çözüm.',
        effects: {
          publicSatisfaction: 8,
          budget: -10000,
          morale: -1,
          risk: -13,
          cleanliness: 8,
          trust: 7,
          xp: 11,
        },
      },
    ),
  },
  {
    id: 'school-perimeter',
    title: 'Okul Çevresi Temizliği',
    category: 'Temizlik',
    riskLevel: 'medium',
    district: 'Yeşilpark Mahallesi',
    neighborhoodId: 'yesilpark',
    contextTag: 'Veli baskısı',
    urgencyHours: 7,
    description: 'Okul çıkış saatinde çöp ve yaprak birikimi. Veliler endişeli.',
    previewEffects: { publicSatisfaction: -4, risk: 6, xp: 12 },
    decisions: decisions(
      {
        id: 'school-schedule',
        title: 'Okul bitimine planlı ekip',
        description: 'Rutin müdahale; düşük maliyet.',
        effects: {
          publicSatisfaction: 5,
          budget: -1800,
          morale: -1,
          risk: 0,
          xp: 8,
        },
      },
      {
        id: 'school-now',
        title: 'Hemen ek süpürme',
        description: 'Aynı gün temizlik; personel yükü artar.',
        effects: {
          publicSatisfaction: 10,
          budget: -3800,
          morale: -4,
          risk: -8,
          xp: 12,
        },
      },
      {
        id: 'school-garden',
        title: 'Okul çevresi yeşil alan bakımı',
        description: 'Kalıcı düzen; bakım sözleşmesi maliyeti.',
        effects: {
          publicSatisfaction: 8,
          budget: -8000,
          morale: -1,
          risk: -11,
          cleanliness: 6,
          trust: 5,
          xp: 10,
        },
      },
    ),
  },
  {
    id: 'main-street-pile',
    title: 'Ana Cadde Çöp Birikimi',
    category: 'Temizlik',
    riskLevel: 'critical',
    district: 'Merkez Mahallesi',
    neighborhoodId: 'merkez',
    contextTag: 'Kritik görünürlük',
    urgencyHours: 3,
    filterTags: ['urgent', 'crisis'],
    description: 'Ana cadde üzerinde büyük hacimli birikim. Trafik ve görünürlük çok yüksek.',
    previewEffects: {
      publicSatisfaction: -10,
      risk: 14,
      xp: 22,
      budget: -9000,
    },
    decisions: decisions(
      {
        id: 'main-night',
        title: 'Gece vardiyasına ertele',
        description: 'Bütçe korunur; sabah şikayet riski yüksek.',
        effects: {
          publicSatisfaction: 0,
          budget: -1000,
          morale: 2,
          risk: 8,
          xp: 5,
        },
      },
      {
        id: 'main-now',
        title: 'Acil müdahale ekipleri',
        description: 'Anında temizlik; yüksek maliyet ve yorgunluk.',
        effects: {
          publicSatisfaction: 14,
          budget: -9500,
          morale: -6,
          risk: -15,
          xp: 16,
        },
        costs: { staffHours: 10, vehicleUsage: 2 },
      },
      {
        id: 'main-street-plan',
        title: 'Cadde temizlik planı revizyonu',
        description: 'Kalıcı sıklık artışı; yatırım gerekir.',
        effects: {
          publicSatisfaction: 11,
          budget: -11500,
          morale: -2,
          risk: -20,
          cleanliness: 9,
          trust: 8,
          xp: 13,
        },
      },
    ),
  },
];
