import {
  PILOT_DISTRICT_IDS,
  type PilotDistrictId,
} from '@/core/models/DistrictProfile';
import type {
  EventCard,
  EventDecision,
  EventDecisionEffect,
} from '@/core/models/EventCard';
import type { PilotDayTheme } from '@/core/models/PilotDayPlan';
import type { PilotEventType } from '@/core/models/PilotDayPlan';

const ALL_DISTRICTS: PilotDistrictId[] = [...PILOT_DISTRICT_IDS];

const DISTRICT_LABELS: Record<PilotDistrictId, string> = {
  central: 'Merkez Pilot Bölge',
  cumhuriyet: 'Cumhuriyet Mahallesi',
  industrial_market: 'Sanayi & Pazar Bölgesi',
};

type PilotEventBase = {
  id: string;
  title: string;
  description: string;
  day: number;
  theme: PilotDayTheme;
  eventType: PilotEventType;
  districtIds: PilotDistrictId[];
  districtLabel: string;
  decisions: EventDecision[];
  riskLevel?: EventCard['riskLevel'];
  category?: string;
  contextTag?: string;
  urgencyHours?: number;
  previewEffects?: EventCard['previewEffects'];
  conditions?: EventCard['conditions'];
  priority?: number;
  fallback?: boolean;
  filterTags?: EventCard['filterTags'];
  delayHint?: boolean;
};

function pilotEvent(base: PilotEventBase): EventCard {
  return {
    id: base.id,
    title: base.title,
    category: base.category ?? 'Pilot Operasyon',
    riskLevel: base.riskLevel ?? 'medium',
    district: base.districtLabel,
    description: base.description,
    contextTag: base.contextTag ?? 'Pilot senaryo',
    urgencyHours: base.urgencyHours ?? 4,
    decisions: base.decisions,
    previewEffects: base.previewEffects ?? {
      publicSatisfaction: -5,
      risk: 8,
      xp: 16,
    },
    day: base.day,
    theme: base.theme,
    districtIds: base.districtIds,
    eventType: base.eventType,
    conditions: base.conditions,
    priority: base.priority,
    fallback: base.fallback,
    filterTags: base.filterTags,
    delayHint: base.delayHint,
  };
}

function learningDay1Decisions(prefix: string): EventDecision[] {
  return [
    {
      id: `${prefix}-fast`,
      title: 'Hızlı Müdahale',
      description: 'Ekibi hemen yönlendir; görünür sonuç, yüksek maliyet.',
      style: 'bold',
      recommended: true,
      decisionStyle: 'fast',
      setFlags: { day1ResponseStyle: 'fast' },
      resultText: 'Saha hızlı müdahale etti; mahalle güveni kısa vadede arttı.',
      effects: {
        publicSatisfaction: 10,
        budget: -6500,
        morale: -5,
        risk: -10,
        xp: 14,
      },
      costs: { staffHours: 7, vehicleUsage: 1 },
      xpReward: 14,
    },
    {
      id: `${prefix}-planned`,
      title: 'Planlı Rotayı Bekle',
      description: 'Mevcut plana sadık kal; bütçe korunur, gecikme riski var.',
      style: 'balanced',
      decisionStyle: 'planned',
      setFlags: { day1ResponseStyle: 'planned' },
      delayHint: true,
      resultText: 'Sorun planlı rotaya alındı; şikayet riski sürüyor.',
      effects: {
        publicSatisfaction: 3,
        budget: -1200,
        morale: 1,
        risk: 6,
        xp: 8,
      },
      xpReward: 8,
    },
    {
      id: `${prefix}-partial`,
      title: 'Kısmi Müdahale',
      description: 'Geçici toparlama; dengeli maliyet, kalıcı risk bırakabilir.',
      style: 'cautious',
      decisionStyle: 'partial',
      setFlags: { day1ResponseStyle: 'partial' },
      resultText: 'Kısmi müdahale yapıldı; tablo stabil ama tam çözülmedi.',
      effects: {
        publicSatisfaction: 6,
        budget: -3200,
        morale: -2,
        risk: 0,
        xp: 10,
      },
      costs: { staffHours: 3 },
      xpReward: 10,
    },
  ];
}

function complaintDay2Decisions(
  prefix: string,
  opts: {
    fast: { title: string; description: string; effects: EventDecisionEffect };
    planned: { title: string; description: string; effects: EventDecisionEffect };
    partial: { title: string; description: string; effects: EventDecisionEffect };
  },
): EventDecision[] {
  return [
    {
      id: `${prefix}-fast`,
      title: opts.fast.title,
      description: opts.fast.description,
      style: 'bold',
      recommended: true,
      decisionStyle: 'fast',
      effects: opts.fast.effects,
    },
    {
      id: `${prefix}-planned`,
      title: opts.planned.title,
      description: opts.planned.description,
      style: 'balanced',
      decisionStyle: 'planned',
      effects: opts.planned.effects,
    },
    {
      id: `${prefix}-partial`,
      title: opts.partial.title,
      description: opts.partial.description,
      style: 'cautious',
      decisionStyle: 'partial',
      effects: opts.partial.effects,
    },
  ];
}

function butterflyDay6Decisions(prefix: string): EventDecision[] {
  return [
    {
      id: `${prefix}-close`,
      title: 'Acil Kapat',
      description: 'Tüm kaynakları bu hatta topla; hızlı kapanış, yorgunluk artar.',
      style: 'bold',
      decisionStyle: 'fast',
      effects: {
        publicSatisfaction: 8,
        budget: -7000,
        morale: -6,
        risk: -12,
        xp: 12,
      },
      costs: { staffHours: 8, vehicleUsage: 1 },
    },
    {
      id: `${prefix}-communicate`,
      title: 'İletişimle Yönet',
      description: 'Mahalleyle açık iletişim; güven artar, operasyon gecikebilir.',
      style: 'balanced',
      decisionStyle: 'communication',
      effects: {
        publicSatisfaction: 6,
        budget: -2000,
        morale: -1,
        risk: -4,
        trust: 6,
        xp: 10,
      },
    },
    {
      id: `${prefix}-promise`,
      title: 'Kalıcı Çözüm Sözü Ver',
      description: 'Kaynak ayır ve taahhüt ver; bütçe yükü, uzun vadeli rahatlama.',
      style: 'cautious',
      decisionStyle: 'permanent',
      delayHint: true,
      effects: {
        publicSatisfaction: 5,
        budget: -9000,
        morale: -3,
        risk: -14,
        trust: 8,
        xp: 11,
      },
      costs: { budget: 9000, staffHours: 4 },
    },
  ];
}

const pilotEventsList: EventCard[] = [
  // —— Gün 1: Learning ——
  pilotEvent({
    id: 'central_day1_learning_main_street',
    title: 'Ana Caddede İlk Müdahale',
    description:
      'Ece: Ana caddede taşan konteyner yoğun yaya trafiğinde görünür. İlk izlenim kritik.',
    day: 1,
    theme: 'learning',
    eventType: 'waste',
    districtIds: ['central'],
    districtLabel: DISTRICT_LABELS.central,
    contextTag: 'Görünür hizmet',
    riskLevel: 'high',
    urgencyHours: 3,
    filterTags: ['urgent'],
    fallback: true,
    previewEffects: { publicSatisfaction: -6, risk: 10, xp: 18, budget: -5000 },
    decisions: learningDay1Decisions('central-d1'),
  }),
  pilotEvent({
    id: 'cumhuriyet_day1_learning_complaint',
    title: 'Koku Şikayeti İlk Sinyal',
    description:
      'Hüseyin Muhtar: Konut sokaklarından koku şikayeti geldi. Sosyal baskı hızlı yükselir.',
    day: 1,
    theme: 'learning',
    eventType: 'citizen_complaint',
    districtIds: ['cumhuriyet'],
    districtLabel: DISTRICT_LABELS.cumhuriyet,
    contextTag: 'Şikayet sinyali',
    riskLevel: 'high',
    urgencyHours: 2,
    filterTags: ['urgent', 'crisis'],
    fallback: true,
    previewEffects: { publicSatisfaction: -8, risk: 12, xp: 18 },
    decisions: learningDay1Decisions('cumhuriyet-d1').map((d) => ({
      ...d,
      effects: {
        ...d.effects,
        publicSatisfaction: d.effects.publicSatisfaction + 1,
        risk: d.id.includes('planned') ? d.effects.risk + 2 : d.effects.risk,
      },
    })),
  }),
  pilotEvent({
    id: 'industrial_market_day1_learning_market_waste',
    title: 'Pazar Alanında Yoğun Atık',
    description:
      'Nermin Usta: Pazar sonrası atık yığıldı. Rota ve personel baskısı yüksek.',
    day: 1,
    theme: 'learning',
    eventType: 'market',
    districtIds: ['industrial_market'],
    districtLabel: DISTRICT_LABELS.industrial_market,
    contextTag: 'Operasyon baskısı',
    riskLevel: 'high',
    urgencyHours: 3,
    filterTags: ['urgent'],
    fallback: true,
    previewEffects: { publicSatisfaction: -7, risk: 11, xp: 17, budget: -6000 },
    decisions: learningDay1Decisions('industrial-d1').map((d) => ({
      ...d,
      effects: {
        ...d.effects,
        morale: d.effects.morale - 1,
        budget: d.effects.budget - 500,
      },
      costs:
        d.id.includes('fast') || d.id.includes('partial')
          ? { staffHours: 8, vehicleUsage: 1 }
          : d.costs,
    })),
  }),

  // —— Gün 2: Complaint ——
  pilotEvent({
    id: 'central_day2_complaint_shopkeepers',
    title: 'Esnaftan Sabah Temizliği Talebi',
    description:
      'Esnaf sabah yoğunluğu öncesi ana cadde temizliği istiyor. Görünürlük yüksek.',
    day: 2,
    theme: 'complaint',
    eventType: 'market',
    districtIds: ['central'],
    districtLabel: DISTRICT_LABELS.central,
    contextTag: 'Esnaf baskısı',
    riskLevel: 'medium',
    urgencyHours: 4,
    fallback: true,
    previewEffects: { publicSatisfaction: -5, risk: 7, xp: 15 },
    decisions: complaintDay2Decisions('central-d2', {
      fast: {
        title: 'Esnaf Bölgesini Öncele',
        description: 'Ana caddeye ek ekip; hızlı sonuç, maliyet artar.',
        effects: {
          publicSatisfaction: 11,
          budget: -5500,
          morale: -4,
          risk: -9,
          xp: 13,
        },
      },
      planned: {
        title: 'Normal Plana Sadık Kal',
        description: 'Rota değişmez; bütçe korunur, sabah şikayeti sürebilir.',
        effects: {
          publicSatisfaction: 2,
          budget: -800,
          morale: 1,
          risk: 5,
          xp: 7,
        },
      },
      partial: {
        title: 'Kısmi Temizlik + Açıklama',
        description: 'Sınırlı müdahale ve bilgilendirme; dengeli tablo.',
        effects: {
          publicSatisfaction: 6,
          budget: -2800,
          morale: -1,
          risk: 1,
          xp: 9,
        },
      },
    }),
  }),
  pilotEvent({
    id: 'cumhuriyet_day2_complaint_muhtar_pressure',
    title: 'Muhtardan İlk Uyarı',
    description:
      'Hüseyin Muhtar: Aynı sokaktan tekrar şikayet gelirse mahalle grubu hareketlenir.',
    day: 2,
    theme: 'complaint',
    eventType: 'citizen_complaint',
    districtIds: ['cumhuriyet'],
    districtLabel: DISTRICT_LABELS.cumhuriyet,
    contextTag: 'Muhtar uyarısı',
    riskLevel: 'high',
    urgencyHours: 3,
    filterTags: ['urgent'],
    fallback: true,
    previewEffects: { publicSatisfaction: -7, risk: 11, xp: 16 },
    decisions: complaintDay2Decisions('cumhuriyet-d2', {
      fast: {
        title: 'Muhtarla Koordineli Çözüm',
        description: 'Ortak plan; güven artar, uygulama biraz gecikebilir.',
        effects: {
          publicSatisfaction: 9,
          budget: -3500,
          morale: -2,
          risk: -6,
          trust: 7,
          xp: 12,
        },
      },
      planned: {
        title: 'Ekibi Doğrudan Yönlendir',
        description: 'Hızlı saha müdahalesi; sosyal baskı düşer, ekip yorulur.',
        effects: {
          publicSatisfaction: 10,
          budget: -6000,
          morale: -5,
          risk: -10,
          xp: 13,
        },
      },
      partial: {
        title: 'Önce Kontrol Ekibi Gönder',
        description: 'Durum tespiti; maliyet düşük, çözüm gecikir.',
        effects: {
          publicSatisfaction: 4,
          budget: -1500,
          morale: 0,
          risk: 4,
          xp: 8,
        },
      },
    }),
  }),
  pilotEvent({
    id: 'industrial_market_day2_complaint_sidewalk_load',
    title: 'Pazar Yüklemesi Kaldırımı Kapattı',
    description:
      'Murat Abi: Yükleme kaldırımı kapattı. Esnaf ve yaya geçişi aksıyor.',
    day: 2,
    theme: 'complaint',
    eventType: 'sidewalk',
    districtIds: ['industrial_market'],
    districtLabel: DISTRICT_LABELS.industrial_market,
    contextTag: 'Kaldırım / zabıta',
    riskLevel: 'medium',
    urgencyHours: 5,
    fallback: true,
    previewEffects: { publicSatisfaction: -6, risk: 8, xp: 14 },
    decisions: complaintDay2Decisions('industrial-d2', {
      fast: {
        title: 'Hızlı Denetim',
        description: 'Anında müdahale; operasyon hızlanır, esnaf gerilir.',
        effects: {
          publicSatisfaction: 8,
          budget: -4200,
          morale: -3,
          risk: -7,
          xp: 11,
        },
      },
      planned: {
        title: 'Esnafla Süreli Uzlaşma',
        description: 'Süre tanı; bütçe korunur, tekrar riski kalır.',
        effects: {
          publicSatisfaction: 4,
          budget: -1000,
          morale: 1,
          risk: 5,
          xp: 7,
        },
      },
      partial: {
        title: 'Kısmi Yönlendirme',
        description: 'Geçiş koridoru aç; tam çözüm ertelenir.',
        effects: {
          publicSatisfaction: 5,
          budget: -2200,
          morale: -1,
          risk: 2,
          xp: 9,
        },
      },
    }),
  }),

  // —— Gün 3: Resource ——
  pilotEvent({
    id: 'central_day3_resource_market_staff_conflict',
    title: 'Pazar Hazırlığı ve Ekip Çakışması',
    description:
      'Nermin Usta: Pazar hazırlığı ile ana cadde temizliği aynı saate denk geldi. Ekip sayısı sınırlı.',
    day: 3,
    theme: 'resource',
    eventType: 'market',
    districtIds: ['central'],
    districtLabel: DISTRICT_LABELS.central,
    contextTag: 'Kaynak çakışması',
    riskLevel: 'high',
    urgencyHours: 4,
    filterTags: ['urgent'],
    priority: 8,
    fallback: false,
    previewEffects: { publicSatisfaction: -5, risk: 10, xp: 15, budget: -4000 },
    decisions: [
      {
        id: 'central-d3-market-first',
        title: 'Pazar Alanını Öncele',
        description: 'Esnaf memnuniyeti önce; ana cadde görünürlüğü ikinci planda.',
        style: 'bold',
        recommended: true,
        decisionStyle: 'fast',
        setFlags: { centralDay3ResourceChoice: 'market' },
        resultText: 'Pazar hattı güçlendirildi; esnaf rahatladı ama ekip yoruldu.',
        effects: {
          publicSatisfaction: 7,
          budget: -2800,
          morale: -6,
          risk: -3,
          trust: 5,
          xp: 12,
        },
        costs: { staffHours: 6 },
      },
      {
        id: 'central-d3-street-first',
        title: 'Ana Caddeyi Öncele',
        description: 'Görünür hizmet öncelikli; pazar hazırlığı gecikebilir.',
        style: 'balanced',
        decisionStyle: 'planned',
        setFlags: { centralDay3ResourceChoice: 'street' },
        resultText: 'Ana cadde toparlandı; pazar tarafında gerginlik sürdü.',
        effects: {
          publicSatisfaction: 5,
          budget: -1800,
          morale: -2,
          risk: 5,
          xp: 10,
        },
        costs: { staffHours: 4 },
      },
      {
        id: 'central-d3-split-teams',
        title: 'Ekipleri İkiye Böl',
        description: 'İki işi de orta seviyede çöz; kapasite ince bıçak gibi.',
        style: 'cautious',
        decisionStyle: 'partial',
        setFlags: { centralDay3ResourceChoice: 'split' },
        resultText: 'İki hat da idare edildi; hiçbiri tam rahatlamadı.',
        effects: {
          publicSatisfaction: 4,
          budget: -3200,
          morale: -4,
          risk: 1,
          xp: 11,
        },
        costs: { staffHours: 5, vehicleUsage: 1 },
      },
    ],
  }),
  pilotEvent({
    id: 'cumhuriyet_day3_resource_complaint_stack',
    title: 'Şikayetler Üst Üste Biniyor',
    description:
      'Hüseyin Muhtar: Birkaç küçük şikayet aynı anda geldi. Hepsini hızlı çözmek ekibi yorabilir.',
    day: 3,
    theme: 'resource',
    eventType: 'citizen_complaint',
    districtIds: ['cumhuriyet'],
    districtLabel: DISTRICT_LABELS.cumhuriyet,
    contextTag: 'Şikayet yığılması',
    riskLevel: 'high',
    urgencyHours: 3,
    filterTags: ['urgent', 'crisis'],
    priority: 8,
    fallback: false,
    previewEffects: { publicSatisfaction: -6, risk: 11, xp: 16 },
    decisions: [
      {
        id: 'cumhuriyet-d3-visible-first',
        title: 'En Görünür Şikayeti Öncele',
        description: 'Sosyal baskı yüksek olan hattı öne al; diğerleri bekler.',
        style: 'bold',
        recommended: true,
        decisionStyle: 'fast',
        resultText: 'Görünür şikayet kapatıldı; arka sıradaki talepler birikti.',
        effects: {
          publicSatisfaction: 6,
          budget: -2400,
          morale: -5,
          risk: -2,
          trust: 4,
          xp: 12,
        },
        costs: { staffHours: 5 },
      },
      {
        id: 'cumhuriyet-d3-muhtar-priority',
        title: 'Muhtarla Öncelik Listesi Yap',
        description: 'Mahalle güveni korunur; uygulama biraz gecikir.',
        style: 'balanced',
        decisionStyle: 'communication',
        resultText: 'Öncelik listesi netleşti; ekip daha kontrollü ilerledi.',
        effects: {
          publicSatisfaction: 5,
          budget: -1500,
          morale: 1,
          risk: 3,
          trust: 7,
          xp: 10,
        },
      },
      {
        id: 'cumhuriyet-d3-all-field',
        title: 'Tüm Ekibi Sahaya Sür',
        description: 'Kısa sürede çok iş; moral ve bütçe baskısı artar.',
        style: 'risky',
        decisionStyle: 'risk',
        resultText: 'Saha yoğun geçti; şikayetler düştü ama ekip tükendi.',
        effects: {
          publicSatisfaction: 8,
          budget: -4200,
          morale: -7,
          risk: -5,
          xp: 13,
        },
        costs: { staffHours: 9, vehicleUsage: 1 },
      },
    ],
  }),
  pilotEvent({
    id: 'industrial_market_day3_resource_vehicle_delay',
    title: 'Araç Gecikmesi Rotayı Sıkıştırdı',
    description:
      'Murat Abi: Araç gecikmesi pazar çevresi atık planını sıkıştırdı. Manuel müdahale gündeme geldi.',
    day: 3,
    theme: 'resource',
    eventType: 'vehicle',
    districtIds: ['industrial_market'],
    districtLabel: DISTRICT_LABELS.industrial_market,
    contextTag: 'Rota baskısı',
    riskLevel: 'high',
    urgencyHours: 4,
    filterTags: ['urgent'],
    priority: 8,
    fallback: false,
    previewEffects: { publicSatisfaction: -5, risk: 12, xp: 15, budget: -3500 },
    decisions: [
      {
        id: 'industrial-d3-backup-vehicle',
        title: 'Yedek Araç Talep Et',
        description: 'Operasyon sürer; bütçe ve lojistik yükü artar.',
        style: 'bold',
        recommended: true,
        decisionStyle: 'planned',
        resultText: 'Yedek araç geldi; rota normale döndü ama maliyet arttı.',
        effects: {
          publicSatisfaction: 6,
          budget: -4500,
          morale: 2,
          risk: -6,
          xp: 12,
        },
        costs: { budget: 2000, vehicleUsage: 2 },
      },
      {
        id: 'industrial-d3-shorten-route',
        title: 'Rotayı Kısalt',
        description: 'Bugünkü plan daralır; bazı noktalar yarına kalır.',
        style: 'balanced',
        decisionStyle: 'resource_saving',
        resultText: 'Rota kısaldı; bütçe korundu, tekrar riski arttı.',
        effects: {
          publicSatisfaction: 2,
          budget: -1200,
          morale: -1,
          risk: 7,
          xp: 9,
        },
      },
      {
        id: 'industrial-d3-manual-start',
        title: 'Manuel Müdahale Başlat',
        description: 'Ekip bekletilmeden sahaya iner; yorgunluk belirgin.',
        style: 'cautious',
        decisionStyle: 'fast',
        resultText: 'Manuel müdahale işi kurtardı; personel morali düştü.',
        effects: {
          publicSatisfaction: 5,
          budget: -2600,
          morale: -6,
          risk: -3,
          xp: 11,
        },
        costs: { staffHours: 7 },
      },
    ],
  }),
  pilotEvent({
    id: 'shared_day3_resource_pressure',
    title: 'Ekip Temposu Yükseliyor',
    description:
      'Kemal: İlk iki günün yükü personelde. Vardiya ve rota baskısı artıyor.',
    day: 3,
    theme: 'resource',
    eventType: 'staff',
    districtIds: ALL_DISTRICTS,
    districtLabel: 'Pilot Bölge',
    contextTag: 'Kaynak baskısı',
    riskLevel: 'medium',
    urgencyHours: 6,
    fallback: true,
    priority: 1,
    previewEffects: { publicSatisfaction: -4, risk: 9, xp: 14 },
    decisions: [
      {
        id: 'd3-overtime',
        title: 'Ek Vardiya Aç',
        description: 'Kapasite artır; maliyet ve moral baskısı.',
        style: 'bold',
        decisionStyle: 'risk',
        setFlags: { staffOverloaded: true },
        effects: {
          publicSatisfaction: 7,
          budget: -8000,
          morale: -6,
          risk: -8,
          xp: 12,
        },
        costs: { staffHours: 12 },
      },
      {
        id: 'd3-defer',
        title: 'Düşük Öncelikli İşi Ertele',
        description: 'Bütçe korunur; bazı hatlar gecikir.',
        style: 'balanced',
        decisionStyle: 'resource_saving',
        setFlags: { staffOverloaded: false },
        delayHint: true,
        effects: {
          publicSatisfaction: -2,
          budget: -500,
          morale: 2,
          risk: 8,
          xp: 7,
        },
      },
      {
        id: 'd3-split',
        title: 'İş Yükünü Bölüştür',
        description: 'Ekipler arası denge; orta maliyet, orta sonuç.',
        style: 'cautious',
        decisionStyle: 'planned',
        setFlags: { staffOverloaded: false },
        effects: {
          publicSatisfaction: 4,
          budget: -3500,
          morale: -2,
          risk: 2,
          xp: 10,
        },
        costs: { staffHours: 5 },
      },
    ],
  }),

  // —— Gün 4: Social pressure ——
  pilotEvent({
    id: 'central_day4_social_shopkeeper_group',
    title: 'Esnaf Grubunda Görünür Hizmet Tartışması',
    description:
      'Deniz: Merkez esnaf grubunda sabah temizliğinin yetersiz göründüğü konuşuluyor.',
    day: 4,
    theme: 'social_pressure',
    eventType: 'social_media',
    districtIds: ['central'],
    districtLabel: DISTRICT_LABELS.central,
    contextTag: 'Esnaf algısı',
    riskLevel: 'high',
    urgencyHours: 3,
    filterTags: ['crisis'],
    priority: 8,
    fallback: false,
    previewEffects: { publicSatisfaction: -7, risk: 11, xp: 16 },
    decisions: [
      {
        id: 'central-d4-visible-clean',
        title: 'Önce Sahada Görünür Temizlik Yap',
        description: 'Fiziksel görünürlük; ekip ve bütçe yükü artar.',
        style: 'bold',
        recommended: true,
        decisionStyle: 'fast',
        resultText: 'Sahada görünür müdahale grup gündemini yumuşattı.',
        effects: {
          publicSatisfaction: 8,
          budget: -3800,
          morale: -4,
          risk: -5,
          xp: 13,
        },
        costs: { staffHours: 5 },
      },
      {
        id: 'central-d4-trader-brief',
        title: 'Esnaf Grubuna Kısa Bilgilendirme Gönder',
        description: 'İletişim öncelikli; sahada gecikme riski var.',
        style: 'balanced',
        decisionStyle: 'communication',
        resultText: 'Kısa bilgilendirme algıyı düşürdü; saha biraz geride kaldı.',
        effects: {
          publicSatisfaction: 5,
          budget: -900,
          morale: 0,
          risk: 4,
          trust: 6,
          xp: 10,
        },
      },
      {
        id: 'central-d4-keep-plan',
        title: 'Mevcut Plana Sadık Kal',
        description: 'Operasyon ritmi korunur; sosyal baskı sürebilir.',
        style: 'cautious',
        decisionStyle: 'planned',
        resultText: 'Plan korundu; esnaf grubunda hafif gerginlik sürdü.',
        effects: {
          publicSatisfaction: 1,
          budget: -600,
          morale: 2,
          risk: 6,
          xp: 7,
        },
      },
    ],
  }),
  pilotEvent({
    id: 'cumhuriyet_day4_social_neighborhood_posts',
    title: 'Mahalle Grubunda Fotoğraflar Yayılıyor',
    description:
      'Deniz: Cumhuriyet’te aynı noktadaki sorunun fotoğrafı mahalle grubunda hızla paylaşılıyor.',
    day: 4,
    theme: 'social_pressure',
    eventType: 'social_media',
    districtIds: ['cumhuriyet'],
    districtLabel: DISTRICT_LABELS.cumhuriyet,
    contextTag: 'Sosyal baskı',
    riskLevel: 'critical',
    urgencyHours: 2,
    filterTags: ['crisis', 'urgent'],
    priority: 8,
    fallback: false,
    previewEffects: { publicSatisfaction: -8, risk: 13, xp: 17 },
    decisions: [
      {
        id: 'cumhuriyet-d4-fix-and-explain',
        title: 'Hemen Çözüm + Kısa Açıklama',
        description: 'Hem saha hem iletişim; maliyet ve tempo yüksek.',
        style: 'bold',
        recommended: true,
        decisionStyle: 'fast',
        resultText: 'Çözüm ve açıklama birlikte gitti; paylaşımlar yavaşladı.',
        effects: {
          publicSatisfaction: 7,
          budget: -4000,
          morale: -5,
          risk: -6,
          trust: 5,
          xp: 14,
        },
        costs: { staffHours: 6 },
      },
      {
        id: 'cumhuriyet-d4-muhtar-calm',
        title: 'Muhtar Üzerinden Sakinleştir',
        description: 'Mahalle güveni korunur; teknik çözüm biraz gecikir.',
        style: 'balanced',
        decisionStyle: 'communication',
        resultText: 'Muhtar arabuluculuğu gerginliği kesti; çözüm yarın sabaha kaldı.',
        effects: {
          publicSatisfaction: 4,
          budget: -1200,
          morale: 0,
          risk: 5,
          trust: 8,
          xp: 10,
        },
      },
      {
        id: 'cumhuriyet-d4-control-team',
        title: 'Önce Kontrol Ekibi Gönder',
        description: 'Durum tespiti önce; kamuoyu kısa süre beklemiş olur.',
        style: 'cautious',
        decisionStyle: 'partial',
        resultText: 'Kontrol ekibi sahayı netleştirdi; tam müdahale öğleden sonra.',
        effects: {
          publicSatisfaction: 3,
          budget: -2000,
          morale: -2,
          risk: 3,
          xp: 9,
        },
        costs: { staffHours: 3 },
      },
    ],
  }),
  pilotEvent({
    id: 'industrial_market_day4_social_low_visibility_risk',
    title: 'Görünmeyen Risk Büyüyor',
    description:
      'Ece: Sosyal medya sessiz ama esnaf gecikmeleri not alıyor. Operasyon riski arka planda büyüyor.',
    day: 4,
    theme: 'social_pressure',
    eventType: 'vehicle',
    districtIds: ['industrial_market'],
    districtLabel: DISTRICT_LABELS.industrial_market,
    contextTag: 'Sessiz risk',
    riskLevel: 'medium',
    urgencyHours: 5,
    priority: 8,
    fallback: false,
    previewEffects: { publicSatisfaction: -3, risk: 10, xp: 14, budget: -2000 },
    decisions: [
      {
        id: 'industrial-d4-risk-route',
        title: 'Riskli Rotayı Öne Çek',
        description: 'Operasyon riski düşer; planlanan işler kayar.',
        style: 'bold',
        recommended: true,
        decisionStyle: 'planned',
        resultText: 'Riskli hat öne alındı; esnaf planı bir gün kaydı.',
        effects: {
          publicSatisfaction: 4,
          budget: -2800,
          morale: -3,
          risk: -7,
          trust: 4,
          xp: 11,
        },
        costs: { vehicleUsage: 1, staffHours: 4 },
      },
      {
        id: 'industrial-d4-schedule-notice',
        title: 'Esnafa Zaman Planı Bildir',
        description: 'Güven artar; bugünkü kapasite değişmez.',
        style: 'balanced',
        decisionStyle: 'communication',
        resultText: 'Zaman planı paylaşıldı; gerginlik azaldı ama işler sürüyor.',
        effects: {
          publicSatisfaction: 3,
          budget: -800,
          morale: 1,
          risk: 2,
          trust: 6,
          xp: 9,
        },
      },
      {
        id: 'industrial-d4-keep-route',
        title: 'Mevcut Rotayı Bozma',
        description: 'Kısa vadede tempo korunur; risk birikebilir.',
        style: 'risky',
        decisionStyle: 'risk',
        resultText: 'Rota korundu; kayıt altına alınan gecikmeler rapora işlendi.',
        effects: {
          publicSatisfaction: 0,
          budget: -500,
          morale: 2,
          risk: 8,
          xp: 6,
        },
      },
    ],
  }),
  pilotEvent({
    id: 'shared_day4_social_pressure',
    title: 'Mahalle Grubunda Gündem',
    description:
      'Deniz: Hizmet aksaklığı mahalle grubunda konuşuluyor. Algı hızla yayılabilir.',
    day: 4,
    theme: 'social_pressure',
    eventType: 'social_media',
    districtIds: ALL_DISTRICTS,
    districtLabel: 'Pilot Bölge',
    contextTag: 'Sosyal baskı',
    riskLevel: 'high',
    urgencyHours: 3,
    filterTags: ['crisis'],
    fallback: true,
    priority: 1,
    previewEffects: { publicSatisfaction: -8, risk: 12, xp: 17 },
    decisions: [
      {
        id: 'd4-field-first',
        title: 'Önce Sahada Çöz, Sonra Duyur',
        description: 'Sessiz müdahale; güven artar, iletişim gecikir.',
        style: 'bold',
        decisionStyle: 'fast',
        setFlags: { publicNarrative: 'controlled', socialCrisisStarted: false },
        effects: {
          publicSatisfaction: 9,
          budget: -5000,
          morale: -4,
          risk: -9,
          xp: 13,
        },
      },
      {
        id: 'd4-quick-comms',
        title: 'Hızlı Açıklama + Ekip',
        description: 'Şeffaf iletişim ve yönlendirme; dengeli maliyet.',
        style: 'balanced',
        decisionStyle: 'communication',
        setFlags: { publicNarrative: 'transparent', socialCrisisStarted: false },
        effects: {
          publicSatisfaction: 7,
          budget: -3500,
          morale: -2,
          risk: -5,
          trust: 5,
          xp: 11,
        },
      },
      {
        id: 'd4-silent-ops',
        title: 'Sessiz Kal, Operasyonu Aksatma',
        description: 'Operasyon sürer; algı riski artabilir.',
        style: 'risky',
        decisionStyle: 'risk',
        setFlags: { publicNarrative: 'silent', socialCrisisStarted: true },
        effects: {
          publicSatisfaction: -3,
          budget: -800,
          morale: 2,
          risk: 10,
          xp: 6,
        },
      },
    ],
  }),

  // —— Gün 5: Opportunity ——
  pilotEvent({
    id: 'shared_day5_opportunity_staff_recovery',
    title: 'Ekip Toparlanma Fırsatı',
    description:
      'Kemal: Ekip son günlerde yorulduysa bugün toparlanma fırsatı var. Kısa düzenleme sonraki günlerin riskini azaltabilir.',
    day: 5,
    theme: 'opportunity',
    eventType: 'opportunity',
    districtIds: ALL_DISTRICTS,
    districtLabel: 'Pilot Bölge',
    contextTag: 'Ekip fırsatı',
    riskLevel: 'low',
    filterTags: ['opportunity'],
    conditions: [{ type: 'metric_lte', metric: 'staffMorale', value: 60 }],
    priority: 7,
    fallback: false,
    previewEffects: { publicSatisfaction: 2, risk: -3, xp: 16 },
    decisions: [
      {
        id: 'd5-rest-partial',
        title: 'Ekibi Kısmen Dinlendir',
        description: 'Moral artar; bugünkü işler gecikebilir.',
        style: 'bold',
        recommended: true,
        decisionStyle: 'resource_saving',
        resultText: 'Kısa dinlenme morali toparladı; birkaç hat yarına kaldı.',
        effects: {
          publicSatisfaction: 3,
          budget: -1200,
          morale: 7,
          risk: 4,
          xp: 12,
        },
      },
      {
        id: 'd5-briefing',
        title: 'Kısa Eğitim / Rota Brifingi Yap',
        description: 'Operasyon riski düşer; küçük bütçe ve zaman harcanır.',
        style: 'balanced',
        decisionStyle: 'planned',
        resultText: 'Brifing ekip ritmini netleştirdi; risk düştü.',
        effects: {
          publicSatisfaction: 4,
          budget: -1800,
          morale: 4,
          risk: -6,
          xp: 11,
        },
        costs: { staffHours: 2 },
      },
      {
        id: 'd5-keep-tempo',
        title: 'Tempoyu Bozma',
        description: 'Bugün iş çıkar; moral ve risk baskı altında kalır.',
        style: 'risky',
        decisionStyle: 'risk',
        resultText: 'Tempo korundu; ekip yorgunluğu sonraki günlere taşındı.',
        effects: {
          publicSatisfaction: 5,
          budget: -800,
          morale: -4,
          risk: 5,
          xp: 8,
        },
      },
    ],
  }),
  pilotEvent({
    id: 'shared_day5_opportunity_permanent_solution',
    title: 'Kalıcı Çözüm Fırsatı',
    description:
      'Ece: Tekrarlayan sorun için küçük kalıcı iyileştirme penceresi açıldı.',
    day: 5,
    theme: 'opportunity',
    eventType: 'permanent_solution',
    districtIds: ALL_DISTRICTS,
    districtLabel: 'Pilot Bölge',
    contextTag: 'Fırsat',
    riskLevel: 'low',
    filterTags: ['opportunity'],
    fallback: true,
    priority: 1,
    previewEffects: { publicSatisfaction: 2, risk: -4, xp: 18 },
    decisions: [
      {
        id: 'd5-permanent',
        title: 'Kalıcı Çözüm Uygula',
        description: 'Yatırım yap; gelecek riski azalır.',
        style: 'cautious',
        decisionStyle: 'permanent',
        setFlags: { permanentSolutionApplied: true },
        effects: {
          publicSatisfaction: 8,
          budget: -10000,
          morale: -2,
          risk: -16,
          trust: 8,
          cleanliness: 8,
          xp: 14,
        },
        costs: { budget: 10000, staffHours: 5 },
      },
      {
        id: 'd5-temp',
        title: 'Geçici Çözümle Devam Et',
        description: 'Maliyet düşük; sorun tekrarlayabilir.',
        style: 'balanced',
        decisionStyle: 'partial',
        setFlags: { permanentSolutionApplied: false },
        effects: {
          publicSatisfaction: 4,
          budget: -2500,
          morale: 0,
          risk: 2,
          xp: 9,
        },
      },
      {
        id: 'd5-community',
        title: 'Mahalleyle Ortak Çözüm Ara',
        description: 'Güven artar; uygulama süresi uzar.',
        style: 'bold',
        decisionStyle: 'communication',
        setFlags: { permanentSolutionApplied: true },
        effects: {
          publicSatisfaction: 7,
          budget: -5500,
          morale: -1,
          risk: -10,
          trust: 10,
          xp: 12,
        },
      },
    ],
  }),

  // —— Gün 6: Butterfly ——
  pilotEvent({
    id: 'day6_butterfly_fast_response_fatigue',
    title: 'Hızlı Kararın Yorgunluğu',
    description:
      'Kemal: İlk gün hızlı müdahaleler güven kazandırdı ama ekip temposu zirvede.',
    day: 6,
    theme: 'butterfly_effect',
    eventType: 'butterfly',
    districtIds: ALL_DISTRICTS,
    districtLabel: 'Pilot Bölge',
    contextTag: 'Kelebek etkisi',
    riskLevel: 'medium',
    conditions: [{ type: 'flag_equals', flag: 'day1ResponseStyle', value: 'fast' }],
    priority: 10,
    fallback: false,
    previewEffects: { publicSatisfaction: -3, risk: 10, xp: 15 },
    decisions: butterflyDay6Decisions('d6-fast'),
  }),
  pilotEvent({
    id: 'day6_butterfly_planned_delay_complaint',
    title: 'Ertelenen Sorun Geri Döndü',
    description:
      'Hüseyin Muhtar: İlk gün bekletilen hat bugün tekrar şikayet olarak döndü.',
    day: 6,
    theme: 'butterfly_effect',
    eventType: 'butterfly',
    districtIds: ALL_DISTRICTS,
    districtLabel: 'Pilot Bölge',
    contextTag: 'Kelebek etkisi',
    riskLevel: 'high',
    conditions: [{ type: 'flag_equals', flag: 'day1ResponseStyle', value: 'planned' }],
    priority: 10,
    fallback: false,
    previewEffects: { publicSatisfaction: -7, risk: 12, xp: 16 },
    decisions: butterflyDay6Decisions('d6-planned'),
  }),
  pilotEvent({
    id: 'day6_butterfly_partial_solution_return',
    title: 'Yarım Kalan Çözüm',
    description:
      'Nermin Usta: Kısmi müdahale sorunu büyütmedi ama tamamen de bitirmedi.',
    day: 6,
    theme: 'butterfly_effect',
    eventType: 'butterfly',
    districtIds: ALL_DISTRICTS,
    districtLabel: 'Pilot Bölge',
    contextTag: 'Kelebek etkisi',
    riskLevel: 'medium',
    conditions: [{ type: 'flag_equals', flag: 'day1ResponseStyle', value: 'partial' }],
    priority: 10,
    fallback: false,
    previewEffects: { publicSatisfaction: -4, risk: 8, xp: 14 },
    decisions: butterflyDay6Decisions('d6-partial'),
  }),
  pilotEvent({
    id: 'day6_butterfly_default_operational_memory',
    title: 'İlk Günlerin Etkisi',
    description:
      'Ece: İlk günlerin kararları bugünkü operasyon dengesini şekillendiriyor.',
    day: 6,
    theme: 'butterfly_effect',
    eventType: 'butterfly',
    districtIds: ALL_DISTRICTS,
    districtLabel: 'Pilot Bölge',
    contextTag: 'Kelebek etkisi',
    riskLevel: 'medium',
    priority: 1,
    fallback: true,
    previewEffects: { publicSatisfaction: -3, risk: 7, xp: 13 },
    decisions: butterflyDay6Decisions('d6-default'),
  }),

  // —— Gün 7: Final ——
  pilotEvent({
    id: 'shared_day7_final_pilot_report_pressure',
    title: 'Pilot Bölge Son Değerlendirmesi',
    description:
      'Selim Kara: Üst yönetime sunulacak rapor öncesi son saha baskısı. Tablo net olmalı.',
    day: 7,
    theme: 'final_report',
    eventType: 'final',
    districtIds: ALL_DISTRICTS,
    districtLabel: 'Pilot Bölge',
    contextTag: 'Final raporu',
    riskLevel: 'high',
    urgencyHours: 2,
    filterTags: ['urgent', 'crisis'],
    fallback: true,
    previewEffects: { publicSatisfaction: -6, risk: 14, xp: 22 },
    decisions: [
      {
        id: 'd7-all-in',
        title: 'Tüm Kaynakları Finale Yükle',
        description: 'Maksimum görünürlük; bütçe ve moral yükü.',
        style: 'bold',
        decisionStyle: 'fast',
        effects: {
          publicSatisfaction: 12,
          budget: -12000,
          morale: -7,
          risk: -15,
          xp: 18,
        },
        costs: { staffHours: 14, vehicleUsage: 2 },
      },
      {
        id: 'd7-prioritize-risk',
        title: 'Riskli Bölgeleri Öncele',
        description: 'Hedefli müdahale; dengeli maliyet.',
        style: 'balanced',
        decisionStyle: 'risk',
        effects: {
          publicSatisfaction: 7,
          budget: -6000,
          morale: -3,
          risk: -10,
          xp: 14,
        },
      },
      {
        id: 'd7-permanent-comms',
        title: 'Kalıcı Çözüm + İletişim',
        description: 'Uzun vadeli iz bırak; yüksek yatırım.',
        style: 'cautious',
        decisionStyle: 'permanent',
        effects: {
          publicSatisfaction: 9,
          budget: -9500,
          morale: -2,
          risk: -18,
          trust: 9,
          xp: 16,
        },
        costs: { budget: 9500, staffHours: 6 },
      },
    ],
  }),
];

export const pilotEvents: EventCard[] = pilotEventsList.map((event) => ({
  ...event,
  decisions: event.decisions.map((d) => ({ ...d })),
}));

export function getPilotEvents(): EventCard[] {
  return pilotEvents.map((event) => ({
    ...event,
    decisions: event.decisions.map((d) => ({ ...d })),
  }));
}

export function getPilotEventsByDay(day: number): EventCard[] {
  return pilotEvents.filter((e) => e.day === day);
}

export function getPilotEventsByDistrict(
  districtId: PilotDistrictId,
): EventCard[] {
  return pilotEvents.filter(
    (e) => e.districtIds?.includes(districtId) ?? false,
  );
}

export function getPilotFallbackEvents(day: number): EventCard[] {
  return pilotEvents.filter((e) => e.day === day && e.fallback === true);
}
