import type { DayPipelineStepDefinition, DayPipelineStepId } from './dayPipelineTypes';

/**
 * Canonical dependency order for audit / documentation.
 * Runtime store order may differ for report_build and authority_badges — see RUNTIME_STEP_SEQUENCE.
 */
export const END_OF_DAY_PIPELINE_STEP_DEFINITIONS: DayPipelineStepDefinition[] = [
  {
    id: 'preflight_guard',
    phase: 'preflight',
    label: 'Ön kontrol',
    description:
      'lastClosedDay, lastDailyReport ve fresh-day guard ile aynı gün çift kapanışı engeller.',
    requiredStateKeys: ['gameState.city.day', 'lastClosedDay', 'lastDailyReport'],
    writesStateKeys: [],
    runsIn: ['pilot', 'post_pilot_limited', 'post_pilot_full', 'main_operation_full', 'unknown'],
    isCritical: true,
    idempotencyKey: 'lastClosedDay',
  },
  {
    id: 'event_outcome_snapshot',
    phase: 'event_outcome',
    label: 'Gün sonu gece snapshot',
    description:
      'Konteyner, araç, sosyal, personel, hedef ve öncelik gün sonu hazırlığı; event outcome rapor girdisi.',
    requiredStateKeys: ['gameState', 'containerState', 'vehicleState', 'personnelState'],
    writesStateKeys: ['containerState', 'vehicleState', 'socialPulseState', 'personnelState'],
    runsIn: ['pilot', 'post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['preflight_guard'],
    isCritical: true,
    idempotencyKey: 'lastClosedDay',
  },
  {
    id: 'operation_signals_base_eod',
    phase: 'operation_signals',
    label: 'Operasyon sinyalleri EOD',
    description: 'operationSignals EOD base processing; lastProcessedDay guard.',
    requiredStateKeys: ['operationSignals', 'gameState', 'decisionHistory'],
    writesStateKeys: ['operationSignals'],
    runsIn: ['pilot', 'post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['event_outcome_snapshot'],
    isCritical: true,
    idempotencyKey: 'operationSignals.lastProcessedDay',
  },
  {
    id: 'daily_plan_effects',
    phase: 'daily_plan',
    label: 'Günlük plan etkileri',
    description: 'dailyOperationsPlan appliedEffects tek kez operationSignals’a yansır.',
    requiredStateKeys: ['dailyOperationsPlan', 'operationSignals'],
    writesStateKeys: ['dailyOperationsPlan', 'operationSignals'],
    runsIn: ['post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['operation_signals_base_eod'],
    isCritical: true,
    idempotencyKey: 'dailyOperationsPlan.lastProcessedDay',
  },
  {
    id: 'assignment_effects',
    phase: 'assignments',
    label: 'Atama etkileri',
    description: 'Onaylanmış atamalar operationSignals’a tek kez uygulanır.',
    requiredStateKeys: ['assignments', 'operationSignals'],
    writesStateKeys: ['assignments', 'operationSignals'],
    runsIn: ['post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['daily_plan_effects'],
    isCritical: true,
    idempotencyKey: 'assignments.lastProcessedDay',
  },
  {
    id: 'micro_decision_effects',
    phase: 'micro_decisions',
    label: 'Canlı karar etkileri',
    description: 'Çözülen mikro kararlar effectsApplied ile tek kez işlenir.',
    requiredStateKeys: ['microDecisionState', 'operationSignals', 'crisisState'],
    writesStateKeys: ['microDecisionState', 'operationSignals', 'crisisState'],
    runsIn: ['post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['assignment_effects'],
    isCritical: true,
    idempotencyKey: 'microDecisionState.lastProcessedDay',
  },
  {
    id: 'crisis_action_effects',
    phase: 'crisis_actions',
    label: 'Kriz hamlesi etkileri',
    description:
      'Seçili kriz hamlesi crisis derive/process öncesi uygulanır; lastProcessedDay guard.',
    requiredStateKeys: ['crisisActionState', 'crisisState', 'operationSignals'],
    writesStateKeys: ['crisisActionState', 'operationSignals', 'crisisState', 'mainOperationSeason'],
    runsIn: ['main_operation_full'],
    mustRunAfter: ['micro_decision_effects'],
    mustRunBefore: ['operational_resources_process'],
    isCritical: true,
    idempotencyKey: 'crisisActionState.lastProcessedDay',
  },
  {
    id: 'operational_resources_process',
    phase: 'operational_resources',
    label: 'Saha kaynakları işleme',
    description:
      'Personel, filo ve konteyner ağı gün sonu etkileri; lastProcessedDay guard.',
    requiredStateKeys: [
      'operationalResources',
      'dailyOperationsPlan',
      'assignments',
      'microDecisionState',
      'crisisActionState',
      'operationSignals',
    ],
    writesStateKeys: ['operationalResources'],
    runsIn: ['post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['crisis_action_effects', 'micro_decision_effects'],
    mustRunBefore: ['main_operation_season_process', 'crisis_state_process'],
    isCritical: true,
    idempotencyKey: 'operationalResources.lastProcessedDay',
  },
  {
    id: 'main_operation_season_process',
    phase: 'main_operation',
    label: 'Ana operasyon sezonu',
    description: 'Sezon hedefleri ve bölge kapsamı gün sonu ilerlemesi.',
    requiredStateKeys: ['mainOperationSeason', 'monetization'],
    writesStateKeys: ['mainOperationSeason'],
    runsIn: ['post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['assignment_effects'],
    isCritical: true,
    idempotencyKey: 'mainOperationSeason.lastProcessedDay',
  },
  {
    id: 'crisis_state_process',
    phase: 'crisis',
    label: 'Kriz masası işleme',
    description: 'crisisState process/derive ve incident contained mantığı.',
    requiredStateKeys: ['crisisState', 'operationSignals'],
    writesStateKeys: ['crisisState'],
    runsIn: ['post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['crisis_action_effects', 'micro_decision_effects'],
    isCritical: true,
    idempotencyKey: 'crisisState.lastProcessedDay',
  },
  {
    id: 'advisor_eod_process',
    phase: 'advisor',
    label: 'Ece gün sonu',
    description:
      'Advisor XP, tahmin değerlendirme; lastExperienceGrantDay ve lastPredictionEvaluatedDay guard.',
    requiredStateKeys: ['advisorState', 'operationSignals'],
    writesStateKeys: ['advisorState'],
    runsIn: ['pilot', 'post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['crisis_state_process'],
    isCritical: true,
    idempotencyKey: 'advisorState.lastExperienceGrantDay',
  },
  {
    id: 'authority_badge_process',
    phase: 'authority_badges',
    label: 'Otorite ve rozet',
    description:
      'Günlük authority trust ve badge değerlendirmesi; rapor satırlarına snapshot olarak girer.',
    requiredStateKeys: ['gameState.pilot.authorityState', 'gameState.pilot.badgeState'],
    writesStateKeys: ['gameState.pilot.authorityState', 'gameState.pilot.badgeState'],
    runsIn: ['pilot', 'post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    isCritical: false,
  },
  {
    id: 'report_build',
    phase: 'report',
    label: 'Gün sonu raporu',
    description:
      'Rapor snapshot; domain kartları canlı slice’lardan okur. Tanımlı sırada gameplay etkilerinden sonra.',
    requiredStateKeys: ['gameState', 'lastDailyReport'],
    writesStateKeys: ['lastDailyReport', 'lastClosedDay'],
    runsIn: ['pilot', 'post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: [
      'daily_plan_effects',
      'assignment_effects',
      'micro_decision_effects',
      'crisis_action_effects',
      'crisis_state_process',
      'main_operation_season_process',
    ],
    isCritical: true,
    idempotencyKey: 'lastDailyReport.day',
  },
  {
    id: 'post_day_refresh',
    phase: 'post_day_refresh',
    label: 'Ertesi gün yenileme',
    description:
      'Pilot/post-pilot event refresh, plan/micro/crisis action refresh, signals refresh.',
    requiredStateKeys: ['gameState', 'eventPool'],
    writesStateKeys: [
      'gameState',
      'eventPool',
      'dailyOperationsPlan',
      'microDecisionState',
      'crisisActionState',
      'operationSignals',
    ],
    runsIn: ['pilot', 'post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['report_build'],
    isCritical: false,
  },
  {
    id: 'cleanup',
    phase: 'cleanup',
    label: 'Temizlik',
    description: 'Expire/prune: micro decisions, crisis actions, assignments history.',
    requiredStateKeys: [],
    writesStateKeys: ['microDecisionState', 'crisisActionState', 'assignments'],
    runsIn: ['post_pilot_limited', 'post_pilot_full', 'main_operation_full'],
    mustRunAfter: ['post_day_refresh'],
    isCritical: false,
  },
];

/**
 * Documented endCurrentDay store order (differs from canonical audit order for report/authority).
 * Report UI reads live slices for post-close domain cards; base report object comes from endDay().
 */
export const END_OF_DAY_RUNTIME_STEP_SEQUENCE: DayPipelineStepId[] = [
  'preflight_guard',
  'event_outcome_snapshot',
  'authority_badge_process',
  'report_build',
  'post_day_refresh',
  'operation_signals_base_eod',
  'daily_plan_effects',
  'assignment_effects',
  'main_operation_season_process',
  'micro_decision_effects',
  'crisis_action_effects',
  'operational_resources_process',
  'advisor_eod_process',
  'crisis_state_process',
  'post_day_refresh',
  'cleanup',
];

export const DAY_PIPELINE_KNOWN_STATE_KEYS = [
  'gameState',
  'monetization',
  'lastClosedDay',
  'lastDailyReport',
  'operationSignals',
  'dailyOperationsPlan',
  'assignments',
  'microDecisionState',
  'crisisActionState',
  'operationalResources',
  'mainOperationSeason',
  'crisisState',
  'advisorState',
  'containerState',
  'vehicleState',
  'personnelState',
  'socialPulseState',
  'eventPool',
  'gameState.pilot.authorityState',
  'gameState.pilot.badgeState',
  'gameState.pilot.postPilotOperation',
] as const;
