import type {
  CreviaStoryChainStepHints,
  CreviaStoryChainStepTemplate,
  CreviaStoryChainTemplate,
} from './storyChainTypes';

function hints(
  mapHint: string,
  advisorHint: string,
  reportHint: string,
  socialHint: string,
  tomorrowHint: string,
  resultHint: string,
): CreviaStoryChainStepHints {
  return { mapHint, advisorHint, reportHint, socialHint, tomorrowHint, resultHint };
}

function step(
  stepKind: CreviaStoryChainStepTemplate['stepKind'],
  dayOffset: number,
  title: string,
  shortLine: string,
  eventFamilyIntent: string,
  variantBias: readonly string[],
  districtMemoryIntent: string,
  districtTrustIntent: string,
  hintBundle: CreviaStoryChainStepHints,
  relatedEventFamilyId?: string,
): CreviaStoryChainStepTemplate {
  return {
    stepKind,
    dayOffset,
    title,
    shortLine,
    eventFamilyIntent,
    variantBias,
    districtMemoryIntent,
    districtTrustIntent,
    relatedEventFamilyId,
    hints: hintBundle,
  };
}

export const STORY_CHAIN_TEMPLATES: readonly CreviaStoryChainTemplate[] = [
  {
    id: 'cumhuriyet_container_recovery_chain',
    kind: 'container_recovery_chain',
    title: 'Cumhuriyet Konteyner Toparlanma Zinciri',
    shortLabel: 'Konteyner Toparlanma',
    districtIds: ['cumhuriyet'],
    relatedDomains: ['container_network', 'container', 'recovery'],
    recommendedVariantKinds: ['carry_over', 'recovery', 'district_trust', 'comeback'],
    relatedEventFamilyIds: [
      'cumhuriyet_sokak_kenari_gece_yigini',
      'cumhuriyet_konteyner_cevresi_baski_izleme',
      'cumhuriyet_guven_toparlanma_penceresi',
    ],
    memoryIntent: 'Konteyner cevresi baskisini blok hafizasina yazmak.',
    trustIntent: 'Apartman onu guven onarimini desteklemek.',
    freshnessIntent: 'Ayni konteyner zincirini ust uste onerme.',
    steps: [
      step(
        'trigger',
        0,
        'Gece Iri Atik Izı',
        'Blok arkasinda gece birakilan iri atik konteyner cevresini daraltiyor.',
        'Konteyner cevresi baskisini izleme katmaninda ac.',
        ['carry_over', 'worsened'],
        'Gece birakma noktasini site hafizasina kaydet.',
        'Blok guven notunu korumak.',
        hints(
          'Konteyner cevresi izleme katmaninda blok arka noktasini goster.',
          'Once cevreyi netlestir, sonra rutin hatti koru.',
          'Gece iri atik izi bugun Cumhuriyet satirina dustu.',
          'Site yonetimi: Set cevresi daraldi, kisa mudahale istiyoruz.',
          'Yarin sabah ayni konteyner cevresini erken oku.',
          'Cumhuriyet konteyner izi kontrollu kapandi.',
        ),
        'cumhuriyet_sokak_kenari_gece_yigini',
      ),
      step(
        'follow_up',
        1,
        'Apartman Onu Guven Onarimi',
        'Apartman onu sikayet satiri buyumeden yumusatma penceresi aciliyor.',
        'Sikayet satirini onleyici cevapla sinirla.',
        ['recovery', 'district_trust'],
        'Sikayet saatini apartman hafizasina yaz.',
        'Blok guven toparlanmasini destekle.',
        hints(
          'Sosyal nabiz katmaninda apartman onunu goster.',
          'Yumusak ama net cevap planini one al.',
          'Apartman onu guven notu gun sonu satirina eklendi.',
          'Temsilci: Satir buyumeden kisa cevap istiyoruz.',
          'Yarin sikayet satirini plan oncesi oku.',
          'Cumhuriyet apartman onu yumusama izi birakti.',
        ),
        'cumhuriyet_apartman_sikayet_yumusatma',
      ),
      step(
        'closure',
        2,
        'Toparlanma veya Takip Notu',
        'Toparlanma penceresi kapanir ya da kontrollu takip satiri kalir.',
        'Toparlanma penceresini gorunur kapat veya iz birak.',
        ['comeback', 'carry_over', 'reward'],
        'Toparlanma saatini mahalle hafizasina yaz.',
        'Guven toparlanmasini olc.',
        hints(
          'Mahalle hafizasi katmaninda toparlanma saatini goster.',
          'Kapanis veya takip secenegini net anlat.',
          'Konteyner toparlanma zinciri Cumhuriyet ozetine eklendi.',
          'Gonullu: Pencere net kapanmali, eski not acik kalmasin.',
          'Yarin guven notunu plan oncesi oku.',
          'Cumhuriyet konteyner toparlanma zinciri olculu kapandi.',
        ),
        'cumhuriyet_guven_toparlanma_penceresi',
      ),
    ],
  },
  {
    id: 'sanayi_route_pressure_chain',
    kind: 'route_pressure_chain',
    title: 'Sanayi Rota Baskisi Zinciri',
    shortLabel: 'Rota Baskisi',
    districtIds: ['sanayi'],
    relatedDomains: ['vehicle_route', 'personnel', 'resource_pressure'],
    recommendedVariantKinds: ['carry_over', 'comeback', 'resource_fatigue', 'improved'],
    relatedEventFamilyIds: [
      'sanayi_vardiya_rota_dengeleme',
      'sanayi_arac_yorgunluk_ekip_plani',
      'sanayi_fabrika_kapi_arac_sirasi',
    ],
    memoryIntent: 'Vardiya cikis baskisini rota hafizasina yazmak.',
    trustIntent: 'Filo denge kararinin guven etkisini olcmek.',
    freshnessIntent: 'Ayni rota zincirini kisa aralikta tekrar etme.',
    steps: [
      step(
        'trigger',
        0,
        'Vardiya Cikis Sikismasi',
        'Uretim bandi cikisinda filo baskisi hat kaydirmasini zorluyor.',
        'Vardiya cikisinda onleyici rota kaydirmasi planla.',
        ['carry_over', 'worsened'],
        'Cikis saatini vardiya hafizasina kaydet.',
        'Sanayi vardiya guven notunu koru.',
        hints(
          'Aktif rota katmaninda vardiya cikisini goster.',
          'Once denge, sonra hiz; rota kaydirmasini netlestir.',
          'Vardiya rota baskisi Sanayi ozetine eklendi.',
          'Koordinator: Cikis baskisi buyuyor, kisa kaydirma istiyoruz.',
          'Yarin cikis saatinde denge planini ac.',
          'Sanayi vardiya rota baskisi kontrollu kapandi.',
        ),
        'sanayi_vardiya_rota_dengeleme',
      ),
      step(
        'pressure_shift',
        1,
        'Arac Yorgunlugu ve Denge',
        'Ucuncu ardisik gorev bakim penceresini zorluyor; denge tercihi gerekli.',
        'Ekip yorgunlugunu onleyici planla kes.',
        ['resource_fatigue', 'comeback'],
        'Yorgunluk saatini filo hafizasina yaz.',
        'Filo guven notunu koru.',
        hints(
          'Kaynak yorgunlugu katmaninda filoyu goster.',
          'Plan guncellemesini kaynak odakli anlat.',
          'Arac yorgunluk plani Sanayi satirina dustu.',
          'Sorumlu: Ucuncu gorev zinciri uzadi, plan istiyoruz.',
          'Yarin vardiya basinda plani erken oku.',
          'Sanayi filo denge plani olculu kapandi.',
        ),
        'sanayi_arac_yorgunluk_ekip_plani',
      ),
      step(
        'closure',
        2,
        'Verimlilik veya Takip',
        'Denge oturursa verimlilik toparlanir; degilse kisa takip satiri kalir.',
        'Denge sonucunu kapanis veya takip olarak isaretle.',
        ['improved', 'carry_over', 'district_trust'],
        'Denge dongusunu rota hafizasina yaz.',
        'Vardiya guven tonunu olc.',
        hints(
          'Aktif rota katmaninda denge sonucunu goster.',
          'Kapanis veya takip yarin icin net olsun.',
          'Rota baskisi zinciri Sanayi gun sonu satirinda.',
          'Koordinator: Denge oturdu ama izi yarin da okuyalim.',
          'Yarin cikis oncesi denge notunu kontrol et.',
          'Sanayi rota baskisi zinciri olculu kapandi.',
        ),
      ),
    ],
  },
  {
    id: 'istasyon_transfer_flow_chain',
    kind: 'route_pressure_chain',
    title: 'Istasyon Aktarma Akisi Zinciri',
    shortLabel: 'Aktarma Akisi',
    districtIds: ['istasyon'],
    relatedDomains: ['vehicle_route', 'crisis_watch', 'prevention'],
    recommendedVariantKinds: ['improved', 'carry_over', 'recovery', 'crisis_adjacent'],
    relatedEventFamilyIds: [
      'istasyon_aktarma_yogunluk_onlemi',
      'istasyon_yaya_peron_baski_izleme',
      'istasyon_rota_koordinasyon_penceresi',
    ],
    memoryIntent: 'Aktarma yogunlugunu salon hafizasina yazmak.',
    trustIntent: 'Aktarma guven notunu korumak.',
    freshnessIntent: 'Ayni aktarma zincirini sabah-aksam tekrar etme.',
    steps: [
      step(
        'trigger',
        0,
        'Aktarma Yogunluk Dalgasi',
        'Sabah salon dalgasinda yolcu yogunlugu gecis penceresini daraltiyor.',
        'Sabah dalgasinda onleyici gecis penceresi ac.',
        ['improved', 'crisis_adjacent'],
        'Yogunluk saatini salon hafizasina yaz.',
        'Istasyon aktarma guvenini koru.',
        hints(
          'Crisis watch katmaninda aktarma salonunu goster.',
          'Gecis penceresini akis odakli netlestir.',
          'Aktarma yogunluk onlemi Istasyon ozetine eklendi.',
          'Gorevli: Sabah dalgasi sikisti, kisa pencere istiyoruz.',
          'Yarin sabah dalgasini plan oncesi oku.',
          'Istasyon aktarma yogunluk onlemi olculu kapandi.',
        ),
        'istasyon_aktarma_yogunluk_onlemi',
      ),
      step(
        'follow_up',
        1,
        'Peron Cevresi Kisa Iz',
        'Aksam kavsak cikisinda yaya baskisi izleme satiri aciliyor.',
        'Kavsak cikisinda onleyici gecis plani kur.',
        ['carry_over', 'district_trust'],
        'Baski saatini kavsak hafizasina yaz.',
        'Kavsak guven notunu koru.',
        hints(
          'Aktif rota katmaninda kavsak cikisini goster.',
          'Izleme ve gecis planini birlikte anlat.',
          'Kavsak yaya akisi izleme satirina dustu.',
          'Ekip: Gecis daraldi, kisa plan istiyoruz.',
          'Yarin aksam akisinda baski notunu erken oku.',
          'Istasyon kavsak akisi kontrollu kapandi.',
        ),
        'istasyon_yaya_peron_baski_izleme',
      ),
      step(
        'closure',
        2,
        'Rota Koordinasyonu veya Sosyal Echo',
        'Koordinasyon oturursa akis yumusar; degilse sosyal echo izi kalir.',
        'Koordinasyon sonucunu kapanis satirina yaz.',
        ['recovery', 'reward', 'carry_over'],
        'Koordinasyon saatini istasyon hafizasina yaz.',
        'Aktarma guven tonunu olc.',
        hints(
          'Aktif rota katmaninda koordinasyon penceresini goster.',
          'Kapanis veya echo yarin icin net olsun.',
          'Aktarma akisi zinciri Istasyon gun sonu satirinda.',
          'Yolcu: Akis duzeldi ama yarin sabah da kontrol edelim.',
          'Yarin aktarma girisinde koordinasyon notunu ac.',
          'Istasyon aktarma akisi zinciri olculu kapandi.',
        ),
        'istasyon_rota_koordinasyon_penceresi',
      ),
    ],
  },
  {
    id: 'yesilvadi_environmental_recovery_chain',
    kind: 'district_recovery_chain',
    title: 'Yesilvadi Cevresel Hassasiyet Zinciri',
    shortLabel: 'Cevre Toparlanma',
    districtIds: ['yesilvadi'],
    relatedDomains: ['recovery', 'prevention', 'district_memory'],
    recommendedVariantKinds: ['recovery', 'comeback', 'improved', 'district_trust'],
    relatedEventFamilyIds: [
      'yesilvadi_park_yogunluk_recovery',
      'yesilvadi_cevre_hassasiyet_plani',
      'yesilvadi_park_kenari_konteyner_dengesi',
    ],
    memoryIntent: 'Park yogunluk izini yesil alan hafizasina yazmak.',
    trustIntent: 'Sakin hizmet algisini korumak.',
    freshnessIntent: 'Ayni cevre zincirini hafta sonu tekrar etme.',
    steps: [
      step(
        'trigger',
        0,
        'Park Yogunluk Temizlik Izi',
        'Hafta sonu yogunlugu sonrasi gol kayasi toparlanma penceresi daraldi.',
        'Yogunluk sonrasi recovery penceresi ac.',
        ['carry_over', 'recovery'],
        'Yogunluk saatini gol kayasi hafizasina yaz.',
        'Yesil alan guven notunu koru.',
        hints(
          'Mahalle hafizasi katmaninda gol kayasini goster.',
          'Sakin toparlanma tonunu koru.',
          'Gol kayasi recovery Yesilvadi satirina dustu.',
          'Aile: Alan duzeni toparlanmadi, kisa recovery istiyoruz.',
          'Yarin alan acilisinda recovery notunu erken oku.',
          'Yesilvadi gol kayasi recovery sakin kapandi.',
        ),
        'yesilvadi_park_yogunluk_recovery',
      ),
      step(
        'recovery_window',
        1,
        'Dusuk Gurultu Hizmet Plani',
        'Sessiz sokakta dusuk gurultu plani gecikirse sakin yorumlari cogalir.',
        'Sessiz sokak planini onleyici olarak netlestir.',
        ['improved', 'district_trust'],
        'Plan saatini yesil rota hafizasina yaz.',
        'Yesilvadi sakin guvenini koru.',
        hints(
          'Mahalle guveni katmaninda sessiz sokagi goster.',
          'Cevre hassasiyeti onceligini vurgula.',
          'Sessiz sokak plani gun sonu satirina dustu.',
          'Sakin: Gurultu plani net olsun, sesimiz kirilmasin istiyoruz.',
          'Yarin ayni sokak planini tekrar oku.',
          'Yesilvadi sessiz sokak plani yumusak kapandi.',
        ),
        'yesilvadi_cevre_hassasiyet_plani',
      ),
      step(
        'closure',
        2,
        'Sakin Hizmet Algisi',
        'Plan oturursa sakin algisi toparlanir; degilse kisa takip notu kalir.',
        'Toparlanma penceresini kapat veya takip birak.',
        ['reward', 'comeback', 'carry_over'],
        'Kapanis saatini yesil alan hafizasina yaz.',
        'Sakin guven tonunu olc.',
        hints(
          'Mahalle guveni katmaninda yesil alani goster.',
          'Kapanis veya takip secenegini sakin anlat.',
          'Cevresel hassasiyet zinciri Yesilvadi ozetine eklendi.',
          'Gonullu: Sakin ton korunmali, yarin da izleyelim.',
          'Yarin yesil alan acilisinda takip notunu oku.',
          'Yesilvadi cevre toparlanma zinciri sakin kapandi.',
        ),
      ),
    ],
  },
  {
    id: 'merkez_visible_service_chain',
    kind: 'visible_service_chain',
    title: 'Merkez Gorunur Hizmet Zinciri',
    shortLabel: 'Gorunur Hizmet',
    districtIds: ['merkez'],
    relatedDomains: ['visible_service', 'operation_era', 'district_trust'],
    recommendedVariantKinds: ['improved', 'reward', 'district_trust', 'recovery'],
    relatedEventFamilyIds: [
      'merkez_hizmet_alani_baski_kontrolu',
      'merkez_mudahale_guven_koruma',
      'merkez_ana_durak_gorunurluk',
    ],
    memoryIntent: 'Gorunur hizmet izini meydan hafizasina yazmak.',
    trustIntent: 'Vatandas algisindaki guven gorunurlugunu korumak.',
    freshnessIntent: 'Ayni meydan zincirini kisa aralikta tekrar etme.',
    steps: [
      step(
        'trigger',
        0,
        'Meydan Gorunur Hizmet Baskisi',
        'Vitrin hatti cevresinde hizmet baskisi buyumeden kontrol gerekli.',
        'Aydinlatma bolgesinde onleyici kontrol dongusu kur.',
        ['improved', 'crisis_adjacent'],
        'Baski saatini bolge hafizasina yaz.',
        'Vitrin hatti algisini koru.',
        hints(
          'Crisis watch katmaninda aydinlatma bolgesini goster.',
          'Gorunur vitrin tonunu koru.',
          'Aydinlatma bolgesi kontrolu gun sonu satirina dustu.',
          'Ekip: Yaya akisi yogun, kisa kontrol istiyoruz.',
          'Yarin vitrin acilisinda baski notunu erken oku.',
          'Merkez aydinlatma bolgesi kontrolu olculu kapandi.',
        ),
        'merkez_hizmet_alani_baski_kontrolu',
      ),
      step(
        'follow_up',
        1,
        'Hizli Mudahale Algisi',
        'Lobi temizligi sonrasi gorunur iz satiri kaybolursa yorumlar sertlesir.',
        'Iz satirinin zayiflamasini onle.',
        ['recovery', 'district_trust'],
        'Iz saatini lobi hafizasina yaz.',
        'Lobi guven notunu koru.',
        hints(
          'Mahalle guveni katmaninda lobi girisini goster.',
          'Gorunur adim onceligini vurgula.',
          'Lobi iz koruma Merkez satirina dustu.',
          'Ziyaretci: Temizlik oldu ama izi goremedik, kisa adim istiyoruz.',
          'Yarin ayni ogle saatinde iz planini ac.',
          'Merkez lobi iz koruma olculu kapandi.',
        ),
        'merkez_mudahale_guven_koruma',
      ),
      step(
        'closure',
        2,
        'Guven Gorunurlugu veya Takip',
        'Gorunurluk oturursa guven toparlanir; degilse takip notu kalir.',
        'Gorunurluk sonucunu kapanis satirina yaz.',
        ['reward', 'carry_over', 'improved'],
        'Gorunurluk saatini meydan hafizasina yaz.',
        'Merkez guven tonunu olc.',
        hints(
          'Sosyal nabiz katmaninda ana durak cevresini goster.',
          'Kapanis veya takip yarin icin net olsun.',
          'Gorunur hizmet zinciri Merkez ozetine eklendi.',
          'Yuruyen: Ekip gecisini gorduk, yarin da kontrol edelim.',
          'Yarin durak temizligi kuyruk saatinden once kontrol edilsin.',
          'Merkez gorunur hizmet zinciri olculu kapandi.',
        ),
        'merkez_ana_durak_gorunurluk',
      ),
    ],
  },
  {
    id: 'social_trust_repair_chain',
    kind: 'social_trust_chain',
    title: 'Sosyal Guven Onarim Zinciri',
    shortLabel: 'Guven Onarim',
    districtIds: ['cumhuriyet', 'merkez'],
    relatedDomains: ['social_trust', 'district_trust', 'social'],
    recommendedVariantKinds: ['recovery', 'district_trust', 'reward', 'carry_over'],
    relatedEventFamilyIds: [
      'cumhuriyet_sohbet_grubu_guven_notu',
      'merkez_meydan_yorum_dalgasi',
      'cumhuriyet_apartman_onu_defter_notu',
    ],
    memoryIntent: 'Sosyal nabiz izini mahalle hafizasina tasimak.',
    trustIntent: 'Gorunur cevabin guven toparlanmasini desteklemek.',
    freshnessIntent: 'Ayni guven zincirini kisa aralikta tekrar etme.',
    steps: [
      step(
        'trigger',
        0,
        'Sosyal Nabiz Sikayet Notu',
        'Mahalle nabizinda sikayet satiri buyumeden kisa cevap penceresi aciliyor.',
        'Sikayet satirini onleyici cevapla sinirla.',
        ['worsened', 'carry_over'],
        'Sikayet saatini nabiz hafizasina yaz.',
        'Mahalle guven notunu koru.',
        hints(
          'Sosyal nabiz katmaninda sikayet satirini goster.',
          'Cevap planini yumusak ama net anlat.',
          'Sosyal nabiz sikayet notu gun sonu satirina dustu.',
          'Mahalleli: Cevap suresi belirsiz, kisa donus istiyoruz.',
          'Yarin sikayet satirini plan oncesi oku.',
          'Sosyal guven sikayet notu olculu kapandi.',
        ),
        'cumhuriyet_apartman_onu_defter_notu',
      ),
      step(
        'follow_up',
        1,
        'Saha Gorunurlugu',
        'Gorunur saha adimi gecikirse nabiz tonu sertlesir.',
        'Gorunur cevap ile guven onarimini destekle.',
        ['recovery', 'district_trust'],
        'Cevap saatini mahalle hafizasina yaz.',
        'Guven onarim etkisini olc.',
        hints(
          'Mahalle guveni katmaninda saha noktasini goster.',
          'Gorunurluk onceligini vurgula.',
          'Saha gorunurlugu gun sonu satirina eklendi.',
          'Grup uyesi: Gorunur cevap bekliyoruz, ton yumusasin.',
          'Yarin nabiz tonunu plan oncesi oku.',
          'Sosyal guven saha gorunurlugu olculu kapandi.',
        ),
        'cumhuriyet_sohbet_grubu_guven_notu',
      ),
      step(
        'closure',
        2,
        'Guven Toparlanmasi veya Suphe',
        'Toparlanma oturursa guven yumusar; degilse yarina suphe izi kalir.',
        'Toparlanma veya takip satirini kapat.',
        ['reward', 'comeback', 'carry_over'],
        'Kapanis saatini guven hafizasina yaz.',
        'Guven toparlanma tonunu olc.',
        hints(
          'Sosyal nabiz katmaninda guven notunu goster.',
          'Kapanis veya suphe izini net anlat.',
          'Guven onarim zinciri gun sonu ozetine eklendi.',
          'Esnaf: Ton yumusadi ama yarin da takip edelim.',
          'Yarin acilis oncesi guven notunu oku.',
          'Sosyal guven onarim zinciri olculu kapandi.',
        ),
        'merkez_meydan_yorum_dalgasi',
      ),
    ],
  },
  {
    id: 'crisis_watch_prevention_chain',
    kind: 'crisis_watch_chain',
    title: 'Kriz Izleme ve Onleme Zinciri',
    shortLabel: 'Kriz Izleme',
    districtIds: ['sanayi', 'istasyon'],
    relatedDomains: ['crisis_adjacent', 'crisis_watch', 'prevention'],
    recommendedVariantKinds: ['crisis_adjacent', 'improved', 'recovery', 'carry_over'],
    relatedEventFamilyIds: [
      'sanayi_atik_noktasi_onleyici_takip',
      'istasyon_kirlilik_sosyal_etki_onleme',
      'istasyon_aktarma_yogunluk_onlemi',
    ],
    memoryIntent: 'Watch katmani izini kontrollu hafizaya almak.',
    trustIntent: 'Onleyici takibin guven tonunu korumak.',
    freshnessIntent: 'Watch zincirini panik dili olmadan seyrelt.',
    steps: [
      step(
        'trigger',
        0,
        'Risk Buyumeden Takip',
        'Birikim hizi artiyor; watch katmaninda kontrollu takip gerekli.',
        'Baskiyi watch listesinde tut, panik dili kullanma.',
        ['crisis_adjacent', 'carry_over'],
        'Watch saatini saha hafizasina yaz.',
        'Onleyici guven tonunu koru.',
        hints(
          'Crisis watch katmaninda baski noktasini goster.',
          'Sakin ve net takip planini anlat.',
          'Kriz izleme notu gun sonu satirina dustu.',
          'Sorumlu: Birikim hizi yukseldi, onleyici liste istiyoruz.',
          'Yarin watch listesini plan oncesi oku.',
          'Kriz izleme notu kontrollu kapandi.',
        ),
        'sanayi_atik_noktasi_onleyici_takip',
      ),
      step(
        'prevention_check',
        1,
        'Onleyici Operasyon',
        'Onleyici takip gecikirse gorunurluk satiri uretir.',
        'Onleyici mudahale penceresini ac.',
        ['improved', 'recovery'],
        'Mudahale saatini cevre hafizasina yaz.',
        'Cevre guven notunu koru.',
        hints(
          'Crisis watch katmaninda cevre noktasini goster.',
          'Hizli ama sakin mudahale tonunu koru.',
          'Onleyici operasyon satiri gun sonu ozetine eklendi.',
          'Ekip: Kisa iz gorunur, mudahale istiyoruz.',
          'Yarin iz satirini erken oku.',
          'Onleyici operasyon kontrollu kapandi.',
        ),
        'istasyon_kirlilik_sosyal_etki_onleme',
      ),
      step(
        'closure',
        2,
        'Recovery veya Kontrollu Takip',
        'Recovery oturursa ton yumusar; degilse kontrollu takip satiri kalir.',
        'Recovery veya takip penceresini kapat.',
        ['recovery', 'carry_over', 'district_trust'],
        'Kapanis saatini watch hafizasina yaz.',
        'Toparlanma tonunu olc.',
        hints(
          'Crisis watch katmaninda kapanis notunu goster.',
          'Recovery veya takip secenegini netlestir.',
          'Kriz izleme zinciri gun sonu satirina dustu.',
          'Ekip: Ton yumusadi, yarin da izleyelim.',
          'Yarin watch notunu plan oncesi oku.',
          'Kriz izleme zinciri kontrollu kapandi.',
        ),
      ),
    ],
  },
  {
    id: 'resource_fatigue_balance_chain',
    kind: 'resource_fatigue_chain',
    title: 'Kaynak Yorgunlugu Denge Zinciri',
    shortLabel: 'Kaynak Denge',
    districtIds: ['cumhuriyet', 'merkez', 'sanayi', 'istasyon', 'yesilvadi'],
    relatedDomains: ['resource_pressure', 'resource_fatigue', 'personnel'],
    recommendedVariantKinds: ['resource_fatigue', 'comeback', 'carry_over', 'recovery'],
    relatedEventFamilyIds: [
      'sanayi_arac_yorgunluk_ekip_plani',
      'merkez_resmi_cadde_vardiya',
      'istasyon_aksam_yaya_akisi',
    ],
    memoryIntent: 'Kaynak baskisi izini ekip hafizasina yazmak.',
    trustIntent: 'Denge tercihinin guven etkisini olcmek.',
    freshnessIntent: 'Kaynak zincirini ust uste onerme.',
    steps: [
      step(
        'trigger',
        0,
        'Arac veya Ekip Baskisi',
        'Ust uste gorev ekip temposunu daraltiyor; kaynak baskisi izleniyor.',
        'Kaynak baskisini watch katmaninda tut.',
        ['resource_fatigue', 'worsened'],
        'Baski saatini ekip hafizasina yaz.',
        'Ekip guven notunu koru.',
        hints(
          'Kaynak yorgunlugu katmaninda ekibi goster.',
          'Denge tercihini kaynak odakli anlat.',
          'Kaynak baskisi notu gun sonu satirina dustu.',
          'Sorumlu: Tempo daraldi, plan guncellemesi istiyoruz.',
          'Yarin vardiya basinda baski notunu oku.',
          'Kaynak baskisi notu kontrollu kapandi.',
        ),
        'sanayi_arac_yorgunluk_ekip_plani',
      ),
      step(
        'pressure_shift',
        1,
        'Dengeleme Tercihi',
        'Denge gecikirse diger hatlar bekler; kisa devam notu yorgunlugu artirir.',
        'Onleyici plan kesmesi ile denge kur.',
        ['comeback', 'carry_over'],
        'Plan saatini kaynak hafizasina yaz.',
        'Denge kararinin guven etkisini olc.',
        hints(
          'Kaynak baskisi katmaninda denge planini goster.',
          'Bekleme ve devam trade-offunu net anlat.',
          'Dengeleme tercihi gun sonu satirina eklendi.',
          'Koordinator: Hatlar bekliyor, kisa plan lazim.',
          'Yarin denge notunu plan oncesi oku.',
          'Kaynak denge tercihi olculu kapandi.',
        ),
      ),
      step(
        'closure',
        2,
        'Kaynak Rahatlamasi veya Takip',
        'Plan oturursa tempo rahatlar; degilse kisa takip satiri kalir.',
        'Rahatlama veya takip penceresini kapat.',
        ['recovery', 'improved', 'district_trust'],
        'Kapanis saatini kaynak hafizasina yaz.',
        'Rahatlama tonunu olc.',
        hints(
          'Kaynak yorgunlugu katmaninda kapanis notunu goster.',
          'Rahatlama veya takip secenegini netlestir.',
          'Kaynak denge zinciri gun sonu ozetine eklendi.',
          'Ekip: Tempo rahatladi, yarin da izleyelim.',
          'Yarin vardiya oncesi takip notunu oku.',
          'Kaynak denge zinciri kontrollu kapandi.',
        ),
      ),
    ],
  },
] as const;

export function getStoryChainTemplateById(id: string): CreviaStoryChainTemplate | undefined {
  return STORY_CHAIN_TEMPLATES.find((template) => template.id === id);
}

export function getStoryChainTemplatesByKind(kind: string): CreviaStoryChainTemplate[] {
  return STORY_CHAIN_TEMPLATES.filter((template) => template.kind === kind);
}

export function getStoryChainTemplatesByDistrict(districtId: string): CreviaStoryChainTemplate[] {
  return STORY_CHAIN_TEMPLATES.filter((template) => template.districtIds.includes(districtId as never));
}

export function isKnownContentPackEventFamilyId(familyId: string): boolean {
  return STORY_CHAIN_TEMPLATES.some((template) => template.relatedEventFamilyIds.includes(familyId));
}
