import { MAP_DISTRICT_IDENTITY_IDS } from '@/core/districts/districtIdentityConstants';

import type { DistrictOperationDefinition } from './districtOperationTypes';

const DEFAULT_PERMISSION = 'district_specific_operations_preview';

export const DISTRICT_OPERATION_CATALOG: readonly DistrictOperationDefinition[] = [
  {
    id: 'visible_service_merkez',
    districtId: 'merkez',
    kind: 'visible_service',
    title: 'Merkez Görünür Hizmet',
    shortLabel: 'Görünür Hizmet',
    description:
      'Kamu alanları ve ana yollarda görünür hizmet odağı; prestij ve vatandaş temasını dengeler.',
    districtFlavorLine: 'Merkezde kararlar kısa sürede görünür olur; prestij baskısı yüksektir.',
    requiredPermissionId: DEFAULT_PERMISSION,
    requiredTrustLevel: 'neutral',
    recommendedTrustLevels: ['stable', 'trusted', 'supportive'],
    unlockAxes: ['rank_permission', 'district_trust', 'event_family_signal'],
    impactDomains: ['social', 'trust', 'personnel', 'map'],
    relatedEventFamilyDomains: ['social', 'district_balance', 'generic_operation'],
    relatedMapLayerIds: ['district_trust', 'social_pulse', 'district_identity'],
    relatedRouteDomains: ['social', 'district_balance'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 92,
    iconKey: 'eye-outline',
  },
  {
    id: 'public_trust_merkez',
    districtId: 'merkez',
    kind: 'public_trust',
    title: 'Merkez Halk Güveni',
    shortLabel: 'Halk Güveni',
    description:
      'Sosyal görünürlük ve kamu algısını güçlendiren operasyon; Merkez prestijini korur.',
    districtFlavorLine: 'Kamu alanlarındaki görünürlük, güven etkisini hızla büyütür.',
    requiredPermissionId: DEFAULT_PERMISSION,
    requiredTrustLevel: 'watch',
    recommendedTrustLevels: ['stable', 'trusted'],
    unlockAxes: ['rank_permission', 'district_trust', 'district_memory'],
    impactDomains: ['social', 'trust', 'map'],
    relatedEventFamilyDomains: ['social', 'district_balance'],
    relatedMapLayerIds: ['district_trust', 'social_pulse', 'district_memory'],
    relatedRouteDomains: ['social'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 88,
    iconKey: 'people-outline',
  },
  {
    id: 'resource_balance_merkez',
    districtId: 'merkez',
    kind: 'resource_balance',
    title: 'Merkez Kaynak Dengesi',
    shortLabel: 'Kaynak Dengesi',
    description:
      'Personel ve araç yükünü yoğun Merkez akışında dengede tutan operasyon önerisi.',
    districtFlavorLine: 'Ana yollar ve kamu alanları personel/araç yükünü artırır.',
    requiredPermissionId: DEFAULT_PERMISSION,
    unlockAxes: ['rank_permission', 'resource_stability', 'active_task_route'],
    impactDomains: ['personnel', 'vehicle_route', 'map'],
    relatedEventFamilyDomains: ['personnel', 'vehicle_route', 'resource_recovery'],
    relatedMapLayerIds: ['resource_pressure', 'resource_fatigue', 'active_task_route'],
    relatedRouteDomains: ['vehicle_route', 'personnel'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 84,
    iconKey: 'scale-outline',
  },
  {
    id: 'public_trust_cumhuriyet',
    districtId: 'cumhuriyet',
    kind: 'public_trust',
    title: 'Cumhuriyet Halk Güveni',
    shortLabel: 'Halk Güveni',
    description:
      'Konut düzeni, aileler ve okul çevresinde sosyal güveni güçlendiren operasyon.',
    districtFlavorLine: 'Cumhuriyet’te sosyal nabız kararları şekillendirir.',
    requiredPermissionId: DEFAULT_PERMISSION,
    requiredTrustLevel: 'neutral',
    recommendedTrustLevels: ['stable', 'trusted', 'supportive'],
    unlockAxes: ['rank_permission', 'district_trust', 'event_family_signal'],
    impactDomains: ['social', 'trust', 'map'],
    relatedEventFamilyDomains: ['social', 'district_balance'],
    relatedMapLayerIds: ['district_trust', 'social_pulse', 'district_memory'],
    relatedRouteDomains: ['social', 'district_balance'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 90,
    iconKey: 'home-outline',
  },
  {
    id: 'container_network_cumhuriyet',
    districtId: 'cumhuriyet',
    kind: 'container_network',
    title: 'Cumhuriyet Konteyner Ağı',
    shortLabel: 'Konteyner Ağı',
    description:
      'Okul ve konut çevresinde konteyner düzenini iyileştiren mahalle özel operasyonu.',
    districtFlavorLine: 'Konut dokusunda konteyner düzeni sosyal güveni doğrudan etkiler.',
    requiredPermissionId: DEFAULT_PERMISSION,
    unlockAxes: ['rank_permission', 'resource_stability', 'event_family_signal'],
    impactDomains: ['container', 'social', 'trust'],
    relatedEventFamilyDomains: ['container', 'social', 'district_balance'],
    relatedMapLayerIds: ['resource_pressure', 'district_trust', 'social_pulse'],
    relatedRouteDomains: ['container', 'social'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 86,
    iconKey: 'cube-outline',
  },
  {
    id: 'recovery_focus_cumhuriyet',
    districtId: 'cumhuriyet',
    kind: 'recovery_focus',
    title: 'Cumhuriyet Güven Toparlama',
    shortLabel: 'Güven Toparlama',
    description:
      'Şikayet sonrası mahalle güvenini toparlamaya odaklanan recovery operasyonu.',
    districtFlavorLine: 'Mahalle güveni hızlı toparlanabilir; gecikme şikayete döner.',
    requiredPermissionId: DEFAULT_PERMISSION,
    requiredTrustLevel: 'fragile',
    unlockAxes: ['rank_permission', 'district_trust', 'district_memory'],
    impactDomains: ['trust', 'social', 'map'],
    relatedEventFamilyDomains: ['social', 'resource_recovery', 'district_balance'],
    relatedMapLayerIds: ['district_trust', 'district_memory', 'social_pulse'],
    relatedRouteDomains: ['social', 'district_balance'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 94,
    iconKey: 'heart-outline',
  },
  {
    id: 'route_discipline_sanayi',
    districtId: 'sanayi',
    kind: 'route_discipline',
    title: 'Sanayi Rota Disiplini',
    shortLabel: 'Rota Disiplini',
    description:
      'Vardiya, rota ve iş akışını dengeleyen Sanayi odaklı operasyon önerisi.',
    districtFlavorLine: 'Sanayi bölgesinde rota ve ekip yükü öne çıkar.',
    requiredPermissionId: DEFAULT_PERMISSION,
    unlockAxes: ['rank_permission', 'resource_stability', 'active_task_route'],
    impactDomains: ['vehicle_route', 'personnel', 'map'],
    relatedEventFamilyDomains: ['vehicle_route', 'personnel', 'generic_operation'],
    relatedMapLayerIds: ['resource_pressure', 'active_task_route', 'resource_fatigue'],
    relatedRouteDomains: ['vehicle_route', 'personnel'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 95,
    iconKey: 'git-branch-outline',
  },
  {
    id: 'vehicle_resource_sanayi',
    districtId: 'sanayi',
    kind: 'resource_balance',
    title: 'Sanayi Araç Kaynak Dengesi',
    shortLabel: 'Araç Dengesi',
    description:
      'Araç yorgunluğu ve bakım penceresini yöneten Sanayi kaynak operasyonu.',
    districtFlavorLine: 'Filo verimliliği kararların sonucunu belirler.',
    requiredPermissionId: DEFAULT_PERMISSION,
    unlockAxes: ['rank_permission', 'resource_stability', 'event_family_signal'],
    impactDomains: ['vehicle_route', 'personnel', 'crisis'],
    relatedEventFamilyDomains: ['vehicle_route', 'resource_recovery', 'personnel'],
    relatedMapLayerIds: ['resource_pressure', 'resource_fatigue', 'crisis_watch'],
    relatedRouteDomains: ['vehicle_route'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 88,
    iconKey: 'car-outline',
  },
  {
    id: 'crisis_prevention_sanayi',
    districtId: 'sanayi',
    kind: 'crisis_prevention',
    title: 'Sanayi Kriz Önleme',
    shortLabel: 'Kriz Önleme',
    description:
      'Gecikmenin krize dönmesini engelleyen Sanayi odaklı önleyici operasyon.',
    districtFlavorLine: 'Gecikmeler zincirleme etki yapar; erken müdahale kritiktir.',
    requiredPermissionId: DEFAULT_PERMISSION,
    unlockAxes: ['rank_permission', 'resource_stability', 'event_family_signal'],
    impactDomains: ['crisis', 'vehicle_route', 'personnel'],
    relatedEventFamilyDomains: ['crisis_adjacent', 'vehicle_route', 'resource_recovery'],
    relatedMapLayerIds: ['crisis_watch', 'resource_pressure', 'active_task_route'],
    relatedRouteDomains: ['crisis', 'vehicle_route'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 91,
    iconKey: 'shield-checkmark-outline',
  },
  {
    id: 'crowd_flow_istasyon',
    districtId: 'istasyon',
    kind: 'route_discipline',
    title: 'İstasyon Akış Disiplini',
    shortLabel: 'Akış Disiplini',
    description:
      'Geçiş noktası ve akşam yoğunluğunu yöneten İstasyon rota operasyonu.',
    districtFlavorLine: 'İstasyon çevresinde geçiş ve yoğunluk baskısı yüksektir.',
    requiredPermissionId: DEFAULT_PERMISSION,
    unlockAxes: ['rank_permission', 'active_task_route', 'event_family_signal'],
    impactDomains: ['vehicle_route', 'social', 'map'],
    relatedEventFamilyDomains: ['vehicle_route', 'social', 'district_balance'],
    relatedMapLayerIds: ['active_task_route', 'social_pulse', 'resource_pressure'],
    relatedRouteDomains: ['vehicle_route', 'social'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 93,
    iconKey: 'swap-horizontal-outline',
  },
  {
    id: 'public_trust_istasyon',
    districtId: 'istasyon',
    kind: 'public_trust',
    title: 'İstasyon Sosyal Nabız',
    shortLabel: 'Sosyal Nabız',
    description:
      'Hızlı değişen sosyal nabzı dengeleyen İstasyon güven operasyonu.',
    districtFlavorLine: 'Geçiş yoğunluğu sosyal algıyı hızla değiştirir.',
    requiredPermissionId: DEFAULT_PERMISSION,
    unlockAxes: ['rank_permission', 'district_trust', 'district_memory'],
    impactDomains: ['social', 'trust', 'map'],
    relatedEventFamilyDomains: ['social', 'district_balance'],
    relatedMapLayerIds: ['social_pulse', 'district_trust', 'district_memory'],
    relatedRouteDomains: ['social'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 87,
    iconKey: 'pulse-outline',
  },
  {
    id: 'crisis_prevention_istasyon',
    districtId: 'istasyon',
    kind: 'crisis_prevention',
    title: 'İstasyon Yoğunluk İzleme',
    shortLabel: 'Yoğunluk İzleme',
    description:
      'Yoğunluk ve risk sinyallerini izleyen İstasyon kriz önleme operasyonu.',
    districtFlavorLine: 'Yoğunluk kısa sürede artar; gecikme sosyal tepkiye dönüşebilir.',
    requiredPermissionId: DEFAULT_PERMISSION,
    unlockAxes: ['rank_permission', 'resource_stability', 'event_family_signal'],
    impactDomains: ['crisis', 'social', 'vehicle_route'],
    relatedEventFamilyDomains: ['crisis_adjacent', 'social', 'vehicle_route'],
    relatedMapLayerIds: ['crisis_watch', 'social_pulse', 'active_task_route'],
    relatedRouteDomains: ['crisis', 'vehicle_route'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 90,
    iconKey: 'alert-circle-outline',
  },
  {
    id: 'environmental_care_yesilvadi',
    districtId: 'yesilvadi',
    kind: 'environmental_care',
    title: 'Yeşilvadi Çevre Bakım Odağı',
    shortLabel: 'Çevre Bakımı',
    description:
      'Parklar, çevresel hassasiyet ve sakin tempo odaklı Yeşilvadi operasyonu.',
    districtFlavorLine: 'Yeşilvadi’de önleyici tempo ve çevre algısı önemlidir.',
    requiredPermissionId: DEFAULT_PERMISSION,
    recommendedTrustLevels: ['stable', 'trusted', 'supportive'],
    unlockAxes: ['rank_permission', 'district_trust', 'event_family_signal'],
    impactDomains: ['social', 'trust', 'map'],
    relatedEventFamilyDomains: ['social', 'district_balance', 'generic_operation'],
    relatedMapLayerIds: ['district_trust', 'social_pulse', 'district_identity'],
    relatedRouteDomains: ['social', 'district_balance'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 89,
    iconKey: 'leaf-outline',
  },
  {
    id: 'container_network_yesilvadi',
    districtId: 'yesilvadi',
    kind: 'container_network',
    title: 'Yeşilvadi Konteyner Ağı',
    shortLabel: 'Konteyner Ağı',
    description:
      'Çevre hassasiyetiyle uyumlu konteyner ağı düzenine odaklanan operasyon.',
    districtFlavorLine: 'Çevre şikayetleri görünür hale gelir; düzen hassas yönetilmeli.',
    requiredPermissionId: DEFAULT_PERMISSION,
    unlockAxes: ['rank_permission', 'resource_stability', 'district_memory'],
    impactDomains: ['container', 'trust', 'map'],
    relatedEventFamilyDomains: ['container', 'social', 'district_balance'],
    relatedMapLayerIds: ['resource_pressure', 'district_memory', 'district_trust'],
    relatedRouteDomains: ['container'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 85,
    iconKey: 'cube-outline',
  },
  {
    id: 'recovery_focus_yesilvadi',
    districtId: 'yesilvadi',
    kind: 'recovery_focus',
    title: 'Yeşilvadi Bakım Toparlanması',
    shortLabel: 'Bakım Toparlanması',
    description:
      'Bakım gecikmesi sonrası mahalle güvenini toparlayan recovery operasyonu.',
    districtFlavorLine: 'Yavaş müdahale güven düşürür; sakin tempo korunmalı.',
    requiredPermissionId: DEFAULT_PERMISSION,
    requiredTrustLevel: 'watch',
    unlockAxes: ['rank_permission', 'district_trust', 'district_memory'],
    impactDomains: ['trust', 'social', 'map'],
    relatedEventFamilyDomains: ['resource_recovery', 'social', 'district_balance'],
    relatedMapLayerIds: ['district_trust', 'district_memory', 'social_pulse'],
    relatedRouteDomains: ['social', 'district_balance'],
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 86,
    iconKey: 'refresh-outline',
  },
] as const;

export const DISTRICT_OPERATION_CATALOG_DISTRICT_IDS = MAP_DISTRICT_IDENTITY_IDS;

export function getDistrictOperationCatalogForDistrict(
  districtId: string,
): readonly DistrictOperationDefinition[] {
  return DISTRICT_OPERATION_CATALOG.filter((definition) => definition.districtId === districtId);
}
