import type { InteractionContract } from './interactionContractTypes';

function c(contract: InteractionContract): InteractionContract {
  return contract;
}

/** Merkezi etkileşim sözleşmeleri — presentation/audit seviyesi, runtime gameplay bağlamaz. */
export const INTERACTION_CONTRACT_REGISTRY: InteractionContract[] = [
  // --- Hub ---
  c({
    id: 'hub_operation_signals_static',
    componentName: 'HubOperationSignalsCard',
    surface: 'hub',
    label: 'Operasyon sinyalleri özeti',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Signals summary is informational; no detail modal in MVP.',
  }),
  c({
    id: 'hub_advisor_ask_daily',
    componentName: 'HubAdvisorCard',
    surface: 'hub',
    label: 'Danışmana Sor',
    visualAffordance: 'primary_cta',
    expectedAction: 'state_update',
    target: { type: 'state_update', actionName: 'askAdvisorForDailySummary', stateSlice: 'advisorState' },
    disabledBehavior: {
      hasDisabledState: true,
      explanationRequired: true,
      explanation: 'Günlük danışman hakkın doldu. Yarın yeni analiz alabilirsin.',
    },
  }),
  c({
    id: 'hub_advisor_card_expand',
    componentName: 'HubAdvisorCard',
    surface: 'hub',
    label: 'Danışman kartı gövdesi',
    visualAffordance: 'static_card',
    expectedAction: 'expand_collapse',
    notes: 'Insight body expands after ask; not a navigation target.',
  }),
  c({
    id: 'hub_advisor_missed_ack',
    componentName: 'AdvisorMissedSignalNote',
    surface: 'hub',
    label: 'Notu İncele',
    visualAffordance: 'inline_action',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'acknowledgeAdvisorMissedSignal',
      stateSlice: 'advisorState',
    },
  }),
  c({
    id: 'hub_daily_plan_confirm',
    componentName: 'HubDailyOperationsPlanCard',
    surface: 'hub',
    label: 'Planı Onayla',
    visualAffordance: 'primary_cta',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'confirmDailyOperationsPlan',
      stateSlice: 'dailyOperationsPlan',
    },
  }),
  c({
    id: 'hub_daily_plan_edit',
    componentName: 'HubDailyOperationsPlanCard',
    surface: 'hub',
    label: 'Düzenle',
    visualAffordance: 'secondary_cta',
    expectedAction: 'modal',
    target: { type: 'modal', modalId: 'daily_operations_plan_editor' },
    guard: { dayRange: 'post_pilot' },
    disabledBehavior: {
      hasDisabledState: true,
      explanationRequired: true,
      explanation: 'İlk gün plan düzenlemesi kapalı; önerilen planı onaylayın.',
    },
  }),
  c({
    id: 'hub_daily_plan_editor_confirm',
    componentName: 'HubDailyOperationsPlanCard',
    surface: 'hub',
    label: 'Planı Kaydet',
    visualAffordance: 'primary_cta',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'confirmDailyOperationsPlan',
      stateSlice: 'dailyOperationsPlan',
    },
    notes: 'Modal içi onay; modalId daily_operations_plan_editor.',
  }),
  c({
    id: 'hub_main_operation_season_goals_cta',
    componentName: 'HubMainOperationSeasonCard',
    surface: 'hub',
    label: 'Hedefleri Gör',
    visualAffordance: 'primary_cta',
    expectedAction: 'modal',
    target: {
      type: 'modal',
      modalId: 'main_operation_season_goals_detail',
    },
    guard: { accessMode: 'full' },
    notes: 'Full Ana Operasyon; opens MainOperationSeasonGoalDetailSheet.',
  }),
  c({
    id: 'hub_main_operation_season_limited_cta',
    componentName: 'HubMainOperationSeasonCard',
    surface: 'hub',
    label: 'Ana Operasyon Kapsamını Gör',
    visualAffordance: 'primary_cta',
    expectedAction: 'navigation',
    target: { type: 'navigation', route: '/post-pilot-offer' },
    isOptional: true,
    guard: { accessMode: 'limited' },
    notes: 'Limited gündem; no goals detail modal.',
  }),
  c({
    id: 'hub_main_operation_season_static',
    componentName: 'HubMainOperationSeasonCard',
    surface: 'hub',
    label: 'Ana operasyon sezon özeti',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Goal rows informational; CTA only when model.ctaLabel set.',
  }),
  c({
    id: 'main_operation_season_goals_detail_close',
    componentName: 'MainOperationSeasonGoalDetailSheet',
    surface: 'hub',
    label: 'Kapat',
    visualAffordance: 'inline_action',
    expectedAction: 'modal',
    target: {
      type: 'modal',
      modalId: 'main_operation_season_goals_detail',
    },
    notes: 'Closes season goals detail sheet.',
  }),
  c({
    id: 'main_operation_season_goals_detail_static',
    componentName: 'MainOperationSeasonGoalDetailSheet',
    surface: 'hub',
    label: 'Sezon hedef detay kartları',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Per-goal detail cards are read-only.',
  }),
  c({
    id: 'hub_crisis_desk_static',
    componentName: 'HubCrisisDeskCard',
    surface: 'hub',
    label: 'Kriz masası özeti',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Crisis detail screen pending; no fake CTA.',
  }),
  c({
    id: 'hub_live_ops_container',
    componentName: 'HubLiveOperationsCard',
    surface: 'hub',
    label: 'Canlı Operasyon',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Container; decisions use LiveOperationDecisionCard options.',
  }),
  c({
    id: 'hub_live_ops_option',
    componentName: 'LiveOperationDecisionCard',
    surface: 'hub',
    label: 'Canlı operasyon seçeneği',
    visualAffordance: 'option_button',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'resolveMicroDecision',
      stateSlice: 'microDecisionState',
    },
    notes: 'Resolved cards hide options; effects applied end of day.',
  }),
  c({
    id: 'hub_quick_action',
    componentName: 'HubQuickActionsPanel',
    surface: 'hub',
    label: 'Hızlı aksiyon',
    visualAffordance: 'pressable_card',
    expectedAction: 'state_update',
    target: { type: 'state_update', actionName: 'useQuickAction', stateSlice: 'hubQuickActionState' },
  }),
  c({
    id: 'hub_critical_event_nav',
    componentName: 'HubCriticalEventCard',
    surface: 'hub',
    label: 'Kritik olayı incele',
    visualAffordance: 'pressable_card',
    expectedAction: 'navigation',
    target: { type: 'navigation', route: '/events/[id]' },
    isOptional: true,
  }),
  c({
    id: 'hub_footer_end_day',
    componentName: 'HubFooterActionRow',
    surface: 'hub',
    label: 'Günü Kapat',
    visualAffordance: 'primary_cta',
    expectedAction: 'state_update',
    target: { type: 'state_update', actionName: 'endCurrentDay', stateSlice: 'gameState' },
  }),
  c({
    id: 'hub_footer_continue',
    componentName: 'HubFooterActionRow',
    surface: 'hub',
    label: 'Operasyona Devam Et',
    visualAffordance: 'secondary_cta',
    expectedAction: 'navigation',
    target: { type: 'navigation', route: '/events' },
    isOptional: true,
  }),
  c({
    id: 'hub_dev_tools',
    componentName: 'HubDevTools',
    surface: 'devtools',
    label: 'Dev araçları',
    visualAffordance: 'debug_button',
    expectedAction: 'debug_only',
    target: { type: 'debug_only', debugGuard: '**DEV**' },
    guard: { dayRange: 'dev_only' },
  }),
  c({
    id: 'hub_post_pilot_dev_tools',
    componentName: 'PostPilotDevTools',
    surface: 'devtools',
    label: 'Post-pilot dev araçları',
    visualAffordance: 'debug_button',
    expectedAction: 'debug_only',
    target: { type: 'debug_only', debugGuard: 'custom_guard' },
    guard: { dayRange: 'dev_only' },
    notes: 'isPostPilotDevToolsEnabled guard.',
  }),

  // --- Event workflow ---
  c({
    id: 'event_advisor_hint',
    componentName: 'EventAdvisorHintCard',
    surface: 'event_plan',
    label: 'Ece ipucu',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Event hint display; ask uses separate flow if CTA present.',
  }),
  c({
    id: 'event_impact_preview_static',
    componentName: 'OperationImpactPreviewStrip',
    surface: 'event_plan',
    label: 'Operasyon etki önizlemesi',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Informational summary for plan/dispatch/decision context.',
  }),
  c({
    id: 'event_assignment_confirm',
    componentName: 'EventAssignmentPanel',
    surface: 'event_dispatch',
    label: 'Atamayı Onayla',
    visualAffordance: 'primary_cta',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'confirmEventAssignment',
      stateSlice: 'assignments',
    },
  }),
  c({
    id: 'event_assignment_edit',
    componentName: 'EventAssignmentPanel',
    surface: 'event_dispatch',
    label: 'Düzenle',
    visualAffordance: 'secondary_cta',
    expectedAction: 'modal',
    target: { type: 'modal', modalId: 'assignment_editor' },
    disabledBehavior: {
      hasDisabledState: true,
      explanationRequired: true,
      explanation: 'Saha işlendikten sonra atama düzenlenemez.',
    },
  }),
  c({
    id: 'event_assignment_editor_confirm',
    componentName: 'AssignmentEditorModal',
    surface: 'event_dispatch',
    label: 'Atamayı Uygula',
    visualAffordance: 'primary_cta',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'confirmEventAssignment',
      stateSlice: 'assignments',
    },
    notes: 'modalId assignment_editor.',
  }),
  c({
    id: 'event_assignment_option',
    componentName: 'AssignmentOptionCard',
    surface: 'event_dispatch',
    label: 'Atama seçeneği',
    visualAffordance: 'option_button',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'updateEventAssignment',
      stateSlice: 'assignments',
    },
  }),
  c({
    id: 'event_field_assignment_summary',
    componentName: 'EventFieldAssignmentSummary',
    surface: 'event_field',
    label: 'Saha atama özeti',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Read-only assignment recap on field phase.',
  }),
  c({
    id: 'event_field_micro_decision',
    componentName: 'EventFieldMicroDecisionCard',
    surface: 'event_field',
    label: 'Saha canlı operasyon',
    visualAffordance: 'option_button',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'resolveMicroDecision',
      stateSlice: 'microDecisionState',
    },
    isOptional: true,
  }),
  c({
    id: 'event_dispatch_footer',
    componentName: 'DispatchWorkflowFooter',
    surface: 'event_dispatch',
    label: 'Sahaya Yönlendir',
    visualAffordance: 'primary_cta',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'markAssignmentDispatched',
      stateSlice: 'assignments',
    },
    disabledBehavior: {
      hasDisabledState: true,
      explanationRequired: true,
      explanation: 'Önce atamayı onaylayın.',
    },
  }),
  c({
    id: 'event_field_footer',
    componentName: 'FieldWorkflowFooter',
    surface: 'event_field',
    label: 'Sonucu Gör',
    visualAffordance: 'primary_cta',
    expectedAction: 'navigation',
    target: { type: 'navigation', route: '/events/decision-result' },
    disabledBehavior: {
      hasDisabledState: true,
      explanationRequired: true,
      explanation: 'Saha adımı tamamlanmadan sonuç açılmaz.',
    },
  }),

  // --- Reports ---
  c({
    id: 'report_operation_signals_static',
    componentName: 'ReportOperationSignalsCard',
    surface: 'report',
    label: 'Gün sonu sinyaller',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Mobile copy uses numberOfLines guards.',
  }),
  c({
    id: 'report_daily_plan_static',
    componentName: 'ReportDailyPlanImpactCard',
    surface: 'report',
    label: 'Günlük plan etkisi',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'report_assignment_static',
    componentName: 'ReportAssignmentBalanceCard',
    surface: 'report',
    label: 'Atama dengesi',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'report_micro_decisions_static',
    componentName: 'ReportMicroDecisionsCard',
    surface: 'report',
    label: 'Canlı operasyon kararları',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Hidden when no micro decisions that day.',
  }),
  c({
    id: 'report_main_operation_static',
    componentName: 'ReportMainOperationSeasonCard',
    surface: 'report',
    label: 'Ana operasyon sezon',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'No CTA; hidden pilot Day 1–7 and when model.visible is false.',
  }),
  c({
    id: 'report_crisis_static',
    componentName: 'ReportCrisisDeskCard',
    surface: 'report',
    label: 'Kriz masası özeti',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'report_advisor_static',
    componentName: 'ReportAdvisorCommentCard',
    surface: 'report',
    label: 'Ece yorumu',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'report_pilot_completion_cta',
    componentName: 'ReportPilotCompletionCard',
    surface: 'report',
    label: 'Ana Operasyona Geç',
    visualAffordance: 'primary_cta',
    expectedAction: 'navigation',
    target: { type: 'navigation', route: '/post-pilot-offer' },
    isOptional: true,
    notes: 'Route varies by access; completionCta from presentation.',
  }),

  // --- Post-pilot ---
  c({
    id: 'post_pilot_offer_primary',
    componentName: 'PostPilotAccessChoiceCard',
    surface: 'post_pilot',
    label: 'Ana Operasyonu Aç',
    visualAffordance: 'primary_cta',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'mockPurchaseMainOperationPack',
      stateSlice: 'monetization',
    },
    notes: 'Mock purchase; then navigates to hub from screen handler.',
  }),
  c({
    id: 'post_pilot_offer_limited',
    componentName: 'PostPilotAccessChoiceCard',
    surface: 'post_pilot',
    label: 'Sınırlı Gündemle Devam Et',
    visualAffordance: 'secondary_cta',
    expectedAction: 'state_update',
    target: {
      type: 'state_update',
      actionName: 'continueWithLimitedAgenda',
      stateSlice: 'monetization',
    },
    isOptional: true,
  }),
  c({
    id: 'post_pilot_offer_restore',
    componentName: 'PostPilotAccessChoiceCard',
    surface: 'post_pilot',
    label: 'Erişimi Kontrol Et',
    visualAffordance: 'inline_action',
    expectedAction: 'external_placeholder',
    target: {
      type: 'external_placeholder',
      actionName: 'restoreMainOperationAccessPlaceholder',
      stateSlice: 'monetization',
    },
    notes: 'Placeholder restore feedback via Alert.',
  }),
  c({
    id: 'post_pilot_offer_screen',
    componentName: 'PostPilotOfferScreen',
    surface: 'post_pilot',
    label: 'Pilot sonrası teklif ekranı',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Composes hero + feature list + access choice cards.',
  }),
  c({
    id: 'post_pilot_hero_static',
    componentName: 'PostPilotOfferHeroCard',
    surface: 'post_pilot',
    label: 'Teklif kahraman',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'post_pilot_features_static',
    componentName: 'MainOperationPackFeatureList',
    surface: 'post_pilot',
    label: 'Özellik listesi',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'main_operation_preview_nav',
    componentName: 'MainOperationPreview',
    surface: 'post_pilot',
    label: 'Ana operasyon önizleme',
    visualAffordance: 'pressable_card',
    expectedAction: 'navigation',
    target: { type: 'navigation', route: '/events/main-operation-preview' },
    isOptional: true,
  }),
  c({
    id: 'progression_bridge_card',
    componentName: 'ProgressionBridgeCard',
    surface: 'profile',
    label: 'İlerleme köprüsü',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Preview districts labeled Önizleme; no simulated lock UI.',
  }),

  // --- Map ---
  c({
    id: 'map_bottom_panel_cta',
    componentName: 'MapOperationBottomPanel',
    surface: 'map',
    label: 'Detayı Gör',
    visualAffordance: 'primary_cta',
    expectedAction: 'state_update',
    target: { type: 'state_update', actionName: 'mapFocusDistrict', stateSlice: 'mapUi' },
    notes: 'Parent passes onPressCta; selection/focus handler.',
  }),
  c({
    id: 'map_bottom_panel_recommended',
    componentName: 'MapOperationBottomPanel',
    surface: 'map',
    label: 'Önerilen aksiyon',
    visualAffordance: 'pressable_card',
    expectedAction: 'state_update',
    target: { type: 'state_update', actionName: 'mapFocusDistrict', stateSlice: 'mapUi' },
    isOptional: true,
  }),
  c({
    id: 'map_bottom_panel_static_body',
    componentName: 'MapOperationBottomPanel',
    surface: 'map',
    label: 'Bölge risk metrikleri',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Risk metric cards are informational.',
  }),
  c({
    id: 'map_neighborhood_select',
    componentName: 'MapNeighborhoodStrip',
    surface: 'map',
    label: 'Mahalle seçimi',
    visualAffordance: 'pressable_card',
    expectedAction: 'state_update',
    target: { type: 'state_update', actionName: 'mapSelectDistrict', stateSlice: 'mapUi' },
    notes: 'Crisis badge on strip is static decoration.',
  }),
  c({
    id: 'map_pin_select',
    componentName: 'MapPin',
    surface: 'map',
    label: 'Harita pini',
    visualAffordance: 'pressable_card',
    expectedAction: 'state_update',
    target: { type: 'state_update', actionName: 'mapSelectPin', stateSlice: 'mapUi' },
    isOptional: true,
    notes: 'onPress optional; static pins omit handler.',
  }),
  c({
    id: 'map_filter_tabs',
    componentName: 'MapFilterTabs',
    surface: 'map',
    label: 'Harita filtresi',
    visualAffordance: 'inline_action',
    expectedAction: 'state_update',
    target: { type: 'state_update', actionName: 'mapSetFilter', stateSlice: 'mapUi' },
  }),
  c({
    id: 'map_legend_static',
    componentName: 'MapLegend',
    surface: 'map',
    label: 'Harita açıklaması',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'map_signal_card_action',
    componentName: 'MapOperationSignalCard',
    surface: 'map',
    label: 'Sinyali izle',
    visualAffordance: 'inline_action',
    expectedAction: 'state_update',
    target: { type: 'state_update', actionName: 'mapFocusDistrict', stateSlice: 'mapUi' },
    isOptional: true,
  }),

  // --- Profile / social / leaderboard ---
  c({
    id: 'profile_authority_static',
    componentName: 'ProfileAuthorityCard',
    surface: 'profile',
    label: 'Yetki durumu',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'profile_badges_static',
    componentName: 'ProfileBadgeShowcaseCard',
    surface: 'profile',
    label: 'Rozet vitrin',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'profile_prestige_static',
    componentName: 'ProfilePrestigeCard',
    surface: 'profile',
    label: 'Prestij özeti',
    visualAffordance: 'static_card',
    expectedAction: 'none',
  }),
  c({
    id: 'social_pulse_card',
    componentName: 'HubSocialSignalCard',
    surface: 'social',
    label: 'Sosyal nabız',
    visualAffordance: 'pressable_card',
    expectedAction: 'navigation',
    target: { type: 'navigation', route: '/social' },
    isOptional: true,
  }),
  c({
    id: 'leaderboard_entry',
    componentName: 'LeaderboardScreen',
    surface: 'leaderboard',
    label: 'Liderlik listesi',
    visualAffordance: 'static_card',
    expectedAction: 'none',
    notes: 'Read-only pilot scores display.',
  }),
];

export function getInteractionContractById(id: string): InteractionContract | undefined {
  return INTERACTION_CONTRACT_REGISTRY.find((c) => c.id === id);
}

export function getInteractionContractsForComponent(
  componentName: string,
): InteractionContract[] {
  return INTERACTION_CONTRACT_REGISTRY.filter((c) => c.componentName === componentName);
}
