import type {
  ReleaseCandidateBoardItem,
  ReleaseCandidateGameplayArea,
  ReleaseCandidateStoreChecklistItem,
} from './releaseCandidateTypes';

export const RELEASE_CANDIDATE_DOCS_PATH = 'docs/crevia-release-candidate-audit.md';

export const RELEASE_CANDIDATE_EXPECTED_SAVE_VERSION = 24;

export const RELEASE_CANDIDATE_MANUAL_LAUNCH_TRACKER_PATH =
  'docs/crevia-manual-launch-blocker-tracker.md';

function gameplayArea(partial: ReleaseCandidateGameplayArea): ReleaseCandidateGameplayArea {
  return partial;
}

export const RELEASE_CANDIDATE_GAMEPLAY_AREAS: readonly ReleaseCandidateGameplayArea[] = [
  gameplayArea({
    id: 'decision_impact_explanation',
    title: 'Decision Impact Explanation',
    status: 'PASS',
    verifyCommand: 'npm run verify:decision-impact-explanation',
    playerValue: 'Karar sonucu etkisini okunur şekilde gösterir.',
    remainingBacklog: 'Real-device readability spot-check.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'tomorrow_risk',
    title: 'Tomorrow Risk',
    status: 'PASS',
    verifyCommand: 'npm run verify:tomorrow-risk',
    playerValue: 'Yarın riski hub/raporda compact görünür.',
    remainingBacklog: 'Device scroll on long risk copy.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'city_echo_binding',
    title: 'City Echo Binding',
    status: 'PASS',
    verifyCommand: 'npm run verify:city-echo-binding',
    playerValue: 'Şehir yankısı karar sonucuna bağlanır.',
    remainingBacklog: 'Pack-origin echo on device.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'main_operation_feel',
    title: 'Day 8+ Main Operation Feel',
    status: 'PASS',
    verifyCommand: 'npm run verify:main-operation-feel',
    playerValue: 'Post-pilot operasyon hissi netleşir.',
    remainingBacklog: 'Balance WARN in season sim — not blocker.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'content_runtime_activation',
    title: 'Content Pack Runtime Activation Lite',
    status: 'PASS',
    verifyCommand: 'npm run verify:content-runtime-activation',
    playerValue: 'Pack-origin eventler runtime’da görünür.',
    remainingBacklog: 'Full activation V1.1 backlog.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'district_report_card',
    title: 'Mahalle Karnesi Lite',
    status: 'PASS',
    verifyCommand: 'npm run verify:district-report-card',
    playerValue: 'Mahalle özeti map/hub’da compact.',
    remainingBacklog: 'None for soft launch lite.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'city_journal',
    title: 'Şehir Günlüğü Lite',
    status: 'PASS',
    verifyCommand: 'npm run verify:city-journal',
    playerValue: 'Şehir günlüğü strip hub’da.',
    remainingBacklog: 'Archive persistence V1.1.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'operational_resource_presence',
    title: 'Ekip & Araç Presence Lite',
    status: 'PASS',
    verifyCommand: 'npm run verify:operational-resource-presence',
    playerValue: 'Operasyonel kaynak varlığı okunur.',
    remainingBacklog: 'Detail sheet device QA.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'map_reactions',
    title: 'Dynamic Map Reaction Lite',
    status: 'PASS',
    verifyCommand: 'npm run verify:map-reactions',
    playerValue: 'Harita reaksiyonu renk+a11y ile taşınır.',
    remainingBacklog: 'Dynamic Map Reactions V1.1.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'offline_resume',
    title: 'Offline / Resume Robustness',
    status: 'WARN',
    verifyCommand: 'npm run verify:offline-resume',
    playerValue: 'Kapat/aç ve offline güvenli devam.',
    remainingBacklog: '1 known WARN (solved stub meta) — device QA.',
    launchRisk: 'low',
  }),
  gameplayArea({
    id: 'ui_density',
    title: 'UI Density + Accessibility',
    status: 'PASS',
    verifyCommand: 'npm run verify:ui-density',
    playerValue: 'Day1 sade, Day8+ priority kartlar.',
    remainingBacklog: 'Large text device smoke pending.',
    launchRisk: 'low',
  }),
] as const;

function storeItem(partial: ReleaseCandidateStoreChecklistItem): ReleaseCandidateStoreChecklistItem {
  return partial;
}

/** Static template — statuses resolved in audit from store/privacy audits. */
export function buildReleaseCandidateStoreChecklistTemplate(): ReleaseCandidateStoreChecklistItem[] {
  return [
    // A. App metadata
    storeItem({
      id: 'store.app_name',
      section: 'app_metadata',
      title: 'App name',
      status: 'draft',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'store_console',
      nextAction: 'Enter TR/EN app name in consoles.',
    }),
    storeItem({
      id: 'store.subtitle_short_description',
      section: 'app_metadata',
      title: 'Subtitle / short description',
      status: 'draft',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'store_console',
      nextAction: 'Copy from metadata draft to consoles.',
    }),
    storeItem({
      id: 'store.full_description',
      section: 'app_metadata',
      title: 'Full description',
      status: 'draft',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'store_console',
      nextAction: 'Paste finalized TR/EN descriptions.',
    }),
    storeItem({
      id: 'store.keywords',
      section: 'app_metadata',
      title: 'Keywords',
      status: 'draft',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'store_console',
      nextAction: 'Enter keyword sets per store rules.',
    }),
    storeItem({
      id: 'store.category',
      section: 'app_metadata',
      title: 'Category',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'store_console',
      nextAction: 'Select primary category in both stores.',
    }),
    storeItem({
      id: 'store.age_rating',
      section: 'app_metadata',
      title: 'Age rating',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'store_console',
      nextAction: 'Complete age rating questionnaires.',
    }),
    storeItem({
      id: 'store.support_url',
      section: 'app_metadata',
      title: 'Support URL',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['url'],
      owner: 'manual',
      nextAction: 'Publish support page URL.',
    }),
    storeItem({
      id: 'store.privacy_url',
      section: 'app_metadata',
      title: 'Privacy URL',
      status: 'blocked',
      blocksPublicLaunch: true,
      evidenceRequired: ['url'],
      owner: 'legal',
      nextAction: 'Publish hosted privacy URL (placeholder BLOCKED).',
    }),
    storeItem({
      id: 'store.contact_email',
      section: 'app_metadata',
      title: 'Contact email',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'store_console',
      nextAction: 'Add support contact email in store listings.',
    }),
    storeItem({
      id: 'store.release_notes',
      section: 'app_metadata',
      title: 'Release notes',
      status: 'draft',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console', 'manual_note'],
      owner: 'manual',
      nextAction: 'Finalize TR/EN release notes.',
    }),
    // B. Visual assets
    storeItem({
      id: 'visual.app_icon',
      section: 'visual_assets',
      title: 'App icon',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['screenshot', 'store_console'],
      owner: 'manual',
      nextAction: 'Upload 1024 master + platform icons.',
    }),
    storeItem({
      id: 'visual.iphone_screenshots',
      section: 'visual_assets',
      title: 'iPhone screenshots',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['screenshot'],
      owner: 'manual',
      nextAction: 'Capture 8 required screens on iOS.',
    }),
    storeItem({
      id: 'visual.android_screenshots',
      section: 'visual_assets',
      title: 'Android phone screenshots',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['screenshot'],
      owner: 'manual',
      nextAction: 'Capture Android device matrix screenshots.',
    }),
    storeItem({
      id: 'visual.feature_graphic',
      section: 'visual_assets',
      title: 'Feature graphic (Play)',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['screenshot'],
      owner: 'manual',
      nextAction: 'Create 1024×500 feature graphic.',
    }),
    storeItem({
      id: 'visual.screenshot_narrative_order',
      section: 'visual_assets',
      title: 'Screenshot narrative order',
      status: 'draft',
      blocksPublicLaunch: true,
      evidenceRequired: ['manual_note'],
      owner: 'manual',
      nextAction: 'Order screenshots: Hub → Event → Map → Report → Offer.',
    }),
    // C. IAP metadata
    storeItem({
      id: 'iap.product_id',
      section: 'iap_metadata',
      title: 'Product id',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'store_console',
      nextAction: 'Create iOS/Android product ids in consoles.',
    }),
    storeItem({
      id: 'iap.entitlement_id',
      section: 'iap_metadata',
      title: 'Entitlement id',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'dashboard',
      nextAction: 'Wire main_operation_full_access in RevenueCat.',
    }),
    storeItem({
      id: 'iap.offering_id',
      section: 'iap_metadata',
      title: 'Offering id',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'dashboard',
      nextAction: 'Configure default offering package.',
    }),
    storeItem({
      id: 'iap.price',
      section: 'iap_metadata',
      title: 'Price tier',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'store_console',
      nextAction: 'Set localized price tiers.',
    }),
    storeItem({
      id: 'iap.sandbox_status',
      section: 'iap_metadata',
      title: 'Sandbox purchase status',
      status: 'blocked',
      blocksPublicLaunch: true,
      evidenceRequired: ['purchase_log'],
      owner: 'manual',
      nextAction: 'Complete sandbox purchase on internal build.',
    }),
    storeItem({
      id: 'iap.restore_status',
      section: 'iap_metadata',
      title: 'Restore purchase status',
      status: 'blocked',
      blocksPublicLaunch: true,
      evidenceRequired: ['purchase_log'],
      owner: 'manual',
      nextAction: 'Verify restore flow on device.',
    }),
    // D. Privacy / data safety
    storeItem({
      id: 'privacy.data_safety_form',
      section: 'privacy_data_safety',
      title: 'Data safety forms',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['store_console'],
      owner: 'legal',
      nextAction: 'Submit App Store + Play data safety forms.',
    }),
    storeItem({
      id: 'privacy.analytics_disclosure',
      section: 'privacy_data_safety',
      title: 'Analytics disclosure',
      status: 'draft',
      blocksPublicLaunch: true,
      evidenceRequired: ['manual_note'],
      owner: 'legal',
      nextAction: 'Confirm analytics categories in forms.',
    }),
    storeItem({
      id: 'privacy.crash_disclosure',
      section: 'privacy_data_safety',
      title: 'Crash reporting disclosure',
      status: 'draft',
      blocksPublicLaunch: true,
      evidenceRequired: ['manual_note'],
      owner: 'legal',
      nextAction: 'Sentry processor listed; confirm after DSN live.',
    }),
    storeItem({
      id: 'privacy.no_raw_save',
      section: 'privacy_data_safety',
      title: 'No raw save dump statement',
      status: 'done',
      blocksPublicLaunch: false,
      evidenceRequired: ['manual_note'],
      owner: 'code',
      nextAction: 'Maintained in privacy draft.',
    }),
    // E. Build readiness
    storeItem({
      id: 'build.eas_internal',
      section: 'build_readiness',
      title: 'EAS internal build',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['manual_note'],
      owner: 'build',
      nextAction: 'Create internal EAS build for iOS + Android.',
    }),
    storeItem({
      id: 'build.sentry_dsn_internal',
      section: 'build_readiness',
      title: 'Sentry DSN on internal build',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['dashboard_event'],
      owner: 'build',
      nextAction: 'Set EXPO_PUBLIC_SENTRY_DSN on internal profile.',
    }),
    storeItem({
      id: 'build.source_maps',
      section: 'build_readiness',
      title: 'Source maps configured',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['manual_note'],
      owner: 'build',
      nextAction: 'EAS Sentry auth token + org/project.',
    }),
    storeItem({
      id: 'build.analytics_dashboard',
      section: 'build_readiness',
      title: 'Analytics dashboard connected',
      status: 'pending_console',
      blocksPublicLaunch: true,
      evidenceRequired: ['dashboard_event'],
      owner: 'dashboard',
      nextAction: 'Wire production SDK + minimum dashboard.',
    }),
    storeItem({
      id: 'build.device_test_matrix',
      section: 'build_readiness',
      title: 'Real device test matrix',
      status: 'blocked',
      blocksPublicLaunch: true,
      evidenceRequired: ['screen_recording', 'manual_note'],
      owner: 'manual',
      nextAction: 'Execute 20-case device matrix.',
    }),
  ];
}

export const RELEASE_CANDIDATE_BOARD: readonly ReleaseCandidateBoardItem[] = [
  { id: 'board.eas_internal', title: 'Create internal EAS build', column: 'now_internal_device_test' },
  { id: 'board.sentry_dsn', title: 'Set Sentry DSN on internal build', column: 'now_internal_device_test' },
  { id: 'board.device_smoke', title: 'Run device smoke matrix', column: 'now_internal_device_test' },
  { id: 'board.iap_sandbox', title: 'Run IAP sandbox purchase + restore', column: 'now_internal_device_test' },
  { id: 'board.sentry_smoke', title: 'Sentry dashboard smoke', column: 'now_internal_device_test' },
  { id: 'board.screenshots_capture', title: 'Capture store screenshots', column: 'before_soft_launch' },
  { id: 'board.metadata_console', title: 'Store metadata console entry', column: 'before_soft_launch' },
  { id: 'board.rc_keys', title: 'RevenueCat keys + offering', column: 'before_soft_launch' },
  { id: 'board.privacy_url', title: 'Publish privacy URL', column: 'before_public_launch' },
  { id: 'board.data_safety', title: 'Data safety final review', column: 'before_public_launch' },
  { id: 'board.source_maps', title: 'Source maps on EAS', column: 'before_public_launch' },
  { id: 'board.analytics_dashboard', title: 'Analytics SDK + dashboard', column: 'before_public_launch' },
  { id: 'board.city_archive', title: 'City Archive Persistence', column: 'v1_1_backlog' },
  { id: 'board.map_reactions_v1', title: 'Dynamic Map Reactions V1', column: 'v1_1_backlog' },
  { id: 'board.content_pack_full', title: 'Content Pack Activation Full', column: 'v1_1_backlog' },
  { id: 'board.vehicle_maintenance', title: 'Vehicle Maintenance Runtime', column: 'v1_1_backlog' },
  { id: 'board.ai_ece', title: 'AI Ece', column: 'v1_1_backlog' },
] as const;

export const RELEASE_CANDIDATE_NON_GOALS: readonly string[] = [
  'No fake PASS for manual blockers',
  'No fabricated store/dashboard completion',
  'No gameplay/persist/SAVE_VERSION changes',
  'No applyDecision/dayPipeline/event generation changes',
  'No new routes or large UI redesign',
  'No monetization behavior changes',
  'No AI / Remote Config / Live-Ops opening',
];

export const RELEASE_CANDIDATE_PROTECTED_PATHS = [
  'src/core/game/applyDecision.ts',
  'src/core/dayPipeline/dayPipelineOrchestrator.ts',
  'src/core/game/generateDailyEventSet.ts',
  'src/store/gamePersist.ts',
] as const;
