import type { RankPermissionId } from '@/core/rankPermissions/rankPermissionTypes';

import type { BenefitCatalogTemplate } from './authorityGameplayExpansionTypes';

export const AUTHORITY_EXPANSION_MAX_PRESENTATION_BENEFITS = 3;
export const AUTHORITY_EXPANSION_MAX_LOCKED_TEASERS = 1;
export const AUTHORITY_EXPANSION_LINE_MAX = 96;
export const AUTHORITY_EXPANSION_ACCESSIBILITY_MAX = 160;
export const AUTHORITY_EXPANSION_PRIORITY_MAX = 100;
export const POST_PILOT_STRATEGIC_DAY = 8;

/** futureKey: authority_profile_showcase — profil vitrin yetkisi henüz rank matrix'te yok. */
export const FUTURE_AUTHORITY_PERMISSION_KEYS = ['authority_profile_showcase', 'advisor_strategy_hint'] as const;

export const PERMISSION_BENEFIT_CATALOG: Partial<
  Record<RankPermissionId, readonly BenefitCatalogTemplate[]>
> = {
  district_trust_preview: [
    {
      kind: 'district_context_detail',
      domain: 'district',
      title: 'Mahalle bağlamı',
      shortLine: 'Mahalle güven hassasiyetini karar öncesi okursun.',
      unlockedLine: 'Güven etkisi ve sosyal tepki bağlantısı netleşir.',
      lockedLine: 'Bölge Sorumlusu yetkisinde mahalle bağlamı açılır.',
      priority: 72,
      tone: 'strategic',
      requiresDistrict: true,
      strategicWeight: 3,
    },
    {
      kind: 'portfolio_defer_reason',
      domain: 'portfolio',
      title: 'Erteleme gerekçesi',
      shortLine: 'Güven kaynaklı erteleme riskini daha net görürsün.',
      unlockedLine: 'Portföyde güven etkili sinyallerin neden önemli olduğu açıklanır.',
      lockedLine: 'Mahalle güveni önizlemesi portföy gerekçesini açar.',
      priority: 68,
      tone: 'strategic',
      requiresPortfolio: true,
      strategicWeight: 2,
    },
    {
      kind: 'ece_analysis_depth',
      domain: 'advisor',
      title: 'Ece güven yorumu',
      shortLine: 'Ece güven tradeoff’larını daha açık yorumlar.',
      unlockedLine: 'Danışman güven hassasiyetini stratejik öncelik olarak okur.',
      lockedLine: 'Mahalle güveni önizlemesi Ece analizini derinleştirir.',
      priority: 64,
      tone: 'positive',
      strategicWeight: 2,
    },
  ],
  resource_pressure_summary: [
    {
      kind: 'resource_pressure_detail',
      domain: 'resource',
      title: 'Kaynak baskısı ayrımı',
      shortLine: 'Personel, araç ve konteyner baskısını ayırırsın.',
      unlockedLine: 'Kaynak maliyeti plan ve operasyonda ayrıştırılmış görünür.',
      lockedLine: 'Saha Koordinatörü yetkisinde kaynak özeti açılır.',
      priority: 70,
      tone: 'strategic',
      strategicWeight: 3,
    },
    {
      kind: 'portfolio_cost_explanation',
      domain: 'portfolio',
      title: 'Kapasite maliyeti',
      shortLine: 'Portföyde kaynak maliyetinin nedenini okursun.',
      unlockedLine: 'Sinyal seçiminde kaynak maliyeti açıklanır.',
      lockedLine: 'Kaynak özeti portföy maliyet açıklamasını açar.',
      priority: 66,
      tone: 'neutral',
      requiresPortfolio: true,
      strategicWeight: 2,
    },
    {
      kind: 'operation_tradeoff_hint',
      domain: 'operation',
      title: 'Operasyon tradeoff',
      shortLine: 'Hızlı müdahale ile kaynak maliyetini bilinçli tartarsın.',
      unlockedLine: 'Plan ve yönlendirmede kaynak tradeoff ipuçları görünür.',
      lockedLine: 'Kaynak özeti operasyon tradeoff ipuçlarını açar.',
      priority: 62,
      tone: 'strategic',
      strategicWeight: 2,
    },
  ],
  assignment_fit_preview: [
    {
      kind: 'assignment_fit_reason',
      domain: 'assignment',
      title: 'Atama uyumu',
      shortLine: 'Ekip ve araç uyum nedenlerini görev öncesi okursun.',
      unlockedLine: 'Yönlendirmede uyum nedenleri ayrıştırılmış görünür.',
      lockedLine: 'Saha Koordinatörü yetkisinde atama uyumu açılır.',
      priority: 74,
      tone: 'strategic',
      strategicWeight: 3,
    },
    {
      kind: 'route_support_reason',
      domain: 'operation',
      title: 'Rota desteği',
      shortLine: 'Rota baskısı ve araç uygunluğunu birlikte okursun.',
      unlockedLine: 'Rota desteği atama kararında gerekçelenir.',
      lockedLine: 'Atama uyumu rota destek gerekçesini açar.',
      priority: 68,
      tone: 'neutral',
      strategicWeight: 2,
    },
    {
      kind: 'operation_tradeoff_hint',
      domain: 'operation',
      title: 'Atama tradeoff',
      shortLine: 'Riskli atamadan önce yorulmuş ekipleri fark edersin.',
      unlockedLine: 'Saha ve yönlendirmede atama tradeoff ipuçları netleşir.',
      lockedLine: 'Atama uyumu operasyon tradeoff ipuçlarını açar.',
      priority: 65,
      tone: 'strategic',
      strategicWeight: 2,
    },
  ],
  advisor_specialist_notes_preview: [
    {
      kind: 'tomorrow_priority_reason',
      domain: 'tomorrow',
      title: 'Yarın önceliği',
      shortLine: 'Seçimin yarınki rota ve kaynak etkisini önceden okursun.',
      unlockedLine: 'Yarın riski rota, kaynak veya sosyal baskı olarak ayrışır.',
      lockedLine: 'Operasyon Asistanı yetkisinde yarın önceliği açılır.',
      priority: 71,
      tone: 'strategic',
      strategicWeight: 3,
    },
    {
      kind: 'portfolio_defer_reason',
      domain: 'portfolio',
      title: 'Erteleme önceliği',
      shortLine: 'Hangi sinyali yarına bırakmanın riskli olduğunu görürsün.',
      unlockedLine: 'Portföyde yarın etkili sinyaller gerekçelenir.',
      lockedLine: 'Ece uzmanlık notları portföy erteleme gerekçesini açar.',
      priority: 67,
      tone: 'strategic',
      requiresPortfolio: true,
      strategicWeight: 2,
    },
    {
      kind: 'ece_analysis_depth',
      domain: 'advisor',
      title: 'Ece strateji derinliği',
      shortLine: 'Ece bazı tradeoff’ları daha açık yorumlayabilir.',
      unlockedLine: 'Danışman yarın ve bugün dengesini stratejik okur.',
      lockedLine: 'Ece uzmanlık notları analiz derinliğini artırır.',
      priority: 63,
      tone: 'positive',
      strategicWeight: 2,
    },
  ],
  map_trust_layer: [
    {
      kind: 'map_layer_detail',
      domain: 'map',
      title: 'Güven katmanı',
      shortLine: 'Hangi mahallede güven hassas olduğunu haritada okursun.',
      unlockedLine: 'Güven katmanı haritada karşılaştırılabilir.',
      lockedLine: 'Şehir Operasyon Yöneticisi yetkisinde güven katmanı açılır.',
      priority: 69,
      tone: 'strategic',
      requiresMap: true,
      strategicWeight: 3,
    },
    {
      kind: 'district_context_detail',
      domain: 'district',
      title: 'Harita mahalle bağlamı',
      shortLine: 'Haritadan mahalle güven bağlamına geçersin.',
      unlockedLine: 'Güven katmanı mahalle seçimini destekler.',
      lockedLine: 'Güven harita katmanı mahalle bağlamını açar.',
      priority: 64,
      tone: 'neutral',
      requiresMap: true,
      requiresDistrict: true,
      strategicWeight: 2,
    },
  ],
  map_resource_layer: [
    {
      kind: 'map_layer_detail',
      domain: 'map',
      title: 'Kaynak katmanı',
      shortLine: 'Kaynak baskısını harita üzerinde özetlersin.',
      unlockedLine: 'Kaynak katmanı bölge seçimini destekler.',
      lockedLine: 'Şehir Operasyon Yöneticisi yetkisinde kaynak katmanı açılır.',
      priority: 70,
      tone: 'strategic',
      requiresMap: true,
      strategicWeight: 3,
    },
    {
      kind: 'resource_pressure_detail',
      domain: 'resource',
      title: 'Harita kaynak okuması',
      shortLine: 'Hangi bölgenin kaynak baskısı yarattığını haritada görürsün.',
      unlockedLine: 'Kaynak dağılımı haritadan plana taşınır.',
      lockedLine: 'Kaynak harita katmanı baskı okumasını açar.',
      priority: 66,
      tone: 'neutral',
      requiresMap: true,
      strategicWeight: 2,
    },
    {
      kind: 'portfolio_extra_signal_visibility',
      domain: 'portfolio',
      title: 'Portföy sinyal okuması',
      shortLine: 'Yetki sayesinde kaynak sinyalinin neden önemli olduğunu net görürsün.',
      unlockedLine: 'Portföy limiti artmaz; sinyal gerekçesi derinleşir.',
      lockedLine: 'Kaynak katmanı portföy sinyal açıklamasını açar.',
      priority: 62,
      tone: 'positive',
      requiresPortfolio: true,
      requiresMap: true,
      strategicWeight: 2,
    },
  ],
  district_memory_trace_preview: [
    {
      kind: 'district_memory_trace_detail',
      domain: 'memory',
      title: 'Mahalle hafıza izi',
      shortLine: 'Önceki kararların mahallede bıraktığı izi okursun.',
      unlockedLine: 'Hafıza izi mahalle bağlamında görünür.',
      lockedLine: 'Bölge Sorumlusu yetkisinde hafıza izi açılır.',
      priority: 68,
      tone: 'strategic',
      requiresDistrict: true,
      strategicWeight: 3,
    },
    {
      kind: 'city_archive_reading',
      domain: 'profile',
      title: 'Şehir arşivi okuması',
      shortLine: 'Geçmiş kararların bugünkü fırsatı nasıl şekillendirdiğini anlarsın.',
      unlockedLine: 'Arşiv izi stratejik bağlam olarak okunur.',
      lockedLine: 'Hafıza izi önizlemesi arşiv okumasını açar.',
      priority: 60,
      tone: 'neutral',
      strategicWeight: 2,
    },
    {
      kind: 'decision_consequence_explanation',
      domain: 'operation',
      title: 'Karar sonucu açıklaması',
      shortLine: 'Karar izlerinin bugünkü operasyona etkisini görürsün.',
      unlockedLine: 'Sonuç fazında karar izi gerekçesi netleşir.',
      lockedLine: 'Hafıza izi karar sonucu açıklamasını açar.',
      priority: 58,
      tone: 'strategic',
      strategicWeight: 2,
    },
  ],
  daily_plan_preview: [
    {
      kind: 'operation_tradeoff_hint',
      domain: 'operation',
      title: 'Günlük plan ipucu',
      shortLine: 'Sabah planında operasyon odağını daha erken okursun.',
      unlockedLine: 'Plan önizlemesi günün tradeoff’unu hazırlar.',
      lockedLine: 'Operasyon Asistanı yetkisinde plan önizlemesi açılır.',
      priority: 55,
      tone: 'neutral',
      strategicWeight: 1,
    },
  ],
  inspect_basic_events: [
    {
      kind: 'authority_title_prestige',
      domain: 'profile',
      title: 'Görev unvanı',
      shortLine: 'Temel operasyon yetkisiyle görev unvanın görünür olur.',
      unlockedLine: 'Profilde görev seviyesi ve temel yetki vitrini açılır.',
      lockedLine: 'Saha Gözlemcisi yetkisinde temel unvan görünür.',
      priority: 40,
      tone: 'positive',
      strategicWeight: 0,
    },
  ],
  reward_recovery_event_preview: [
    {
      kind: 'badge_showcase_unlock',
      domain: 'achievement',
      title: 'Toparlanma vitrini',
      shortLine: 'Kazanım ve toparlanma fırsatları vitrinde görünür.',
      unlockedLine: 'Başarı vitrininde toparlanma fırsatları öne çıkar.',
      lockedLine: 'Strateji Koordinatörü yetkisinde toparlanma vitrini açılır.',
      priority: 52,
      tone: 'positive',
      strategicWeight: 2,
    },
  ],
  team_specialization_preview: [
    {
      kind: 'assignment_fit_reason',
      domain: 'assignment',
      title: 'Ekip uzmanlığı',
      shortLine: 'Ekiplerin güçlü olduğu operasyon türlerini görürsün.',
      unlockedLine: 'Uzmanlık uyumu atama kararını destekler.',
      lockedLine: 'Operasyon Sorumlusu yetkisinde ekip uzmanlığı açılır.',
      priority: 61,
      tone: 'strategic',
      strategicWeight: 2,
    },
  ],
  vehicle_maintenance_window_preview: [
    {
      kind: 'route_support_reason',
      domain: 'operation',
      title: 'Bakım penceresi',
      shortLine: 'Filo yorgunluğu ve bakım penceresini operasyon öncesi okursun.',
      unlockedLine: 'Araç baskısı ve bakım riski ayrı okunur.',
      lockedLine: 'Operasyon Sorumlusu yetkisinde bakım penceresi açılır.',
      priority: 59,
      tone: 'neutral',
      strategicWeight: 2,
    },
  ],
};

export const RANK_LABEL_BY_KEY: Record<string, string> = {
  field_observer: 'Saha Gözlemcisi',
  operations_assistant: 'Operasyon Asistanı',
  field_coordinator: 'Saha Koordinatörü',
  district_supervisor: 'Bölge Sorumlusu',
  operations_supervisor: 'Operasyon Sorumlusu',
  city_operations_manager: 'Şehir Operasyon Yöneticisi',
  strategy_coordinator: 'Strateji Koordinatörü',
  chief_operations_director: 'Baş Operasyon Direktörü',
};
