import type { IapSandboxQaChecklistItem } from './iapSandboxQaTypes';

export const IAP_SANDBOX_QA_DOCS_PATH = 'docs/crevia-iap-sandbox-qa.md';
export const IAP_INTEGRATION_DOCS_PATH = 'docs/crevia-iap-integration.md';

export const IAP_SANDBOX_QA_ENV_KEYS = {
  ios: 'EXPO_PUBLIC_REVENUECAT_IOS_API_KEY',
  android: 'EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY',
  appUserId: 'EXPO_PUBLIC_REVENUECAT_APP_USER_ID',
} as const;

export const IAP_SANDBOX_QA_AREAS = [
  'env_config',
  'revenuecat_dashboard',
  'app_store_connect',
  'play_console',
  'native_capabilities',
  'development_build',
  'purchase_flow',
  'restore_flow',
  'mock_flow',
  'analytics',
  'soft_launch_readiness',
  'release_blockers',
] as const;

function item(
  partial: IapSandboxQaChecklistItem,
): IapSandboxQaChecklistItem {
  return partial;
}

export const IAP_SANDBOX_QA_CHECKLIST: IapSandboxQaChecklistItem[] = [
  // env_config
  item({
    id: 'env.ios_public_key',
    area: 'env_config',
    title: 'EXPO_PUBLIC_REVENUECAT_IOS_API_KEY (public SDK key)',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'appl_* public key set; not placeholder or secret.',
    failSignal: 'Missing, placeholder, or secret pattern.',
  }),
  item({
    id: 'env.android_public_key',
    area: 'env_config',
    title: 'EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY (public SDK key)',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'goog_* public key set; not placeholder or secret.',
    failSignal: 'Missing, placeholder, or secret pattern.',
  }),
  item({
    id: 'env.no_secret_key',
    area: 'env_config',
    title: 'Secret RevenueCat key not used in client',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'No sk_/rcsk_/secret pattern in public env.',
    failSignal: 'Secret key detected — rotate and remove from app.',
  }),
  item({
    id: 'env.dev_mock_fallback',
    area: 'env_config',
    title: 'Dev mock fallback when keys missing',
    requiredForSandbox: false,
    requiredForProduction: false,
    checkType: 'automatic',
    passCriteria: '__DEV__ without keys uses mock mode; no crash.',
    failSignal: 'Runtime throws or production crashes without keys.',
  }),
  item({
    id: 'env.production_graceful_disabled',
    area: 'env_config',
    title: 'Production without keys disables purchase gracefully',
    requiredForSandbox: false,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'disabled mode; CTA blocked with friendly copy.',
    failSignal: 'Unhandled purchase attempt or crash.',
  }),

  // revenuecat_dashboard
  item({
    id: 'rc.project_created',
    area: 'revenuecat_dashboard',
    title: 'RevenueCat project created',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Project exists in RevenueCat dashboard.',
    failSignal: 'No project configured.',
  }),
  item({
    id: 'rc.ios_app',
    area: 'revenuecat_dashboard',
    title: 'RevenueCat iOS app configured',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'iOS app + public SDK key linked.',
    failSignal: 'iOS app missing.',
  }),
  item({
    id: 'rc.android_app',
    area: 'revenuecat_dashboard',
    title: 'RevenueCat Android app configured',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Android app + public SDK key linked.',
    failSignal: 'Android app missing.',
  }),
  item({
    id: 'rc.entitlement',
    area: 'revenuecat_dashboard',
    title: 'Entitlement main_operation_full_access',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Entitlement id matches code constant.',
    failSignal: 'Entitlement id mismatch in docs/code.',
  }),
  item({
    id: 'rc.product_ios_attached',
    area: 'revenuecat_dashboard',
    title: 'Product crevia.main_operation.season1 attached',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'iOS store product linked to entitlement.',
    failSignal: 'Product not attached.',
  }),
  item({
    id: 'rc.product_android_attached',
    area: 'revenuecat_dashboard',
    title: 'Product crevia_main_operation_season_1 attached',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Android store product linked to entitlement.',
    failSignal: 'Product not attached.',
  }),
  item({
    id: 'rc.offering_package',
    area: 'revenuecat_dashboard',
    title: 'Offering/package with main_operation_season_1',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Default/current offering contains matching package.',
    failSignal: 'getOfferings empty or no matching package.',
  }),
  item({
    id: 'rc.sandbox_customer',
    area: 'revenuecat_dashboard',
    title: 'Sandbox customer purchase verified',
    requiredForSandbox: true,
    requiredForProduction: false,
    checkType: 'manual',
    passCriteria: 'Test purchase shows active entitlement in dashboard.',
    failSignal: 'No sandbox transaction recorded.',
  }),

  // app_store_connect
  item({
    id: 'asc.product_id',
    area: 'app_store_connect',
    title: 'IAP product crevia.main_operation.season1',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Product id documented and matches RevenueCat mapping.',
    failSignal: 'Product id mismatch.',
  }),
  item({
    id: 'asc.product_type',
    area: 'app_store_connect',
    title: 'Non-consumable one-time unlock',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Non-consumable (not subscription).',
    failSignal: 'Wrong product type.',
  }),
  item({
    id: 'asc.metadata',
    area: 'app_store_connect',
    title: 'Product metadata complete',
    requiredForSandbox: false,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Display name and description localized.',
    failSignal: 'Missing metadata.',
  }),
  item({
    id: 'asc.price_tier',
    area: 'app_store_connect',
    title: 'Price tier selected',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Price tier active for sandbox.',
    failSignal: 'Pricing not set.',
  }),
  item({
    id: 'asc.sandbox_status',
    area: 'app_store_connect',
    title: 'IAP ready for sandbox testing',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Product status allows sandbox purchase.',
    failSignal: 'Missing agreements or product not cleared.',
  }),
  item({
    id: 'asc.sandbox_tester',
    area: 'app_store_connect',
    title: 'Sandbox tester account',
    requiredForSandbox: true,
    requiredForProduction: false,
    checkType: 'manual',
    passCriteria: 'Sandbox Apple ID configured on device.',
    failSignal: 'No sandbox tester.',
  }),

  // play_console
  item({
    id: 'play.product_id',
    area: 'play_console',
    title: 'Product id crevia_main_operation_season_1',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Product id matches code/docs.',
    failSignal: 'Product id mismatch.',
  }),
  item({
    id: 'play.one_time_product',
    area: 'play_console',
    title: 'One-time managed product (not subscription)',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'In-app product one-time unlock.',
    failSignal: 'Subscription/base plan used incorrectly.',
  }),
  item({
    id: 'play.price_active',
    area: 'play_console',
    title: 'Price active',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Product price published for test track.',
    failSignal: 'Price inactive.',
  }),
  item({
    id: 'play.license_tester',
    area: 'play_console',
    title: 'License tester account',
    requiredForSandbox: true,
    requiredForProduction: false,
    checkType: 'manual',
    passCriteria: 'Gmail added to license testers.',
    failSignal: 'Purchase fails on test device.',
  }),
  item({
    id: 'play.internal_track',
    area: 'play_console',
    title: 'Internal testing build uploaded',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Dev build on internal track if required by Play.',
    failSignal: 'Billing unavailable — upload build first.',
  }),

  // native_capabilities
  item({
    id: 'native.ios_iap_capability',
    area: 'native_capabilities',
    title: 'iOS In-App Purchase capability',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Xcode target capability enabled after prebuild.',
    failSignal: 'Capability missing — purchases fail on iOS.',
  }),
  item({
    id: 'native.ios_deployment_13_4',
    area: 'native_capabilities',
    title: 'iOS deployment target >= 13.4',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Documented in IAP sandbox QA docs.',
    failSignal: 'Requirement not documented.',
  }),
  item({
    id: 'native.android_api_23',
    area: 'native_capabilities',
    title: 'Android minSdkVersion >= 23',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Documented; verify after EAS prebuild.',
    failSignal: 'Requirement not documented.',
  }),
  item({
    id: 'native.android_billing_permission',
    area: 'native_capabilities',
    title: 'Android BILLING permission',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'com.android.vending.BILLING in manifest after prebuild.',
    failSignal: 'Permission missing in generated manifest.',
  }),
  item({
    id: 'native.dev_build_required',
    area: 'native_capabilities',
    title: 'Development build required (not Expo Go)',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Docs state Expo Go cannot run native purchases.',
    failSignal: 'Team attempts purchase in Expo Go.',
  }),
  item({
    id: 'native.expo_go_unsupported',
    area: 'native_capabilities',
    title: 'Expo Go unsupported for real IAP',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Documented in integration + sandbox QA docs.',
    failSignal: 'Missing warning in docs.',
  }),

  // development_build
  item({
    id: 'devbuild.eas_created',
    area: 'development_build',
    title: 'EAS development build created',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'eas build --profile development completed.',
    failSignal: 'No dev build artifact.',
  }),
  item({
    id: 'devbuild.ios_installed',
    area: 'development_build',
    title: 'iOS dev build installed on device',
    requiredForSandbox: true,
    requiredForProduction: false,
    checkType: 'manual',
    passCriteria: 'Physical device or simulator with store login.',
    failSignal: 'Cannot test iOS purchase.',
  }),
  item({
    id: 'devbuild.android_installed',
    area: 'development_build',
    title: 'Android dev build installed',
    requiredForSandbox: true,
    requiredForProduction: false,
    checkType: 'manual',
    passCriteria: 'Internal track or local install with testers.',
    failSignal: 'Cannot test Android purchase.',
  }),
  item({
    id: 'devbuild.revenuecat_configure',
    area: 'development_build',
    title: 'RevenueCat configure succeeds',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'No native module null; configure once.',
    failSignal: 'RNPurchases null or configure error.',
  }),
  item({
    id: 'devbuild.get_offerings',
    area: 'development_build',
    title: 'getOfferings returns package',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'PostPilotOffer shows product/price if available.',
    failSignal: 'Empty offerings — check RC dashboard.',
  }),

  // purchase_flow
  item({
    id: 'purchase.pilot_day7_offer',
    area: 'purchase_flow',
    title: 'Pilot Day 7 → post-pilot offer reachable',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'shouldRouteToPostPilotOffer path exists.',
    failSignal: 'Offer screen unreachable.',
  }),
  item({
    id: 'purchase.cta_starts_flow',
    area: 'purchase_flow',
    title: 'Ana Operasyonu Aç starts purchase',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'purchaseIapProduct wired on screen.',
    failSignal: 'CTA not connected.',
  }),
  item({
    id: 'purchase.cancellation_friendly',
    area: 'purchase_flow',
    title: 'User cancellation friendly',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'cancelled status without scary error.',
    failSignal: 'Aggressive error on cancel.',
  }),
  item({
    id: 'purchase.entitlement_applied',
    area: 'purchase_flow',
    title: 'Completed purchase applies entitlement',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'applyIapEntitlementToMonetization in store.',
    failSignal: 'Missing store sync.',
  }),
  item({
    id: 'purchase.full_access_state',
    area: 'purchase_flow',
    title: 'mainOperationAccess full after unlock',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'applyIapEntitlementToMonetizationState sets full.',
    failSignal: 'Access remains limited.',
  }),
  item({
    id: 'purchase.sandbox_manual',
    area: 'purchase_flow',
    title: 'Sandbox purchase smoke test',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Real sandbox transaction completes on device.',
    failSignal: 'Purchase not manually verified.',
  }),

  // restore_flow
  item({
    id: 'restore.cta_visible',
    area: 'restore_flow',
    title: 'Restore CTA visible',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'PostPilotAccessChoiceCard restore label.',
    failSignal: 'Restore hidden.',
  }),
  item({
    id: 'restore.user_action_only',
    area: 'restore_flow',
    title: 'restorePurchases only on user CTA',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'No restoreIapPurchases in mount bootstrap.',
    failSignal: 'Automatic restore on mount.',
  }),
  item({
    id: 'restore.no_sync_purchases',
    area: 'restore_flow',
    title: 'No syncPurchases in MVP',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Adapter does not call syncPurchases.',
    failSignal: 'syncPurchases used.',
  }),
  item({
    id: 'restore.restored_entitlement',
    area: 'restore_flow',
    title: 'Restored applies entitlement',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'handleRestore calls apply on restored.',
    failSignal: 'Restore success not applied.',
  }),
  item({
    id: 'restore.not_found_copy',
    area: 'restore_flow',
    title: 'not_found friendly copy',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'IAP_STATUS_COPY / offer copy for not_found.',
    failSignal: 'Harsh or missing copy.',
  }),
  item({
    id: 'restore.sandbox_manual',
    area: 'restore_flow',
    title: 'Sandbox restore smoke test',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Restore on second device or reinstall works.',
    failSignal: 'Restore not manually tested.',
  }),

  // mock_flow
  item({
    id: 'mock.dev_without_keys',
    area: 'mock_flow',
    title: 'DEV without keys uses mock purchase',
    requiredForSandbox: false,
    requiredForProduction: false,
    checkType: 'automatic',
    passCriteria: 'shouldUseMockPurchaseForOfferScreen + mockPurchase.',
    failSignal: 'Dev flow broken.',
  }),
  item({
    id: 'mock.full_operation',
    area: 'mock_flow',
    title: 'Mock unlock opens full operation',
    requiredForSandbox: false,
    requiredForProduction: false,
    checkType: 'automatic',
    passCriteria: 'mockPurchaseMainOperationPack sets full.',
    failSignal: 'Mock does not unlock.',
  }),
  item({
    id: 'mock.limited_flow',
    area: 'mock_flow',
    title: 'Limited continue still works',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'continueWithLimitedAgenda preserved.',
    failSignal: 'Limited path broken.',
  }),
  item({
    id: 'mock.production_no_crash',
    area: 'mock_flow',
    title: 'Production no-key crash-free',
    requiredForSandbox: false,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'disabled mode in runtime service.',
    failSignal: 'Crash without keys.',
  }),

  // analytics
  item({
    id: 'analytics.purchase_events',
    area: 'analytics',
    title: 'iap_purchase_* events schema valid',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Analytics schema defines purchase events.',
    failSignal: 'Invalid or missing events.',
  }),
  item({
    id: 'analytics.restore_events',
    area: 'analytics',
    title: 'iap_restore_* events schema valid',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Restore events in schema.',
    failSignal: 'Missing restore events.',
  }),
  item({
    id: 'analytics.no_raw_error',
    area: 'analytics',
    title: 'No raw error in analytics payloads',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Screen uses resultBand/source enums.',
    failSignal: 'Error message string in payload.',
  }),
  item({
    id: 'analytics.instrumented_screen',
    area: 'analytics',
    title: 'PostPilotOfferScreen tracks IAP events',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'trackAnalyticsEvent calls present.',
    failSignal: 'Instrumentation missing.',
  }),

  // soft_launch_readiness
  item({
    id: 'softlaunch.readiness_audit',
    area: 'soft_launch_readiness',
    title: 'verify:soft-launch-readiness compatible',
    requiredForSandbox: false,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Soft launch audit references IAP sandbox QA.',
    failSignal: 'Drift between audits.',
  }),

  // release_blockers
  item({
    id: 'blocker.secret_key',
    area: 'release_blockers',
    title: 'No secret key in client env',
    requiredForSandbox: true,
    requiredForProduction: true,
    checkType: 'automatic',
    passCriteria: 'Secret patterns rejected.',
    failSignal: 'BLOCKER — remove secret from bundle.',
  }),
  item({
    id: 'blocker.public_launch_without_store',
    area: 'release_blockers',
    title: 'Public launch without store products',
    requiredForSandbox: false,
    requiredForProduction: true,
    checkType: 'manual',
    passCriteria: 'Store products live before public release.',
    failSignal: 'Launch with pending store setup.',
  }),
];

export function buildIapSandboxQaChecklist(): IapSandboxQaChecklistItem[] {
  return [...IAP_SANDBOX_QA_CHECKLIST];
}
