import type { FinalPolishGuard } from './finalPolishTypes';

/** Final polish döneminde yasaklı veya ai_later ertelenmiş kapsam. */
export const FINAL_POLISH_FORBIDDEN_SCOPE: readonly string[] = [
  'Tam gerçek zamanlı rota simülasyonu (full logistics simulation)',
  'Gerçek GPS / pathfinding',
  'Tekil personel envanteri',
  'Tekil araç filosu yönetimi',
  'Tekil konteyner kapasite simülasyonu',
  'Drag-drop dispatch',
  'Yeni büyük navigation sistemi',
  'Season 2 restart',
  'Çoklu danışman upgrade sistemi',
  'Runtime AI advisor entegrasyonu',
  'Büyük monetization redesign',
  'applyDecision refactor',
  'authority / badge / progression engine rewrite',
  'SAVE_VERSION gereksiz artış (persist shape değişmeden)',
] as const;

/** Final polish döneminde izinli kapsam. */
export const FINAL_POLISH_ALLOWED_SCOPE: readonly string[] = [
  'Content pack genişletme',
  'Event writing standard',
  'Presentation helper',
  'UI prioritization',
  'Map presentation layer',
  'Lightweight derived state',
  'Carry-over presentation',
  'Social echo presentation',
  'Advisor template variation',
  'Report preview',
  'Day 7 recap',
  'Main operation preview polish',
  'Analytics SDK adapter',
  'IAP manual setup checklist',
  'EAS smoke test checklist',
  'Manual playtest checklist',
  'Release candidate audit',
] as const;

export const FINAL_POLISH_GUARDS: FinalPolishGuard[] = [
  {
    id: 'preserve_pilot_days_1_7',
    title: 'Pilot Gün 1–7 Akışı',
    severity: 'blocker',
    description: 'Pilot günleri, event ritmi ve gün sonu pipeline değişmez.',
    appliesToGroups: [
      'scope_freeze',
      'anti_boredom_core',
      'content_safety_pack',
      'decision_visibility',
      'premium_wow',
    ],
    checkType: 'scenario',
    expectedBehavior: 'verify:pilot-rhythm ve verify:day-pipeline PASS.',
  },
  {
    id: 'preserve_day_1_tutorial',
    title: 'Gün 1 Tutorial / Progressive Reveal',
    severity: 'blocker',
    description: 'İlk gün onboarding ve kademeli UI açılımı korunur.',
    appliesToGroups: ['scope_freeze', 'decision_visibility', 'premium_wow'],
    checkType: 'scenario',
    expectedBehavior: 'verify:onboarding ve verify:first-10-minutes PASS.',
  },
  {
    id: 'preserve_apply_decision_core',
    title: 'applyDecision Core',
    severity: 'blocker',
    description: 'Karar uygulama motoru refactor edilmez.',
    appliesToGroups: ['scope_freeze', 'content_safety_pack', 'decision_visibility'],
    checkType: 'scenario',
    expectedBehavior: 'verify:decision-result ve verify:full-loop PASS; applyDecision refactor yasak.',
  },
  {
    id: 'preserve_authority_badge_progression_core',
    title: 'Authority / Badge / Progression Core',
    severity: 'blocker',
    description: 'Meta progression motorları yeniden yazılmaz.',
    appliesToGroups: ['scope_freeze', 'post_pilot_variety', 'premium_wow'],
    checkType: 'scenario',
    expectedBehavior: 'verify:authority, verify:badges, verify:meta-progression PASS.',
  },
  {
    id: 'preserve_post_pilot_phase_contract',
    title: 'Post-Pilot Phase Sözleşmesi',
    severity: 'blocker',
    description: 'limited / light / full post-pilot ayrımı korunur.',
    appliesToGroups: ['scope_freeze', 'post_pilot_variety', 'monetization_iap'],
    checkType: 'scenario',
    expectedBehavior: 'verify:post-pilot-ux ve verify:monetization-gate PASS.',
  },
  {
    id: 'preserve_monetization_gate_contract',
    title: 'Monetization Gate Sözleşmesi',
    severity: 'blocker',
    description: 'Gate, preview copy ve entitlement sözleşmesi bozulmaz.',
    appliesToGroups: ['monetization_iap', 'premium_wow'],
    checkType: 'scenario',
    expectedBehavior: 'verify:monetization-gate ve verify:iap-sandbox-qa PASS.',
  },
  {
    id: 'preserve_save_version_unless_persist_changes',
    title: 'SAVE_VERSION Disiplini',
    severity: 'fail',
    description: 'Persist shape değişmedikçe SAVE_VERSION artırılmaz.',
    appliesToGroups: ['scope_freeze'],
    checkType: 'static',
    expectedBehavior: 'Persist migration yoksa SAVE_VERSION sabit kalır.',
  },
  {
    id: 'avoid_new_routes_unless_explicit',
    title: 'Yeni Route Kısıtı',
    severity: 'fail',
    description: 'Roadmap maddesi allowsNewRoute açıkça true değilse yeni ekran eklenmez.',
    appliesToGroups: ['scope_freeze', 'decision_visibility', 'dynamic_map_presence'],
    checkType: 'manual',
    expectedBehavior: 'Navigation diff yalnızca onaylı maddelerde.',
  },
  {
    id: 'avoid_large_navigation_redesign',
    title: 'Büyük Navigation Redesign Yok',
    severity: 'fail',
    description: 'Alt nav ve hub mimarisi kökten değiştirilmez.',
    appliesToGroups: ['scope_freeze', 'post_pilot_variety'],
    checkType: 'manual',
    expectedBehavior: 'Mevcut tab/stack yapısı korunur.',
  },
  {
    id: 'avoid_full_logistics_simulation',
    title: 'Tam Lojistik Simülasyon Yok',
    severity: 'blocker',
    description: 'Gerçek zamanlı rota, GPS ve filo simülasyonu yasak.',
    appliesToGroups: ['dynamic_map_presence', 'resource_visual_states'],
    checkType: 'manual',
    expectedBehavior: 'Harita yalnızca presentation / derived state katmanı.',
  },
  {
    id: 'avoid_individual_inventory_management',
    title: 'Tekil Envanter Yok',
    severity: 'blocker',
    description: 'Personel/araç/konteyner tekil envanter yönetimi eklenmez.',
    appliesToGroups: ['dynamic_map_presence', 'content_safety_pack'],
    checkType: 'manual',
    expectedBehavior: 'Aggregate operational signals kullanılır.',
  },
  {
    id: 'avoid_drag_drop_dispatch',
    title: 'Drag-Drop Dispatch Yok',
    severity: 'blocker',
    description: 'Sürükle-bırak dispatch UI eklenmez.',
    appliesToGroups: ['dynamic_map_presence', 'decision_visibility'],
    checkType: 'manual',
    expectedBehavior: 'Mevcut karar kartı akışı korunur.',
  },
  {
    id: 'avoid_runtime_ai_before_ai_phase',
    title: 'Runtime AI Erken Entegrasyon Yok',
    severity: 'blocker',
    description: 'AI maddeleri ai_later grubunda; runtime entegrasyon yasak.',
    appliesToGroups: ['ai_later', 'advisor_depth'],
    checkType: 'static',
    expectedBehavior: 'AI roadmap status later; main path dışında.',
  },
  {
    id: 'require_verify_script_for_new_patch',
    title: 'Patch Verify Script Zorunlu',
    severity: 'fail',
    description: 'Her patch verify:final-polish ve ilgili domain verify ile kapanır.',
    appliesToGroups: ['scope_freeze', 'release_candidate', 'manual_playtest'],
    checkType: 'scenario',
    expectedBehavior: 'npm run verify:final-polish 0 FAIL.',
  },
  {
    id: 'require_mobile_overflow_guards',
    title: 'Mobile Overflow Guard',
    severity: 'warn',
    description: 'UI patch’lerinde taşma ve küçük ekran kırılımı kontrol edilir.',
    appliesToGroups: [
      'decision_visibility',
      'dynamic_map_presence',
      'premium_wow',
      'post_pilot_variety',
    ],
    checkType: 'manual',
    expectedBehavior: 'ScrollView / flexShrink / numberOfLines kullanımı.',
  },
  {
    id: 'require_privacy_safe_analytics',
    title: 'Privacy-Safe Analytics',
    severity: 'fail',
    description: 'Analytics yalnızca onaylı şema ve privacy kurallarıyla.',
    appliesToGroups: ['analytics_sdk'],
    checkType: 'scenario',
    expectedBehavior: 'verify:analytics-runtime ve verify:analytics-events PASS.',
  },
  {
    id: 'require_devtools_guard',
    title: 'Devtools Guard',
    severity: 'warn',
    description: 'Debug araçları production bundle’da guard altında.',
    appliesToGroups: ['scope_freeze', 'release_candidate'],
    checkType: 'manual',
    expectedBehavior: '__DEV__ veya explicit guard.',
  },
  {
    id: 'require_no_paywall_language_in_preview_copy',
    title: 'Preview Copy Paywall Dili Yok',
    severity: 'warn',
    description: 'Önizleme metinlerinde agresif paywall dili kullanılmaz.',
    appliesToGroups: ['monetization_iap', 'premium_wow'],
    checkType: 'scenario',
    expectedBehavior: 'verify:monetization-gate ve IAP forbidden words PASS.',
  },
];
