import type { FinalPolishRoadmapItem } from './finalPolishTypes';

function item(
  partial: FinalPolishRoadmapItem,
): FinalPolishRoadmapItem {
  return partial;
}

export const FINAL_POLISH_ROADMAP: FinalPolishRoadmapItem[] = [
  item({
    id: 'scope-freeze-final-polish-guard',
    title: 'Scope Freeze & Final Polish Guard',
    group: 'scope_freeze',
    priority: 'mandatory',
    status: 'completed',
    softLaunchImpact: 'critical',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description:
      'Soft-launch öncesi merkezi roadmap, guard ve verify altyapısı. Gameplay core değişmez.',
    acceptanceChecks: [
      'verify:final-polish 0 FAIL',
      'Roadmap ve guard registry dokümante',
      'Forbidden/allowed scope listeleri mevcut',
    ],
    forbiddenChanges: [
      'applyDecision refactor',
      'SAVE_VERSION gereksiz artış',
      'Yeni gameplay sistemi',
    ],
  }),
  item({
    id: 'daily-theme-rhythm',
    title: 'Daily Theme Rhythm',
    group: 'anti_boredom_core',
    priority: 'critical',
    status: 'completed',
    softLaunchImpact: 'high',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description:
      'Günlük tema ritmi: pilot ve post-pilot günlerinde tekrar hissini azaltan hafif tema varyasyonu (presentation + content tagging).',
    acceptanceChecks: [
      'Gün başına tema etiketi görünür',
      'Pilot 1–7 ritmi bozulmaz',
      'verify:pilot-rhythm PASS',
    ],
    forbiddenChanges: ['applyDecision refactor', 'Yeni event generation motoru'],
  }),
  item({
    id: 'dynamic-event-writing-standard',
    title: 'Dynamic Event Writing Standard + Content Schema Audit',
    group: 'anti_boredom_core',
    priority: 'critical',
    status: 'completed',
    softLaunchImpact: 'high',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description:
      'Event yazım standardı, schema audit ve authoring guide uyumu; yeni generation motoru yok.',
    acceptanceChecks: [
      'verify:event-writing-standard PASS',
      'verify:event-authoring PASS',
      'Schema audit raporu güncel',
    ],
    forbiddenChanges: ['Event generation pipeline değişimi'],
  }),
  item({
    id: 'content-safety-pack-stage-1',
    title: 'Content Safety Pack Aşama 1: Mahalle + Konteyner Events',
    group: 'content_safety_pack',
    priority: 'critical',
    status: 'completed',
    softLaunchImpact: 'high',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Mahalle ve konteyner domain event içerik güvenliği ve çeşitlilik paketi.',
    acceptanceChecks: ['verify:event-content ilgili domain PASS', 'Yasaklı kelime taraması temiz'],
    forbiddenChanges: ['applyDecision refactor'],
  }),
  item({
    id: 'content-safety-pack-stage-2',
    title: 'Content Safety Pack Aşama 2: Araç/Rota + Personel/Moral + Sosyal/Kriz Events',
    group: 'content_safety_pack',
    priority: 'critical',
    status: 'completed',
    softLaunchImpact: 'high',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Araç, personel, sosyal ve kriz event içerik güvenliği aşama 2.',
    acceptanceChecks: ['verify:vehicle-events ve verify:personnel senaryoları PASS'],
    forbiddenChanges: ['Tam rota simülasyonu', 'Tekil envanter'],
  }),
  item({
    id: 'content-safety-pack-stage-3',
    title: 'Content Safety Pack Aşama 3: Ece + Social Mentions + Report Echo Variations',
    group: 'content_safety_pack',
    priority: 'high',
    status: 'completed',
    softLaunchImpact: 'medium',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Ece, sosyal mention ve rapor echo varyasyonları içerik paketi.',
    acceptanceChecks: ['verify:social PASS', 'Report echo copy audit'],
    forbiddenChanges: ['Runtime AI yorum üretimi'],
  }),
  item({
    id: 'event-domain-ui-prioritization',
    title: 'Event Domain UI Prioritization',
    group: 'decision_visibility',
    priority: 'high',
    status: 'completed',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Event kartlarında domain önceliklendirme ve görsel hiyerarşi (presentation only).',
    acceptanceChecks: ['Mobile overflow guard', 'verify:event-result-ui PASS'],
    forbiddenChanges: ['Yeni route', 'Karar motoru değişimi'],
  }),
  item({
    id: 'carry-over-memory-cards',
    title: 'Carry-over Memory Cards',
    group: 'decision_visibility',
    priority: 'high',
    status: 'completed',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Önceki günlerden taşan hafıza kartları presentation katmanında.',
    acceptanceChecks: ['verify:carry-over PASS'],
    forbiddenChanges: ['Persist shape değişimi olmadan SAVE_VERSION artışı'],
  }),
  item({
    id: 'dynamic-social-echo',
    title: 'Dynamic Social Echo',
    group: 'decision_visibility',
    priority: 'high',
    status: 'completed',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Sosyal nabızda karar yankısı presentation; core social motor değişmez.',
    acceptanceChecks: ['verify:social-pulse-ui PASS'],
    forbiddenChanges: ['Social generation core rewrite'],
  }),
  item({
    id: 'report-tomorrow-preview',
    title: 'Report Tomorrow Preview',
    group: 'decision_visibility',
    priority: 'high',
    status: 'completed',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Rapor ekranında yarın önizlemesi (derived/presentation).',
    acceptanceChecks: ['verify:report-ui PASS'],
    forbiddenChanges: ['Rapor generation motoru refactor'],
  }),
  item({
    id: 'dynamic-field-presence-map-layer',
    title: 'Dynamic Field Presence Map Layer',
    group: 'dynamic_map_presence',
    priority: 'high',
    status: 'completed',
    softLaunchImpact: 'high',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description:
      'Harita presentation katmanı: container cluster marker, vehicle marker ve team marker hedefleri; gerçek GPS/pathfinding yok.',
    acceptanceChecks: [
      'Container cluster marker hedefi tanımlı',
      'Vehicle marker hedefi tanımlı',
      'Team marker hedefi tanımlı',
      'verify:map-ui PASS',
    ],
    forbiddenChanges: [
      'Gerçek GPS/pathfinding',
      'Tam gerçek zamanlı rota simülasyonu',
      'Drag-drop dispatch',
    ],
  }),
  item({
    id: 'resource-fatigue-visual-states',
    title: 'Resource Fatigue Visual States',
    group: 'resource_visual_states',
    priority: 'medium',
    status: 'completed',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Operasyonel kaynak yorgunluk göstergeleri (görsel state only).',
    acceptanceChecks: ['verify:operational-resources PASS'],
    forbiddenChanges: ['Kaynak simülasyon motoru rewrite'],
  }),
  item({
    id: 'map-before-after-state',
    title: 'Map Before After State',
    group: 'dynamic_map_presence',
    priority: 'medium',
    status: 'completed',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Karar öncesi/sonrası harita presentation snapshot.',
    acceptanceChecks: ['verify:dispatch-field-ui PASS'],
    forbiddenChanges: ['Harita core state machine rewrite'],
  }),
  item({
    id: 'ece-player-style-recognition',
    title: 'Ece Player Style Recognition',
    group: 'advisor_depth',
    priority: 'medium',
    status: 'completed',
    softLaunchImpact: 'medium',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Oyuncu stil tanıma şablonları (rule-based / template; canlı model entegrasyonu yok).',
    acceptanceChecks: ['Şablon varyasyonları dokümante'],
    forbiddenChanges: ['Runtime AI entegrasyonu'],
  }),
  item({
    id: 'advisor-seniority-system',
    title: 'Advisor Seniority System',
    group: 'advisor_depth',
    priority: 'medium',
    status: 'completed',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Danışman kıdem gösterimi presentation katmanında.',
    acceptanceChecks: ['verify:advisor PASS'],
    forbiddenChanges: ['Çoklu danışman upgrade sistemi'],
  }),
  item({
    id: 'specialist-advisor-notes-mvp',
    title: 'Specialist Advisor Notes MVP',
    group: 'advisor_depth',
    priority: 'medium',
    status: 'planned',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Uzman danışman notları MVP (statik şablon).',
    acceptanceChecks: ['Not şablonları içerik audit'],
    forbiddenChanges: ['Runtime AI not üretimi'],
  }),
  item({
    id: 'day-7-personal-pilot-recap',
    title: 'Day 7 Personal Pilot Recap',
    group: 'premium_wow',
    priority: 'high',
    status: 'planned',
    softLaunchImpact: 'high',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Pilot gün 7 kişisel özet recap presentation.',
    acceptanceChecks: ['verify:pilot-completion PASS'],
    forbiddenChanges: ['Pilot gün sayısı değişimi'],
  }),
  item({
    id: 'main-operation-trailer-preview',
    title: 'Main Operation Trailer Preview',
    group: 'premium_wow',
    priority: 'high',
    status: 'planned',
    softLaunchImpact: 'high',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Ana operasyon trailer/önizleme polish; paywall dili yok.',
    acceptanceChecks: [
      'verify:main-operation-preview-ui PASS',
      'Preview copy paywall dili içermez',
    ],
    forbiddenChanges: ['Büyük monetization redesign'],
  }),
  item({
    id: 'reward-showcase-moments',
    title: 'Reward Showcase Moments',
    group: 'premium_wow',
    priority: 'medium',
    status: 'planned',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Ödül ve başarı showcase anları (presentation).',
    acceptanceChecks: ['verify:badges ve verify:profile-badges PASS'],
    forbiddenChanges: ['Progression engine rewrite'],
  }),
  item({
    id: 'public-bulletin-polish',
    title: 'Public Bulletin Polish',
    group: 'premium_wow',
    priority: 'medium',
    status: 'planned',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Şehir bulletin presentation polish.',
    acceptanceChecks: ['Copy audit temiz'],
    forbiddenChanges: [],
  }),
  item({
    id: 'post-pilot-variety-polish',
    title: 'Post-Pilot Variety Polish',
    group: 'post_pilot_variety',
    priority: 'high',
    status: 'planned',
    softLaunchImpact: 'high',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Post-pilot çeşitlilik polish; phase contract korunur.',
    acceptanceChecks: ['verify:post-pilot-ux PASS', 'verify:post-pilot-event-loop PASS'],
    forbiddenChanges: ['post-pilot phase contract bozulması'],
  }),
  item({
    id: 'district-story-arcs-mvp',
    title: 'District Story Arcs MVP',
    group: 'post_pilot_variety',
    priority: 'medium',
    status: 'planned',
    softLaunchImpact: 'medium',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'İlçe hikâye arkı MVP içerik/presentation.',
    acceptanceChecks: ['verify:district-identity PASS'],
    forbiddenChanges: ['Season 2 restart'],
  }),
  item({
    id: 'rare-special-incidents',
    title: 'Rare Special Incidents',
    group: 'post_pilot_variety',
    priority: 'medium',
    status: 'planned',
    softLaunchImpact: 'medium',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Nadir özel olay içerik paketi (düşük frekans).',
    acceptanceChecks: ['Event authoring standard uyumu'],
    forbiddenChanges: ['Event generation core değişimi'],
  }),
  item({
    id: 'season-goal-variety-polish',
    title: 'Season Goal Variety Polish',
    group: 'post_pilot_variety',
    priority: 'medium',
    status: 'planned',
    softLaunchImpact: 'medium',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Sezon hedef çeşitlilik presentation.',
    acceptanceChecks: ['verify:season-goals-ui PASS'],
    forbiddenChanges: ['Season goal engine rewrite'],
  }),
  item({
    id: 'dynamic-bottom-nav-alerts',
    title: 'Dynamic Bottom Nav Alerts',
    group: 'post_pilot_variety',
    priority: 'medium',
    status: 'planned',
    softLaunchImpact: 'low',
    riskLevel: 'low',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Alt navigasyon uyarı rozetleri (mevcut nav içinde).',
    acceptanceChecks: ['Yeni route yok', 'verify:hub-ui PASS'],
    forbiddenChanges: ['Büyük navigation redesign'],
  }),
  item({
    id: 'analytics-sdk-adapter',
    title: 'Analytics SDK Adapter + Dashboard Funnel Setup',
    group: 'analytics_sdk',
    priority: 'mandatory',
    status: 'planned',
    softLaunchImpact: 'critical',
    riskLevel: 'high',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description:
      'Analytics Runtime Instrumentation MVP Aşama 2 tamamlandı (33 privacy-safe event, runtime no-op). Sonraki adım: gerçek SDK adapter ve dashboard funnel.',
    acceptanceChecks: [
      'verify:analytics-runtime PASS',
      'verify:analytics-events PASS',
      'SDK adapter bağlandı',
      'Dashboard funnel tanımlı',
    ],
    forbiddenChanges: ['Privacy-unsafe event', 'Persist shape değişimi zorunlu olmadan SAVE_VERSION artışı'],
  }),
  item({
    id: 'revenuecat-store-manual-setup',
    title: 'RevenueCat Store Manual Setup Checklist',
    group: 'monetization_iap',
    priority: 'mandatory',
    status: 'planned',
    softLaunchImpact: 'critical',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Store ve RevenueCat manuel kurulum checklist (kod refactor değil).',
    acceptanceChecks: [
      'verify:iap-product-design PASS',
      'Store product/entitlement eşlemesi dokümante',
    ],
    forbiddenChanges: ['Büyük monetization redesign'],
  }),
  item({
    id: 'eas-dev-build-iap-sandbox-smoke',
    title: 'EAS Dev Build IAP Sandbox Smoke Test',
    group: 'monetization_iap',
    priority: 'mandatory',
    status: 'planned',
    softLaunchImpact: 'critical',
    riskLevel: 'high',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'EAS dev build üzerinde IAP sandbox smoke test.',
    acceptanceChecks: ['verify:iap-sandbox-qa PASS', 'Sandbox purchase smoke kayıtlı'],
    forbiddenChanges: ['Production gate bypass'],
  }),
  item({
    id: 'manual-playtest-checklist',
    title: 'Manual Playtest Checklist Execution',
    group: 'manual_playtest',
    priority: 'mandatory',
    status: 'planned',
    softLaunchImpact: 'critical',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Manuel playtest checklist yürütmesi ve bulgu kaydı.',
    acceptanceChecks: [
      'verify:player-flow-audit PASS',
      'Pilot 1–7 manuel smoke tamam',
    ],
    forbiddenChanges: ['Gameplay core değişimi', 'Yeni route', 'Persist shape değişimi olmadan SAVE_VERSION artışı'],
  }),
  item({
    id: 'release-candidate-audit',
    title: 'Release Candidate Audit',
    group: 'release_candidate',
    priority: 'mandatory',
    status: 'planned',
    softLaunchImpact: 'critical',
    riskLevel: 'medium',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Release candidate audit: tüm verify regression ve soft-launch readiness.',
    acceptanceChecks: [
      'verify:soft-launch-readiness PASS',
      'verify:final-polish PASS',
      'Regression suite 0 FAIL',
    ],
    forbiddenChanges: ['Launch öncesi scope creep'],
  }),
  item({
    id: 'ai-advisor-architecture-foundation',
    title: 'AI-1 Advisor AI Architecture Foundation',
    group: 'ai_later',
    priority: 'later',
    status: 'later',
    softLaunchImpact: 'low',
    riskLevel: 'high',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Danışman AI mimari temeli (post soft-launch).',
    acceptanceChecks: ['Mimari doküman onayı'],
    forbiddenChanges: ['Final polish main path runtime entegrasyonu'],
  }),
  item({
    id: 'ai-ece-dynamic-comments',
    title: 'AI-2 Ece Dynamic Comments',
    group: 'ai_later',
    priority: 'later',
    status: 'later',
    softLaunchImpact: 'low',
    riskLevel: 'high',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Ece dinamik yorumları AI ile (later faz).',
    acceptanceChecks: ['Privacy review'],
    forbiddenChanges: ['Pilot gün 1–7 core değişimi'],
  }),
  item({
    id: 'ai-player-style-analysis',
    title: 'AI-3 Player Style AI Analysis',
    group: 'ai_later',
    priority: 'later',
    status: 'later',
    softLaunchImpact: 'low',
    riskLevel: 'high',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Oyuncu stil AI analizi (later faz).',
    acceptanceChecks: ['Offline evaluation planı'],
    forbiddenChanges: ['Runtime blocking inference'],
  }),
  item({
    id: 'ai-specialist-advisor-notes',
    title: 'AI-4 Specialist Advisor AI Notes',
    group: 'ai_later',
    priority: 'later',
    status: 'later',
    softLaunchImpact: 'low',
    riskLevel: 'high',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Uzman danışman AI notları (later faz).',
    acceptanceChecks: ['Human review gate'],
    forbiddenChanges: ['Unreviewed production copy'],
  }),
  item({
    id: 'ai-dynamic-report-city-bulletin',
    title: 'AI-5 Dynamic Report & City Bulletin',
    group: 'ai_later',
    priority: 'later',
    status: 'later',
    softLaunchImpact: 'low',
    riskLevel: 'high',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Dinamik rapor ve şehir bulletin AI (later faz).',
    acceptanceChecks: ['Content safety filter'],
    forbiddenChanges: ['Report core rewrite'],
  }),
  item({
    id: 'ai-season-end-evaluation',
    title: 'AI-6 Season End AI Evaluation',
    group: 'ai_later',
    priority: 'later',
    status: 'later',
    softLaunchImpact: 'low',
    riskLevel: 'high',
    requiresPersistChange: false,
    allowsNewRoute: false,
    allowsGameplayCoreChange: false,
    description: 'Sezon sonu AI değerlendirmesi (later faz).',
    acceptanceChecks: ['Season end contract korunur'],
    forbiddenChanges: ['Season 2 restart'],
  }),
];

export const FINAL_POLISH_DOCS_PATH = 'docs/crevia-final-roadmap.md';

export function getFinalPolishRoadmapItemById(id: string): FinalPolishRoadmapItem | undefined {
  return FINAL_POLISH_ROADMAP.find((r) => r.id === id);
}

export function getFinalPolishRoadmapItemsByGroup(
  group: FinalPolishRoadmapItem['group'],
): FinalPolishRoadmapItem[] {
  return FINAL_POLISH_ROADMAP.filter((r) => r.group === group);
}
