import type {
  AdvisorEchoTemplate,
  ReportEchoTemplate,
  SocialEchoTemplate,
  TomorrowHintEchoTemplate,
} from './eventEchoTypes';
import {
  buildAdvisorEchoCatalog,
  buildDistrictEchoExtras,
  buildReportEchoCatalog,
  buildSocialEchoCatalog,
  buildTomorrowHintCatalog,
} from './eventEchoCopyBuilder';

const extras = buildDistrictEchoExtras();

const EXTRA_SOCIAL: SocialEchoTemplate[] = [
  {
    id: 'echo-soc-fill-001',
    surface: 'social',
    domain: 'generic_operation',
    tone: 'calm',
    outcomeBand: ['mixed', 'partial_success', 'strong_success'],
    text: 'Mahalle grubu kısa notla müdahaleyi onayladı.',
    tags: ['fill', 'social'],
    maxLines: 2,
    sentiment: 'positive',
    speakerType: 'neighborhood_group',
    mentionStyle: 'feed',
  },
  {
    id: 'echo-soc-fill-002',
    surface: 'social',
    domain: 'vehicle',
    tone: 'mixed',
    outcomeBand: ['mixed', 'strained_success'],
    text: 'Sürücü notları yolun açıldığını yazıyor; araç yoğunluğu tartışılıyor.',
    tags: ['fill', 'vehicle'],
    maxLines: 2,
    sentiment: 'mixed',
    speakerType: 'driver',
    mentionStyle: 'short',
  },
  {
    id: 'echo-soc-fill-003',
    surface: 'social',
    domain: 'personnel',
    tone: 'mixed',
    outcomeBand: ['partial_success', 'mixed'],
    text: 'Ekip hızlıydı; aynı bölgede sürekli sahada olmaları dikkat çekti.',
    tags: ['fill', 'personnel'],
    maxLines: 2,
    sentiment: 'mixed',
    speakerType: 'worker',
    mentionStyle: 'topic',
  },
  {
    id: 'echo-soc-fill-004',
    surface: 'social',
    domain: 'route',
    tone: 'warning',
    outcomeBand: ['mixed', 'weak'],
    text: 'Geçiş düzeldi ama akşam gecikmesi hâlâ konuşuluyor.',
    tags: ['fill', 'route'],
    maxLines: 2,
    sentiment: 'concerned',
    speakerType: 'driver',
    mentionStyle: 'short',
  },
  {
    id: 'echo-soc-fill-005',
    surface: 'social',
    domain: 'crisis_adjacent',
    tone: 'warning',
    outcomeBand: ['mixed', 'strained_success'],
    text: 'Henüz büyük sorun yok; takip edildiği mesajı paylaşıldı.',
    tags: ['fill', 'crisis'],
    maxLines: 2,
    forbiddenInDay1: true,
    sentiment: 'neutral',
    speakerType: 'general_public',
    mentionStyle: 'feed',
  },
];

const EXTRA_PERSONNEL_ADVISOR: AdvisorEchoTemplate[] = [
  {
    id: 'echo-adv-personnel-extra-01',
    surface: 'advisor',
    domain: 'personnel',
    tone: 'strategic',
    outcomeBand: ['mixed', 'partial_success'],
    text: 'Ekip rotasyonu bugünkü hızı biraz düşürür; yarın tempo daha dengeli olur.',
    tags: ['personnel', 'extra'],
    maxLines: 2,
    advisorRole: 'ece',
    focus: 'carry_over',
  },
  {
    id: 'echo-adv-personnel-extra-02',
    surface: 'advisor',
    domain: 'personnel',
    tone: 'mixed',
    outcomeBand: ['strained_success', 'mixed'],
    text: 'Üst üste tempo moral kaybına yol açabilir; kısa dinlenme değerli.',
    tags: ['personnel', 'extra'],
    maxLines: 2,
    advisorRole: 'ece',
    focus: 'trade_off',
  },
  {
    id: 'echo-adv-personnel-extra-03',
    surface: 'advisor',
    domain: 'personnel',
    tone: 'recovery',
    outcomeBand: ['strong_success', 'partial_success'],
    text: 'Deneyimli ekip güven verir; kaynak paylaşımı diğer hatları bekletebilir.',
    tags: ['personnel', 'extra'],
    maxLines: 2,
    advisorRole: 'ece',
    focus: 'result_explanation',
  },
  {
    id: 'echo-adv-personnel-extra-04',
    surface: 'advisor',
    domain: 'personnel',
    tone: 'warning',
    outcomeBand: ['mixed', 'weak'],
    text: 'İletişim ekibi çekilirse saha temposu düşer; denge gerekir.',
    tags: ['personnel', 'extra'],
    maxLines: 2,
    advisorRole: 'ece',
    focus: 'social_read',
  },
  {
    id: 'echo-adv-personnel-extra-05',
    surface: 'advisor',
    domain: 'personnel',
    tone: 'calm',
    outcomeBand: ['partial_success'],
    text: 'Saha ekibi tanıdık bölgede hızlı; rotasyon uzun vadede dayanıklılık sağlar.',
    tags: ['personnel', 'extra'],
    maxLines: 2,
    advisorRole: 'ece',
    focus: 'carry_over',
  },
];

const EXTRA_CRISIS: (
  | AdvisorEchoTemplate
  | SocialEchoTemplate
  | ReportEchoTemplate
)[] = [
  {
    id: 'echo-adv-crisis-extra-01',
    surface: 'advisor',
    domain: 'crisis_adjacent',
    tone: 'warning',
    outcomeBand: ['mixed', 'strained_success'],
    text: 'Henüz kriz yok; birleşen sinyaller önleyici karar ister.',
    tags: ['crisis', 'extra'],
    maxLines: 2,
    forbiddenInDay1: true,
    advisorRole: 'ece',
    focus: 'theme_context',
  },
  {
    id: 'echo-soc-crisis-extra-01',
    surface: 'social',
    domain: 'crisis_adjacent',
    tone: 'warning',
    outcomeBand: ['mixed'],
    text: 'Risk izleniyor; gecikme olursa tekrar konuşulur.',
    tags: ['crisis', 'extra'],
    maxLines: 2,
    forbiddenInDay1: true,
    sentiment: 'concerned',
    speakerType: 'general_public',
    mentionStyle: 'short',
  },
  {
    id: 'echo-rep-crisis-extra-01',
    surface: 'report',
    domain: 'crisis_adjacent',
    tone: 'preventive',
    outcomeBand: ['mixed'],
    text: 'Önleyici sinyal rapora işlendi; eşik yarın izlenecek.',
    tags: ['crisis', 'extra'],
    maxLines: 2,
    forbiddenInDay1: true,
    reportSection: 'tomorrow_signal',
  },
  {
    id: 'echo-adv-crisis-extra-02',
    surface: 'advisor',
    domain: 'crisis_adjacent',
    tone: 'preventive',
    outcomeBand: ['partial_success', 'mixed'],
    text: 'Kaynak yoğun müdahale bugün riski dağıtır; izleme yarına eşiği yükseltebilir.',
    tags: ['crisis', 'extra'],
    maxLines: 2,
    forbiddenInDay1: true,
    advisorRole: 'ece',
    focus: 'resource_warning',
  },
  {
    id: 'echo-soc-crisis-extra-02',
    surface: 'social',
    domain: 'crisis_adjacent',
    tone: 'mixed',
    outcomeBand: ['strained_success'],
    text: 'Sorun büyümeden takip edildiği notu paylaşıldı.',
    tags: ['crisis', 'extra'],
    maxLines: 2,
    forbiddenInDay1: true,
    sentiment: 'neutral',
    speakerType: 'neighborhood_group',
    mentionStyle: 'feed',
  },
  {
    id: 'echo-rep-crisis-extra-02',
    surface: 'report',
    domain: 'crisis_adjacent',
    tone: 'warning',
    outcomeBand: ['mixed'],
    text: 'Kriz öncesi sinyal dağıtıldı; kaynak ve algı birlikte değerlendirilmeli.',
    tags: ['crisis', 'extra'],
    maxLines: 2,
    forbiddenInDay1: true,
    reportSection: 'tomorrow_signal',
  },
  {
    id: 'echo-adv-crisis-extra-03',
    surface: 'advisor',
    domain: 'crisis_adjacent',
    tone: 'strategic',
    outcomeBand: ['mixed'],
    text: 'Önleyici karar panik değil; risk birleşimini erken kesmek için değerli.',
    tags: ['crisis', 'extra'],
    maxLines: 2,
    forbiddenInDay1: true,
    advisorRole: 'ece',
    focus: 'theme_context',
  },
];

const EXTRA_SOCIAL_DOMAIN: SocialEchoTemplate[] = [
  {
    id: 'echo-soc-social-domain-01',
    surface: 'social',
    domain: 'social',
    tone: 'positive',
    outcomeBand: ['strong_success', 'partial_success'],
    text: 'Vatandaşlar müdahalenin fark edildiğini kısa notla paylaştı.',
    tags: ['social', 'extra'],
    maxLines: 2,
    sentiment: 'positive',
    speakerType: 'general_public',
    mentionStyle: 'feed',
  },
  {
    id: 'echo-soc-social-domain-02',
    surface: 'social',
    domain: 'social',
    tone: 'calm',
    outcomeBand: ['mixed'],
    text: 'Görünürlük yüksek noktada algı yumuşadı; takip sürüyor.',
    tags: ['social', 'extra'],
    maxLines: 2,
    sentiment: 'neutral',
    speakerType: 'resident',
    mentionStyle: 'topic',
  },
];

const EXTRA_REPORT: ReportEchoTemplate[] = [
  {
    id: 'echo-rep-fill-001',
    surface: 'report',
    domain: 'generic_operation',
    tone: 'mixed',
    outcomeBand: ['mixed', 'partial_success'],
    text: 'Günlük operasyon özeti kaydedildi; yarın plan güncellenecek.',
    tags: ['fill', 'report'],
    maxLines: 2,
    reportSection: 'main_result',
  },
  {
    id: 'echo-rep-fill-002',
    surface: 'report',
    domain: 'vehicle',
    tone: 'warning',
    outcomeBand: ['mixed', 'strained_success'],
    text: 'Filo yükü raporda not edildi; bakım riski izleniyor.',
    tags: ['fill', 'vehicle'],
    maxLines: 2,
    reportSection: 'resource_effect',
  },
  {
    id: 'echo-rep-fill-003',
    surface: 'report',
    domain: 'route',
    tone: 'strategic',
    outcomeBand: ['partial_success', 'mixed'],
    text: 'Rota dengesi sağlandı; gün sonu yükü yarın değerlendirilecek.',
    tags: ['fill', 'route'],
    maxLines: 2,
    reportSection: 'resource_effect',
  },
  {
    id: 'echo-rep-fill-004',
    surface: 'report',
    domain: 'personnel',
    tone: 'mixed',
    outcomeBand: ['strong_success', 'mixed'],
    text: 'Ekip performansı raporlandı; rotasyon önerisi yarın gündemde.',
    tags: ['fill', 'personnel'],
    maxLines: 2,
    reportSection: 'resource_effect',
  },
  {
    id: 'echo-rep-fill-005',
    surface: 'report',
    domain: 'crisis_adjacent',
    tone: 'preventive',
    outcomeBand: ['mixed', 'strained_success'],
    text: 'Kriz öncesi sinyal rapora işlendi; birleşik izleme sürüyor.',
    tags: ['fill', 'crisis'],
    maxLines: 2,
    forbiddenInDay1: true,
    reportSection: 'tomorrow_signal',
  },
];

const EXTRA_TOMORROW: TomorrowHintEchoTemplate[] = [
  {
    id: 'echo-tmr-fill-001',
    surface: 'tomorrow_hint',
    domain: 'generic_operation',
    tone: 'mixed',
    outcomeBand: ['mixed', 'partial_success'],
    text: 'Yarın aynı hat için tekrar izleme planlanmalı.',
    tags: ['fill', 'tomorrow'],
    maxLines: 2,
  },
  {
    id: 'echo-tmr-fill-002',
    surface: 'tomorrow_hint',
    domain: 'pilot_final',
    tone: 'recovery',
    outcomeBand: ['strong_success', 'mixed'],
    text: 'Pilot sonrası ana operasyon planında bugünkü sinyaller taşınmalı.',
    tags: ['fill', 'pilot_final'],
    maxLines: 2,
    allowInPilotFinal: true,
  },
  {
    id: 'echo-tmr-fill-003',
    surface: 'tomorrow_hint',
    domain: 'social',
    tone: 'calm',
    outcomeBand: ['partial_success', 'strong_success'],
    text: 'Sosyal nabız sakinleşti; yarın görünür sonuç korunmalı.',
    tags: ['fill', 'social'],
    maxLines: 2,
  },
  {
    id: 'echo-tmr-fill-004',
    surface: 'tomorrow_hint',
    domain: 'vehicle',
    tone: 'warning',
    outcomeBand: ['mixed', 'strained_success'],
    text: 'Araç yorgunluğu düşükse yarın hızlı hat mümkün; değilse rota bölünmeli.',
    tags: ['fill', 'vehicle'],
    maxLines: 2,
  },
  {
    id: 'echo-tmr-fill-005',
    surface: 'tomorrow_hint',
    domain: 'personnel',
    tone: 'recovery',
    outcomeBand: ['partial_success', 'mixed'],
    text: 'Ekip dinlendiyse yarın tempo artırılabilir.',
    tags: ['fill', 'personnel'],
    maxLines: 2,
  },
  {
    id: 'echo-tmr-fill-006',
    surface: 'tomorrow_hint',
    domain: 'district_balance',
    tone: 'strategic',
    outcomeBand: ['mixed'],
    text: 'Mahalle dengesi yarın sabah planında önceliklendirilmeli.',
    tags: ['fill', 'district'],
    maxLines: 2,
  },
];

const CONTAINER_EXTRA_ADVISOR: AdvisorEchoTemplate[] = [
  {
    id: 'echo-adv-container-extra-01',
    surface: 'advisor',
    domain: 'container',
    tone: 'mixed',
    outcomeBand: ['mixed', 'partial_success'],
    text: 'Konteyner hattı bugün rahatladı; sıklık yarın değerli olur.',
    tags: ['container', 'extra'],
    maxLines: 2,
    advisorRole: 'ece',
    focus: 'carry_over',
  },
  {
    id: 'echo-adv-container-extra-02',
    surface: 'advisor',
    domain: 'container',
    tone: 'preventive',
    outcomeBand: ['partial_success', 'strong_success'],
    text: 'Önleyici tur konteyner baskısını düşürür; bugün tempo düşebilir.',
    tags: ['container', 'extra'],
    maxLines: 2,
    advisorRole: 'ece',
    focus: 'trade_off',
  },
];

const CONTAINER_EXTRA_SOCIAL: SocialEchoTemplate[] = [
  {
    id: 'echo-soc-container-extra-01',
    surface: 'social',
    domain: 'container',
    tone: 'positive',
    outcomeBand: ['strong_success', 'partial_success'],
    text: 'Konteyner çevresi daha düzenli; kısa teşekkür notları var.',
    tags: ['container', 'extra'],
    maxLines: 2,
    sentiment: 'positive',
    speakerType: 'resident',
    mentionStyle: 'short',
  },
  {
    id: 'echo-soc-container-extra-02',
    surface: 'social',
    domain: 'container',
    tone: 'mixed',
    outcomeBand: ['mixed'],
    text: 'Toplama gecikmesi azaldı; koku konusu hâlâ izleniyor.',
    tags: ['container', 'extra'],
    maxLines: 2,
    sentiment: 'mixed',
    speakerType: 'neighborhood_group',
    mentionStyle: 'feed',
  },
];

export const ADVISOR_ECHO_TEMPLATES: AdvisorEchoTemplate[] = [
  ...buildAdvisorEchoCatalog(),
  ...extras.advisor,
  ...CONTAINER_EXTRA_ADVISOR,
  ...EXTRA_PERSONNEL_ADVISOR,
  ...EXTRA_CRISIS.filter((t): t is AdvisorEchoTemplate => t.surface === 'advisor'),
];

export const SOCIAL_ECHO_TEMPLATES: SocialEchoTemplate[] = [
  ...buildSocialEchoCatalog(),
  ...extras.social,
  ...EXTRA_SOCIAL,
  ...CONTAINER_EXTRA_SOCIAL,
  ...EXTRA_SOCIAL_DOMAIN,
  ...EXTRA_CRISIS.filter((t): t is SocialEchoTemplate => t.surface === 'social'),
];

export const REPORT_ECHO_TEMPLATES: ReportEchoTemplate[] = [
  ...buildReportEchoCatalog(),
  ...extras.report,
  ...EXTRA_REPORT,
  ...EXTRA_CRISIS.filter((t): t is ReportEchoTemplate => t.surface === 'report'),
  {
    id: 'echo-rep-fill-extra-01',
    surface: 'report',
    domain: 'generic_operation',
    tone: 'mixed',
    outcomeBand: ['mixed', 'partial_success'],
    text: 'Günlük özet kaydedildi; yarın plan güncellenecek.',
    tags: ['fill'],
    maxLines: 2,
    reportSection: 'main_result',
  },
];

export const TOMORROW_HINT_ECHO_TEMPLATES: TomorrowHintEchoTemplate[] = [
  ...buildTomorrowHintCatalog(),
  ...EXTRA_TOMORROW,
  {
    id: 'echo-tmr-fill-extra-01',
    surface: 'tomorrow_hint',
    domain: 'container',
    tone: 'preventive',
    outcomeBand: ['mixed', 'partial_success'],
    text: 'Yarın konteyner hattında önleyici sıklık planlanmalı.',
    tags: ['container', 'tomorrow'],
    maxLines: 2,
  },
];

export const ALL_EVENT_ECHO_TEMPLATES = [
  ...ADVISOR_ECHO_TEMPLATES,
  ...SOCIAL_ECHO_TEMPLATES,
  ...REPORT_ECHO_TEMPLATES,
  ...TOMORROW_HINT_ECHO_TEMPLATES,
];
