import type { ContentPackEventTemplate } from './contentPackTypes';

/** Content Safety Pack Aşama 1 — mahalle + konteyner şablonları. */
export const NEIGHBORHOOD_CONTAINER_CONTENT_PACK: ContentPackEventTemplate[] = [
  // —— Merkez ×3 ——
  {
    id: 'csp1-merkez-meydan-gorunurluk',
    title: 'Merkez Meydanında Görünür Temizlik Baskısı',
    districtId: 'merkez',
    domain: 'district_specific',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [2],
    avoidPilotDays: [1, 7],
    sceneText:
      'Merkez meydanında sabah yoğunluğu öncesi çöp kutuları taşıyor; belediye binası çevresindeki görünür alan daralıyor.',
    pressureText:
      'Kamu alanında küçük aksaklık bile hızlı şikayet üretir; hızlı tepki beklentisi yüksek.',
    decisionContextText:
      'Hızlı ekip meydanı bugün toparlar; ölçülü plan ise görünürlüğü korur ama tempo düşer.',
    shortTermEffectText: 'Hızlı müdahale meydan çevresini sabah saatinde toparlar.',
    tradeOffText: 'Ama aynı ekip hattı öğleden sonra başka çağrılara geç kalabilir.',
    carryOverText: 'Önleyici düzen seçilirse yarın Merkez meydanında baskı daha düşük başlar.',
    socialEchoText: 'Sosyal Nabız’da meydan temizliği kısa sürede olumlu yankı alır.',
    advisorEchoText: 'Ece, Merkez’de görünürlüğün karar baskısını hızlandırdığını söyler.',
    reportEchoText: 'Merkez meydanında görünür düzen sağlandı; öğleden sonra tempo izlenmeli.',
    tags: ['merkez', 'gorunurluk', 'meydan'],
    auditTargetScore: 88,
  },
  {
    id: 'csp1-merkez-carsi-konteyner',
    title: 'Merkez Çarşı Konteyner Doluluğu',
    districtId: 'merkez',
    domain: 'container',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [2, 3],
    avoidPilotDays: [1, 7],
    sceneText:
      'Merkez çarşı girişindeki konteyner noktası sabah açılış öncesi doluyor; esnaf yük indirmekte zorlanıyor.',
    pressureText: 'Çarşı görünürlüğü yüksek olduğu için gecikme aynı gün sosyal tepki üretebilir.',
    decisionContextText: 'Ek sefer bugün çarşıyı rahatlatır; sık toplama ise araç hattını yorar.',
    shortTermEffectText: 'Ek sefer çarşı girişindeki yığılmayı bugün azaltır.',
    tradeOffText: 'Fakat araç yorgunluğu artar ve bakım riski yarına taşınır.',
    carryOverText: 'Sık toplama yerine önleyici rota seçilirse yarın çarşı hattı daha sakin açılır.',
    socialEchoText: 'Esnaf grupları çarşı girişinin açıldığını hızlı paylaşır.',
    advisorEchoText: 'Ece, çarşıda hız ile araç dayanıklılığını birlikte düşünmeni önerir.',
    reportEchoText: 'Merkez çarşı konteyner baskısı düştü; araç yükü raporda izleniyor.',
    tags: ['merkez', 'konteyner', 'carsi'],
    auditTargetScore: 90,
  },
  {
    id: 'csp1-merkez-belediye-hizli-tepki',
    title: 'Belediye Çevresi Hızlı Tepki Talebi',
    districtId: 'merkez',
    domain: 'district_specific',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [2],
    avoidPilotDays: [1, 7],
    sceneText:
      'Belediye hizmet binası önündeki yürüyüş yolunda sabah temizlik izleri zayıf; vatandaş beklentisi net.',
    pressureText: 'Kamu çevresinde gecikme diğer mahallelere kıyasla daha hızlı konuşulur.',
    decisionContextText: 'Anında ekip yönlendirme bugün beklentiyi karşılar; planlı rota ise kaynak korur.',
    shortTermEffectText: 'Anında müdahale kamu çevresinde görünür düzen sağlar.',
    tradeOffText: 'Buna karşılık diğer hatlarda bekleme süresi uzayabilir.',
    carryOverText: 'Planlı rota tercih edilirse yarın Merkez genelinde denge daha iyi olur.',
    socialEchoText: 'Sosyal Nabız’da belediye çevresi “hızlı toparlandı” notu görünür.',
    advisorEchoText: 'Ece, kamu görünürlüğünde hızın bedelinin diğer hatlar olduğunu hatırlatır.',
    reportEchoText: 'Belediye çevresi toparlandı; hat dengesi yarın değerlendirilecek.',
    tags: ['merkez', 'belediye', 'hizli_tepki'],
    auditTargetScore: 87,
  },

  // —— Cumhuriyet ×3 ——
  {
    id: 'csp1-cumhuriyet-iri-atik-sikisma',
    title: 'Cumhuriyet’te İri Atık Sıkışması',
    districtId: 'cumhuriyet',
    domain: 'container',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [2],
    avoidPilotDays: [1, 7],
    sceneText:
      'Cumhuriyet’te gece bırakılan iri atıklar konteyner çevresini kapattı. Esnaf sabah saatlerinde sokağın daraldığını bildiriyor.',
    pressureText: 'Sorun sadece temizlik değil; yol daraldığı için görünür şikayet hızla büyüyebilir.',
    decisionContextText:
      'Hızlı ekip bugünkü şikayeti düşürür, önleyici rota ise yarınki konteyner baskısını azaltır.',
    shortTermEffectText: 'Hızlı müdahale yol çevresini açar ve sabah şikayetini düşürür.',
    tradeOffText: 'Ama aynı araç hattı tekrar kullanılırsa araç yorgunluğu artar.',
    carryOverText: 'Önleyici rota seçilirse yarın Cumhuriyet’te konteyner baskısı daha düşük başlar.',
    socialEchoText: 'Mahalle grubu yolun açıldığını fark eder, ancak araç yoğunluğu konuşulabilir.',
    advisorEchoText: 'Ece, hızlı çözümün bugünü rahatlattığını ama araç yükünü yarına taşıyabileceğini söyler.',
    reportEchoText: 'Cumhuriyet’te görünür konteyner baskısı düştü; araç yükü yarın izlenmeli.',
    tags: ['cumhuriyet', 'iri_atik', 'konteyner'],
    auditTargetScore: 95,
  },
  {
    id: 'csp1-cumhuriyet-apartman-doluluk',
    title: 'Cumhuriyet Apartman Bloklarında Doluluk',
    districtId: 'cumhuriyet',
    domain: 'container',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [2, 4],
    avoidPilotDays: [1, 7],
    sceneText:
      'Cumhuriyet’te apartman görevlileri konteynerin iki gündür dolu kaldığını bildiriyor; sokak köşesinde koku yükseliyor.',
    pressureText: 'Konut yoğunluğu nedeniyle şikayet zinciri hızlı büyür.',
    decisionContextText: 'Ara sefer bugün rahatlatır; bekleme ise apartman grubunu hareketlendirir.',
    shortTermEffectText: 'Ara sefer apartman hattında görünür doluluk sorununu bugün çözer.',
    tradeOffText: 'Fakat ekip temposu düşer ve diğer sokaklar kısa süre bekleyebilir.',
    carryOverText: 'Düzenli sıklık planı seçilirse yarın apartman hattı daha sakin kalır.',
    socialEchoText: 'Apartman temsilcileri müdahaleyi olumlu paylaşır.',
    advisorEchoText: 'Ece, konut yoğunluğunda tek seferlik hızın yetmeyebileceğini belirtir.',
    reportEchoText: 'Apartman hattı toparlandı; sıklık planı yarın etkisini gösterecek.',
    tags: ['cumhuriyet', 'apartman', 'konteyner'],
    auditTargetScore: 91,
  },
  {
    id: 'csp1-cumhuriyet-esnaf-sokak-daralma',
    title: 'Cumhuriyet Esnaf Hattında Sokak Daralması',
    districtId: 'cumhuriyet',
    domain: 'district_specific',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3],
    avoidPilotDays: [1, 7],
    sceneText:
      'Cumhuriyet esnaf hattında sabah tezgahtan taşan malzemeler yürüyüş yolunu daraltıyor; konteyner çevresi de kalabalık.',
    pressureText: 'Esnaf baskısı ile konteyner baskısı aynı saatte görünür olursa şikayet katlanır.',
    decisionContextText: 'Önce esnaf hattı mı konteyner mi netleştirmek bugünkü görünürlüğü belirler.',
    shortTermEffectText: 'Öncelikli hat bugün yürüyüş yolunu açar ve esnaf şikayetini düşürür.',
    tradeOffText: 'Ancak ikinci hat için ekip geç kalabilir.',
    carryOverText: 'İki hat için dengeli plan seçilirse yarın esnaf hattı daha rahat açılır.',
    socialEchoText: 'Esnaf odası kısa süreli rahatlama notu düşer.',
    advisorEchoText: 'Ece, Cumhuriyet’te öncelik seçiminin sosyal yankıyı belirlediğini söyler.',
    reportEchoText: 'Esnaf hattı açıldı; ikinci hat yarın sabah izlenecek.',
    tags: ['cumhuriyet', 'esnaf', 'sokak'],
    auditTargetScore: 86,
  },

  // —— Sanayi ×3 ——
  {
    id: 'csp1-sanayi-agir-atik-hatti',
    title: 'Sanayi’de Ağır Atık Hattı',
    districtId: 'sanayi',
    domain: 'container',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [2, 3],
    avoidPilotDays: [1, 7],
    sceneText:
      'Sanayi’de atölye çıkışına bırakılan ağır atıklar standart konteyner hattını yavaşlatıyor. Büyük araç geçmezse servis yolu sabah daralabilir.',
    pressureText: 'Araç kapasitesi doğru seçilmezse temizlik gecikir ve bakım riski aynı gün içinde büyür.',
    decisionContextText:
      'Büyük araç hızlı sonuç verir ama bakım baskısı yaratır; bölünmüş rota daha yavaş ilerler ama aracı korur.',
    shortTermEffectText: 'Büyük araç atık hattını hızlı temizler.',
    tradeOffText: 'Ama yoğun hat aynı aracı yorar ve bakım riskini artırır.',
    carryOverText: 'Bölünmüş rota seçilirse yarın Sanayi hattı daha dengeli başlar.',
    socialEchoText: 'Atölye çalışanları servis yolunun açılmasını olumlu görür.',
    advisorEchoText: 'Ece, Sanayi’de hız kadar araç dayanıklılığının da kritik olduğunu belirtir.',
    reportEchoText: 'Sanayi’de ağır atık baskısı kontrol altına alındı; araç bakım riski izleniyor.',
    tags: ['sanayi', 'agir_atik', 'konteyner'],
    auditTargetScore: 94,
  },
  {
    id: 'csp1-sanayi-arac-kapasite-konteyner',
    title: 'Sanayi Konteyner Hattında Araç Kapasitesi',
    districtId: 'sanayi',
    domain: 'container',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3],
    avoidPilotDays: [1, 7],
    sceneText:
      'Sanayi konteyner noktasında standart araç kapasitesi yetersiz kalıyor; atölye sahipleri ikinci sefer talep ediyor.',
    pressureText: 'İkinci sefer gecikirse atık yığılması öğleden sonra rota sıkışıklığı yaratır.',
    decisionContextText: 'Büyük araç bugün tek seferde toparlar; iki küçük sefer ise esneklik sağlar.',
    shortTermEffectText: 'Büyük araç yığılmayı bugün erken saatte çözer.',
    tradeOffText: 'Fakat bakım penceresi daralır ve yedek araç ihtiyacı doğabilir.',
    carryOverText: 'İki sefer planı seçilirse yarın kapasite baskısı daha öngörülebilir olur.',
    socialEchoText: 'Sanayi esnaf grubu erken toparlanmayı olumlu yorumlar.',
    advisorEchoText: 'Ece, kapasite seçiminin yarınki rota riskini belirlediğini söyler.',
    reportEchoText: 'Kapasite baskısı giderildi; bakım penceresi raporda not edildi.',
    tags: ['sanayi', 'arac', 'konteyner'],
    auditTargetScore: 89,
  },
  {
    id: 'csp1-sanayi-atolye-bakim-riski',
    title: 'Sanayi Atölye Hattında Bakım Riski',
    districtId: 'sanayi',
    domain: 'district_specific',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3, 4],
    avoidPilotDays: [1, 7],
    sceneText:
      'Sanayi atölye hattında konteyner yanında yağlı atık izleri birikiyor; kaydırma işlemi ekipmanı zorluyor.',
    pressureText: 'Bakım ertelenirse aynı hat öğleden sonra ikinci müdahale isteyebilir.',
    decisionContextText: 'Özel ekipman bugün riski keser; standart ekip ise maliyeti korur ama tempo düşer.',
    shortTermEffectText: 'Özel ekipman hattı bugün güvenli şekilde açar.',
    tradeOffText: 'Ancak bütçe baskısı artar ve diğer hatlara kaynak azalır.',
    carryOverText: 'Standart ekip + planlı bakım seçilirse yarın hat daha az zorlanır.',
    socialEchoText: 'Atölye temsilcileri güvenli müdahaleyi kısa notla paylaşır.',
    advisorEchoText: 'Ece, Sanayi’de ekipman seçiminin yarınki bakım yükünü azalttığını söyler.',
    reportEchoText: 'Atölye hattı açıldı; bakım planı yarın devreye alınacak.',
    tags: ['sanayi', 'atolye', 'bakim'],
    auditTargetScore: 88,
  },

  // —— İstasyon ×3 ——
  {
    id: 'csp1-istasyon-gecis-yogunlugu',
    title: 'İstasyon Geçiş Yoğunluğu',
    districtId: 'istasyon',
    domain: 'district_specific',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [4],
    avoidPilotDays: [1, 7],
    sceneText:
      'İstasyon çevresinde sabah geçiş yoğunluğu konteyner noktasını çevreliyor; yolcu akışı temizlik alanını daraltıyor.',
    pressureText: 'Geç kalan müdahale akşam dalgasıyla çakışırsa rota gecikmesi büyür.',
    decisionContextText: 'Sabah erken ekip geçişi rahatlatır; akşam ağırlıklı plan ise gündüz riskini artırır.',
    shortTermEffectText: 'Sabah müdahalesi geçiş hattını bugün görünür şekilde açar.',
    tradeOffText: 'Fakat akşam ek mesai ihtiyacı doğabilir.',
    carryOverText: 'Akşam hafif kontrol seçilirse yarın İstasyon hattı daha dengeli başlar.',
    socialEchoText: 'Yolcu yoğunluğu olan gruplar sabah düzenini olumlu görür.',
    advisorEchoText: 'Ece, İstasyon’da zamanlama seçiminin akşam yükünü belirlediğini belirtir.',
    reportEchoText: 'Geçiş hattı açıldı; akşam mesai ihtiyacı raporda izleniyor.',
    tags: ['istasyon', 'gecis', 'rota'],
    auditTargetScore: 87,
  },
  {
    id: 'csp1-istasyon-aksam-dalga',
    title: 'İstasyon Akşam Dalga Baskısı',
    districtId: 'istasyon',
    domain: 'container',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [4, 5],
    avoidPilotDays: [1, 7],
    sceneText:
      'İstasyon çevresinde akşamüstü konteyner doluluğu artıyor; servis yolu yolcu kuyruğu ile çakışıyor.',
    pressureText: 'Rota gecikmesi aynı akşam sosyal nabızda “çöp birikti” yorumuna dönüşebilir.',
    decisionContextText: 'Ek akşam seferi bugün görünürlüğü korur; sabaha erteleme ise risk biriktirir.',
    shortTermEffectText: 'Ek sefer akşam hattını bugün rahatlatır.',
    tradeOffText: 'Ama ekip yorgunluğu artar ve yarın sabah temposu düşebilir.',
    carryOverText: 'Sabah erken toplama planı seçilirse yarın İstasyon hattı daha sakin açılır.',
    socialEchoText: 'Sosyal Nabız’da akşam müdahalesi kısa süreli rahatlama getirir.',
    advisorEchoText: 'Ece, akşam kararının yarın sabah ekibini etkileyebileceğini söyler.',
    reportEchoText: 'Akşam baskısı kontrol altına alındı; sabah tempo raporda takip edilecek.',
    tags: ['istasyon', 'aksam', 'konteyner'],
    auditTargetScore: 92,
  },
  {
    id: 'csp1-istasyon-durak-rota-cakisma',
    title: 'İstasyon Durak Çevresi Rota Çakışması',
    districtId: 'istasyon',
    domain: 'route',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [5],
    avoidPilotDays: [1, 7],
    sceneText:
      'İstasyon durak çevresinde iki hat aynı saatte konteyner toplamak için bekliyor; sürücüler rota çakışması bildiriyor.',
    pressureText: 'Çakışma çözülmezse her iki hat da gecikir ve şikayet ikiye katlanır.',
    decisionContextText: 'Hat önceliği netleştirmek bugünkü gecikmeyi keser; paralel deneme riski artırır.',
    shortTermEffectText: 'Öncelikli hat bugün durak çevresini açar.',
    tradeOffText: 'Fakat ikinci hat kısa süre bekler ve baskı taşınır.',
    carryOverText: 'Çakışmayı bölen plan seçilirse yarın durak hattı daha akıcı olur.',
    socialEchoText: 'Sürücü notları rota düzeninin düzeldiğini gösterir.',
    advisorEchoText: 'Ece, rota çakışmasında net önceliğin kritik olduğunu hatırlatır.',
    reportEchoText: 'Durak çevresi açıldı; ikinci hat yarın sabah plana alındı.',
    tags: ['istasyon', 'durak', 'rota'],
    auditTargetScore: 88,
  },

  // —— Yeşilvadi ×3 ——
  {
    id: 'csp1-yesilvadi-park-hassasiyet',
    title: 'Yeşilvadi’de Park Çevresi Hassasiyeti',
    districtId: 'yesilvadi',
    domain: 'container',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [4],
    avoidPilotDays: [1, 7],
    sceneText:
      'Yeşilvadi’de park çevresindeki konteyner noktası sabah yürüyüş saatinde dikkat çekiyor. Sorun büyük değil ama çevre düzeni algısı yüksek.',
    pressureText: 'Geç kalınırsa küçük temizlik sorunu sosyal memnuniyeti gereksiz düşürebilir.',
    decisionContextText: 'Sessiz hızlı müdahale bugünü toparlar; önleyici çevre düzeni yarın aynı noktayı daha sakin tutar.',
    shortTermEffectText: 'Hızlı müdahale park çevresini görünür şekilde toparlar.',
    tradeOffText: 'Ancak ek düzenleme seçilmezse aynı nokta yarın tekrar baskı üretebilir.',
    carryOverText: 'Önleyici çevre düzeni yarın Yeşilvadi’de temizlik baskısını azaltır.',
    socialEchoText: 'Yeşilvadi sakinleri park çevresindeki düzeni fark eder.',
    advisorEchoText: 'Ece, Yeşilvadi’de küçük sorunların algı etkisinin yüksek olduğunu söyler.',
    reportEchoText: 'Park çevresi toparlandı; önleyici bakım yarınki riski düşürdü.',
    tags: ['yesilvadi', 'park', 'konteyner'],
    auditTargetScore: 93,
  },
  {
    id: 'csp1-yesilvadi-site-koku',
    title: 'Yeşilvadi Site Çevresi Koku Şikayeti',
    districtId: 'yesilvadi',
    domain: 'container',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [5],
    avoidPilotDays: [1, 7],
    sceneText:
      'Yeşilvadi site girişindeki konteyner noktasında koku şikayeti artıyor; apartman sakinleri pencere açmakta tereddüt ediyor.',
    pressureText: 'Koku görünür şikayete dönüşmeden müdahale edilmeli.',
    decisionContextText: 'Derin temizlik bugün kokuyu keser; yüzeysel toplama hızlıdır ama sorun sürebilir.',
    shortTermEffectText: 'Derin temizlik site girişinde bugün koku baskısını düşürür.',
    tradeOffText: 'Fakat ekip süresi uzar ve diğer Yeşilvadi hatları bekleyebilir.',
    carryOverText: 'Haftalık sık plan seçilirse yarın site hattı daha sakin kalır.',
    socialEchoText: 'Site grubu kısa süreli rahatlama mesajı paylaşır.',
    advisorEchoText: 'Ece, koku olaylarında hızlı ama yüzeysel çözümün yetmeyebileceğini belirtir.',
    reportEchoText: 'Site girişi toparlandı; sık plan raporda işlendi.',
    tags: ['yesilvadi', 'koku', 'konteyner'],
    auditTargetScore: 90,
  },
  {
    id: 'csp1-yesilvadi-onleyici-duzen',
    title: 'Yeşilvadi Önleyici Çevre Düzeni',
    districtId: 'yesilvadi',
    domain: 'district_specific',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [5, 6],
    avoidPilotDays: [1, 7],
    sceneText:
      'Yeşilvadi yürüyüş yolunda konteyner çevresine düzenli olmayan atık bırakılıyor; site yönetimi önleyici düzen talep ediyor.',
    pressureText: 'Düzen oturtulmazsa küçük ihlaller tekrar eder.',
    decisionContextText: 'Bilgilendirme + hafif denetim bugün algıyı toparlar; sadece toplama ise kısa vadeli kalır.',
    shortTermEffectText: 'Bilgilendirme turu bugün düzen algısını güçlendirir.',
    tradeOffText: 'Ancak ek personel saati gerekir.',
    carryOverText: 'Önleyici düzen rutini seçilirse yarın ihlal sayısı düşer.',
    socialEchoText: 'Sakinler düzen kartlarının asıldığını olumlu yorumlar.',
    advisorEchoText: 'Ece, Yeşilvadi’de algı yönetiminin operasyon kadar önemli olduğunu söyler.',
    reportEchoText: 'Önleyici düzen başlatıldı; ihlal takibi yarın sürecek.',
    tags: ['yesilvadi', 'duzen', 'onleyici'],
    auditTargetScore: 86,
  },

  // —— Ek konteyner çeşitliliği (mahalleler arası) ——
  {
    id: 'csp1-merkez-gece-atik',
    title: 'Merkez’de Gece Bırakılan Atık',
    districtId: 'merkez',
    domain: 'container',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [2],
    avoidPilotDays: [1, 7],
    sceneText:
      'Merkez ana yürüyüş hattında gece bırakılan atıklar sabah trafiğinden önce yolu daraltıyor.',
    pressureText: 'Sabah yoğunluğu başlamadan açılmazsa görünür şikayet artar.',
    decisionContextText: 'Erken ekip bugün yolu açar; normal saat müdahalesi gecikme riski taşır.',
    shortTermEffectText: 'Erken ekip sabah trafiğinden önce yolu açar.',
    tradeOffText: 'Fakat mesai maliyeti artar.',
    carryOverText: 'Gece denetim turu seçilirse yarın benzer bırakım azalır.',
    socialEchoText: 'Sosyal Nabız’da sabah yolunun açık olduğu notu görünür.',
    advisorEchoText: 'Ece, erken müdahalenin maliyetini de hesaba katmayı önerir.',
    reportEchoText: 'Sabah yolu açıldı; gece denetim planı rapora eklendi.',
    tags: ['merkez', 'gece_atik', 'konteyner'],
    auditTargetScore: 88,
  },
  {
    id: 'csp1-cumhuriyet-yanlis-atik',
    title: 'Cumhuriyet’te Yanlış Atık Ayrımı',
    districtId: 'cumhuriyet',
    domain: 'container',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3],
    avoidPilotDays: [1, 7],
    sceneText:
      'Cumhuriyet konteyner noktasında yanlış atık ayrımı kutuyu tıkıyor; apartman sakinleri karışıklık bildiriyor.',
    pressureText: 'Ayrım düzeltilmezse toplama hattı yavaşlar.',
    decisionContextText: 'Ayrıştırma ekibi bugün kutuyu kurtarır; tek toplama hızlıdır ama sorun tekrarlar.',
    shortTermEffectText: 'Ayrıştırma ekibi bugün kutuyu işler hale getirir.',
    tradeOffText: 'Fakat ek süre diğer sokakları bekletebilir.',
    carryOverText: 'Kısa bilgilendirme seçilirse yarın yanlış atık oranı düşer.',
    socialEchoText: 'Apartman grubu düzenleme çalışmasını olumlu karşılar.',
    advisorEchoText: 'Ece, ayrım hatalarında iletişimin operasyon kadar etkili olduğunu söyler.',
    reportEchoText: 'Kutu açıldı; bilgilendirme yarın hatlarda sürecek.',
    tags: ['cumhuriyet', 'yanlis_atik', 'konteyner'],
    auditTargetScore: 87,
  },
  {
    id: 'csp1-sanayi-onleyici-temizlik',
    title: 'Sanayi Önleyici Hat Temizliği',
    districtId: 'sanayi',
    domain: 'container',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [2, 3],
    avoidPilotDays: [1, 7],
    sceneText:
      'Sanayi servis yolunda konteyner çevresine biriken ince atık yağmur sonrası kayganlık yaratıyor.',
    pressureText: 'Kayganlık riski sürücü raporlarına yansımadan önce giderilmeli.',
    decisionContextText: 'Önleyici temizlik bugün riski keser; ertelenmiş müdahale ise öğleden sonra baskı bırakır.',
    shortTermEffectText: 'Önleyici temizlik servis yolunu bugün güvenli hale getirir.',
    tradeOffText: 'Ancak planlanan başka hat gecikebilir.',
    carryOverText: 'Haftalık önleyici hat seçilirse yarın kayganlık riski düşer.',
    socialEchoText: 'Sürücü notları yolun güvenli olduğunu belirtir.',
    advisorEchoText: 'Ece, önleyici temizliğin Sanayi’de kaza riskini azalttığını hatırlatır.',
    reportEchoText: 'Servis yolu güvenli; önleyici plan raporda kayıtlı.',
    tags: ['sanayi', 'onleyici', 'konteyner'],
    auditTargetScore: 89,
  },
  {
    id: 'csp1-istasyon-sosyal-goruntu',
    title: 'İstasyon’da Sosyal Nabza Düşen Görüntü',
    districtId: 'istasyon',
    domain: 'container',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [4],
    avoidPilotDays: [1, 7],
    sceneText:
      'İstasyon çıkışında konteyner yanında biriken poşetler fotoğraflanıyor; sosyal nabızda paylaşım hızlanıyor.',
    pressureText: 'Görüntü büyümeden müdahale edilmeli.',
    decisionContextText: 'Hızlı toplama görünürlüğü bugün düşürür; açıklama metni ise algıyı yumuşatır.',
    shortTermEffectText: 'Hızlı toplama paylaşım öncesi alanı temizler.',
    tradeOffText: 'Fakat iletişim ekibi diğer hatlardan çekilir.',
    carryOverText: 'Düzenli görüntü kontrolü seçilirse yarın benzer paylaşım azalır.',
    socialEchoText: 'Sosyal Nabız’da “toparlandı” yorumları görünmeye başlar.',
    advisorEchoText: 'Ece, görünürlük yüksek hatlarda hızın algıyı belirlediğini söyler.',
    reportEchoText: 'Alan temizlendi; görüntü takibi raporda devam edecek.',
    tags: ['istasyon', 'sosyal', 'konteyner'],
    auditTargetScore: 91,
  },
  {
    id: 'csp1-yesilvadi-sakin-yuruyus',
    title: 'Yeşilvadi Sakin Yürüyüş Hattı',
    districtId: 'yesilvadi',
    domain: 'container',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [6],
    avoidPilotDays: [1, 7],
    sceneText:
      'Yeşilvadi sakin yürüyüş hattında konteyner kapakları gece açık kalmış; sabah düzen bozuk görünüyor.',
    pressureText: 'Sakin mahallede küçük düzensizlik bile hızlı yankı alır.',
    decisionContextText: 'Sabah düzenleme bugün algıyı toparlar; sadece kapatma ise kısa süreli kalır.',
    shortTermEffectText: 'Sabah düzenleme hattı bugün görünür şekilde düzeltir.',
    tradeOffText: 'Fakat kapak kontrolü için ek tur gerekir.',
    carryOverText: 'Kapak kontrol rutini seçilirse yarın aynı sorun tekrarlamaz.',
    socialEchoText: 'Sakinler yürüyüş hattının düzeldiğini kısa notla paylaşır.',
    advisorEchoText: 'Ece, Yeşilvadi’de rutin kontrolün tekrarı azalttığını belirtir.',
    reportEchoText: 'Yürüyüş hattı düzeldi; kapak rutini raporda planlandı.',
    tags: ['yesilvadi', 'sakin', 'konteyner'],
    auditTargetScore: 85,
  },
];
