import type { ContentPackEventTemplate } from './contentPackTypes';

const AVOID_DAY1_7: number[] = [1, 7];

/** Content Safety Pack Aşama 2 — araç/rota, personel, sosyal, kriz-adjacent. */
export const OPERATION_DIVERSITY_CONTENT_PACK: ContentPackEventTemplate[] = [
  // —— Araç / Rota (9) ——
  {
    id: 'csp2-istasyon-aksam-rota-cakisma',
    title: 'İstasyon’da Akşam Rota Çakışması',
    districtId: 'istasyon',
    domain: 'route',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'İstasyon çevresinde akşam servis saatinden önce iki farklı sokaktan temizlik talebi geldi. Aynı araç iki noktaya yetişirse geçiş yolu kısa süreli daralabilir.',
    pressureText:
      'Sorun büyümeden çözülmezse akşam yoğunluğu araç rotasını daha görünür şekilde geciktirebilir.',
    decisionContextText:
      'Tek aracı hızlı yönlendirmek bugünkü gecikmeyi azaltır; rotayı bölmek daha yavaş görünür ama yarınki araç yorgunluğunu düşürür.',
    shortTermEffectText: 'Hızlı yönlendirme İstasyon’daki geçiş şikayetini bugün azaltır.',
    tradeOffText: 'Ama aynı araç hattı tekrar yüklenirse bakım riski ve yorgunluk artar.',
    carryOverText: 'Bölünmüş rota seçilirse ertesi gün İstasyon hattı daha dengeli başlar.',
    socialEchoText:
      'Yolun açık kalması fark edilir, fakat gecikme uzarsa sosyal nabızda rota eleştirisi oluşabilir.',
    advisorEchoText: 'Ece, İstasyon’da hız kadar rota dayanıklılığının önemli olduğunu belirtir.',
    reportEchoText: 'İstasyon’da akşam rota baskısı kontrol edildi; araç yükü yarın izlenmeli.',
    tags: ['istasyon', 'rota', 'gecis'],
    auditTargetScore: 92,
  },
  {
    id: 'csp2-merkez-rota-gecikme',
    title: 'Merkez’de Sabah Rota Gecikme Riski',
    districtId: 'merkez',
    domain: 'route',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Merkez çarşı hattında sabah toplama sırası kaydı; aynı araç meydan ve çarşı girişine ardışık bağlanırsa gecikme riski yükselir.',
    pressureText: 'Görünür alanda gecikme vatandaş beklentisini hızla düşürebilir.',
    decisionContextText:
      'Tek hat hızlı görünür sonuç verir; bölünmüş rota daha yavaş başlar ama gün sonu yükünü dengeler.',
    shortTermEffectText: 'Tek hat bugün çarşı girişindeki baskıyı hızla düşürür.',
    tradeOffText: 'Fakat gün sonuna kalan rota yükü artar ve araç bakım riski yükselir.',
    carryOverText: 'Dengeli rota seçilirse yarın Merkez hattı daha sakin açılır.',
    socialEchoText: 'Esnaf grupları erken toparlanmayı olumlu paylaşır, gecikme notları izlenir.',
    advisorEchoText: 'Ece, Merkez’de rota sırasının görünürlük etkisini hatırlatır.',
    reportEchoText: 'Merkez sabah hattı toparlandı; gün sonu rota yükü raporda izleniyor.',
    tags: ['merkez', 'rota', 'gecikme'],
    auditTargetScore: 88,
  },
  {
    id: 'csp2-cumhuriyet-dar-sokak-rota',
    title: 'Cumhuriyet’te Dar Sokak Rota Baskısı',
    districtId: 'cumhuriyet',
    domain: 'route',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Cumhuriyet apartman arası dar sokakta büyük araç manevra yapamıyor; küçük destek aracı gecikirse toplama hattı sabah sıkışır.',
    pressureText: 'Dar geçiş yolu tek araç hatasında tüm hattı yavaşlatır.',
    decisionContextText:
      'Büyük araç hızlı sonuç verir ama sokakta risk artar; küçük araç güvenli ilerler ama tempo düşer.',
    shortTermEffectText: 'Doğru araç seçimi dar sokağı bugün işler hale getirir.',
    tradeOffText: 'Ancak büyük araç tekrar yüklenirse bakım ve gecikme riski artar.',
    carryOverText: 'Küçük araç planı seçilirse ertesi gün dar sokak hattı daha güvenli kalır.',
    socialEchoText: 'Apartman temsilcileri sokağın açıldığını kısa notla paylaşır.',
    advisorEchoText: 'Ece, dar sokaklarda araç boyutu kadar rotanın da kritik olduğunu söyler.',
    reportEchoText: 'Dar sokak hattı açıldı; araç tipi yarın tekrar değerlendirilecek.',
    tags: ['cumhuriyet', 'dar_sokak', 'rota'],
    auditTargetScore: 90,
  },
  {
    id: 'csp2-sanayi-agir-arac-kapasite',
    title: 'Sanayi’de Ağır Araç Kapasite Seçimi',
    districtId: 'sanayi',
    domain: 'vehicle',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [3],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Sanayi servis yolunda ağır atık için büyük araç talebi var; aynı araç öğleden sonra başka hatta bağlanırsa kapasite baskısı büyür.',
    pressureText: 'Yanlış kapasite seçimi gecikme ve bakım riskini aynı güne sıkıştırır.',
    decisionContextText:
      'Büyük araç hattı hızlı temizler; bölünmüş kapasite yavaş görünür ama aracı korur.',
    shortTermEffectText: 'Büyük araç ağır atık hattını bugün hızla toparlar.',
    tradeOffText: 'Fakat yoğun kullanım araç yorgunluğunu artırır ve bakım riski yarına taşınır.',
    carryOverText: 'Bölünmüş kapasite seçilirse yarın Sanayi hattı daha dengeli başlar.',
    socialEchoText: 'Atölye çalışanları servis yolunun açılmasını olumlu görür.',
    advisorEchoText: 'Ece, Sanayi’de kapasite ile araç dayanıklılığını birlikte düşünmeni önerir.',
    reportEchoText: 'Ağır atık hattı kontrol altında; araç bakım riski yarın izlenmeli.',
    tags: ['sanayi', 'arac', 'kapasite'],
    auditTargetScore: 93,
  },
  {
    id: 'csp2-sanayi-bakim-risk-hatti',
    title: 'Sanayi Hattında Bakım Riski',
    districtId: 'sanayi',
    domain: 'vehicle',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Sanayi’de aynı kamyon üç gündür ağır hat üzerinde; bakım uyarısı yaklaşırken sabah yine yoğun rota isteniyor.',
    pressureText: 'Bakım ertelenirse gecikme riski ve saha güvenliği aynı anda zayıflar.',
    decisionContextText:
      'Araç bugün sahada kalırsa tempo korunur; kısa bakım penceresi yavaşlatır ama yarına dayanıklılık bırakır.',
    shortTermEffectText: 'Sahada tutulan araç bugünkü hattı kesintisiz sürdürür.',
    tradeOffText: 'Ama bakım riski artar ve ertesi gün arıza ihtimali yükselir.',
    carryOverText: 'Bakım penceresi seçilirse yarın Sanayi hattı daha güvenli açılır.',
    socialEchoText: 'Sürücü notları hızlı hattı olumlu görür, bakım gecikmesi konuşulabilir.',
    advisorEchoText: 'Ece, kısa vadeli hız ile araç ömrü arasındaki farkı vurgular.',
    reportEchoText: 'Hat sürdürüldü; bakım planı yarın raporda önceliklendirildi.',
    tags: ['sanayi', 'bakim', 'arac'],
    auditTargetScore: 89,
  },
  {
    id: 'csp2-yesilvadi-kucuk-arac-secimi',
    title: 'Yeşilvadi’de Küçük Araç Geçiş Planı',
    districtId: 'yesilvadi',
    domain: 'vehicle',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Yeşilvadi site içi dar yolda büyük araç park çevresine giremiyor; küçük destek aracı gecikirse düzen algısı bozulur.',
    pressureText: 'Hassas mahallede küçük gecikme bile görünürlük baskısı üretir.',
    decisionContextText:
      'Küçük araç sessiz ve hızlı toparlar; büyük araç dışarıdan toplar ama gürültü ve risk artar.',
    shortTermEffectText: 'Küçük araç park çevresini bugün düzenli tutar.',
    tradeOffText: 'Fakat ek tur gerekir ve gün sonu rota yükü artar.',
    carryOverText: 'Site içi plan seçilirse yarın Yeşilvadi hattı daha sakin kalır.',
    socialEchoText: 'Site sakinleri düzenin korunduğunu kısa notla paylaşır.',
    advisorEchoText: 'Ece, Yeşilvadi’de araç boyutunun algı kadar önemli olduğunu söyler.',
    reportEchoText: 'Park çevresi toparlandı; site içi rota yarın izlenecek.',
    tags: ['yesilvadi', 'arac', 'park'],
    auditTargetScore: 87,
  },
  {
    id: 'csp2-istasyon-durak-rota-gecikme',
    title: 'İstasyon Durak Hattında Rota Gecikmesi',
    districtId: 'istasyon',
    domain: 'route',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'İstasyon durak önünde sabah yolcu yoğunluğu başlamadan rota gecikmesi oluştu; servis yolu kısa süreli daralıyor.',
    pressureText: 'Durak çevresinde gecikme akşam dalgasına taşınırsa şikayet zinciri büyür.',
    decisionContextText:
      'Öncelikli yönlendirme bugün gecikmeyi keser; sıralı plan kaynak korur ama tempo düşer.',
    shortTermEffectText: 'Öncelikli yönlendirme durak hattını bugün rahatlatır.',
    tradeOffText: 'Ancak diğer hatlar kısa süre bekler ve rota çakışması riski artar.',
    carryOverText: 'Sıralı plan seçilirse ertesi gün durak hattı daha dengeli başlar.',
    socialEchoText: 'Yolcu grupları sabah düzenini olumlu görür, gecikme notları sürebilir.',
    advisorEchoText: 'Ece, durak hattında sabah gecikmesinin akşamı etkilediğini belirtir.',
    reportEchoText: 'Durak hattı toparlandı; akşam rota yükü yarın izlenmeli.',
    tags: ['istasyon', 'durak', 'rota'],
    auditTargetScore: 88,
  },
  {
    id: 'csp2-merkez-gun-sonu-rota-yuku',
    title: 'Merkez’de Gün Sonu Rota Yükü',
    districtId: 'merkez',
    domain: 'route',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Merkez belediye çevresinde öğleden sonra biriken çağrılar aynı araca yükleniyor; gün sonu rotası şişme eşiğine yaklaşıyor.',
    pressureText: 'Gün sonu yükü ertelenirse akşam görünürlük baskısı artar.',
    decisionContextText:
      'Ek sefer bugün yükü dağıtır; tek araçta sürdürmek hızlı görünür ama yorgunluk bırakır.',
    shortTermEffectText: 'Ek sefer gün sonu rota yükünü bugün dengeler.',
    tradeOffText: 'Fakat araç ve ekip temposu artar, bakım riski yarına taşınır.',
    carryOverText: 'Dengeli dağıtım seçilirse yarın Merkez rotası daha hafif başlar.',
    socialEchoText: 'Sosyal Nabız’da akşam toparlanma notu görünür, yorgunluk tartışılabilir.',
    advisorEchoText: 'Ece, gün sonu yükünün ertesi sabahı etkilediğini hatırlatır.',
    reportEchoText: 'Gün sonu rota yükü kontrol edildi; sabah tempo yarın izlenecek.',
    tags: ['merkez', 'rota', 'gun_sonu'],
    auditTargetScore: 86,
  },
  {
    id: 'csp2-cumhuriyet-ayni-arac-tekrar',
    title: 'Cumhuriyet’te Aynı Araç Tekrar Yükleme',
    districtId: 'cumhuriyet',
    domain: 'vehicle',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Cumhuriyet apartman hattında sabah müdahale için aynı kamyon tekrar yönlendiriliyor; ikinci tur gecikme riski taşır.',
    pressureText: 'Aynı aracın üst üste yüklenmesi bakım ve tempo kaybına yol açar.',
    decisionContextText:
      'Tek araç bugün hızlı sonuç verir; yedek araç daha yavaş başlar ama hattı korur.',
    shortTermEffectText: 'Tek araç apartman hattını bugün hızla toparlar.',
    tradeOffText: 'Ama araç yorgunluğu artar ve gecikme riski yarına taşınır.',
    carryOverText: 'Yedek araç planı seçilirse ertesi gün Cumhuriyet hattı daha dengeli başlar.',
    socialEchoText: 'Mahalle hızlı müdahaleyi fark eder, araç yoğunluğu konuşulabilir.',
    advisorEchoText: 'Ece, aynı aracı tekrar yüklemenin bedelini netleştirir.',
    reportEchoText: 'Apartman hattı toparlandı; araç rotasyonu yarın değerlendirilecek.',
    tags: ['cumhuriyet', 'arac', 'tekrar'],
    auditTargetScore: 88,
  },
  {
    id: 'csp2-merkez-arac-bakim-penceresi',
    title: 'Merkez Araç Bakım Penceresi',
    districtId: 'merkez',
    domain: 'vehicle',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Merkez hattındaki toplama aracı bakım uyarısı veriyor; sabah meydan çağrısı ile bakım penceresi çakışıyor.',
    pressureText: 'Bakım ertelenirse gecikme görünür alanda hızla şikayet üretir.',
    decisionContextText:
      'Araç sahada kalırsa bugün tempo korunur; kısa bakım güvenliği artırır ama bir hat bekler.',
    shortTermEffectText: 'Sahada araç meydan hattını bugün sürdürür.',
    tradeOffText: 'Fakat bakım riski artar ve ertesi gün arıza ihtimali yükselir.',
    carryOverText: 'Bakım penceresi seçilirse yarın Merkez aracı daha güvenli başlar.',
    socialEchoText: 'Vatandaşlar sabah hizmetini olumlu görür, gecikme riski izlenir.',
    advisorEchoText: 'Ece, görünür hatlarda bakım ertelemenin bedelini anlatır.',
    reportEchoText: 'Meydan hattı sürdürüldü; bakım yarın plana alındı.',
    tags: ['merkez', 'bakim', 'arac'],
    auditTargetScore: 85,
  },

  // —— Personel / Moral (8) ——
  {
    id: 'csp2-cumhuriyet-ekip-ust-ust-tempo',
    title: 'Cumhuriyet Ekibinde Üst Üste Tempo',
    districtId: 'cumhuriyet',
    domain: 'personnel',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Cumhuriyet’te saha ekibi iki gündür aynı apartman hattındaki şikayetlere müdahale ediyor. Bugün aynı ekibi tekrar göndermek hızlı sonuç verebilir.',
    pressureText:
      'Ekip tanıdığı bölgede hızlı çalışır, ancak üst üste yoğun tempo moral ve dikkat kaybı yaratabilir.',
    decisionContextText:
      'Aynı ekip bugünkü şikayeti çabuk düşürür; rotasyon daha yavaş görünür ama yarına ekip dayanıklılığı bırakır.',
    shortTermEffectText: 'Aynı ekip sahayı hızlı toparlar ve mahalle güvenini bugün korur.',
    tradeOffText: 'Fakat tekrar yüklenen ekipte moral düşüşü ve yarın yavaşlama riski artar.',
    carryOverText: 'Rotasyon seçilirse ertesi gün Cumhuriyet’te ekip temposu daha dengeli başlar.',
    socialEchoText:
      'Mahalle hızlı müdahaleyi fark eder, ama aynı ekibin sürekli sahada olması dikkat çekebilir.',
    advisorEchoText: 'Ece, hızlı sonuç ile ekip dayanıklılığı arasındaki farkı vurgular.',
    reportEchoText: 'Cumhuriyet’te müdahale hızı korundu; ekip temposu yarın dikkat istiyor.',
    tags: ['cumhuriyet', 'ekip', 'moral'],
    auditTargetScore: 94,
  },
  {
    id: 'csp2-merkez-saha-ekip-yorgun',
    title: 'Merkez Saha Ekibinde Yorgunluk',
    districtId: 'merkez',
    domain: 'personnel',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Merkez çarşı hattında sabah ekibi dün geç saate kadar sahada kaldı; bugün yine yoğun tempo isteniyor.',
    pressureText: 'Yorgun ekip hızlı başlar ama öğleden sonra dikkat kaybı riski artar.',
    decisionContextText:
      'Aynı tempo bugün görünür sonuç verir; kısa rotasyon daha yavaş görünür ama morali korur.',
    shortTermEffectText: 'Yoğun tempo çarşı hattını bugün erken toparlar.',
    tradeOffText: 'Ama ekip moralinde düşüş ve yarın yavaşlama riski artar.',
    carryOverText: 'Rotasyon seçilirse yarın Merkez ekibi daha taze başlar.',
    socialEchoText: 'Esnaf erken toparlanmayı olumlu görür, ekip yorgunluğu konuşulabilir.',
    advisorEchoText: 'Ece, Merkez’de tempo kadar ekip dinlenmesinin de kritik olduğunu söyler.',
    reportEchoText: 'Çarşı hattı toparlandı; ekip rotasyonu yarın planlandı.',
    tags: ['merkez', 'ekip', 'tempo'],
    auditTargetScore: 88,
  },
  {
    id: 'csp2-sanayi-atolye-ekip-moral',
    title: 'Sanayi Atölye Hattında Ekip Morali',
    districtId: 'sanayi',
    domain: 'personnel',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Sanayi ağır hat ekibi üst üste erken mesai aldı; atölye temsilcileri hız bekliyor, ekip ise tempo kaybı sinyali veriyor.',
    pressureText: 'Moral düşerse aynı gün içinde ikinci hat gecikebilir.',
    decisionContextText:
      'Hızlı ekip aynı hatta kalırsa bugün sonuç nettir; deneyimli yedek ekip daha yavaş ama güvenli ilerler.',
    shortTermEffectText: 'Deneyimli ekip atölye hattını bugün güvenle sürdürür.',
    tradeOffText: 'Fakat maliyet ve planlama baskısı artar, diğer hatlar bekleyebilir.',
    carryOverText: 'Kısa dinlenme arası seçilirse yarın Sanayi ekibi daha dengeli başlar.',
    socialEchoText: 'Atölye temsilcileri sürekliliği olumlu görür, tempo tartışması sürebilir.',
    advisorEchoText: 'Ece, Sanayi’de ekip moralinin hat güvenliğini etkilediğini belirtir.',
    reportEchoText: 'Atölye hattı sürdürüldü; ekip morali yarın izlenecek.',
    tags: ['sanayi', 'ekip', 'atolye'],
    auditTargetScore: 87,
  },
  {
    id: 'csp2-istasyon-servis-ekip-rotasyon',
    title: 'İstasyon Servis Ekibi Rotasyonu',
    districtId: 'istasyon',
    domain: 'personnel',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'İstasyon geçiş hattında aynı servis ekibi üç gündür akşam dalgasında; rotasyon gecikirse iletişim yükü artar.',
    pressureText: 'Tek ekip hızlıdır ama üst üste akşam temposu dayanıklılığı düşürür.',
    decisionContextText:
      'Aynı ekip bugün akşamı bilir; yeni ekip daha yavaş başlar ama taze tempo getirir.',
    shortTermEffectText: 'Aynı ekip akşam geçiş hattını bugün hızlı toparlar.',
    tradeOffText: 'Ancak moral düşüşü ve yarın sabah yavaşlama riski artar.',
    carryOverText: 'Rotasyon seçilirse ertesi gün İstasyon ekibi daha taze başlar.',
    socialEchoText: 'Yolcu grupları akşam düzenini olumlu görür, ekip değişimi fark edilir.',
    advisorEchoText: 'Ece, akşam dalgasında rotasyonun uzun vadede hız getirdiğini söyler.',
    reportEchoText: 'Geçiş hattı toparlandı; ekip rotasyonu yarın sürdürülecek.',
    tags: ['istasyon', 'rotasyon', 'ekip'],
    auditTargetScore: 86,
  },
  {
    id: 'csp2-yesilvadi-ekip-rotasyon',
    title: 'Yeşilvadi Ekip Rotasyon Talebi',
    districtId: 'yesilvadi',
    domain: 'personnel',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Yeşilvadi site hattında aynı ekip hafta boyunca sabah turu aldı; sakinler düzeni seviyor, ekip ise tempo kaybı bildiriyor.',
    pressureText: 'Küçük mahallede ekip yorgunluğu hızlı algıya yansır.',
    decisionContextText:
      'Aynı ekip tanıdık alanda hızlıdır; rotasyon daha yavaş görünür ama dikkati artırır.',
    shortTermEffectText: 'Aynı ekip site hattını bugün tanıdık tempoda toparlar.',
    tradeOffText: 'Fakat moral düşüşü yarın aynı noktada tekrar baskı üretebilir.',
    carryOverText: 'Rotasyon seçilirse yarın Yeşilvadi ekibi daha taze başlar.',
    socialEchoText: 'Site sakinleri düzeni olumlu görür, ekip değişimi kısa süre konuşulur.',
    advisorEchoText: 'Ece, Yeşilvadi’de küçük ekiplerin rotasyonla güçlendiğini söyler.',
    reportEchoText: 'Site hattı toparlandı; rotasyon yarın uygulanacak.',
    tags: ['yesilvadi', 'rotasyon', 'ekip'],
    auditTargetScore: 84,
  },
  {
    id: 'csp2-cumhuriyet-deneyimli-ekip',
    title: 'Cumhuriyet’te Deneyimli Ekip Seçimi',
    districtId: 'cumhuriyet',
    domain: 'personnel',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Cumhuriyet esnaf hattında karmaşık şikayet için deneyimli ekip talep ediliyor; genç ekip hızlı ama iletişim riski taşır.',
    pressureText: 'Yanlış ekip eşleşmesi aynı gün ikinci müdahale ihtiyacı doğurur.',
    decisionContextText:
      'Deneyimli ekip bugün güven verir; hızlı ekip daha erken biter ama tekrar çağrı riski artar.',
    shortTermEffectText: 'Deneyimli ekip esnaf hattını bugün tek seferde toparlar.',
    tradeOffText: 'Ama diğer hatlar kısa süre bekler ve kaynak baskısı artar.',
    carryOverText: 'Doğru eşleşme seçilirse yarın Cumhuriyet hattı daha sakin kalır.',
    socialEchoText: 'Esnaf odası müdahale kalitesini olumlu not eder.',
    advisorEchoText: 'Ece, doğru ekip eşleşmesinin tekrar maliyetini düşürdüğünü belirtir.',
    reportEchoText: 'Esnaf hattı toparlandı; ekip eşleşmesi yarın kayıtlı.',
    tags: ['cumhuriyet', 'deneyimli', 'ekip'],
    auditTargetScore: 87,
  },
  {
    id: 'csp2-sanayi-teknik-ekip-eslesme',
    title: 'Sanayi Teknik Ekip Eşleşmesi',
    districtId: 'sanayi',
    domain: 'personnel',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [3, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Sanayi ağır hat için teknik ekip ile saha ekibi aynı saatte talep ediliyor; yanlış sıra gecikme üretir.',
    pressureText: 'Teknik ve saha eşleşmezse atölye şikayeti aynı gün büyür.',
    decisionContextText:
      'Önce teknik hazırlık güvenli ilerler; önce saha hızlı görünür ama geri dönüş riski artar.',
    shortTermEffectText: 'Doğru sıra atölye hattını bugün kesintisiz sürdürür.',
    tradeOffText: 'Fakat toplam tempo düşer ve diğer hatlar bekleyebilir.',
    carryOverText: 'Eşleşme planı seçilirse yarın Sanayi hattı daha az tekrar üretir.',
    socialEchoText: 'Atölye temsilcileri doğru sırayı olumlu görür.',
    advisorEchoText: 'Ece, teknik-saha eşleşmesinin Sanayi’de kritik olduğunu söyler.',
    reportEchoText: 'Atölye hattı sürdürüldü; ekip sırası yarın sabitlenecek.',
    tags: ['sanayi', 'teknik', 'ekip'],
    auditTargetScore: 86,
  },
  {
    id: 'csp2-istasyon-aksam-ekip-tempo',
    title: 'İstasyon Akşam Ekip Temposu',
    districtId: 'istasyon',
    domain: 'personnel',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [3],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'İstasyon akşam dalgasında ekip üst üste geçiş müdahalesi aldı; halk iletişimi ekibi de aynı saate çekilmek isteniyor.',
    pressureText: 'İletişim ve saha aynı anda yüklenirse tempo çöker, gecikme görünür olur.',
    decisionContextText:
      'Saha önceliği bugün fiziksel düzeni toparlar; iletişim önceliği algıyı yumuşatır ama sahayı yavaşlatır.',
    shortTermEffectText: 'Saha önceliği geçiş hattını bugün hızla toparlar.',
    tradeOffText: 'Ama sosyal nabızda gecikme eleştirisi sürebilir ve moral baskısı artar.',
    carryOverText: 'Dengeli görev paylaşımı seçilirse yarın İstasyon temposu daha iyi başlar.',
    socialEchoText: 'Yolcu grupları düzeni fark eder, iletişim gecikmesi tartışılabilir.',
    advisorEchoText: 'Ece, akşamda saha ve iletişim yükünü ayırmanın önemini vurgular.',
    reportEchoText: 'Geçiş hattı toparlandı; görev paylaşımı yarın güncellenecek.',
    tags: ['istasyon', 'aksam', 'ekip'],
    auditTargetScore: 88,
  },

  // —— Sosyal Nabız (8) ——
  {
    id: 'csp2-merkez-gorunurluk-baskisi',
    title: 'Merkez’de Görünürlük Baskısı',
    districtId: 'merkez',
    domain: 'social',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [4, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Merkez çarşı hattındaki küçük bir temizlik aksaması sabah kalabalığında hızlı fark edildi. Sorun fiziksel olarak sınırlı, fakat görünürlüğü yüksek.',
    pressureText:
      'Geç kalınırsa küçük aksama sosyal nabızda büyük bir hizmet algısı sorununa dönüşebilir.',
    decisionContextText:
      'Sessiz saha müdahalesi hızlı sonuç verir; kısa bilgilendirme sosyal baskıyı daha hızlı sakinleştirir ama ekip temposunu yavaşlatır.',
    shortTermEffectText: 'Bilgilendirme seçilirse vatandaş güveni bugün daha hızlı toparlanır.',
    tradeOffText: 'Fakat iletişim odaklı çözüm saha temizliğini birkaç adım yavaşlatabilir.',
    carryOverText: 'Doğru iletişim yapılırsa ertesi gün Merkez’de görünürlük baskısı daha düşük başlar.',
    socialEchoText: 'Vatandaşlar küçük sorunun fark edildiğini ve takip edildiğini konuşur.',
    advisorEchoText: 'Ece, Merkez’de fiziksel sorun kadar görünürlük etkisinin de önemli olduğunu söyler.',
    reportEchoText: 'Merkez’de sosyal görünürlük baskısı sakinleşti; saha temposu yarın dengelenmeli.',
    tags: ['merkez', 'gorunurluk', 'sosyal'],
    auditTargetScore: 93,
  },
  {
    id: 'csp2-cumhuriyet-mahalle-kiyasi',
    title: 'Cumhuriyet’te Mahalle Kıyası',
    districtId: 'cumhuriyet',
    domain: 'social',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [4, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Cumhuriyet apartman grubu, komşu mahalledeki hızlı müdahaleyi kendi hattıyla kıyaslıyor. Sorun küçük ama algı büyüyor.',
    pressureText: 'Mahalle kıyası sosyal nabızda adil dağılım tartışması başlatabilir.',
    decisionContextText:
      'Hızlı müdahale bugün algıyı düşürür; planlı sıra adaleti korur ama tempo düşer.',
    shortTermEffectText: 'Hızlı müdahale mahalle kıyasını bugün yumuşatır.',
    tradeOffText: 'Ama diğer hatlar kısa süre bekler ve kaynak dengesi bozulabilir.',
    carryOverText: 'Planlı sıra seçilirse yarın Cumhuriyet’te kıyas baskısı daha düşük başlar.',
    socialEchoText: 'Apartman temsilcileri müdahaleyi olumlu paylaşır, kıyas notları sürer.',
    advisorEchoText: 'Ece, mahalle kıyasının görünür adalet ihtiyacı doğurduğunu belirtir.',
    reportEchoText: 'Cumhuriyet algısı toparlandı; hat sırası yarın güncellenecek.',
    tags: ['cumhuriyet', 'kiyas', 'sosyal'],
    auditTargetScore: 89,
  },
  {
    id: 'csp2-sanayi-atolye-algi',
    title: 'Sanayi Atölye Algısı',
    districtId: 'sanayi',
    domain: 'social',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [4],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Sanayi atölye hattında gürültü ve düzen şikayeti birleşti; fiziksel risk sınırlı ama esnaf algısı hızla kötüleşiyor.',
    pressureText: 'Algı bozulursa teknik müdahale bile geç kalıyor gibi görünür.',
    decisionContextText:
      'Saha önceliği düzeni bugün toparlar; kısa bilgilendirme algıyı yumuşatır ama tempo düşer.',
    shortTermEffectText: 'Bilgilendirme atölye güvenini bugün hızla toparlar.',
    tradeOffText: 'Fakat saha müdahalesi birkaç saat gecikebilir.',
    carryOverText: 'Doğru iletişim seçilirse yarın Sanayi algısı daha sakin başlar.',
    socialEchoText: 'Esnaf grupları sosyal nabızda takip edildiğini olumlu not eder.',
    advisorEchoText: 'Ece, Sanayi’de algı ile teknik çözümün aynı günde yönetilmesi gerektiğini söyler.',
    reportEchoText: 'Atölye algısı toparlandı; saha temposu yarın izlenecek.',
    tags: ['sanayi', 'atolye', 'sosyal'],
    auditTargetScore: 87,
  },
  {
    id: 'csp2-istasyon-yolcu-algi',
    title: 'İstasyon Yolcu Algısı',
    districtId: 'istasyon',
    domain: 'social',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [4],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'İstasyon durak çevresinde düzensiz görüntü yolcular tarafından fotoğraflandı; sorun küçük ama paylaşım hızlı.',
    pressureText: 'Görünürlük yüksek geçiş noktasında gecikme algısı hızla büyür.',
    decisionContextText:
      'Hızlı saha müdahalesi görüntüyü bugün temizler; kısa duyuru algıyı yumuşatır ama ekip temposunu böler.',
    shortTermEffectText: 'Hızlı müdahale paylaşım öncesi alanı toparlar.',
    tradeOffText: 'Ama iletişim ekibi diğer hatlardan çekilir.',
    carryOverText: 'Düzenli görüntü kontrolü seçilirse yarın benzer paylaşım azalır.',
    socialEchoText: 'Sosyal Nabız’da toparlanma notları görünmeye başlar.',
    advisorEchoText: 'Ece, geçiş noktalarında görünürlüğün karar hızını artırdığını belirtir.',
    reportEchoText: 'Durak çevresi toparlandı; görüntü takibi yarın sürecek.',
    tags: ['istasyon', 'yolcu', 'sosyal'],
    auditTargetScore: 88,
  },
  {
    id: 'csp2-yesilvadi-cevre-algi',
    title: 'Yeşilvadi Çevre Algısı',
    districtId: 'yesilvadi',
    domain: 'social',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [4, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Yeşilvadi park çevresinde küçük düzensizlik sabah yürüyüş saatinde dikkat çekti; sakinler çevre düzenine duyarlı.',
    pressureText: 'Küçük sorun hassas mahallede sosyal memnuniyeti hızla düşürebilir.',
    decisionContextText:
      'Sessiz müdahale bugünü toparlar; kısa bilgilendirme güveni artırır ama ek süre ister.',
    shortTermEffectText: 'Sessiz müdahale park çevresini bugün görünür şekilde düzeltir.',
    tradeOffText: 'Fakat bilgilendirme olmazsa algı yavaş toparlanır.',
    carryOverText: 'Doğru iletişim seçilirse yarın Yeşilvadi algısı daha sakin başlar.',
    socialEchoText: 'Sakinler düzenin fark edildiğini kısa notla paylaşır.',
    advisorEchoText: 'Ece, Yeşilvadi’de algı etkisinin fiziksel boyuttan büyük olabileceğini söyler.',
    reportEchoText: 'Park çevresi toparlandı; algı yarın izlenecek.',
    tags: ['yesilvadi', 'cevre', 'sosyal'],
    auditTargetScore: 86,
  },
  {
    id: 'csp2-merkez-takdir-sikayet',
    title: 'Merkez’de Takdir ve Şikayet Birlikte',
    districtId: 'merkez',
    domain: 'social',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [4, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Merkez meydanında bir esnaf hızlı müdahale için teşekkür ederken, çarşı girişinden yeni şikayet geliyor; takdir ve baskı aynı saate denk geldi.',
    pressureText: 'Yalnızca takdiri görmek ikinci şikayeti büyütebilir.',
    decisionContextText:
      'Çarşı önceliği bugün şikayeti düşürür; meydan önceliği görünürlüğü korur ama esnaf algısını zorlar.',
    shortTermEffectText: 'Doğru öncelik bugün her iki noktada da güven üretir.',
    tradeOffText: 'Ama tek ekip iki alanda yorulur ve tempo düşer.',
    carryOverText: 'Dengeli öncelik seçilirse yarın Merkez algısı daha stabil başlar.',
    socialEchoText: 'Vatandaşlar hem teşekkür hem takip beklentisini aynı anda konuşur.',
    advisorEchoText: 'Ece, Merkez’de takdirin ikinci şikayeti gölgelememesi gerektiğini söyler.',
    reportEchoText: 'Meydan ve çarşı algısı dengelendi; öncelik yarın gözden geçirilecek.',
    tags: ['merkez', 'takdir', 'sosyal'],
    auditTargetScore: 88,
  },
  {
    id: 'csp2-cumhuriyet-apartman-algi',
    title: 'Cumhuriyet Apartman Algısı',
    districtId: 'cumhuriyet',
    domain: 'social',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [4],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Cumhuriyet apartman temsilcileri, konut hattındaki gecikmenin sosyal grupta paylaşıldığını bildiriyor; sorun orta, algı hızlı.',
    pressureText: 'Apartman zincirinde gecikme aynı gün yeni şikayet üretir.',
    decisionContextText:
      'Hızlı müdahale paylaşımı bugün keser; kısa bilgilendirme güveni artırır ama sahayı böler.',
    shortTermEffectText: 'Hızlı müdahale apartman algısını bugün yumuşatır.',
    tradeOffText: 'Fakat iletişim süresi diğer sokakları bekletebilir.',
    carryOverText: 'Bilgilendirme planı seçilirse yarın apartman hattı daha sakin başlar.',
    socialEchoText: 'Apartman grubu müdahaleyi olumlu paylaşır, gecikme notları azalır.',
    advisorEchoText: 'Ece, konut yoğunluğunda algının hızla yayıldığını hatırlatır.',
    reportEchoText: 'Apartman algısı toparlandı; iletişim planı yarın sürecek.',
    tags: ['cumhuriyet', 'apartman', 'sosyal'],
    auditTargetScore: 87,
  },
  {
    id: 'csp2-istasyon-sessiz-mudahale',
    title: 'İstasyon’da Sessiz Müdahale Tartışması',
    districtId: 'istasyon',
    domain: 'social',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [4, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'İstasyon çıkışında sessiz saha müdahalesi hızlı sonuç verdi; yolcu algısı için kısa bilgilendirme talebi de geliyor.',
    pressureText: 'Sessiz çözüm hızlıdır ama algı yönetimi gecikirse eleştiri sürer.',
    decisionContextText:
      'Saha önceliği düzeni bugün toparlar; kısa duyuru algıyı dengeler ama tempo düşer.',
    shortTermEffectText: 'Kısa duyuru yolcu güvenini bugün toparlar.',
    tradeOffText: 'Ama saha müdahalesi bir tur gecikebilir.',
    carryOverText: 'Dengeli iletişim seçilirse yarın İstasyon algısı daha stabil başlar.',
    socialEchoText: 'Yolcu notlarında takip edildiği mesajı artar.',
    advisorEchoText: 'Ece, sessiz hız ile görünür iletişim arasında denge kurmanı önerir.',
    reportEchoText: 'Çıkış hattı toparlandı; iletişim tonu yarın güncellenecek.',
    tags: ['istasyon', 'iletisim', 'sosyal'],
    auditTargetScore: 85,
  },

  // —— Kriz-adjacent (7) ——
  {
    id: 'csp2-sanayi-risk-sinyal-birlesimi',
    title: 'Sanayi’de Risk Sinyali Birleşiyor',
    districtId: 'sanayi',
    domain: 'crisis_adjacent',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [6],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Sanayi’de ağır atık hattı, araç yorgunluğu ve atölye çıkışı şikayetleri aynı sabaha sıkıştı. Henüz kriz yok, ama üç sinyal aynı bölgede birleşiyor.',
    pressureText:
      'Bugün yanlış kaynak seçilirse sorun tek bir temizlik aksamasından operasyon baskısına dönebilir.',
    decisionContextText:
      'Kaynak yoğun müdahale riski bugün düşürür; kontrollü izleme kaynakları korur ama yarın kriz eşiğini yükseltebilir.',
    shortTermEffectText: 'Güçlü müdahale Sanayi’de risk sinyallerini bugün dağıtır.',
    tradeOffText: 'Fakat kaynak yoğun çözüm araç ve ekip temposunu artırarak yarına yorgunluk bırakır.',
    carryOverText: 'Kontrollü izleme seçilirse ertesi gün Sanayi’de kriz eşiği daha hassas başlar.',
    socialEchoText:
      'Atölye hattında sorun büyümeden izleniyor algısı oluşur, ancak gecikme eleştirisi sürebilir.',
    advisorEchoText:
      'Ece, bunun kriz değil ama birleşen sinyaller nedeniyle önleyici karar istediğini belirtir.',
    reportEchoText:
      'Sanayi’de kriz öncesi sinyal izlendi; kaynak yükü ve sosyal tepki yarın birlikte değerlendirilmeli.',
    tags: ['sanayi', 'sinyal', 'onleyici'],
    auditTargetScore: 95,
  },
  {
    id: 'csp2-merkez-kaynak-gorunurluk',
    title: 'Merkez’de Kaynak ve Görünürlük Birleşimi',
    districtId: 'merkez',
    domain: 'crisis_adjacent',
    intensity: 'high',
    phase: ['pilot'],
    preferredPilotDays: [6],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Merkez’de çarşı görünürlük baskısı ile gün sonu rota yükü aynı anda yükseldi. Henüz kriz değil, fakat iki sinyal kamu algısını zorluyor.',
    pressureText: 'Yanlış öncelik hem sahayı hem sosyal nabzı aynı gün zorlar.',
    decisionContextText:
      'Görünür hız bugün algıyı korur; kaynak koruma yavaş görünür ama yarına denge bırakır.',
    shortTermEffectText: 'Görünür hız Merkez algısını bugün stabilize eder.',
    tradeOffText: 'Ama rota ve ekip yükü yarına taşınır.',
    carryOverText: 'Kaynak koruma seçilirse yarın Merkez eşiği daha kontrollü başlar.',
    socialEchoText: 'Vatandaşlar müdahaleyi fark eder, gecikme riski konuşulabilir.',
    advisorEchoText: 'Ece, henüz kriz olmayan birleşen sinyallerde önceliği netleştirmeni ister.',
    reportEchoText: 'Merkez sinyalleri izlendi; kaynak ve algı yarın birlikte değerlendirilecek.',
    tags: ['merkez', 'sinyal', 'gorunurluk'],
    auditTargetScore: 91,
  },
  {
    id: 'csp2-cumhuriyet-sinyal-zinciri',
    title: 'Cumhuriyet’te Sinyal Zinciri',
    districtId: 'cumhuriyet',
    domain: 'crisis_adjacent',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [6],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Cumhuriyet’te apartman şikayeti, ekip yorgunluğu ve dar sokak rota baskısı aynı hatta birleşti. Henüz kriz yok, önleyici karar gerekli.',
    pressureText: 'Tek hatta üç sinyal birleşince ikinci müdahale riski artar.',
    decisionContextText:
      'Yoğun müdahale zinciri bugün kırar; kontrollü tempo yavaş görünür ama yarına dayanıklılık bırakır.',
    shortTermEffectText: 'Yoğun müdahale sinyal zincirini bugün dağıtır.',
    tradeOffText: 'Ama ekip moralinde düşüş ve yarın yavaşlama riski artar.',
    carryOverText: 'Kontrollü tempo seçilirse ertesi gün zincir baskısı daha düşük başlar.',
    socialEchoText: 'Apartman grubu izleniyor algısı görür, tempo eleştirisi sürebilir.',
    advisorEchoText: 'Ece, zincirleşen sinyallerde hız kadar sürdürülebilirliği hatırlatır.',
    reportEchoText: 'Sinyal zinciri izlendi; ekip ve rota yarın birlikte değerlendirilecek.',
    tags: ['cumhuriyet', 'sinyal', 'zincir'],
    auditTargetScore: 90,
  },
  {
    id: 'csp2-istasyon-onleyici-sinyal',
    title: 'İstasyon’da Önleyici Sinyal',
    districtId: 'istasyon',
    domain: 'crisis_adjacent',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [6],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'İstasyon’da akşam rota gecikmesi, yolcu algısı ve ekip yorgunluğu aynı saate denk geldi. Henüz kriz değil, sinyal yükseliyor.',
    pressureText: 'Akşam dalgasında gecikme görünür şikayete hızla dönüşebilir.',
    decisionContextText:
      'Önleyici rota bölme bugün riski düşürür; tek hat hızlı görünür ama yorgunluk bırakır.',
    shortTermEffectText: 'Önleyici bölme akşam riskini bugün dağıtır.',
    tradeOffText: 'Fakat toplam tempo düşer ve bazı hatlar bekler.',
    carryOverText: 'Bölünmüş rota seçilirse yarın İstasyon eşiği daha düşük başlar.',
    socialEchoText: 'Yolcu grupları önleyici müdahaleyi fark eder, gecikme notları azalabilir.',
    advisorEchoText: 'Ece, akşamda birleşen sinyallerin önleyici karar istediğini söyler.',
    reportEchoText: 'İstasyon önleyici sinyal izlendi; akşam yükü yarın değerlendirilecek.',
    tags: ['istasyon', 'onleyici', 'sinyal'],
    auditTargetScore: 89,
  },
  {
    id: 'csp2-yesilvadi-hassas-sinyal',
    title: 'Yeşilvadi Hassas Sinyal Birleşimi',
    districtId: 'yesilvadi',
    domain: 'crisis_adjacent',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [6],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Yeşilvadi’de park çevresi algısı, küçük rota gecikmesi ve ekip tempo kaybı aynı sabaha denk geldi. Henüz kriz yok, hassas eşik yaklaşıyor.',
    pressureText: 'Hassas mahallede küçük birleşim bile sosyal memnuniyeti düşürebilir.',
    decisionContextText:
      'Hızlı toparlama bugün algıyı korur; önleyici plan yavaş görünür ama yarına düzen bırakır.',
    shortTermEffectText: 'Hızlı toparlama park çevresi algısını bugün korur.',
    tradeOffText: 'Ama ekip ve rota yükü yarına taşınabilir.',
    carryOverText: 'Önleyici plan seçilirse yarın Yeşilvadi eşiği daha sakin başlar.',
    socialEchoText: 'Sakinler izleniyor algısı görür, küçük gecikme notları sürebilir.',
    advisorEchoText: 'Ece, hassas mahallede birleşen sinyallerin erken yönetilmesini önerir.',
    reportEchoText: 'Hassas sinyal izlendi; park ve rota yarın birlikte değerlendirilecek.',
    tags: ['yesilvadi', 'hassas', 'sinyal'],
    auditTargetScore: 88,
  },
  {
    id: 'csp2-sanayi-onleyici-baski',
    title: 'Sanayi Önleyici Baskı Eşiği',
    districtId: 'sanayi',
    domain: 'crisis_adjacent',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [6],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Sanayi’de konteyner baskısı ile araç bakım riski aynı hatta birleşti. Henüz kriz değil, önleyici karar eşiği yaklaşıyor.',
    pressureText: 'İki operasyon sinyali birleşince tek hat baskı riski hızla artar.',
    decisionContextText:
      'Kaynak yoğun çözüm bugün baskıyı keser; izleme kaynak korur ama yarın eşiği yükseltir.',
    shortTermEffectText: 'Kaynak yoğun çözüm baskıyı bugün dağıtır.',
    tradeOffText: 'Fakat araç ve ekip yorgunluğu yarına taşınır.',
    carryOverText: 'İzleme seçilirse ertesi gün Sanayi eşiği daha hassas başlar.',
    socialEchoText: 'Atölye hattında kontrol altında algısı oluşur.',
    advisorEchoText: 'Ece, önleyici kararın kriz başlatmadan riski kestiğini vurgular.',
    reportEchoText: 'Önleyici baskı izlendi; kaynak yükü yarın raporlanacak.',
    tags: ['sanayi', 'onleyici', 'baski'],
    auditTargetScore: 87,
  },
  {
    id: 'csp2-merkez-mahalle-denge',
    title: 'Merkez Mahalle Denge Sinyali',
    districtId: 'merkez',
    domain: 'crisis_adjacent',
    intensity: 'medium',
    phase: ['pilot'],
    preferredPilotDays: [6, 5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Merkez’de meydan önceliği ile çarşı hattı arasında kaynak çekişmesi büyüyor; henüz kriz değil, mahalle dengesi sinyali veriyor.',
    pressureText: 'Denge bozulursa bir noktada memnuniyet düşerken diğerinde risk artar.',
    decisionContextText:
      'Dengeli paylaşım her iki hattı orta seviyede tutar; tek öncelik bir tarafı hızlı toparlar ama diğerini zorlar.',
    shortTermEffectText: 'Dengeli paylaşım her iki hattı bugün kabul edilebilir seviyede tutar.',
    tradeOffText: 'Ama tam çözüm bugün görünmeyebilir ve yarına takip bırakır.',
    carryOverText: 'Denge planı seçilirse yarın Merkez hatları daha uyumlu başlar.',
    socialEchoText: 'Vatandaşlar kısmi toparlanmayı konuşur, adalet beklentisi sürer.',
    advisorEchoText: 'Ece, birleşen öncelik sinyallerinde dengeyi kritik görür.',
    reportEchoText: 'Mahalle dengesi izlendi; öncelik paylaşımı yarın güncellenecek.',
    tags: ['merkez', 'denge', 'sinyal'],
    auditTargetScore: 86,
  },
  {
    id: 'csp2-yesilvadi-park-rota',
    title: 'Yeşilvadi Park Rota Daralması',
    districtId: 'yesilvadi',
    domain: 'route',
    intensity: 'low',
    phase: ['pilot'],
    preferredPilotDays: [5],
    avoidPilotDays: AVOID_DAY1_7,
    sceneText:
      'Yeşilvadi park çevresinde sabah toplama aracı yürüyüş yoluna yaklaştı; rota daralması sakinlerde dikkat çekti.',
    pressureText: 'Hassas alanda rota hatası algıyı hızla düşürür.',
    decisionContextText:
      'Alternatif rota daha uzun ama güvenli; kısa rota hızlı ama görünürlük riski taşır.',
    shortTermEffectText: 'Alternatif rota park çevresini bugün güvenle toparlar.',
    tradeOffText: 'Fakat toplama süresi uzar ve gün sonu yükü artar.',
    carryOverText: 'Güvenli rota seçilirse yarın park hattı daha sakin kalır.',
    socialEchoText: 'Sakinler güvenli müdahaleyi olumlu görür.',
    advisorEchoText: 'Ece, park çevresinde rota seçiminin algıyı belirlediğini söyler.',
    reportEchoText: 'Park rotası güncellendi; yarın aynı plan izlenecek.',
    tags: ['yesilvadi', 'park', 'rota'],
    auditTargetScore: 85,
  },
];
