import type {
  PlayerFlowCheckDefinition,
  PlayerFlowManualChecklistItem,
  PlayerFlowStage,
} from './playerFlowAuditTypes';

export const PLAYER_FLOW_FORBIDDEN_WORDS = [
  'xp',
  'premium',
  'satın al',
  'kilitli',
] as const;

export const PLAYER_FLOW_AUDIT_SCENARIO_ID = 'crevia_player_flow_v1';

export const REQUIRED_PLAYER_FLOW_STAGES: PlayerFlowStage[] = [
  'day1_first_session',
  'day2_reinforcement',
  'day3_system_expansion',
  'day7_pilot_completion',
  'post_pilot_offer',
  'day8_limited',
  'day8_full',
  'full_main_crisis',
  'full_main_resources',
  'full_main_report',
];

export const PLAYER_FLOW_STAGE_LABELS: Record<PlayerFlowStage, string> = {
  day1_first_session: 'Gün 1 — İlk oturum',
  day2_reinforcement: 'Gün 2 — Pekiştirme',
  day3_system_expansion: 'Gün 3 — Sistem genişlemesi',
  day7_pilot_completion: 'Gün 7 — Pilot kapanışı',
  post_pilot_offer: 'Post-pilot teklif',
  day8_limited: 'Gün 8 — Sınırlı gündem',
  day8_full: 'Gün 8 — Ana Operasyon',
  full_main_crisis: 'Ana Operasyon — Kriz',
  full_main_resources: 'Ana Operasyon — Saha kaynakları',
  full_main_report: 'Ana Operasyon — Rapor',
};

export const PLAYER_FLOW_SURFACE_LABELS: Record<
  import('./playerFlowAuditTypes').PlayerFlowSurface,
  string
> = {
  hub: 'Operasyon Merkezi',
  event_plan: 'Olay planı',
  event_dispatch: 'Atama',
  event_field: 'Saha',
  event_result: 'Sonuç',
  report: 'Gün sonu raporu',
  map: 'Harita',
  social: 'Sosyal nabız',
  profile: 'Profil',
  post_pilot_offer: 'Ana Operasyon teklifi',
};

export const PLAYER_FLOW_AUDIT_SCENARIO_META = {
  id: PLAYER_FLOW_AUDIT_SCENARIO_ID,
  title: 'Crevia Gerçek Oyuncu Akışı Denetimi',
  description:
    'First 10 Minutes, kaynaklar, kriz, monetization gate ve rapor yüzeylerinin otomatik sözleşme denetimi.',
};

/** Otomatik + manuel işaretli akış kontrolleri */
export const PLAYER_FLOW_CHECK_DEFINITIONS: PlayerFlowCheckDefinition[] = [
  // —— Day 1 ——
  {
    id: 'day1_hub_max_featured',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Hub yoğunluğu',
    question: 'Hub’da en fazla 2 featured kart var mı?',
    expectedOutcome: 'maxFeaturedCards ≤ 2; oyuncu boğulmaz.',
    riskLevel: 'high',
    recommendation: 'Featured kart sayısını 2’de tut; diğer kartları compact/hidden bırak.',
  },
  {
    id: 'day1_advisor_short',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Ece kısa mod',
    question: 'Ece tek net aksiyon öneriyor mu?',
    expectedOutcome: 'Day 1 advisor short mode; uzun trade-off yok.',
    riskLevel: 'medium',
    recommendation: 'Ece metnini tek cümle + tek CTA ile sınırla.',
  },
  {
    id: 'day1_daily_plan_featured',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Önerilen plan',
    question: 'Günlük plan önerilen plan olarak görünüyor mu?',
    expectedOutcome: 'DailyPlan featured; confirm CTA net.',
    riskLevel: 'high',
    recommendation: '“Planı Onayla” CTA’sını birincil aksiyon yap.',
  },
  {
    id: 'day1_daily_plan_edit_locked',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Plan düzenleme kapalı',
    question: 'Day 1 plan düzenleme kapalı ve açıklamalı mı?',
    expectedOutcome: 'Edit disabled + educational note.',
    riskLevel: 'medium',
    recommendation: 'Düzenleme kapalıyken kısa neden metni göster.',
  },
  {
    id: 'day1_assignment_recommended',
    stage: 'day1_first_session',
    surface: 'event_dispatch',
    title: 'Önerilen atama',
    question: 'Atama önerilen akışla ilerliyor mu?',
    expectedOutcome: 'Simple assignment mode; önerilen onay CTA.',
    riskLevel: 'high',
    recommendation: 'Gelişmiş editörü Day 1’de gizle.',
  },
  {
    id: 'day1_micro_hidden',
    stage: 'day1_first_session',
    surface: 'event_field',
    title: 'MicroDecision gizli',
    question: 'Canlı operasyon kararı Day 1’de görünmüyor mu?',
    expectedOutcome: 'MicroDecision UI/engine Day 1 inactive.',
    riskLevel: 'critical',
    recommendation: 'Day 1–2 micro decision kartını tamamen gizle.',
  },
  {
    id: 'day1_crisis_hidden',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Kriz gizli',
    question: 'Kriz masası Day 1’de görünmüyor mu?',
    expectedOutcome: 'Crisis desk ve crisis actions hidden.',
    riskLevel: 'critical',
    recommendation: 'Pilot günlerinde kriz UI’ını kapalı tut.',
  },
  {
    id: 'day1_main_op_hidden',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Ana Operasyon sezonu gizli',
    question: 'MainOperationSeason Day 1’de görünmüyor mu?',
    expectedOutcome: 'Season card hidden.',
    riskLevel: 'high',
    recommendation: 'Sezon kartını post-pilot sonrasına bırak.',
  },
  {
    id: 'day1_resources_hidden',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Saha kaynakları minimum',
    question: 'Saha Kaynakları Day 1’de gizli mi?',
    expectedOutcome: 'Operational resources hub card hidden.',
    riskLevel: 'medium',
    recommendation: 'Kaynak kartını Day 2+ aç.',
  },
  {
    id: 'day1_report_educational',
    stage: 'day1_first_session',
    surface: 'report',
    title: 'Day 1 rapor',
    question: 'Rapor öğretici ve kısa mı?',
    expectedOutcome: 'Educational line; advanced kartlar gizli.',
    riskLevel: 'high',
    recommendation: 'Raporu tek eğitim satırı + dönüş CTA ile sınırla.',
  },
  {
    id: 'day1_report_cta_hub',
    stage: 'day1_first_session',
    surface: 'report',
    title: 'Rapor CTA',
    question: 'Rapor CTA Operasyon Merkezine Dön mü?',
    expectedOutcome: 'Primary CTA hub’a döner.',
    riskLevel: 'medium',
    recommendation: 'CTA etiketini “Operasyon Merkezine Dön” olarak sabitle.',
  },
  // —— Day 2 ——
  {
    id: 'day2_signals_visible',
    stage: 'day2_reinforcement',
    surface: 'hub',
    title: 'Operasyon sinyalleri',
    question: 'OperationSignals compact/normal görünür mü?',
    expectedOutcome: 'Signals card visible, not overwhelming.',
    riskLevel: 'medium',
    recommendation: 'Compact modda en fazla 3 sinyal satırı göster.',
  },
  {
    id: 'day2_resources_compact',
    stage: 'day2_reinforcement',
    surface: 'hub',
    title: 'Saha kaynakları',
    question: 'Saha Kaynakları kontrollü açıldı mı?',
    expectedOutcome: 'Resources visible; detail CTA Day 2+.',
    riskLevel: 'medium',
    recommendation: 'Compact özet + isteğe bağlı detay sheet.',
  },
  {
    id: 'day2_advisor_resource_hint',
    stage: 'day2_reinforcement',
    surface: 'hub',
    title: 'Ece kaynak satırı',
    question: 'Ece en fazla tek kısa kaynak/sinyal satırı veriyor mu?',
    expectedOutcome: 'Advisor line optional, short.',
    riskLevel: 'low',
    recommendation: 'İkinci paragraf ekleme.',
  },
  {
    id: 'day2_micro_still_hidden',
    stage: 'day2_reinforcement',
    surface: 'event_field',
    title: 'MicroDecision Day 2',
    question: 'MicroDecision hâlâ görünmüyor mu?',
    expectedOutcome: 'Engine/UI Day 2 inactive.',
    riskLevel: 'high',
    recommendation: 'Day 3’e kadar micro UI kapalı kalsın.',
  },
  {
    id: 'day2_crisis_hidden',
    stage: 'day2_reinforcement',
    surface: 'hub',
    title: 'Kriz Day 2',
    question: 'Kriz Day 2’de yok mu?',
    expectedOutcome: 'Crisis hidden during pilot.',
    riskLevel: 'high',
    recommendation: 'Pilot bitene kadar kriz masasını gizle.',
  },
  {
    id: 'day2_report_cause_effect',
    stage: 'day2_reinforcement',
    surface: 'report',
    title: 'Rapor neden-sonuç',
    question: 'Day 2 raporu biraz daha neden-sonuç anlatıyor mu?',
    expectedOutcome: 'Report lines reference plan/assignment lightly.',
    riskLevel: 'medium',
    manualOnly: true,
    recommendation: 'Oyuncu playtestinde rapor okunurluğunu ölç.',
  },
  // —— Day 3 ——
  {
    id: 'day3_micro_eligible',
    stage: 'day3_system_expansion',
    surface: 'event_field',
    title: 'MicroDecision açılışı',
    question: 'MicroDecision engine Day 3’te eligible ama spam değil mi?',
    expectedOutcome: 'Max 1–2 decisions; not on Day 1–2.',
    riskLevel: 'high',
    recommendation: 'Günlük limit ve duplicate guard koru.',
  },
  {
    id: 'day3_assignment_editor',
    stage: 'day3_system_expansion',
    surface: 'event_dispatch',
    title: 'Atama editörü',
    question: 'Assignment edit akışı anlaşılır mı?',
    expectedOutcome: 'Editor available Day 3+ with contract CTA.',
    riskLevel: 'medium',
    manualOnly: true,
    recommendation: 'Playtest: atama ekranında duraksama süresi ölç.',
  },
  {
    id: 'day3_resource_detail_sheet',
    stage: 'day3_system_expansion',
    surface: 'hub',
    title: 'Kaynak detay sheet',
    question: 'Kaynakları Gör sheet açılabiliyor mu?',
    expectedOutcome: 'Detail sheet model Day 2+; tabs Ekipler/Araçlar/Konteyner.',
    riskLevel: 'medium',
    recommendation: 'Sheet sekmelerini kısa tut.',
  },
  {
    id: 'day3_map_resource_overlay',
    stage: 'day3_system_expansion',
    surface: 'map',
    title: 'Harita kaynak overlay',
    question: 'Harita overlay Day 3+ baskı varsa görünür mü?',
    expectedOutcome: 'Overlay hidden Day 1–2; max 2 panel lines.',
    riskLevel: 'medium',
    recommendation: 'Stable durumda overlay gizle.',
  },
  {
    id: 'day3_hub_density',
    stage: 'day3_system_expansion',
    surface: 'hub',
    title: 'Hub kalabalığı',
    question: 'Hub kart yoğunluğu kontrol altında mı?',
    expectedOutcome: 'maxFeaturedCards ≤ 4 on Day 3.',
    riskLevel: 'high',
    recommendation: 'Featured üst sınırı aşma.',
  },
  // —— Day 7 ——
  {
    id: 'day7_report_completion',
    stage: 'day7_pilot_completion',
    surface: 'report',
    title: 'Pilot completion kartı',
    question: 'Day 7 raporu pilot kapanışını net gösteriyor mu?',
    expectedOutcome: 'Pilot completion card visible; clear CTA.',
    riskLevel: 'critical',
    recommendation: '“Pilot bitti” hissini tek kartta topla.',
  },
  {
    id: 'day7_cta_post_pilot',
    stage: 'day7_pilot_completion',
    surface: 'report',
    title: 'Post-pilot CTA',
    question: 'CTA Ana Operasyon teklifine yönlendiriyor mu?',
    expectedOutcome: 'Ana Operasyona Geç / teklif copy.',
    riskLevel: 'high',
    recommendation: 'CTA hedefini state’e göre tekilleştir.',
  },
  {
    id: 'day7_pilot_finished_feel',
    stage: 'day7_pilot_completion',
    surface: 'report',
    title: 'Pilot bitti hissi',
    question: 'Oyuncu pilotun bittiğini anlıyor mu?',
    expectedOutcome: 'Completion copy + grade/summary.',
    riskLevel: 'high',
    manualOnly: true,
    recommendation: 'Playtest: 5 sn içinde “pilot bitti” diyebiliyor mu?',
  },
  {
    id: 'day7_no_shadow_cards',
    stage: 'day7_pilot_completion',
    surface: 'report',
    title: 'Kart hiyerarşisi',
    question: 'Yetki/rozet pilot completion’ı gölgelemiyor mu?',
    expectedOutcome: 'Completion hero öncelikli.',
    riskLevel: 'medium',
    manualOnly: true,
    recommendation: 'Meta kartları completion altına al.',
  },
  {
    id: 'day7_forbidden_words',
    stage: 'day7_pilot_completion',
    surface: 'post_pilot_offer',
    title: 'Yasaklı kelimeler',
    question: 'Pilot completion copy yasaklı kelime içermiyor mu?',
    expectedOutcome: 'No XP/premium/satın al/kilitli.',
    riskLevel: 'critical',
    recommendation: 'Monetization copy denetimini sürdür.',
  },
  // —— Post-pilot offer ——
  {
    id: 'offer_full_value_prop',
    stage: 'post_pilot_offer',
    surface: 'post_pilot_offer',
    title: 'Full değer önerisi',
    question: 'Full erişim faydaları net mi?',
    expectedOutcome: 'Mahalle, sezon, kriz, kaynak, canlı karar, rapor listelenir.',
    riskLevel: 'high',
    manualOnly: true,
    recommendation: 'Playtest: full vs limited farkını söylet.',
  },
  {
    id: 'offer_limited_clear',
    stage: 'post_pilot_offer',
    surface: 'post_pilot_offer',
    title: 'Limited continue',
    question: 'Sınırlı gündem net mi?',
    expectedOutcome: 'Limited CTA + scope açıklaması.',
    riskLevel: 'high',
    recommendation: '“Sınırlı gündem” dilini koru.',
  },
  {
    id: 'offer_no_dev_copy',
    stage: 'post_pilot_offer',
    surface: 'post_pilot_offer',
    title: 'Mock purchase gizli',
    question: 'Dev/test dili oyuncu UI’ında yok mu?',
    expectedOutcome: 'Mock unlock sadece dev guard altında.',
    riskLevel: 'critical',
    recommendation: 'Production build’de dev CTA gizle.',
  },
  {
    id: 'offer_contract_ctas',
    stage: 'post_pilot_offer',
    surface: 'post_pilot_offer',
    title: 'Offer CTA sözleşmesi',
    question: 'CTA’lar interaction contract ile uyumlu mu?',
    expectedOutcome: 'PostPilotAccessChoiceCard contracts registered.',
    riskLevel: 'high',
    recommendation: 'Registry’de primary/secondary CTA doğrula.',
  },
  // —— Day 8 limited ——
  {
    id: 'limited_main_op_light',
    stage: 'day8_limited',
    surface: 'hub',
    title: 'main_operation_light',
    question: 'Limited oyuncu main_operation_light modunda mı?',
    expectedOutcome: 'Limited access; light season scope.',
    riskLevel: 'high',
    recommendation: 'Full season goals görünmesin.',
  },
  {
    id: 'limited_crisis_actions_hidden',
    stage: 'day8_limited',
    surface: 'hub',
    title: 'Limited kriz hamlesi',
    question: 'Kriz aksiyonları limited’da görünmüyor mu?',
    expectedOutcome: 'Crisis actions inactive in limited.',
    riskLevel: 'high',
    recommendation: 'Limited preview cap koru.',
  },
  {
    id: 'limited_map_overlay_cap',
    stage: 'day8_limited',
    surface: 'map',
    title: 'Limited harita cap',
    question: 'Harita overlay limited cap’e uyuyor mu?',
    expectedOutcome: 'Max 1 resource/crisis line.',
    riskLevel: 'medium',
    recommendation: 'Panel satır sayısını 1 ile sınırla.',
  },
  {
    id: 'limited_report_copy',
    stage: 'day8_limited',
    surface: 'report',
    title: 'Limited rapor',
    question: 'Rapor limited copy kullanıyor mu?',
    expectedOutcome: 'Limited context lines in report.',
    riskLevel: 'medium',
    manualOnly: true,
    recommendation: 'Playtest: limited oyuncu kapsamı anlıyor mu?',
  },
  // —— Day 8 full ——
  {
    id: 'full_season_card',
    stage: 'day8_full',
    surface: 'hub',
    title: 'Sezon kartı',
    question: 'HubMainOperationSeasonCard görünür mü?',
    expectedOutcome: 'Season card visible with full access.',
    riskLevel: 'high',
    recommendation: 'Sezon hedeflerini featured yap.',
  },
  {
    id: 'full_resources_visible',
    stage: 'day8_full',
    surface: 'hub',
    title: 'Saha kaynakları full',
    question: 'Saha Kaynakları full modda görünür mü?',
    expectedOutcome: 'Resources card + detail CTA.',
    riskLevel: 'medium',
    recommendation: 'Max 3 özet satır koru.',
  },
  {
    id: 'full_crisis_desk_context',
    stage: 'day8_full',
    surface: 'hub',
    title: 'Kriz masası',
    question: 'Crisis Desk uygun context’te görünür mü?',
    expectedOutcome: 'Crisis desk when elevated + full access.',
    riskLevel: 'high',
    recommendation: 'Kriz spam’ini max 2 satırla sınırla.',
  },
  {
    id: 'full_event_density',
    stage: 'day8_full',
    surface: 'hub',
    title: 'Olay yoğunluğu',
    question: 'Full event density limited’dan farklı mı?',
    expectedOutcome: 'Full max 3 events/day vs limited 2.',
    riskLevel: 'medium',
    recommendation: 'Density cap engine’de kalsın.',
  },
  {
    id: 'full_map_scopes',
    stage: 'day8_full',
    surface: 'map',
    title: 'Harita mahalleleri',
    question: 'Harita active/agenda/preview mahalleleri gösteriyor mu?',
    expectedOutcome: 'Strip badges for main operation scopes.',
    riskLevel: 'medium',
    manualOnly: true,
    recommendation: 'Playtest: haritada 5 sn ana aksiyon bulma.',
  },
  {
    id: 'full_report_context',
    stage: 'day8_full',
    surface: 'report',
    title: 'Full rapor',
    question: 'Rapor Ana Operasyon bağlamı veriyor mu?',
    expectedOutcome: 'Main operation lines in EOD report.',
    riskLevel: 'high',
    recommendation: 'Raporu 3 ana mesajla sınırla.',
  },
  // —— Full crisis ——
  {
    id: 'crisis_desk_risk',
    stage: 'full_main_crisis',
    surface: 'hub',
    title: 'Kriz masası risk',
    question: 'HubCrisisDeskCard risk gösteriyor mu?',
    expectedOutcome: 'Desk visible when crisis elevated.',
    riskLevel: 'high',
    recommendation: 'Risk tonunu soft amber tut.',
  },
  {
    id: 'crisis_action_sheet',
    stage: 'full_main_crisis',
    surface: 'hub',
    title: 'Kriz hamlesi sheet',
    question: 'CrisisActionSheet 5 hamle gösteriyor mu?',
    expectedOutcome: 'Five resolution options with contracts.',
    riskLevel: 'critical',
    recommendation: 'Sheet scroll + kısa trade-off satırları.',
  },
  {
    id: 'crisis_advisor_short',
    stage: 'full_main_crisis',
    surface: 'hub',
    title: 'Ece kriz önerisi',
    question: 'Ece kısa kriz önerisi veriyor mu?',
    expectedOutcome: 'One-line advisor crisis hint.',
    riskLevel: 'medium',
    recommendation: 'Uzun paragraf yazma.',
  },
  {
    id: 'crisis_report_reflection',
    stage: 'full_main_crisis',
    surface: 'report',
    title: 'Kriz raporu',
    question: 'Seçilen hamle rapora yansıyor mu?',
    expectedOutcome: 'Crisis action line in report max 3.',
    riskLevel: 'high',
    recommendation: 'Hamle sonucunu tek satırda özetle.',
  },
  {
    id: 'crisis_map_priority',
    stage: 'full_main_crisis',
    surface: 'map',
    title: 'Harita önceliği',
    question: 'Kriz overlay kaynak overlay’den öncelikli mi?',
    expectedOutcome: 'Crisis panel/strip beats resource.',
    riskLevel: 'critical',
    recommendation: 'mergeMapPanelCrisisAndResourceLines max 2 kuralı.',
  },
  {
    id: 'crisis_no_spam',
    stage: 'full_main_crisis',
    surface: 'hub',
    title: 'Kriz spam',
    question: 'Kriz sistemi spam yapmıyor mu?',
    expectedOutcome: 'One generation per day; idempotent EOD.',
    riskLevel: 'high',
    recommendation: 'Günde tek kriz hamlesi seti.',
  },
  // —— Full resources ——
  {
    id: 'resources_hub_max_rows',
    stage: 'full_main_resources',
    surface: 'hub',
    title: 'Kaynak özet',
    question: 'HubOperationalResourcesCard max 3 satır mı?',
    expectedOutcome: '≤ 3 summary rows.',
    riskLevel: 'medium',
    recommendation: 'Detayı sheet’e taşı.',
  },
  {
    id: 'resources_detail_cta',
    stage: 'full_main_resources',
    surface: 'hub',
    title: 'Kaynakları Gör',
    question: 'CTA bottom sheet açıyor mu?',
    expectedOutcome: 'Modal contract operational_resources_detail_sheet.',
    riskLevel: 'high',
    recommendation: 'Boş onPress bırakma.',
  },
  {
    id: 'resources_sheet_tabs',
    stage: 'full_main_resources',
    surface: 'hub',
    title: 'Sheet sekmeleri',
    question: 'Sheet sekmeleri Ekipler/Araçlar/Konteyner net mi?',
    expectedOutcome: '3 tabs with metrics + recommendation.',
    riskLevel: 'medium',
    recommendation: 'Sekme başına max 5 satır.',
  },
  {
    id: 'resources_map_overlay',
    stage: 'full_main_resources',
    surface: 'map',
    title: 'Harita kaynak',
    question: 'Harita overlay full context’te anlamlı mı?',
    expectedOutcome: 'Day 3+ strained; crisis wins strip.',
    riskLevel: 'medium',
    recommendation: 'Stable’da overlay gizle.',
  },
  {
    id: 'resources_day1_safe',
    stage: 'full_main_resources',
    surface: 'hub',
    title: 'Day 1 sade akış',
    question: 'Day 1 kaynak detayı gizli mi?',
    expectedOutcome: 'Detail sheet null Day 1.',
    riskLevel: 'critical',
    recommendation: 'First 10 minutes guard koru.',
  },
  {
    id: 'resources_report_lines',
    stage: 'full_main_resources',
    surface: 'report',
    title: 'Rapor kaynak satırları',
    question: 'Rapor kaynak satırları kısa mı?',
    expectedOutcome: 'Max 3 lines; stable compact line.',
    riskLevel: 'medium',
    recommendation: '“Saha kaynakları dengeli kaldı.” tek satır.',
  },
  // —— Full report ——
  {
    id: 'report_max_messages',
    stage: 'full_main_report',
    surface: 'report',
    title: 'Rapor mesaj sayısı',
    question: 'Rapor en fazla 3 ana mesaj veriyor mu?',
    expectedOutcome: 'Primary impact + trade-off + tomorrow focus.',
    riskLevel: 'high',
    recommendation: 'Kart hiyerarşisini 3 ile sınırla.',
  },
  {
    id: 'report_advisor_short',
    stage: 'full_main_report',
    surface: 'report',
    title: 'Danışman yorumu',
    question: 'Advisor comment kısa mı?',
    expectedOutcome: 'Short advisor block in report.',
    riskLevel: 'medium',
    recommendation: 'Uzun danışman paragrafı ekleme.',
  },
  {
    id: 'report_systems_consistent',
    stage: 'full_main_report',
    surface: 'report',
    title: 'Sistem tutarlılığı',
    question: 'Crisis/resources/micro/assignment/plan çelişmiyor mu?',
    expectedOutcome: 'No contradictory tones in same report.',
    riskLevel: 'critical',
    recommendation: 'Presentation helper’ları aynı state’ten besle.',
  },
  {
    id: 'report_cta_clear',
    stage: 'full_main_report',
    surface: 'report',
    title: 'Rapor CTA',
    question: 'Rapor CTA net mi?',
    expectedOutcome: 'Single primary next-day/hub CTA.',
    riskLevel: 'medium',
    recommendation: 'Çoklu eşit CTA’dan kaçın.',
  },
  {
    id: 'report_readability',
    stage: 'full_main_report',
    surface: 'report',
    title: 'Okunabilirlik',
    question: 'Rapor karar hikayesi gibi okunuyor mu?',
    expectedOutcome: 'Cause-effect narrative, not system list.',
    riskLevel: 'high',
    manualOnly: true,
    recommendation: 'Playtest: rapor okuma / atlama oranı ölç.',
  },
  // —— Cross-cutting automated ——
  {
    id: 'cross_interaction_contracts',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Interaction contracts',
    question: 'Fake CTA audit FAIL üretiyor mu?',
    expectedOutcome: 'Interaction audit health not FAIL.',
    riskLevel: 'critical',
    recommendation: 'Registry’de boş onPress bırakma.',
  },
  {
    id: 'cross_day_pipeline',
    stage: 'full_main_report',
    surface: 'report',
    title: 'Day pipeline',
    question: 'Day pipeline audit FAIL üretiyor mu?',
    expectedOutcome: 'Pipeline audit PASS or WARN only.',
    riskLevel: 'critical',
    recommendation: 'EOD step sırasını bozma.',
  },
  {
    id: 'cross_forbidden_words',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Yasaklı kelimeler global',
    question: 'Audit metinlerinde yasaklı kelime var mı?',
    expectedOutcome: 'No XP/premium/satın al/kilitli in flow copy samples.',
    riskLevel: 'critical',
    recommendation: 'Copy review checklist kullan.',
  },
  {
    id: 'cross_human_playtest',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'İnsan playtest',
    question: 'Gerçek cihaz playtest yapıldı mı?',
    expectedOutcome: 'Manual checklist completed on device.',
    riskLevel: 'medium',
    manualOnly: true,
    recommendation: 'docs/crevia-player-flow-playtest-checklist.md ile ölç.',
  },
  {
    id: 'cross_analytics_pending',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Analytics',
    question: 'Oturum analytics entegre mi?',
    expectedOutcome: 'Analytics integration optional.',
    riskLevel: 'low',
    manualOnly: true,
    recommendation: 'Analytics integration pending — WARN beklenir.',
  },
  {
    id: 'cross_recording_pending',
    stage: 'day1_first_session',
    surface: 'hub',
    title: 'Kayıt',
    question: 'Video/session recording var mı?',
    expectedOutcome: 'Recording not implemented.',
    riskLevel: 'low',
    manualOnly: true,
    recommendation: 'Video/session recording not implemented — WARN.',
  },
];

export const PLAYER_FLOW_MANUAL_CHECKLIST_ITEMS: PlayerFlowManualChecklistItem[] = [
  {
    id: 'manual_day1_cta_time',
    stage: 'day1_first_session',
    surface: 'hub',
    prompt: 'Ana CTA’yı kaç saniyede buldun?',
    expectedPlayerReaction: '5 sn içinde Planı Onayla veya operasyon CTA’sına basar.',
    passCriteria: '≤ 8 sn, doğru kart',
    failSignal: '10+ sn arama, yanlış karta basma',
  },
  {
    id: 'manual_day1_ece_read',
    stage: 'day1_first_session',
    surface: 'hub',
    prompt: 'Ece metnini okudun mu, geçtin mi?',
    expectedPlayerReaction: 'Kısa metni okur veya görmezden gelir ama akışı bozmaz.',
    passCriteria: 'Metin 2 cümleyi geçmiyor hissi',
    failSignal: '“Çok uzun” geri bildirimi',
  },
  {
    id: 'manual_day1_plan_why',
    stage: 'day1_first_session',
    surface: 'hub',
    prompt: 'Planı neden onayladığını tek cümleyle söyle.',
    expectedPlayerReaction: '“Önerilen plan” / “ilk gün” mantığı.',
    passCriteria: 'Önerilen plan kavramı anlaşıldı',
    failSignal: 'Rastgele onay',
  },
  {
    id: 'manual_day1_assignment_pause',
    stage: 'day1_first_session',
    surface: 'event_dispatch',
    prompt: 'Atama ekranında duraksadın mı?',
    expectedPlayerReaction: 'Önerilen atamayı hızlı onaylar.',
    passCriteria: '≤ 30 sn atama tamamlanır',
    failSignal: 'Editör arar, kaybolur',
  },
  {
    id: 'manual_day1_report_read',
    stage: 'day1_first_session',
    surface: 'report',
    prompt: 'Raporu okudun mu, geçtin mi?',
    expectedPlayerReaction: 'Kısa raporu okur veya CTA ile döner.',
    passCriteria: 'Eğitim satırı fark edildi',
    failSignal: 'Raporu tamamen atlar ve şaşırır',
  },
  {
    id: 'manual_day2_resource_notice',
    stage: 'day2_reinforcement',
    surface: 'hub',
    prompt: 'Saha Kaynakları kartını fark ettin mi?',
    expectedPlayerReaction: 'Compact kartı görür, detay isteğe bağlı.',
    passCriteria: 'Kart varlığı fark edildi',
    failSignal: 'Hiç fark etmedi / korktu',
  },
  {
    id: 'manual_day3_micro_understand',
    stage: 'day3_system_expansion',
    surface: 'event_field',
    prompt: 'Canlı operasyon kararı ne işe yaradığını anladın mı?',
    expectedPlayerReaction: 'Trade-off’u kısaca anlar.',
    passCriteria: 'Seçim gerekçesi söylenebilir',
    failSignal: 'Spam / anlamsız',
  },
  {
    id: 'manual_day3_map_resource',
    stage: 'day3_system_expansion',
    surface: 'map',
    prompt: 'Haritada kaynak baskısını ayırt ettin mi?',
    expectedPlayerReaction: 'Mahalle badge veya panel satırı fark edilir.',
    passCriteria: 'Baskı mahallesi söylenebilir',
    failSignal: 'Harita gürültülü',
  },
  {
    id: 'manual_day7_pilot_done',
    stage: 'day7_pilot_completion',
    surface: 'report',
    prompt: 'Pilot bittiğini nasıl anladın?',
    expectedPlayerReaction: 'Completion kartı / Ana Operasyon CTA.',
    passCriteria: '“Pilot bitti” ifadesi',
    failSignal: 'Belirsiz geçiş',
  },
  {
    id: 'manual_day7_offer_diff',
    stage: 'post_pilot_offer',
    surface: 'post_pilot_offer',
    prompt: 'Full ve sınırlı farkını söyle.',
    expectedPlayerReaction: 'Kapsam, kriz, sezon, kaynak farkı.',
    passCriteria: 'En az 2 fark maddesi',
    failSignal: 'Farkı bilemez',
  },
  {
    id: 'manual_day8_limited_scope',
    stage: 'day8_limited',
    surface: 'hub',
    prompt: 'Sınırlı gündemde neyin kapalı olduğunu söyle.',
    expectedPlayerReaction: 'Kriz hamlesi / tam sezon kapalı.',
    passCriteria: 'Kapsam dar hissi',
    failSignal: 'Full sanır',
  },
  {
    id: 'manual_day8_full_scope',
    stage: 'day8_full',
    surface: 'hub',
    prompt: 'Ana Operasyon’da neyin açıldığını söyle.',
    expectedPlayerReaction: 'Sezon, kriz, kaynak, geniş harita.',
    passCriteria: '≥ 2 yeni sistem',
    failSignal: 'Limited ile aynı sanır',
  },
  {
    id: 'manual_crisis_choice',
    stage: 'full_main_crisis',
    surface: 'hub',
    prompt: 'Kriz hamlesinde hangi seçeneği neden seçtin?',
    expectedPlayerReaction: 'Trade-off ile gerekçe.',
    passCriteria: 'Seçim gerekçesi net',
    failSignal: 'Rastgele seçim',
  },
  {
    id: 'manual_resources_sheet',
    stage: 'full_main_resources',
    surface: 'hub',
    prompt: 'Kaynakları Gör sheet’te hangi sekme işine yaradı?',
    expectedPlayerReaction: 'Ekip/filo/konteyner ihtiyacı.',
    passCriteria: 'Sekme amacı anlaşıldı',
    failSignal: 'Sheet kapatıldı, okunmadı',
  },
  {
    id: 'manual_map_crisis_vs_resource',
    stage: 'full_main_crisis',
    surface: 'map',
    prompt: 'Haritada kriz ve kaynak farkını ayırt et.',
    expectedPlayerReaction: 'Kriz amber, kaynak mint; kriz öncelikli.',
    passCriteria: 'Doğru öncelik',
    failSignal: 'Karıştırır',
  },
  {
    id: 'manual_report_story',
    stage: 'full_main_report',
    surface: 'report',
    prompt: 'Bugünkü ana etkiyi tek cümleyle özetle.',
    expectedPlayerReaction: 'Plan/atama/kriz sonucu hikayesi.',
    passCriteria: 'Neden-sonuç cümlesi',
    failSignal: 'Sistem listesi okur',
  },
  {
    id: 'manual_hub_5sec',
    stage: 'day1_first_session',
    surface: 'hub',
    prompt: '5 saniyede nereye basacağını söyle (karışıklık testi).',
    expectedPlayerReaction: 'Plan veya operasyon CTA.',
    passCriteria: 'Doğru hedef ≤ 5 sn',
    failSignal: 'Scroll / kaybolma',
  },
  {
    id: 'manual_strategist_tradeoff',
    stage: 'full_main_report',
    surface: 'report',
    prompt: 'Bugünkü trade-off’u okudun mu?',
    expectedPlayerReaction: 'Strateji oyuncusu satırları okur.',
    passCriteria: 'Trade-off fark edildi',
    failSignal: '“Etki yok” hissi',
  },
  {
    id: 'manual_fast_mobile_cta',
    stage: 'day2_reinforcement',
    surface: 'hub',
    prompt: 'Hızlı geçerken CTA etiketleri net mi?',
    expectedPlayerReaction: 'Tek kelimelik net CTA.',
    passCriteria: 'Yanlış tap yok',
    failSignal: 'Yanlış ekran',
  },
  {
    id: 'manual_new_player_10min',
    stage: 'day1_first_session',
    surface: 'hub',
    prompt: 'İlk 10 dakikada ne yapacağını baştan sona anlat.',
    expectedPlayerReaction: 'Plan → olay → atama → sonuç → rapor.',
    passCriteria: 'Akış sırası doğru',
    failSignal: 'Adım eksik / karışık',
  },
  {
    id: 'manual_offer_mock_hidden',
    stage: 'post_pilot_offer',
    surface: 'post_pilot_offer',
    prompt: 'Ekranda “mock” veya “dev” yazısı gördün mü?',
    expectedPlayerReaction: 'Hayır.',
    passCriteria: 'Oyuncu dili temiz',
    failSignal: 'Teknik kelime görüldü',
  },
  {
    id: 'manual_limited_map_line',
    stage: 'day8_limited',
    surface: 'map',
    prompt: 'Sınırlı haritada kaç uyarı satırı var?',
    expectedPlayerReaction: 'En fazla 1 kompakt satır.',
    passCriteria: '≤ 1 satır',
    failSignal: 'Panel taşması',
  },
  {
    id: 'manual_full_hub_density',
    stage: 'day8_full',
    surface: 'hub',
    prompt: 'Hub seni boğdu mu?',
    expectedPlayerReaction: 'Yoğun ama hiyerarşik.',
    passCriteria: 'Featured kartlar öncelikli',
    failSignal: '“Çok kart” şikayeti',
  },
  {
    id: 'manual_crisis_sheet_5',
    stage: 'full_main_crisis',
    surface: 'hub',
    prompt: 'Kriz sheet’te kaç hamle saydın?',
    expectedPlayerReaction: '5 seçenek.',
    passCriteria: '5 hamle',
    failSignal: 'Eksik/fazla',
  },
  {
    id: 'manual_resources_tabs',
    stage: 'full_main_resources',
    surface: 'hub',
    prompt: 'Kaynak sheet sekmelerini gez; hangisi en kritik?',
    expectedPlayerReaction: 'Baskılı sekme seçilir.',
    passCriteria: 'Sekmeler ayırt edilir',
    failSignal: 'Hepsi aynı görünür',
  },
  {
    id: 'manual_report_tomorrow',
    stage: 'full_main_report',
    surface: 'report',
    prompt: 'Yarınki odak satırını bul.',
    expectedPlayerReaction: 'Tomorrow/risk line.',
    passCriteria: 'Odak bulundu',
    failSignal: 'Yarın belirsiz',
  },
  {
    id: 'manual_social_day1_hidden',
    stage: 'day1_first_session',
    surface: 'social',
    prompt: 'Day 1 sosyal derinlemesine girdin mi?',
    expectedPlayerReaction: 'Hayır veya yüzeysel.',
    passCriteria: 'Deep dive yok',
    failSignal: 'Sosyal’de kayboldu',
  },
  {
    id: 'manual_profile_day1_low',
    stage: 'day1_first_session',
    surface: 'profile',
    prompt: 'Profilde prestij/rozet seni çekti mi?',
    expectedPlayerReaction: 'Düşük profil.',
    passCriteria: 'Ana akışa dönüş',
    failSignal: 'Profilde takılı kaldı',
  },
  {
    id: 'manual_day3_assignment_edit',
    stage: 'day3_system_expansion',
    surface: 'event_dispatch',
    prompt: 'Atama editörünü açtın mı, önerilenle yetindin mi?',
    expectedPlayerReaction: 'İsteğe bağlı edit.',
    passCriteria: 'Edit bulunabilir',
    failSignal: 'Edit bulunamadı',
  },
  {
    id: 'manual_observation_notes',
    stage: 'day1_first_session',
    surface: 'hub',
    prompt: 'Gözlem notlarını doldur (süre, duraksama, alıntı).',
    expectedPlayerReaction: 'Testör formu doldurur.',
    passCriteria: 'Form tamam',
    failSignal: 'Boş form',
  },
];

export const PLAYER_FLOW_DOCS_PATH = 'docs/crevia-player-flow-playtest-checklist.md';
