import type {
  CreviaRealDevicePlaytestArea,
  CreviaRealDevicePlaytestRisk,
} from './playtestTypes';

export const REAL_DEVICE_PLAYTEST_DOCS_PATH = 'docs/crevia-real-device-playtest-round-1.md';

/** Round 1 QA evidence template — iOS/Android checklist + attach format. */
export const REAL_DEVICE_QA_EVIDENCE_DOCS_PATH = 'docs/crevia-real-device-qa-evidence-round-1.md';

export const REAL_DEVICE_PLAYTEST_MIN_AREAS = 12;
export const REAL_DEVICE_PLAYTEST_MIN_SCENARIOS = 16;

export const REAL_DEVICE_PLAYTEST_AREA_LABELS: Record<CreviaRealDevicePlaytestArea, string> = {
  install_launch: 'A. Install / Launch / Fresh Start',
  first_ten_minutes: 'B. First 10 Minutes',
  event_flow: 'C. Event Flow',
  assignment_route: 'D. Assignment / Active Route',
  map: 'E. Map',
  result_screen: 'F. Result Screen',
  end_of_day_report: 'G. End-of-Day Report',
  hub_day2_plus: 'H. Hub Day 2+',
  day7_post_pilot_offer: 'I. Day 7 Completion / Post-Pilot Offer',
  day8_open_ended: 'J. Day 8+ Open-Ended Operation',
  profile_career: 'K. Profile / Career / Authority',
  performance_device_ux: 'L. Performance / Device UX',
};

export const REAL_DEVICE_PLAYTEST_BLOCKER_CATEGORIES = [
  'crash',
  'save_corrupt',
  'purchase_flow_crash',
  'main_event_flow_stuck',
  'day7_day8_transition_broken',
  'forbidden_end_game_copy',
  'false_gps_tracking_claim',
  'iap_wrong_unlock_state',
] as const;

export const REAL_DEVICE_PLAYTEST_RISK_TAXONOMY: readonly CreviaRealDevicePlaytestRisk[] = [
  {
    id: 'risk.crash',
    category: 'crash',
    severity: 'blocker',
    title: 'Crash or hard freeze',
    description: 'App crashes, ANR, or becomes unresponsive during core flow.',
    examples: ['Launch crash', 'Event result crash', 'Map open crash'],
  },
  {
    id: 'risk.save_corrupt',
    category: 'save_corrupt',
    severity: 'blocker',
    title: 'Save corruption or state loss',
    description: 'Progress lost, invalid state, or migration failure after restart.',
    examples: ['Day reset after relaunch', 'Monetization state wrong'],
  },
  {
    id: 'risk.purchase_flow_crash',
    category: 'purchase_flow_crash',
    severity: 'blocker',
    title: 'IAP offer screen crash',
    description: 'Post-pilot offer crashes; real purchase smoke is separate phase.',
    examples: ['Offer screen white screen', 'Restore tap crash'],
  },
  {
    id: 'risk.main_event_flow_stuck',
    category: 'main_event_flow_stuck',
    severity: 'blocker',
    title: 'Main event flow stuck',
    description: 'Player cannot complete Inspect→Plan→Dispatch→Field→Result.',
    examples: ['CTA dead', 'Cannot advance phase', 'Back stack trap'],
  },
  {
    id: 'risk.day7_day8_transition',
    category: 'day7_day8_transition_broken',
    severity: 'blocker',
    title: 'Day 7 → Day 8 transition broken',
    description: 'Pilot completion or post-pilot routing fails.',
    examples: ['Stuck after Day 7 report', 'Offer never appears'],
  },
  {
    id: 'risk.forbidden_copy',
    category: 'forbidden_end_game_copy',
    severity: 'blocker',
    title: 'Forbidden end-game language',
    description: 'Player-facing oyun sonu / sezon finali / 14 gün bitti copy.',
    examples: ['Hub says sezon finali', 'Report implies game over'],
  },
  {
    id: 'risk.false_gps',
    category: 'false_gps_tracking_claim',
    severity: 'blocker',
    title: 'False GPS / live tracking claim',
    description: 'Copy implies real GPS navigation or pathfinding.',
    examples: ['Canlı GPS takibi', 'Harita navigasyonu'],
  },
  {
    id: 'risk.iap_unlock',
    category: 'iap_wrong_unlock_state',
    severity: 'blocker',
    title: 'Wrong IAP unlock state',
    description: 'Limited/full access inconsistent with purchase or mock path.',
    examples: ['Full without unlock', 'Limited after mock purchase'],
  },
  {
    id: 'risk.cta_unclear',
    category: 'cta_unclear',
    severity: 'high',
    title: 'Primary CTA unclear',
    description: 'Player does not know next action.',
    examples: ['Hub CTA ambiguous', 'Report CTA hidden'],
  },
  {
    id: 'risk.density_unreadable',
    category: 'density_unreadable',
    severity: 'high',
    title: 'Hub/map/report unreadable density',
    description: 'Too many cards or lines on small screen.',
    examples: ['Hub scroll fatigue', 'Map panel overflow'],
  },
  {
    id: 'risk.assignment_confusion',
    category: 'assignment_confusion',
    severity: 'high',
    title: 'Assignment flow confusing',
    description: 'Team/vehicle/approach selection unclear.',
    examples: ['Route preview misleading', 'Stepper confusing'],
  },
  {
    id: 'risk.result_impact_unclear',
    category: 'result_impact_unclear',
    severity: 'high',
    title: 'Result impact unclear',
    description: 'Decision impact on city not felt.',
    examples: ['Systems echo ignored', 'Metrics meaningless'],
  },
  {
    id: 'risk.large_text_overflow',
    category: 'large_text_overflow',
    severity: 'high',
    title: 'Large text / accessibility overflow',
    description: 'Dynamic type or long copy breaks layout.',
    examples: ['CTA clipped', 'Report title truncated badly'],
  },
  {
    id: 'risk.excess_copy',
    category: 'excess_copy',
    severity: 'medium',
    title: 'Excess copy in cards',
    description: 'Some cards too wordy but still readable.',
    examples: ['Report systems card long', 'Advisor repeats hub'],
  },
  {
    id: 'risk.duplicate_echo',
    category: 'duplicate_echo',
    severity: 'medium',
    title: 'Duplicate echo across surfaces',
    description: 'Same hint on hub, result, and report.',
    examples: ['Carry-over triple echo', 'Route line repeated'],
  },
  {
    id: 'risk.minor_overflow',
    category: 'minor_overflow',
    severity: 'medium',
    title: 'Minor layout overflow',
    description: 'Small clip or awkward wrap on one device.',
    examples: ['Chip wraps awkwardly', 'Icon misaligned'],
  },
  {
    id: 'risk.weak_tone',
    category: 'weak_tone',
    severity: 'medium',
    title: 'Weak icon or tone',
    description: 'Tone/icon does not match operational calm.',
    examples: ['Alarmist chip color', 'Unclear icon'],
  },
  {
    id: 'risk.microcopy',
    category: 'microcopy',
    severity: 'low',
    title: 'Microcopy polish',
    description: 'Wording could be clearer but not blocking.',
    examples: ['Button label tweak', 'Helper text shorten'],
  },
  {
    id: 'risk.spacing',
    category: 'spacing',
    severity: 'polish',
    title: 'Spacing polish',
    description: 'Padding/margin refinement only.',
    examples: ['Card gap', 'Section rhythm'],
  },
  {
    id: 'risk.animation',
    category: 'animation',
    severity: 'polish',
    title: 'Animation polish',
    description: 'Transition timing or easing tweak.',
    examples: ['Sheet enter', 'Chip fade'],
  },
];
