import type {
  ManualLaunchBlocker,
  ManualLaunchBlockerGroupId,
  ManualLaunchDeviceTestCase,
  ManualLaunchEvidenceRecord,
} from './manualLaunchTrackerTypes';

export const MANUAL_LAUNCH_TRACKER_DOCS_PATH = 'docs/crevia-manual-launch-blocker-tracker.md';

export const MANUAL_LAUNCH_RELEASE_CANDIDATE_AUDIT_PATH = 'docs/crevia-release-candidate-audit.md';

export const MANUAL_LAUNCH_TRACKER_EXPECTED_SAVE_VERSION = 26;

export const MANUAL_LAUNCH_TRACKER_MIN_BLOCKER_COUNT = 30;

export const MANUAL_LAUNCH_BLOCKER_GROUP_LABELS: Record<ManualLaunchBlockerGroupId, string> = {
  iap_revenuecat: 'A. IAP / RevenueCat',
  store_metadata_screenshots: 'B. Store metadata / screenshots',
  privacy_data_safety: 'C. Privacy / data safety',
  crash_sentry: 'D. Crash / Sentry',
  analytics_dashboard: 'E. Analytics dashboard',
  device_test: 'F. Internal device test',
  performance_device_smoke: 'G. Performance device smoke',
};

export const MANUAL_LAUNCH_BLOCKER_GROUP_IDS: readonly ManualLaunchBlockerGroupId[] = [
  'iap_revenuecat',
  'store_metadata_screenshots',
  'privacy_data_safety',
  'crash_sentry',
  'analytics_dashboard',
  'device_test',
  'performance_device_smoke',
] as const;

function blocker(partial: ManualLaunchBlocker): ManualLaunchBlocker {
  return partial;
}

/** Static registry — statuses updated at audit time only for factual code/docs signals. */
export const MANUAL_LAUNCH_BLOCKERS: readonly ManualLaunchBlocker[] = [
  // A. IAP / RevenueCat
  blocker({
    id: 'revenuecat_public_keys',
    title: 'RevenueCat public keys',
    category: 'iap',
    status: 'pending',
    owner: 'dashboard',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'EAS secrets + verify:iap-manual-setup-tracker',
    evidenceRequired: ['store_console', 'manual_note'],
    nextAction: 'Set EXPO_PUBLIC_REVENUECAT_IOS/ANDROID in EAS secrets.',
    relatedVerifyCommand: 'npm run verify:iap-manual-setup-tracker',
    docsLinkLabel: 'docs/crevia-revenuecat-store-manual-setup-tracker.md',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'revenuecat_entitlement_config',
    title: 'RevenueCat entitlement config',
    category: 'iap',
    status: 'pending',
    owner: 'dashboard',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'RevenueCat dashboard entitlement matches code',
    evidenceRequired: ['store_console', 'screenshot'],
    nextAction: 'Create entitlement matching MAIN_OPERATION_ENTITLEMENT_ID.',
    relatedVerifyCommand: 'npm run verify:iap-manual-setup-tracker',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'revenuecat_offering_config',
    title: 'RevenueCat offering config',
    category: 'iap',
    status: 'pending',
    owner: 'dashboard',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Offering + package product wired in RevenueCat',
    evidenceRequired: ['store_console', 'screenshot'],
    nextAction: 'Configure default offering and package product.',
    relatedVerifyCommand: 'npm run verify:iap-manual-setup-tracker',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'app_store_product_created',
    title: 'App Store product created',
    category: 'iap',
    status: 'pending',
    owner: 'store_console',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'App Store Connect IAP product exists',
    evidenceRequired: ['store_console', 'screenshot'],
    nextAction: 'Create IAP product in App Store Connect.',
    relatedVerifyCommand: 'npm run verify:iap-manual-setup-tracker',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'play_console_product_created',
    title: 'Play Console product created',
    category: 'iap',
    status: 'pending',
    owner: 'store_console',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Play Console in-app product exists',
    evidenceRequired: ['store_console', 'screenshot'],
    nextAction: 'Create in-app product in Play Console.',
    relatedVerifyCommand: 'npm run verify:iap-manual-setup-tracker',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'iap_sandbox_purchase_test',
    title: 'IAP sandbox purchase test',
    category: 'iap',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    verificationMethod: 'Sandbox purchase on internal EAS build',
    evidenceRequired: ['purchase_log', 'screenshot'],
    nextAction: 'Run sandbox purchase matrix on device.',
    relatedVerifyCommand: 'npm run verify:iap-sandbox-smoke-execution',
    docsLinkLabel: 'docs/crevia-iap-sandbox-smoke-test.md',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'iap_restore_test',
    title: 'IAP restore test',
    category: 'iap',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    verificationMethod: 'Restore purchases flow on device',
    evidenceRequired: ['purchase_log', 'manual_note'],
    nextAction: 'Verify restore CTA after reinstall or second device.',
    relatedVerifyCommand: 'npm run verify:iap-sandbox-smoke-execution',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'product_price_finalized',
    title: 'Product price finalized',
    category: 'iap',
    status: 'pending',
    owner: 'store_console',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Store pricing entered and reviewed',
    evidenceRequired: ['store_console', 'screenshot'],
    nextAction: 'Finalize localized pricing in both stores.',
    relatedVerifyCommand: 'npm run verify:iap-product-design',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  // B. Store metadata / screenshots
  blocker({
    id: 'app_store_metadata_entered',
    title: 'App Store metadata entered',
    category: 'metadata',
    status: 'pending',
    owner: 'store_console',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'App Store Connect listing fields complete',
    evidenceRequired: ['store_console', 'screenshot'],
    nextAction: 'Enter title, subtitle, description, keywords in ASC.',
    relatedVerifyCommand: 'npm run verify:store-metadata-finalization',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'play_store_metadata_entered',
    title: 'Play Store metadata entered',
    category: 'metadata',
    status: 'pending',
    owner: 'store_console',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Play Console listing fields complete',
    evidenceRequired: ['store_console', 'screenshot'],
    nextAction: 'Enter Play Store listing copy and categories.',
    relatedVerifyCommand: 'npm run verify:store-metadata-finalization',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'store_screenshots_captured',
    title: 'Store screenshots captured',
    category: 'store',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Screenshot set uploaded to both stores',
    evidenceRequired: ['screenshot', 'store_console'],
    nextAction: 'Capture device screenshots per store matrix.',
    relatedVerifyCommand: 'npm run verify:store-screenshot-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'screenshots_device_matrix_completed',
    title: 'Screenshots device matrix completed',
    category: 'store',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Required device sizes covered',
    evidenceRequired: ['screenshot'],
    nextAction: 'Complete iOS + Android screenshot size matrix.',
    relatedVerifyCommand: 'npm run verify:store-screenshot-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'app_icon_final',
    title: 'App icon final',
    category: 'store',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Final icon assets in store consoles',
    evidenceRequired: ['screenshot', 'store_console'],
    nextAction: 'Upload final app icon to both stores.',
    relatedVerifyCommand: 'npm run verify:store-metadata-finalization',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'feature_graphic_if_required',
    title: 'Feature graphic (if required)',
    category: 'store',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Play feature graphic uploaded if required',
    evidenceRequired: ['screenshot', 'store_console'],
    nextAction: 'Add Play feature graphic per listing requirements.',
    relatedVerifyCommand: 'npm run verify:store-screenshot-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'release_notes_final',
    title: 'Release notes final',
    category: 'metadata',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Store release notes drafted and approved',
    evidenceRequired: ['manual_note', 'store_console'],
    nextAction: 'Finalize TR/EN release notes for soft launch.',
    relatedVerifyCommand: 'npm run verify:store-metadata-finalization',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  // C. Privacy / data safety
  blocker({
    id: 'privacy_url_published',
    title: 'Privacy policy URL published',
    category: 'privacy',
    status: 'pending',
    owner: 'legal',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Hosted privacy URL live (not placeholder)',
    evidenceRequired: ['url', 'screenshot'],
    nextAction: 'Publish hosted privacy policy URL.',
    relatedVerifyCommand: 'npm run verify:privacy-policy-readiness',
    docsLinkLabel: 'docs/crevia-privacy-policy-draft.md',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'privacy_policy_sentry_processor_added',
    title: 'Privacy policy Sentry processor listed',
    category: 'privacy',
    status: 'pending',
    owner: 'code',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Sentry processor in privacy draft + data safety matrix',
    evidenceRequired: ['manual_note'],
    nextAction: 'Confirm Sentry processor copy in published policy.',
    relatedVerifyCommand: 'npm run verify:privacy-policy-readiness',
    canBeDoneInCode: true,
    fakePassRisk: false,
  }),
  blocker({
    id: 'revenuecat_data_safety_review',
    title: 'RevenueCat data safety review',
    category: 'privacy',
    status: 'pending',
    owner: 'legal',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'RevenueCat data processing confirmed in data safety forms',
    evidenceRequired: ['manual_note', 'store_console'],
    nextAction: 'Map purchase data to store data safety answers.',
    relatedVerifyCommand: 'npm run verify:privacy-policy-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'analytics_data_safety_review',
    title: 'Analytics data safety review',
    category: 'privacy',
    status: 'pending',
    owner: 'legal',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Analytics collection disclosed in data safety forms',
    evidenceRequired: ['manual_note', 'store_console'],
    nextAction: 'Confirm analytics categories in App Store / Play forms.',
    relatedVerifyCommand: 'npm run verify:privacy-policy-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'sentry_data_safety_review',
    title: 'Sentry data safety review',
    category: 'privacy',
    status: 'pending',
    owner: 'legal',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Crash diagnostics disclosed; no PII/raw save',
    evidenceRequired: ['manual_note', 'store_console'],
    nextAction: 'Add crash diagnostics to data safety forms after DSN active.',
    relatedVerifyCommand: 'npm run verify:privacy-policy-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'store_data_safety_forms_completed',
    title: 'Store data safety forms completed',
    category: 'privacy',
    status: 'pending',
    owner: 'store_console',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'App Store privacy + Play data safety submitted',
    evidenceRequired: ['store_console', 'screenshot'],
    nextAction: 'Complete both store data safety questionnaires.',
    relatedVerifyCommand: 'npm run verify:privacy-policy-readiness',
    docsLinkLabel: 'docs/crevia-data-safety-draft.md',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'legal_final_review',
    title: 'Legal final review',
    category: 'privacy',
    status: 'pending',
    owner: 'legal',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Counsel sign-off on privacy + terms',
    evidenceRequired: ['manual_note'],
    nextAction: 'Schedule legal review of privacy and data safety drafts.',
    relatedVerifyCommand: 'npm run verify:privacy-policy-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  // D. Crash / Sentry
  blocker({
    id: 'sentry_dsn_set',
    title: 'Sentry DSN set',
    category: 'crash',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'EXPO_PUBLIC_SENTRY_DSN in internal EAS build',
    evidenceRequired: ['manual_note'],
    nextAction: 'Set EXPO_PUBLIC_SENTRY_DSN + EXPO_PUBLIC_CRASH_REPORTING_ENABLED.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'sentry_enabled_internal_build',
    title: 'Sentry enabled on internal build',
    category: 'crash',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Internal EAS build reports to Sentry',
    evidenceRequired: ['dashboard_event', 'manual_note'],
    nextAction: 'Build internal profile with crash reporting enabled.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'sentry_dashboard_smoke_test',
    title: 'Sentry dashboard smoke test',
    category: 'crash',
    status: 'pending',
    owner: 'dashboard',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    verificationMethod: 'Dev/internal crash visible in Sentry dashboard',
    evidenceRequired: ['dashboard_event', 'screenshot'],
    nextAction: 'Trigger DEV crash test; confirm issue in Sentry.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'sentry_source_maps_configured',
    title: 'Sentry source maps configured',
    category: 'crash',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'EAS Sentry auth token + org/project secrets',
    evidenceRequired: ['manual_note', 'dashboard_event'],
    nextAction: 'Configure SENTRY_AUTH_TOKEN / ORG / PROJECT for EAS.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'sentry_release_environment_tags_verified',
    title: 'Sentry release/environment tags verified',
    category: 'crash',
    status: 'pending',
    owner: 'dashboard',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Events tagged with release + app env',
    evidenceRequired: ['dashboard_event', 'screenshot'],
    nextAction: 'Verify release/dist/env tags on smoke event.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'sentry_privacy_safe_breadcrumbs_verified',
    title: 'Sentry privacy-safe breadcrumbs verified',
    category: 'crash',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'No PII/raw save in breadcrumb payload on device',
    evidenceRequired: ['dashboard_event', 'manual_note'],
    nextAction: 'Inspect Sentry event payload after internal smoke.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  // E. Analytics
  blocker({
    id: 'analytics_sdk_selected',
    title: 'Analytics SDK selected',
    category: 'analytics',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Production analytics provider chosen',
    evidenceRequired: ['manual_note'],
    nextAction: 'Select production analytics SDK (schema ready).',
    relatedVerifyCommand: 'npm run verify:analytics-runtime',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'analytics_sdk_integrated',
    title: 'Analytics SDK integrated',
    category: 'analytics',
    status: 'pending',
    owner: 'code',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Real SDK wired (not verify no-op only)',
    evidenceRequired: ['dashboard_event', 'manual_note'],
    nextAction: 'Replace no-op tracker with production SDK in internal build.',
    relatedVerifyCommand: 'npm run verify:analytics-runtime',
    canBeDoneInCode: true,
    fakePassRisk: true,
  }),
  blocker({
    id: 'analytics_dashboard_created',
    title: 'Analytics dashboard created',
    category: 'analytics',
    status: 'pending',
    owner: 'dashboard',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Dashboard project + charts exist',
    evidenceRequired: ['screenshot', 'url'],
    nextAction: 'Create dashboard with KPI/funnel cards from telemetry defs.',
    relatedVerifyCommand: 'npm run verify:post-launch-telemetry-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'analytics_events_visible_in_dashboard',
    title: 'Analytics events visible in dashboard',
    category: 'analytics',
    status: 'pending',
    owner: 'dashboard',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Key events visible after device session',
    evidenceRequired: ['dashboard_event', 'screenshot'],
    nextAction: 'Run Day 1 session; confirm events in dashboard.',
    relatedVerifyCommand: 'npm run verify:post-launch-telemetry-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'day1_funnel_verified',
    title: 'Day 1 funnel verified',
    category: 'analytics',
    status: 'pending',
    owner: 'dashboard',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Day 1 funnel steps visible in dashboard',
    evidenceRequired: ['dashboard_event', 'screenshot'],
    nextAction: 'Verify first-session funnel on real device.',
    relatedVerifyCommand: 'npm run verify:post-launch-telemetry-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'iap_funnel_verified',
    title: 'IAP funnel verified',
    category: 'analytics',
    status: 'pending',
    owner: 'dashboard',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'IAP funnel events after sandbox purchase',
    evidenceRequired: ['dashboard_event', 'purchase_log'],
    nextAction: 'Verify IAP funnel after sandbox smoke.',
    relatedVerifyCommand: 'npm run verify:post-launch-telemetry-readiness',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'crash_vs_analytics_separation_verified',
    title: 'Crash vs analytics separation verified',
    category: 'analytics',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    verificationMethod: 'Crash events in Sentry; product events in analytics',
    evidenceRequired: ['dashboard_event', 'manual_note'],
    nextAction: 'Confirm no duplicate PII across Sentry and analytics.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  // F. Device test
  blocker({
    id: 'ios_internal_device_test',
    title: 'iOS internal device test',
    category: 'device_test',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    verificationMethod: 'Physical iPhone internal EAS build smoke',
    evidenceRequired: ['screen_recording', 'manual_note'],
    nextAction: 'Install internal build on iPhone; run device test matrix.',
    relatedVerifyCommand: 'npm run verify:real-device-playtest',
    docsLinkLabel: 'docs/crevia-real-device-playtest-round-1.md',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'android_internal_device_test',
    title: 'Android internal device test',
    category: 'device_test',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    verificationMethod: 'Physical Android internal EAS build smoke',
    evidenceRequired: ['screen_recording', 'manual_note'],
    nextAction: 'Install internal build on Android; run device test matrix.',
    relatedVerifyCommand: 'npm run verify:real-device-playtest',
    docsLinkLabel: 'docs/crevia-real-device-playtest-round-1.md',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'day1_first_session_smoke',
    title: 'Day 1 first session smoke',
    category: 'device_test',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    verificationMethod: 'Fresh install Day 1 comprehension on device',
    evidenceRequired: ['screenshot', 'manual_note'],
    nextAction: 'Complete idt.day1_first_session test case.',
    relatedVerifyCommand: 'npm run verify:first-10-minutes',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'day5_mid_event_resume_smoke',
    title: 'Day 5 mid-event resume smoke',
    category: 'device_test',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'Close/reopen during mid-event on Day 5',
    evidenceRequired: ['screen_recording', 'manual_note'],
    nextAction: 'Complete idt.day5_mid_event_resume test case.',
    relatedVerifyCommand: 'npm run verify:offline-resume',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'day8_pack_origin_event_smoke',
    title: 'Day 8 pack-origin event smoke',
    category: 'device_test',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'Pack-origin event appears after Day 8 transition',
    evidenceRequired: ['screenshot', 'manual_note'],
    nextAction: 'Complete idt.day8_pack_origin_event test case.',
    relatedVerifyCommand: 'npm run verify:offline-resume',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'report_before_close_resume_smoke',
    title: 'Report before close resume smoke',
    category: 'device_test',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'Report screen survives close/reopen',
    evidenceRequired: ['screen_recording', 'manual_note'],
    nextAction: 'Complete idt.day8_report_resume test case.',
    relatedVerifyCommand: 'npm run verify:offline-resume',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'iap_offer_screen_smoke',
    title: 'IAP offer screen smoke',
    category: 'device_test',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    verificationMethod: 'PostPilotOffer screen readable on device',
    evidenceRequired: ['screenshot', 'manual_note'],
    nextAction: 'Complete idt.iap_offer_screen test case.',
    relatedVerifyCommand: 'npm run verify:iap-integration',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'map_reaction_smoke',
    title: 'Map reaction smoke',
    category: 'device_test',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'Map district + Mahalle Karnesi + reaction on device',
    evidenceRequired: ['screenshot', 'manual_note'],
    nextAction: 'Complete idt.map_reaction test case.',
    relatedVerifyCommand: 'npm run verify:ui-density',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'crash_test_smoke',
    title: 'Sentry crash test smoke (DEV/internal)',
    category: 'device_test',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'DEV crash button triggers Sentry event',
    evidenceRequired: ['dashboard_event', 'manual_note'],
    nextAction: 'Complete idt.sentry_crash_smoke test case.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  // G. Performance device smoke
  blocker({
    id: 'low_end_android_smoke',
    title: 'Low-end Android smoke',
    category: 'performance',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    verificationMethod: 'Mid-range Android scroll/jank check',
    evidenceRequired: ['screen_recording', 'manual_note'],
    nextAction: 'Test Hub/Map scroll on low-end Android.',
    relatedVerifyCommand: 'npm run verify:performance-selectors',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'iphone_se_layout_smoke',
    title: 'iPhone SE layout smoke',
    category: 'performance',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'Small iOS screen layout safe',
    evidenceRequired: ['screenshot', 'manual_note'],
    nextAction: 'Verify compact layouts on iPhone SE class device.',
    relatedVerifyCommand: 'npm run verify:ui-density',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'large_text_smoke',
    title: 'Large text accessibility smoke',
    category: 'performance',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'Dynamic type / large text does not break CTA',
    evidenceRequired: ['screenshot', 'manual_note'],
    nextAction: 'Complete idt.large_text_smoke test case.',
    relatedVerifyCommand: 'npm run verify:ui-density',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'map_screen_performance_smoke',
    title: 'Map screen performance smoke',
    category: 'performance',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'Map panel scroll/pan acceptable on device',
    evidenceRequired: ['screen_recording', 'manual_note'],
    nextAction: 'Profile map open/overlay on real device.',
    relatedVerifyCommand: 'npm run verify:performance-selectors',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'report_screen_scroll_smoke',
    title: 'Report screen scroll smoke',
    category: 'performance',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'End-of-day report scroll smooth',
    evidenceRequired: ['screen_recording', 'manual_note'],
    nextAction: 'Scroll full Day 8 report on device.',
    relatedVerifyCommand: 'npm run verify:ui-density',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'app_start_smoke',
    title: 'App start smoke',
    category: 'performance',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    verificationMethod: 'Cold start acceptable on device',
    evidenceRequired: ['manual_note', 'screen_recording'],
    nextAction: 'Measure cold start on iOS + Android.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
  blocker({
    id: 'memory_warning_observation',
    title: 'Memory warning observation',
    category: 'performance',
    status: 'pending',
    owner: 'manual',
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: false,
    verificationMethod: 'No memory warnings during 20-min session',
    evidenceRequired: ['manual_note'],
    nextAction: 'Observe memory during extended play session.',
    relatedVerifyCommand: 'npm run verify:crash-performance',
    canBeDoneInCode: false,
    fakePassRisk: true,
  }),
] as const;

export const MANUAL_LAUNCH_BLOCKER_GROUP_MAP: Record<
  ManualLaunchBlockerGroupId,
  readonly string[]
> = {
  iap_revenuecat: [
    'revenuecat_public_keys',
    'revenuecat_entitlement_config',
    'revenuecat_offering_config',
    'app_store_product_created',
    'play_console_product_created',
    'iap_sandbox_purchase_test',
    'iap_restore_test',
    'product_price_finalized',
  ],
  store_metadata_screenshots: [
    'app_store_metadata_entered',
    'play_store_metadata_entered',
    'store_screenshots_captured',
    'screenshots_device_matrix_completed',
    'app_icon_final',
    'feature_graphic_if_required',
    'release_notes_final',
  ],
  privacy_data_safety: [
    'privacy_url_published',
    'privacy_policy_sentry_processor_added',
    'revenuecat_data_safety_review',
    'analytics_data_safety_review',
    'sentry_data_safety_review',
    'store_data_safety_forms_completed',
    'legal_final_review',
  ],
  crash_sentry: [
    'sentry_dsn_set',
    'sentry_enabled_internal_build',
    'sentry_dashboard_smoke_test',
    'sentry_source_maps_configured',
    'sentry_release_environment_tags_verified',
    'sentry_privacy_safe_breadcrumbs_verified',
  ],
  analytics_dashboard: [
    'analytics_sdk_selected',
    'analytics_sdk_integrated',
    'analytics_dashboard_created',
    'analytics_events_visible_in_dashboard',
    'day1_funnel_verified',
    'iap_funnel_verified',
    'crash_vs_analytics_separation_verified',
  ],
  device_test: [
    'ios_internal_device_test',
    'android_internal_device_test',
    'day1_first_session_smoke',
    'day5_mid_event_resume_smoke',
    'day8_pack_origin_event_smoke',
    'report_before_close_resume_smoke',
    'iap_offer_screen_smoke',
    'map_reaction_smoke',
    'crash_test_smoke',
  ],
  performance_device_smoke: [
    'low_end_android_smoke',
    'iphone_se_layout_smoke',
    'large_text_smoke',
    'map_screen_performance_smoke',
    'report_screen_scroll_smoke',
    'app_start_smoke',
    'memory_warning_observation',
  ],
};

function testCase(partial: ManualLaunchDeviceTestCase): ManualLaunchDeviceTestCase {
  return partial;
}

export const MANUAL_LAUNCH_DEVICE_TEST_MATRIX: readonly ManualLaunchDeviceTestCase[] = [
  testCase({
    id: 'idt.day1_first_session',
    title: 'Day 1 first session',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Fresh install; no prior save.',
    steps: [
      'Launch app; complete Day 1 hub guide.',
      'Open first event; complete decision flow.',
      'Return to hub; confirm compact Day 1 layout.',
    ],
    expectedResult: 'Player understands first action without overload.',
    evidenceRequired: ['screenshot', 'manual_note'],
    passCriteria: 'No crash; guide + first event completable in <10 min.',
    relatedSystems: ['hub', 'first_10_minutes', 'event_flow'],
    blockerIfFails: 'day1_first_session_smoke',
  }),
  testCase({
    id: 'idt.day1_decision_result',
    title: 'Day 1 decision result',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Day 1 first event opened.',
    steps: ['Select decision; view result screen.', 'Check impact explanation card.', 'Tap primary CTA back to hub.'],
    expectedResult: 'Impact readable; CTA returns to hub.',
    evidenceRequired: ['screenshot'],
    passCriteria: 'No overflow; impact text within guards.',
    relatedSystems: ['decision_result', 'ui_density'],
    blockerIfFails: 'day1_first_session_smoke',
  }),
  testCase({
    id: 'idt.day5_mid_event_resume',
    title: 'Day 5 mid-event close/reopen',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Pilot day 5 save or fast-forward.',
    steps: ['Open mid-event; background app.', 'Force close; reopen.', 'Resume same event phase.'],
    expectedResult: 'State restored; no duplicate events.',
    evidenceRequired: ['screen_recording', 'manual_note'],
    passCriteria: 'Resume idempotent per offline-resume audit.',
    relatedSystems: ['offline_resume', 'event_flow'],
    blockerIfFails: 'day5_mid_event_resume_smoke',
  }),
  testCase({
    id: 'idt.day7_day8_transition',
    title: 'Day 7 completion → Day 8 transition',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Day 7 pilot completion available.',
    steps: ['Complete Day 7; view pilot completion.', 'Advance to Day 8 hub.'],
    expectedResult: 'Transition copy correct; post-pilot surfaces appear.',
    evidenceRequired: ['screenshot', 'manual_note'],
    passCriteria: 'No crash; Day 8 hub loads.',
    relatedSystems: ['pilot_completion', 'post_pilot'],
  }),
  testCase({
    id: 'idt.day8_pack_origin_event',
    title: 'Day 8 pack-origin event appears',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Day 8+ save with content pack activation.',
    steps: ['Open hub; locate pack-origin event.', 'Confirm pack metadata visible in flow.'],
    expectedResult: 'Pack-origin event surfaces once (cap respected).',
    evidenceRequired: ['screenshot'],
    passCriteria: 'Max 1 light pack per day cap on device.',
    relatedSystems: ['content_runtime_activation', 'offline_resume'],
    blockerIfFails: 'day8_pack_origin_event_smoke',
  }),
  testCase({
    id: 'idt.day8_pack_origin_decision_result',
    title: 'Day 8 pack-origin decision result',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Pack-origin event open on Day 8+.',
    steps: ['Complete decision; view result.', 'Check city echo / impact lines.'],
    expectedResult: 'Pack-origin impact visible; no crash.',
    evidenceRequired: ['screenshot'],
    passCriteria: 'Impact explanation renders.',
    relatedSystems: ['decision_impact', 'city_echo'],
  }),
  testCase({
    id: 'idt.day8_report_resume',
    title: 'Day 8 report before close/reopen',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Day 8 report available.',
    steps: ['Open report; scroll full content.', 'Background and reopen before closing day.'],
    expectedResult: 'Report state preserved; scroll position acceptable.',
    evidenceRequired: ['screen_recording'],
    passCriteria: 'No crash; tomorrow risk card visible.',
    relatedSystems: ['report', 'tomorrow_risk', 'offline_resume'],
    blockerIfFails: 'report_before_close_resume_smoke',
  }),
  testCase({
    id: 'idt.hub_resume_after_report',
    title: 'Hub resume after report',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Viewed Day 8 report.',
    steps: ['Return to hub from report.', 'Kill app; reopen to hub.'],
    expectedResult: 'Hub cards consistent; no duplicate journal entries.',
    evidenceRequired: ['screenshot', 'manual_note'],
    passCriteria: 'City journal duplicate guard holds.',
    relatedSystems: ['hub', 'city_journal', 'offline_resume'],
  }),
  testCase({
    id: 'idt.map_reaction',
    title: 'Map district + Mahalle Karnesi + Map Reaction',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Day 8+ with map reactions eligible.',
    steps: ['Open map; select district.', 'View Mahalle Karnesi strip.', 'Confirm reaction label + a11y.'],
    expectedResult: 'Reaction readable; panel does not overflow.',
    evidenceRequired: ['screenshot'],
    passCriteria: 'Map reaction smoke PASS per ui-density guards.',
    relatedSystems: ['map', 'district_report_card', 'map_reactions'],
    blockerIfFails: 'map_reaction_smoke',
  }),
  testCase({
    id: 'idt.operational_resources_detail',
    title: 'Operational resources detail sheet',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Day 8+ operational resources visible.',
    steps: ['Open resources card.', 'Open detail sheet; verify max 2 lines.'],
    expectedResult: 'Compact lines; no individual vehicle/person rows.',
    evidenceRequired: ['screenshot'],
    passCriteria: 'Matches operational resources lite spec.',
    relatedSystems: ['operational_resources', 'ui_density'],
  }),
  testCase({
    id: 'idt.social_pulse_mention_cap',
    title: 'Social Pulse mention count',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Social Pulse eligible day.',
    steps: ['Open Social Pulse.', 'Count mentions; verify cap.'],
    expectedResult: 'Mention count within cap; compact Day 1 if applicable.',
    evidenceRequired: ['screenshot'],
    passCriteria: 'No unbounded mention list.',
    relatedSystems: ['social_pulse', 'ui_density'],
  }),
  testCase({
    id: 'idt.iap_offer_screen',
    title: 'PostPilotOffer screen',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Post-pilot offer eligible.',
    steps: ['Navigate to offer screen.', 'Review copy and CTA.'],
    expectedResult: 'Offer readable; restore CTA present.',
    evidenceRequired: ['screenshot'],
    passCriteria: 'No false purchase claims.',
    relatedSystems: ['iap', 'post_pilot_offer'],
    blockerIfFails: 'iap_offer_screen_smoke',
  }),
  testCase({
    id: 'idt.iap_sandbox_purchase',
    title: 'IAP sandbox purchase',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Sandbox accounts + products configured.',
    steps: ['Open purchase flow.', 'Complete sandbox purchase.', 'Verify entitlement unlock.'],
    expectedResult: 'Purchase succeeds; limited/full access updates.',
    evidenceRequired: ['purchase_log', 'screenshot'],
    passCriteria: 'Sandbox matrix case passes.',
    relatedSystems: ['iap', 'revenuecat'],
    blockerIfFails: 'iap_sandbox_purchase_test',
  }),
  testCase({
    id: 'idt.iap_restore_sandbox',
    title: 'IAP restore sandbox',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Prior sandbox purchase on account.',
    steps: ['Reinstall or use restore CTA.', 'Run restore purchases.'],
    expectedResult: 'Entitlement restored.',
    evidenceRequired: ['purchase_log', 'manual_note'],
    passCriteria: 'Restore flow completes without crash.',
    relatedSystems: ['iap', 'revenuecat'],
    blockerIfFails: 'iap_restore_test',
  }),
  testCase({
    id: 'idt.sentry_crash_smoke',
    title: 'Sentry crash test (DEV/internal only)',
    platform: 'both',
    buildType: 'development',
    precondition: 'DSN set; DEV tools or internal build.',
    steps: ['Trigger DEV crash test button.', 'Confirm app recovers or restarts cleanly.'],
    expectedResult: 'Event appears in Sentry dashboard.',
    evidenceRequired: ['dashboard_event', 'screenshot'],
    passCriteria: 'Sentry issue received within 5 min.',
    relatedSystems: ['crash_performance', 'sentry'],
    blockerIfFails: 'crash_test_smoke',
  }),
  testCase({
    id: 'idt.sentry_dashboard_visible',
    title: 'Sentry dashboard event visible',
    platform: 'both',
    buildType: 'internal',
    precondition: 'After crash smoke or handled error.',
    steps: ['Open Sentry dashboard.', 'Locate event with release/env tags.'],
    expectedResult: 'Event visible with correct environment.',
    evidenceRequired: ['dashboard_event', 'screenshot'],
    passCriteria: 'Tags match internal build profile.',
    relatedSystems: ['crash_performance', 'sentry'],
    blockerIfFails: 'sentry_dashboard_smoke_test',
  }),
  testCase({
    id: 'idt.large_text_smoke',
    title: 'Large text smoke',
    platform: 'both',
    buildType: 'internal',
    precondition: 'OS accessibility large text enabled.',
    steps: ['Navigate Hub, Map, Report with large text.', 'Verify primary CTAs visible.'],
    expectedResult: 'No clipped CTAs; scroll available where needed.',
    evidenceRequired: ['screenshot'],
    passCriteria: 'Primary CTA accessible labels present.',
    relatedSystems: ['ui_density', 'accessibility'],
    blockerIfFails: 'large_text_smoke',
  }),
  testCase({
    id: 'idt.low_end_android_performance',
    title: 'Low-end Android scroll/performance',
    platform: 'android',
    buildType: 'internal',
    precondition: 'Mid-range or low-end Android device.',
    steps: ['Scroll Hub, Map bottom panel, Report.', 'Note jank or frame drops.'],
    expectedResult: 'Acceptable scroll; no ANR.',
    evidenceRequired: ['screen_recording', 'manual_note'],
    passCriteria: 'No critical jank on primary flows.',
    relatedSystems: ['performance', 'map', 'hub'],
    blockerIfFails: 'low_end_android_smoke',
  }),
  testCase({
    id: 'idt.offline_launch',
    title: 'Offline / no-network launch',
    platform: 'both',
    buildType: 'internal',
    precondition: 'Airplane mode or no network.',
    steps: ['Launch app offline.', 'Navigate hub and resume save.'],
    expectedResult: 'App opens; monetization fallback safe.',
    evidenceRequired: ['manual_note', 'screenshot'],
    passCriteria: 'No network crash; offline fallback per audit.',
    relatedSystems: ['offline_resume', 'iap'],
  }),
  testCase({
    id: 'idt.privacy_store_metadata_check',
    title: 'Privacy / store metadata final check',
    platform: 'both',
    buildType: 'production_preview',
    precondition: 'Store consoles accessible.',
    steps: [
      'Verify privacy URL placeholder not used in listing.',
      'Cross-check data safety drafts vs store forms.',
    ],
    expectedResult: 'Listing matches published privacy policy.',
    evidenceRequired: ['url', 'store_console', 'screenshot'],
    passCriteria: 'No placeholder URL in production listing.',
    relatedSystems: ['privacy', 'store_metadata'],
    blockerIfFails: 'privacy_url_published',
  }),
] as const;

export const MANUAL_LAUNCH_EVIDENCE_TEMPLATE: readonly ManualLaunchEvidenceRecord[] =
  MANUAL_LAUNCH_BLOCKERS.map((b) => ({
    blockerOrTestId: b.id,
    evidenceType: b.evidenceRequired[0] ?? 'manual_note',
    evidenceStatus: 'missing' as const,
  }));

export const MANUAL_LAUNCH_NON_GOALS: readonly string[] = [
  'No fake PASS for manual blockers',
  'No fabricated RevenueCat / store / Sentry dashboard completion',
  'No gameplay system changes',
  'No applyDecision / dayPipeline / event generation changes',
  'No persist shape or SAVE_VERSION bump',
  'No monetization behavior changes',
  'No invented product ids or prices',
  'No privacy URL placeholder marked published',
  'No analytics dashboard PASS without wiring',
  'No new routes or large UI redesign',
];
