import type {
  ManualLaunchRoundOneTestCase,
  ManualLaunchTestRound,
  ManualLaunchTestRoundScope,
} from './manualLaunchTestRounds';

export const MANUAL_LAUNCH_ROUND_ONE_ID = 'round_1_internal_device_playtest';

export const MANUAL_LAUNCH_ROUND_ONE_DOCS_PATH = 'docs/crevia-internal-device-test-round-one.md';

/** Round 1 QA evidence template — iOS/Android tables + attach JSON format. */
export const MANUAL_LAUNCH_QA_EVIDENCE_DOCS_PATH = 'docs/crevia-real-device-qa-evidence-round-1.md';

export const MANUAL_LAUNCH_ROUND_ONE_SCOPES: ManualLaunchTestRoundScope[] = [
  {
    id: 'build_readiness',
    title: 'A) Build readiness',
    description: 'Internal EAS build, version record, iOS/Android install smoke.',
    testCaseIds: [
      'eas_internal_build_created',
      'ios_install_smoke',
      'android_install_smoke',
      'offline_no_network_launch',
    ],
  },
  {
    id: 'day1_first_session',
    title: 'B) Day 1 first session smoke',
    description: 'Fresh open, hub sade akış, event, decision, report, hub return.',
    testCaseIds: ['day1_first_session', 'day1_decision_result', 'day1_report_return_to_hub'],
  },
  {
    id: 'day8_pack_origin',
    title: 'C) Day 8 pack-origin ana operasyon smoke',
    description: 'Main Operation Feel, pack-origin event, systems echo, map, report resume.',
    testCaseIds: [
      'day7_to_day8_transition',
      'day8_main_operation_feel',
      'day8_pack_origin_event_appears',
      'day8_pack_origin_decision_result',
      'day8_pack_origin_report_echo',
      'day8_map_district_reaction',
      'day8_district_report_card',
      'day8_city_journal_strip',
      'day8_operational_resources_sheet',
    ],
  },
  {
    id: 'resume_smoke',
    title: 'D) Resume smoke',
    description: 'Mid-event and report close/reopen persistence.',
    testCaseIds: ['day5_mid_event_resume', 'day8_report_before_close_resume'],
  },
  {
    id: 'ui_density',
    title: 'E) UI density smoke',
    description: 'Small screen + large text on Hub, Map, DecisionResult, Report.',
    testCaseIds: ['large_text_hub_map_report'],
  },
  {
    id: 'sentry_conditional',
    title: 'F) Sentry smoke (env-ready only)',
    description: 'Dashboard event smoke — pending until EXPO_PUBLIC_SENTRY_DSN set.',
    testCaseIds: ['sentry_dashboard_smoke_if_env_ready'],
  },
];

export const MANUAL_LAUNCH_ROUND_ONE_TEST_CASE_IDS = [
  'eas_internal_build_created',
  'ios_install_smoke',
  'android_install_smoke',
  'day1_first_session',
  'day1_decision_result',
  'day1_report_return_to_hub',
  'day5_mid_event_resume',
  'day7_to_day8_transition',
  'day8_main_operation_feel',
  'day8_pack_origin_event_appears',
  'day8_pack_origin_decision_result',
  'day8_pack_origin_report_echo',
  'day8_map_district_reaction',
  'day8_district_report_card',
  'day8_city_journal_strip',
  'day8_operational_resources_sheet',
  'day8_report_before_close_resume',
  'large_text_hub_map_report',
  'offline_no_network_launch',
  'sentry_dashboard_smoke_if_env_ready',
] as const;

export type ManualLaunchRoundOneTestCaseId = (typeof MANUAL_LAUNCH_ROUND_ONE_TEST_CASE_IDS)[number];

function tc(
  partial: Omit<ManualLaunchRoundOneTestCase, 'status' | 'evidenceStatus'>,
): Omit<ManualLaunchRoundOneTestCase, 'status' | 'evidenceStatus'> {
  return partial;
}

export const MANUAL_LAUNCH_ROUND_ONE_TEST_CASE_TEMPLATES: Omit<
  ManualLaunchRoundOneTestCase,
  'status' | 'evidenceStatus'
>[] = [
  tc({
    testCaseId: 'eas_internal_build_created',
    title: 'Internal EAS build created',
    scopeId: 'build_readiness',
    platform: 'both',
    preconditions: ['EAS CLI logged in', 'internal profile configured'],
    steps: [
      'Run eas build --profile internal for iOS and Android',
      'Record app version + build number in tracker notes',
      'Upload build_log evidence path (not committed until real build exists)',
    ],
    expectedResult: 'Installable internal builds available for testers.',
    evidenceRequired: ['build_log', 'manual_note'],
    passCriteria: ['Build succeeds on both platforms', 'Version/build number recorded'],
    failCriteria: ['Build fails', 'Wrong profile', 'No distribution channel'],
    relatedSystems: ['eas', 'build'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    linkedBlockerIds: ['internal_eas_build_ios', 'internal_eas_build_android'],
  }),
  tc({
    testCaseId: 'ios_install_smoke',
    title: 'iOS install smoke',
    scopeId: 'build_readiness',
    platform: 'ios',
    preconditions: ['iOS internal build artifact or TestFlight internal'],
    steps: ['Install on physical iPhone', 'Cold launch', 'Confirm app opens to Hub or fresh state'],
    expectedResult: 'App installs and launches without crash.',
    evidenceRequired: ['screenshot', 'manual_note'],
    passCriteria: ['Install succeeds', 'Cold launch no crash'],
    failCriteria: ['Install blocked', 'Crash on launch'],
    relatedSystems: ['ios', 'hub'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    linkedLegacyTestId: 'idt.day1_first_session',
  }),
  tc({
    testCaseId: 'android_install_smoke',
    title: 'Android install smoke',
    scopeId: 'build_readiness',
    platform: 'android',
    preconditions: ['Android internal APK/AAB distributed'],
    steps: ['Install on physical Android device', 'Cold launch', 'Confirm app opens'],
    expectedResult: 'App installs and launches without crash.',
    evidenceRequired: ['screenshot', 'manual_note'],
    passCriteria: ['Install succeeds', 'Cold launch no crash'],
    failCriteria: ['Install blocked', 'Crash on launch'],
    relatedSystems: ['android', 'hub'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
  }),
  tc({
    testCaseId: 'day1_first_session',
    title: 'Day 1 first session',
    scopeId: 'day1_first_session',
    platform: 'both',
    preconditions: ['Fresh install or cleared save', 'Day 1 state'],
    steps: [
      'Open app — observe Hub',
      'Confirm guide strip + max 2 featured cards',
      'Confirm heavy systems hidden (Crisis, PostPilot, Main Operation)',
      'Navigate to first event',
    ],
    expectedResult: 'Hub sade; büyük sistemler sızmaz; crash yok.',
    evidenceRequired: ['screenshot', 'screen_recording'],
    passCriteria: [
      'Hub sade layout',
      'Şehir Günlüğü hidden',
      'Dynamic Map Reaction hidden/minimal',
      'Post-pilot cards hidden',
      'No crash',
    ],
    failCriteria: ['Hub overcrowded', 'Wrong systems visible', 'Crash', 'Stuck navigation'],
    relatedSystems: ['hub', 'first_ten_minutes', 'tutorial'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    linkedLegacyTestId: 'idt.day1_first_session',
    linkedBlockerIds: ['day1_first_session_smoke'],
  }),
  tc({
    testCaseId: 'day1_decision_result',
    title: 'Day 1 decision result',
    scopeId: 'day1_first_session',
    platform: 'both',
    preconditions: ['Day 1 event in progress'],
    steps: ['Complete decision flow', 'View Decision Impact', 'View Tomorrow Risk'],
    expectedResult: 'Decision Impact sade; Tomorrow Risk ağır risk dili kullanmaz.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['Decision Impact sade', 'Tomorrow Risk calm copy', 'Result screen readable'],
    failCriteria: ['Generic fallback copy', 'Heavy risk language', 'Crash'],
    relatedSystems: ['decision_impact', 'tomorrow_risk', 'event_workflow'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    linkedLegacyTestId: 'idt.day1_decision_result',
  }),
  tc({
    testCaseId: 'day1_report_return_to_hub',
    title: 'Day 1 report + return to Hub',
    scopeId: 'day1_first_session',
    platform: 'both',
    preconditions: ['Day 1 decisions complete'],
    steps: ['Open end-of-day report', 'Verify compact layout', 'Tap CTA back to Hub'],
    expectedResult: 'Report compact; CTA görünür; Hub resume clean.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['Report compact', 'CTA visible', 'Hub resume without crash'],
    failCriteria: ['Report overcrowded', 'Missing CTA', 'Crash on return'],
    relatedSystems: ['daily_report', 'hub'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    linkedLegacyTestId: 'idt.day1_first_session',
  }),
  tc({
    testCaseId: 'day5_mid_event_resume',
    title: 'Day 5 mid-event close/reopen',
    scopeId: 'resume_smoke',
    platform: 'both',
    preconditions: ['Reach Day 5', 'Event mid-flow (e.g. Planla phase)'],
    steps: ['Background or kill app', 'Reopen', 'Resume same event phase'],
    expectedResult: 'State preserved; no duplicate events; no crash.',
    evidenceRequired: ['screen_recording', 'manual_note'],
    passCriteria: ['Same day/event phase', 'No data loss', 'No crash'],
    failCriteria: ['Reset to wrong day', 'Duplicate event', 'Crash'],
    relatedSystems: ['persist', 'event_workflow', 'offline_resume'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    linkedLegacyTestId: 'idt.day5_mid_event_resume',
  }),
  tc({
    testCaseId: 'day7_to_day8_transition',
    title: 'Day 7 → Day 8 transition',
    scopeId: 'day8_pack_origin',
    platform: 'both',
    preconditions: ['Complete Day 7 pilot OR use dev seed to Day 8'],
    steps: ['Finish Day 7 report', 'Advance to Day 8', 'Observe Hub transition'],
    expectedResult: 'Day 8 opens; no false game-over; Main Operation path visible.',
    evidenceRequired: ['screenshot', 'screen_recording'],
    passCriteria: ['Day 8 reached', 'No season-final false claim', 'Hub stable'],
    failCriteria: ['Stuck on Day 7', 'False game over UI', 'Crash'],
    relatedSystems: ['day_pipeline', 'pilot_completion', 'hub'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    linkedLegacyTestId: 'idt.day7_day8_transition',
  }),
  tc({
    testCaseId: 'day8_main_operation_feel',
    title: 'Day 8 Main Operation Feel',
    scopeId: 'day8_pack_origin',
    platform: 'both',
    preconditions: ['Day 8 state'],
    steps: ['Open Hub', 'Locate Main Operation Feel card', 'Read player-facing copy'],
    expectedResult: 'Main Operation Feel kartı görünür; teknik pack adı yok.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['Card visible', 'Player-facing copy', 'No internal pack id in UI'],
    failCriteria: ['Card missing', 'Technical pack name visible', 'Crash'],
    relatedSystems: ['main_operation_feel', 'hub'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    linkedBlockerIds: ['day8_main_operation_feel_smoke'],
  }),
  tc({
    testCaseId: 'day8_pack_origin_event_appears',
    title: 'Day 8 pack-origin event appears',
    scopeId: 'day8_pack_origin',
    platform: 'both',
    preconditions: ['Day 8 + content pack runtime active'],
    steps: ['Open daily events', 'Find pack-origin event', 'Check PostPilotEventContextChip'],
    expectedResult: 'Pack-origin event görünür; chip player-facing; max caps içinde.',
    evidenceRequired: ['screenshot'],
    passCriteria: [
      'Pack-origin event visible',
      'PostPilotEventContextChip player-facing',
      'Within max caps',
      'No technical pack name',
    ],
    failCriteria: ['Event missing', 'Generic chip only', 'Pack id in UI'],
    relatedSystems: ['content_runtime', 'events', 'post_pilot_context'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    linkedLegacyTestId: 'idt.day8_pack_origin_event',
    linkedBlockerIds: ['day8_pack_origin_event_smoke'],
  }),
  tc({
    testCaseId: 'day8_pack_origin_decision_result',
    title: 'Day 8 pack-origin decision result',
    scopeId: 'day8_pack_origin',
    platform: 'both',
    preconditions: ['Pack-origin event active'],
    steps: ['Complete decision', 'Read Decision Impact pack-specific line', 'Read Tomorrow Risk pack/domain line'],
    expectedResult: 'Decision Impact generic fallback’e düşmez; Tomorrow Risk pack context kullanır.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['Pack-specific Decision Impact', 'Pack/domain Tomorrow Risk', 'No duplicate echo lines'],
    failCriteria: ['Generic fallback only', 'Duplicate City Echo lines', 'Crash'],
    relatedSystems: ['decision_impact', 'tomorrow_risk', 'city_echo'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    linkedLegacyTestId: 'idt.day8_pack_origin_decision_result',
  }),
  tc({
    testCaseId: 'day8_pack_origin_report_echo',
    title: 'Day 8 pack-origin report echo',
    scopeId: 'day8_pack_origin',
    platform: 'both',
    preconditions: ['Day 8 pack-origin day complete'],
    steps: ['Open end-of-day report', 'Check City Echo / Social / Report lines', 'Return to Hub'],
    expectedResult: 'Echo satırları duplicate değil; report duplicate yapmaz; Hub resume OK.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['No duplicate echo', 'Report readable', 'Hub resume preserves state'],
    failCriteria: ['Duplicate lines', 'Report crash', 'Lost state on resume'],
    relatedSystems: ['daily_report', 'city_echo', 'social_pulse', 'hub'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: true,
    linkedLegacyTestId: 'idt.day8_report_resume',
    linkedBlockerIds: ['report_before_close_resume_smoke'],
  }),
  tc({
    testCaseId: 'day8_map_district_reaction',
    title: 'Day 8 Map district + reaction',
    scopeId: 'day8_pack_origin',
    platform: 'both',
    preconditions: ['Day 8', 'Map accessible'],
    steps: ['Open Map', 'Select district', 'View Dynamic Map Reaction (max 4)', 'Mahalle Karnesi entry'],
    expectedResult: 'Map Reaction max 4 içinde; district selection meaningful.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['Map Reaction ≤4 items', 'District selected', 'No overflow on small screen'],
    failCriteria: ['Reactions missing', '>4 reactions', 'Layout break'],
    relatedSystems: ['map', 'map_reactions', 'district_report_card'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    linkedLegacyTestId: 'idt.map_reaction',
    linkedBlockerIds: ['map_reaction_smoke'],
  }),
  tc({
    testCaseId: 'day8_district_report_card',
    title: 'Day 8 Mahalle Karnesi',
    scopeId: 'day8_pack_origin',
    platform: 'both',
    preconditions: ['Day 8', 'District selected on map'],
    steps: ['Open Mahalle Karnesi for selected district', 'Read summary'],
    expectedResult: 'Selected district için anlamlı özet; crash yok.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['District-specific content', 'Readable layout'],
    failCriteria: ['Empty/wrong district', 'Crash'],
    relatedSystems: ['district_report_card', 'map'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
  }),
  tc({
    testCaseId: 'day8_city_journal_strip',
    title: 'Day 8 Şehir Günlüğü strip',
    scopeId: 'day8_pack_origin',
    platform: 'both',
    preconditions: ['Day 8 Hub'],
    steps: ['Observe Şehir Günlüğü on Hub', 'Count entries'],
    expectedResult: 'Şehir Günlüğü max 5 entry; Hub max 2 featured journal surfacing.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['Journal ≤5 entries', 'Hub journal surfacing ≤2'],
    failCriteria: ['Overflow entries', 'Hub overcrowded'],
    relatedSystems: ['city_journal', 'hub'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
  }),
  tc({
    testCaseId: 'day8_operational_resources_sheet',
    title: 'Day 8 Ekip & Araç Presence sheet',
    scopeId: 'day8_pack_origin',
    platform: 'both',
    preconditions: ['Day 8', 'Operational resources available'],
    steps: ['Open operational resources detail sheet', 'Verify presence copy'],
    expectedResult: 'Tekil personel/araç listesi göstermez; presence-lite copy.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['No individual roster list', 'Presence-lite readable'],
    failCriteria: ['Named staff/vehicle list', 'Sheet crash'],
    relatedSystems: ['operational_resources', 'hub'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    linkedLegacyTestId: 'idt.operational_resources_detail',
  }),
  tc({
    testCaseId: 'day8_report_before_close_resume',
    title: 'Day 8 report before close/reopen',
    scopeId: 'resume_smoke',
    platform: 'both',
    preconditions: ['Day 8 report visible before closing day'],
    steps: ['Open report mid-day or pre-close', 'Kill app', 'Reopen', 'Verify report + Hub state'],
    expectedResult: 'Resume sonrası aynı bilgiler korunur.',
    evidenceRequired: ['screen_recording', 'manual_note'],
    passCriteria: ['Report state preserved', 'Hub consistent', 'No crash'],
    failCriteria: ['Lost report progress', 'Wrong day', 'Crash'],
    relatedSystems: ['daily_report', 'persist', 'offline_resume'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    linkedLegacyTestId: 'idt.day8_report_resume',
  }),
  tc({
    testCaseId: 'large_text_hub_map_report',
    title: 'Large text Hub / Map / Report',
    scopeId: 'ui_density',
    platform: 'both',
    preconditions: ['iPhone SE or small Android', 'System Large Text / Büyük Yazı enabled'],
    steps: [
      'Hub scroll + featured cards',
      'Map bottom panel',
      'DecisionResult screen',
      'End-of-day report scroll',
    ],
    expectedResult: 'No critical clipping; CTAs remain tappable.',
    evidenceRequired: ['screenshot'],
    passCriteria: ['Hub readable', 'Map panel usable', 'DecisionResult no overlap', 'Report scrollable'],
    failCriteria: ['CTA clipped', 'Unreadable overflow', 'Crash'],
    relatedSystems: ['ui_density', 'hub', 'map', 'daily_report'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    linkedLegacyTestId: 'idt.large_text_smoke',
    linkedBlockerIds: ['large_text_smoke'],
  }),
  tc({
    testCaseId: 'offline_no_network_launch',
    title: 'Offline / no-network launch',
    scopeId: 'build_readiness',
    platform: 'both',
    preconditions: ['Airplane mode or no network'],
    steps: ['Cold launch app', 'Navigate Hub + one event if possible'],
    expectedResult: 'App launches offline; no crash; graceful degradation.',
    evidenceRequired: ['manual_note', 'screenshot'],
    passCriteria: ['Launch without network', 'No crash', 'Clear offline behavior'],
    failCriteria: ['Crash on launch', 'Infinite spinner', 'Corrupt save'],
    relatedSystems: ['offline_resume', 'hub'],
    blocksInternalDeviceTest: true,
    blocksPublicLaunch: false,
    linkedLegacyTestId: 'idt.offline_launch',
  }),
  tc({
    testCaseId: 'sentry_dashboard_smoke_if_env_ready',
    title: 'Sentry dashboard smoke (if env ready)',
    scopeId: 'sentry_conditional',
    platform: 'both',
    preconditions: ['EXPO_PUBLIC_SENTRY_DSN set', 'EXPO_PUBLIC_CRASH_REPORTING_ENABLED=true', 'Internal build'],
    steps: [
      'Trigger DEV/internal crash test button',
      'Open Sentry dashboard',
      'Verify event environment, release, breadcrumb, safe context',
    ],
    expectedResult: 'Dashboard event visible; no PII/raw save/event body.',
    evidenceRequired: ['dashboard_event', 'screenshot', 'manual_note'],
    passCriteria: [
      'Event in dashboard',
      'No PII',
      'Screen breadcrumb',
      'Environment tag',
    ],
    failCriteria: ['No event', 'PII leaked', 'App crash unrelated'],
    relatedSystems: ['sentry', 'crash_performance'],
    blocksInternalDeviceTest: false,
    blocksPublicLaunch: true,
    linkedLegacyTestId: 'idt.sentry_dashboard_visible',
    linkedBlockerIds: ['sentry_dashboard_smoke_test'],
    conditionalOnEnvReady: true,
  }),
];

export const MANUAL_LAUNCH_ROUND_ONE_TEMPLATE: Omit<ManualLaunchTestRound, 'status' | 'highestPriorityMissing'> = {
  roundId: MANUAL_LAUNCH_ROUND_ONE_ID,
  title: 'Round 1 — Internal Device Playtest',
  purpose:
    'First real-device batch: EAS internal build, Day 1 first session, Day 8 pack-origin, resume, UI density, conditional Sentry.',
  includedTestCaseIds: [...MANUAL_LAUNCH_ROUND_ONE_TEST_CASE_IDS],
  requiredEvidenceIds: MANUAL_LAUNCH_ROUND_ONE_TEST_CASE_IDS.map((id) => `evidence.round1.${id}`),
  optionalEvidenceIds: ['evidence.round1.extra_notes'],
  platformCoverage: ['ios', 'android', 'both'],
  canPassWithoutEvidence: false,
  fakePassGuard: true,
};

export const MANUAL_LAUNCH_ROUND_ONE_PRIORITY_MISSING = [
  'evidence.round1.eas_internal_build_created',
  'evidence.round1.day1_first_session',
  'evidence.round1.day8_pack_origin_event_appears',
  'evidence.round1.day8_main_operation_feel',
  'evidence.round1.day7_to_day8_transition',
  'evidence.round1.large_text_hub_map_report',
  'evidence.round1.sentry_dashboard_smoke_if_env_ready',
] as const;

/** Docs-only example — no file created, tracker stays missing. */
export const MANUAL_LAUNCH_EVIDENCE_ATTACH_EXAMPLE = {
  evidenceId: 'ev_day8_pack_origin_ios_001',
  testCaseId: 'day8_pack_origin_event_appears',
  blockerId: 'day8_pack_origin_event_smoke',
  evidenceType: 'screenshot' as const,
  status: 'attached' as const,
  platform: 'ios' as const,
  deviceName: 'iPhone 15',
  osVersion: 'iOS 18.2',
  buildProfile: 'internal',
  appVersion: '1.0.0',
  buildNumber: '42',
  testDate: '2026-06-28',
  tester: 'QA — Ada',
  result: 'pass' as const,
  evidenceLocation: 'docs/evidence/ios/day8-pack-origin.png',
  evidenceSummary: 'Day 8 pack-origin event visible with player-facing chip.',
  notes: 'Full checklist: docs/crevia-real-device-qa-evidence-round-1.md',
  fakePassGuard: true as const,
};
