import { EXPECTED_SAVE_VERSION_FOR_VERIFY } from '@/core/quality/saveVersionPolicy';
import type {
  SoftLaunchCompletionModuleRegistration,
  SoftLaunchManualBlocker,
} from './softLaunchRegressionCleanupTypes';

export const SOFT_LAUNCH_REGRESSION_CLEANUP_DOCS_PATH =
  'docs/crevia-soft-launch-regression-cleanup.md';

export const SOFT_LAUNCH_REGRESSION_CLEANUP_EXPECTED_SAVE_VERSION = EXPECTED_SAVE_VERSION_FOR_VERIFY;

export const SOFT_LAUNCH_MANUAL_BLOCKERS: readonly SoftLaunchManualBlocker[] = [
  {
    id: 'manual.revenuecat_public_keys',
    title: 'RevenueCat public keys',
    category: 'iap',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'manual',
    verificationCommand: 'npm run verify:iap-sandbox-readiness',
    nextAction: 'Set EXPO_PUBLIC_REVENUECAT_IOS/ANDROID in EAS secrets.',
  },
  {
    id: 'manual.app_store_product',
    title: 'App Store product',
    category: 'iap',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'manual',
    verificationCommand: 'npm run verify:iap-manual-setup-tracker',
    nextAction: 'Create App Store Connect IAP product.',
  },
  {
    id: 'manual.play_console_product',
    title: 'Play Console product',
    category: 'iap',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'manual',
    verificationCommand: 'npm run verify:iap-manual-setup-tracker',
    nextAction: 'Create Play Console IAP product.',
  },
  {
    id: 'manual.iap_sandbox_purchase',
    title: 'IAP sandbox purchase',
    category: 'iap',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: true,
    owner: 'manual',
    verificationCommand: 'npm run verify:iap-sandbox-smoke-execution',
    nextAction: 'Run sandbox purchase on internal EAS build.',
  },
  {
    id: 'manual.iap_restore_test',
    title: 'IAP restore test',
    category: 'iap',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: true,
    owner: 'manual',
    verificationCommand: 'npm run verify:iap-sandbox-smoke-execution',
    nextAction: 'Verify restore flow on device.',
  },
  {
    id: 'manual.store_screenshots',
    title: 'Store screenshots',
    category: 'store',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'manual',
    verificationCommand: 'npm run verify:store-screenshot-readiness',
    nextAction: 'Capture and upload store screenshots.',
  },
  {
    id: 'manual.store_metadata',
    title: 'Store metadata',
    category: 'metadata',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'manual',
    verificationCommand: 'npm run verify:store-metadata-finalization',
    nextAction: 'Complete App Store / Play listing metadata.',
  },
  {
    id: 'manual.privacy_policy_url',
    title: 'Privacy policy URL',
    category: 'privacy',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'manual',
    verificationCommand: 'npm run verify:privacy-policy-readiness',
    nextAction: 'Publish hosted privacy policy URL (placeholder is BLOCKED).',
  },
  {
    id: 'manual.privacy_data_safety_review',
    title: 'Privacy / data safety final review',
    category: 'privacy',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'manual',
    verificationCommand: 'npm run verify:privacy-policy-readiness',
    nextAction: 'Legal review of privacy + data safety drafts.',
  },
  {
    id: 'manual.sentry_dsn_env',
    title: 'Sentry DSN / env',
    category: 'crash',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'manual',
    verificationCommand: 'npm run verify:crash-performance',
    nextAction: 'Set EXPO_PUBLIC_SENTRY_DSN + EXPO_PUBLIC_CRASH_REPORTING_ENABLED.',
  },
  {
    id: 'manual.sentry_dashboard_smoke',
    title: 'Sentry dashboard smoke',
    category: 'crash',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: true,
    owner: 'dashboard',
    verificationCommand: 'npm run verify:crash-performance',
    nextAction: 'Trigger dev crash on internal build; confirm Sentry issue.',
  },
  {
    id: 'manual.sentry_source_maps',
    title: 'Sentry source maps',
    category: 'crash',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'manual',
    verificationCommand: 'npm run verify:crash-performance',
    nextAction: 'Configure SENTRY_AUTH_TOKEN + EAS secrets for source maps.',
  },
  {
    id: 'manual.analytics_sdk_dashboard',
    title: 'Analytics SDK / dashboard wiring',
    category: 'analytics',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: false,
    owner: 'dashboard',
    verificationCommand: 'npm run verify:analytics-runtime',
    nextAction: 'Connect production analytics SDK + dashboard after schema review.',
  },
  {
    id: 'manual.real_device_playtest',
    title: 'Real device playtest',
    category: 'device_test',
    status: 'pending',
    blocksPublicLaunch: true,
    blocksInternalDeviceTest: true,
    owner: 'manual',
    verificationCommand: 'npm run verify:real-device-playtest',
    nextAction: 'Complete playtest checklist on physical device.',
  },
  {
    id: 'manual.performance_device_smoke',
    title: 'Performance device smoke',
    category: 'device_test',
    status: 'pending',
    blocksPublicLaunch: false,
    blocksInternalDeviceTest: true,
    owner: 'manual',
    verificationCommand: 'npm run verify:performance-selectors',
    nextAction: 'Low-end device scroll/jank smoke on Hub/Map.',
  },
] as const;

export const SOFT_LAUNCH_COMPLETION_MODULE_REGISTRY: readonly SoftLaunchCompletionModuleRegistration[] =
  [
    {
      id: 'crashPerformance',
      coreDir: 'src/core/crashPerformance',
      kind: 'observability',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'Sentry-first crash/performance observability; no-op without DSN.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'uiDensity',
      coreDir: 'src/core/uiDensity',
      kind: 'audit',
      freezeRisk: 'none',
      allowedBeforeSoftLaunch: true,
      reason: 'UI density + accessibility audit pass.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'offlineResume',
      coreDir: 'src/core/offlineResume',
      kind: 'audit',
      freezeRisk: 'none',
      allowedBeforeSoftLaunch: true,
      reason: 'Offline/resume robustness audit.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'mapReactions',
      coreDir: 'src/core/mapReactions',
      kind: 'runtime_lite',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'Dynamic map reaction lite presentation.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'operationalResourcePresence',
      coreDir: 'src/core/operationalResourcePresence',
      kind: 'presentation',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'Operational resource presence lite.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'cityJournal',
      coreDir: 'src/core/cityJournal',
      kind: 'presentation',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'Şehir günlüğü lite.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'cityArchive',
      coreDir: 'src/core/cityArchive',
      kind: 'runtime_lite',
      freezeRisk: 'medium',
      allowedBeforeSoftLaunch: true,
      reason: 'City archive persistence V1 — SAVE_VERSION 24 migration.',
      saveVersionImpact: true,
      persistImpact: true,
      gameplayImpact: false,
    },
    {
      id: 'districtReportCard',
      coreDir: 'src/core/districtReportCard',
      kind: 'presentation',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'Mahalle karnesi lite.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'contentRuntimeActivation',
      coreDir: 'src/core/contentRuntimeActivation',
      kind: 'runtime_lite',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'Content pack runtime activation lite.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'mainOperationFeel',
      coreDir: 'src/core/mainOperationFeel',
      kind: 'presentation',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'Day 8+ main operation feel.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'cityEchoBinding',
      coreDir: 'src/core/cityEchoBinding',
      kind: 'presentation',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'City echo binding presentation.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'tomorrowRisk',
      coreDir: 'src/core/tomorrowRisk',
      kind: 'presentation',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'Tomorrow risk strip.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
    {
      id: 'decisionImpactExplanation',
      coreDir: 'src/core/decisionImpactExplanation',
      kind: 'presentation',
      freezeRisk: 'low',
      allowedBeforeSoftLaunch: true,
      reason: 'Decision impact explanation.',
      saveVersionImpact: false,
      persistImpact: false,
      gameplayImpact: false,
    },
  ] as const;

export const STALE_EXPECTATION_FIXES = [
  'analytics-schema-decoupled-from-selector-perf',
  'iap-analytics-decoupled-from-selector-perf',
  'telemetry-nested-soft-launch-review-removed',
  'freeze-unregistered-completion-modules',
  'privacy-sentry-processor-listed',
] as const;
