import type {
  StoreScreenshotNarrativeCaptionGuideline,
  StoreScreenshotNarrativeCaptureScenario,
  StoreScreenshotNarrativeDeviceMatrixEntry,
  StoreScreenshotNarrativeItem,
} from './storeScreenshotNarrativeTypes';

export const STORE_SCREENSHOT_NARRATIVE_PACK_ID = 'crevia_store_screenshot_narrative_v1';

export const STORE_SCREENSHOT_NARRATIVE_DOCS_PATH = 'docs/crevia-store-screenshot-narrative-pack.md';

export const STORE_SCREENSHOT_NARRATIVE_MIN_COUNT = 8;

export const STORE_SCREENSHOT_NARRATIVE_FORBIDDEN_PHRASES = [
  'gerçek zamanlı gps',
  'canlı şehir',
  'yapay zeka ile yönet',
  'online oyuncular',
  'gerçek belediye verisi',
  'sınırsız operasyon',
  'kazanmak için satın al',
  'premium kilidi aç',
  'krizi durdur yoksa kaybedersin',
  'resmi belediye uygulaması',
  'real-time gps',
  'live city',
  'ai powered',
  'online players',
  'real municipality data',
  'unlimited operation',
  'buy to win',
  'unlock premium',
  'official municipality app',
  'free forever',
  'guaranteed result',
  'multiplayer',
  'satın al',
  'premium',
  'kilitli',
] as const;

export const STORE_SCREENSHOT_NARRATIVE_CAPTION_GUIDELINES: StoreScreenshotNarrativeCaptionGuideline[] = [
  { id: 'headline_length', rule: 'Headline 3–6 words; store-readable at large font.' },
  { id: 'subtitle_length', rule: 'Max one short subtitle line under headline.' },
  { id: 'no_jargon', rule: 'No technical jargon (pack, runtime, metadata).' },
  { id: 'no_paywall', rule: 'No premium / satın al / kilitli in overlay copy.' },
  { id: 'no_fomo', rule: 'No panic, FOMO, or disaster language.' },
  { id: 'municipal_tone', rule: 'Civic operations feel — not boring government dashboard.' },
  { id: 'player_ownership', rule: 'Emphasize player decisions and neighborhood impact.' },
  { id: 'tr_en_length', rule: 'Check TR and EN headline length on small phones.' },
];

export const STORE_SCREENSHOT_NARRATIVE_DEVICE_MATRIX: StoreScreenshotNarrativeDeviceMatrixEntry[] = [
  {
    id: 'ios_6_7',
    platform: 'ios',
    label: 'iPhone 6.7" (15/16 Pro Max class)',
    storeSizeNotes: 'App Store primary phone set — 1290×2796 or current ASC requirement.',
    safeAreaNotes: 'Respect notch + bottom tab bar; headline in top safe band.',
    trCopyLengthNote: 'TR headlines ≤28 chars recommended on 6.7".',
    enCopyLengthNote: 'EN headlines ≤32 chars recommended on 6.7".',
    cropRisk: 'Low — primary capture target.',
  },
  {
    id: 'ios_6_5',
    platform: 'ios',
    label: 'iPhone 6.5" legacy set',
    storeSizeNotes: 'Confirm if still required in App Store Connect for your listing.',
    safeAreaNotes: 'Same UI crop as 6.7"; verify subtitle wrap.',
    trCopyLengthNote: 'TR subtitles may wrap — test 2 lines max.',
    enCopyLengthNote: 'EN shorter words often fit better.',
    cropRisk: 'Medium — subtitle overflow.',
  },
  {
    id: 'ios_5_5_note',
    platform: 'ios',
    label: 'iPhone 5.5" (optional legacy)',
    storeSizeNotes: 'Only if ASC still mandates; otherwise backlog.',
    safeAreaNotes: 'Compact Hub — verify featured cards not clipped.',
    trCopyLengthNote: 'Prefer shorter TR headlines.',
    enCopyLengthNote: 'Prefer shorter EN headlines.',
    cropRisk: 'High — Hub density.',
  },
  {
    id: 'android_phone',
    platform: 'android',
    label: 'Android phone portrait',
    storeSizeNotes: 'Play Console phone screenshots — min 1080px short side.',
    safeAreaNotes: 'Gesture nav inset + tab bar; headline above fold.',
    trCopyLengthNote: 'TR diacritics — verify font weight at export.',
    enCopyLengthNote: 'EN baseline for Play listing.',
    cropRisk: 'Medium — bottom panel overlap.',
  },
  {
    id: 'android_tablet_backlog',
    platform: 'android',
    label: 'Android tablet (V1.1 backlog)',
    storeSizeNotes: 'Optional — not required for soft launch.',
    safeAreaNotes: 'N/A this phase.',
    trCopyLengthNote: 'Backlog.',
    enCopyLengthNote: 'Backlog.',
    cropRisk: 'N/A',
  },
];

export const STORE_SCREENSHOT_NARRATIVE_CAPTURE_SCENARIOS: StoreScreenshotNarrativeCaptureScenario[] = [
  {
    id: 'state_day1',
    title: 'Day 1 — tutorial sade',
    targetDayRange: 'Day 1',
    description:
      'Fresh save; Hub sade; first event flow; Decision Impact compact; report compact. No crisis/post-pilot cards.',
    screenshotIds: ['ssn_hub_operations', 'ssn_decision_plan', 'ssn_decision_impact'],
    devToolsPresetNote: 'Use fresh install or cleared save; HubDevTools hidden in production capture.',
  },
  {
    id: 'state_day5',
    title: 'Day 5 — pilot derinleşmiş',
    targetDayRange: 'Day 4–7',
    description:
      'Trust/social signals visible; Social Pulse active; Ece more contextual; map district selection.',
    screenshotIds: ['ssn_map_neighborhood', 'ssn_social_pulse', 'ssn_end_of_day_report'],
    devToolsPresetNote: 'Play through Day 5 or use existing pilot save — no fake runtime seed.',
  },
  {
    id: 'state_day8',
    title: 'Day 8+ — ana operasyon',
    targetDayRange: 'Day 8+',
    description:
      'Main Operation Feel; pack-origin event; Mahalle Karnesi; Map Reaction; resources; City Journal; Tomorrow Risk.',
    screenshotIds: [
      'ssn_main_operation',
      'ssn_map_neighborhood',
      'ssn_end_of_day_report',
      'ssn_operational_resources',
      'ssn_city_journal',
    ],
    devToolsPresetNote: 'Complete Day 7 pilot or internal Day 8 test seed on device only — do not persist fake data.',
  },
  {
    id: 'state_profile',
    title: 'Profile — authority & career',
    targetDayRange: 'Day 4+',
    description: 'Authority card, badges, career showcase; no fake achievements.',
    screenshotIds: ['ssn_profile_career'],
    devToolsPresetNote: 'Use natural progression save; no fabricated badge unlock.',
  },
];

function item(
  partial: Omit<StoreScreenshotNarrativeItem, 'captureStatus' | 'blocksStoreSubmission'> & {
    optional?: boolean;
  },
): Omit<StoreScreenshotNarrativeItem, 'captureStatus'> {
  return {
    ...partial,
    blocksStoreSubmission: !partial.optional,
  };
}

export const STORE_SCREENSHOT_NARRATIVE_ITEMS_TEMPLATE: Omit<
  StoreScreenshotNarrativeItem,
  'captureStatus'
>[] = [
  item({
    id: 'ssn_hub_operations',
    order: 1,
    screenKey: 'hub_operations_desk',
    titleTR: 'Şehri Bugün Sen Yönet',
    titleEN: "Run Today's City Operations",
    subtitleTR: 'Operasyon masasından günlük kararları planla.',
    subtitleEN: 'Plan daily decisions from your operations desk.',
    playerPromise: 'Belediye operasyon simülasyonu — merkezden yönetim hissi.',
    screenshotGoal: 'Hub with Ece, Tomorrow Risk, resources, journal — compact, polished.',
    requiredGameState: 'state_day1 or state_day5 — Hub visible; Day 1 sade or Day 5+ normal.',
    requiredSurface: 'HubReferenceHome / HubScreen',
    captureNotes: 'Capture after plan confirm; hide devtools; max 2 featured cards on Day 1.',
    safeAreaNotes: 'Header gradient + tab bar; headline overlay in top safe band.',
    forbiddenElements: ['devtools_panel', 'crisis_overload', 'placeholder_iap_price'],
    storeComplianceNotes: 'No official municipality branding.',
    evidenceRequired: ['screenshot', 'store_console'],
  }),
  item({
    id: 'ssn_decision_plan',
    order: 2,
    screenKey: 'event_decision_plan',
    titleTR: 'Karar Ver, Etkisini Gör',
    titleEN: 'Make Decisions That Matter',
    subtitleTR: 'Her karar kısa vadeli etki ve yarına risk taşır.',
    subtitleEN: 'Every choice carries impact and tomorrow risk.',
    playerPromise: 'Tradeoff and planning — not random outcomes.',
    screenshotGoal: 'Event inspect/plan with clear CTA and readable options.',
    requiredGameState: 'state_day1 — first event plan flow.',
    requiredSurface: 'Event detail workflow — Planla phase',
    captureNotes: 'No text overflow; decision options fully visible.',
    safeAreaNotes: 'Bottom CTA above gesture area.',
    forbiddenElements: ['gps_claim', 'paywall_overlay'],
    storeComplianceNotes: 'No guaranteed outcome language.',
    evidenceRequired: ['screenshot'],
  }),
  item({
    id: 'ssn_decision_impact',
    order: 3,
    screenKey: 'decision_impact_result',
    titleTR: 'Neden Böyle Oldu?',
    titleEN: 'See Why It Happened',
    subtitleTR: 'Crevia kararını açıklar; rastgele sonuç vermez.',
    subtitleEN: 'Crevia explains your decision — not random results.',
    playerPromise: 'Decision Impact Explanation visibility.',
    screenshotGoal: 'Result screen with impact card and systems echo.',
    requiredGameState: 'state_day1 or state_day5 — after first meaningful decision.',
    requiredSurface: 'DecisionResultScreen / EventResultImpactExplanationCard',
    captureNotes: 'Show impact lines; avoid duplicate echo spam.',
    safeAreaNotes: 'Impact card within maxVisibleLines guard.',
    forbiddenElements: ['raw_save_dump', 'technical_pack_id'],
    storeComplianceNotes: 'No false precision claims.',
    evidenceRequired: ['screenshot'],
  }),
  item({
    id: 'ssn_map_neighborhood',
    order: 4,
    screenKey: 'map_neighborhood_reactions',
    titleTR: 'Mahalleler Tepki Verir',
    titleEN: 'Neighborhoods React',
    subtitleTR: 'Haritada seçili mahalle ve tepki izleri.',
    subtitleEN: 'Selected districts and reactions on the map.',
    playerPromise: 'Map Reaction + Mahalle Karnesi + district selection.',
    screenshotGoal: 'Map with reaction hint, district report card, bottom panel.',
    requiredGameState: 'state_day5 or state_day8 — district selected.',
    requiredSurface: 'MapScreen / MapOperationBottomPanel',
    captureNotes: 'Max 4 reactions Day 8+; no GPS/live tracking UI.',
    safeAreaNotes: 'Bottom panel scroll; neighborhood strip visible.',
    forbiddenElements: ['live_gps', 'real_map_data_badge'],
    storeComplianceNotes: 'Simulation map — not real city data.',
    evidenceRequired: ['screenshot'],
  }),
  item({
    id: 'ssn_social_pulse',
    order: 5,
    screenKey: 'social_pulse',
    titleTR: 'Sosyal Nabzı Oku',
    titleEN: "Read the City's Pulse",
    subtitleTR: 'Halk sahadaki değişimi fark eder.',
    subtitleEN: 'Citizens notice changes in the field.',
    playerPromise: 'Social Pulse mentions and city echo.',
    screenshotGoal: 'Social screen with mentions; Day 5+ context.',
    requiredGameState: 'state_day5 — social pulse active.',
    requiredSurface: 'Social index / mentions',
    captureNotes: 'Mention cap respected; no overflow on large text test device.',
    safeAreaNotes: 'Mention cards 2-line body guard.',
    forbiddenElements: ['online_multiplayer', 'real_names'],
    storeComplianceNotes: 'Fictional civic social layer only.',
    evidenceRequired: ['screenshot'],
  }),
  item({
    id: 'ssn_end_of_day_report',
    order: 6,
    screenKey: 'end_of_day_report',
    titleTR: 'Günün Etkisini Gör',
    titleEN: "Review the Day's Impact",
    subtitleTR: 'Rapor, yarın riski ve şehir günlüğü bir arada.',
    subtitleEN: 'Report, tomorrow risk, and city journal together.',
    playerPromise: 'End-of-day synthesis — not a spreadsheet.',
    screenshotGoal: 'Report hero + journal line + mahalle note + resource line.',
    requiredGameState: 'state_day5 or state_day8 — post-decision report.',
    requiredSurface: 'EndOfDayReportView',
    captureNotes: 'Capture top fold; secondary lines compact on Day 8+.',
    safeAreaNotes: 'Scroll start clean; CTA visible at end if possible.',
    forbiddenElements: ['season_final_wording', 'game_over'],
    storeComplianceNotes: 'Open-ended career — no game over claim.',
    evidenceRequired: ['screenshot'],
  }),
  item({
    id: 'ssn_main_operation',
    order: 7,
    screenKey: 'main_operation_day8',
    titleTR: 'Ana Operasyon Başladı',
    titleEN: 'The Main Operation Begins',
    subtitleTR: 'Pilot biter; şehir kapsamı büyür.',
    subtitleEN: 'After the pilot, the city scope expands.',
    playerPromise: 'Day 8+ Main Operation Feel — not season finale.',
    screenshotGoal: 'HubMainOperationFeelCard + season compact line if visible.',
    requiredGameState: 'state_day8 — post-pilot main operation.',
    requiredSurface: 'HubMainOperationFeelCard',
    captureNotes: 'No technical pack name in UI; player-facing chip only.',
    safeAreaNotes: 'Feel card above Tomorrow Risk strip.',
    forbiddenElements: ['paywall_pressure', 'placeholder_price'],
    storeComplianceNotes: 'IAP screen optional — not in required 8.',
    evidenceRequired: ['screenshot'],
  }),
  item({
    id: 'ssn_profile_career',
    order: 8,
    screenKey: 'profile_career',
    titleTR: 'Kariyerini Büyüt',
    titleEN: 'Grow Your Civic Career',
    subtitleTR: 'Yetki, rozetler ve operatör kimliği.',
    subtitleEN: 'Authority, badges, and operator identity.',
    playerPromise: 'Long-term career and authority progression.',
    screenshotGoal: 'Profile authority + badge showcase.',
    requiredGameState: 'state_profile — Day 4+ natural progression.',
    requiredSurface: 'ProfileScreen',
    captureNotes: 'No fake achievement badges; real progression only.',
    safeAreaNotes: 'Badge grid readable on small phone.',
    forbiddenElements: ['fake_badge', 'certification_claim'],
    storeComplianceNotes: 'In-game progression only.',
    evidenceRequired: ['screenshot'],
  }),
  item({
    id: 'ssn_operational_resources',
    order: 9,
    screenKey: 'operational_resources',
    titleTR: 'Ekip ve Araçları Dengele',
    titleEN: 'Balance Teams and Vehicles',
    subtitleTR: 'Saha kaynakları operasyonu taşır.',
    subtitleEN: 'Field resources carry the operation.',
    playerPromise: 'Presence-lite resources — not roster micromanagement.',
    screenshotGoal: 'Operational resources card or detail sheet teams tab.',
    requiredGameState: 'state_day8 — resources visible.',
    requiredSurface: 'HubOperationalResourcesCard / OperationalResourcesDetailSheet',
    captureNotes: 'No individual staff names or plates.',
    safeAreaNotes: 'Sheet tabs accessible; 2-line presence cards.',
    forbiddenElements: ['gps_plate', 'named_roster'],
    storeComplianceNotes: 'Abstract team/vehicle groups only.',
    evidenceRequired: ['screenshot'],
    optional: true,
  }),
  item({
    id: 'ssn_city_journal',
    order: 10,
    screenKey: 'city_journal_memory',
    titleTR: 'Şehrin Bir Hafızası Var',
    titleEN: 'The City Remembers',
    subtitleTR: 'Şehir günlüğü kararlarını hatırlar.',
    subtitleEN: 'The city journal remembers your decisions.',
    playerPromise: 'City memory and journal strip.',
    screenshotGoal: 'HubCityJournalStrip or report journal line.',
    requiredGameState: 'state_day8 — journal entries present.',
    requiredSurface: 'HubCityJournalStrip / report journal row',
    captureNotes: 'Max 5 journal entries; Hub max 2 surfacing.',
    safeAreaNotes: 'Compact strip on Hub.',
    forbiddenElements: ['full_archive_ui', 'technical_ids'],
    storeComplianceNotes: 'Lite journal — not full archive product.',
    evidenceRequired: ['screenshot'],
    optional: true,
  }),
];

export const STORE_SCREENSHOT_NARRATIVE_VISUAL_DIRECTION = {
  theme: 'premium light — cream background, teal/mint accent, dark teal CTA',
  overlay: 'Short headline top, single subtitle, device frame center, soft cream/mint gradient',
  avoid: 'Dashboard clutter, excessive chips, government portal aesthetic',
} as const;
