import type {
  SoftLaunchCoreAuditArea,
  SoftLaunchCorePreLaunchPass,
} from './softLaunchCoreCompletenessTypes';

export const SOFT_LAUNCH_CORE_DOCS_PATH =
  'docs/crevia-soft-launch-core-completeness.md';

export const SOFT_LAUNCH_CORE_REQUIRED_AREA_IDS = [
  'first_10_minutes',
  'pilot_loop_day_1_7',
  'day_8_main_operation_feel',
  'decision_impact_chain',
  'tomorrow_risk_one_more_day',
  'ece_social_report_echo_binding',
  'city_memory_archive_lite',
  'district_report_card_lite',
  'content_variety_visibility',
  'map_as_living_city',
  'player_style_recognition',
  'weekly_bulletin_season_summary',
  'offline_resume_continuity',
  'performance_selector_ui_density',
  'monetization_iap_store_blockers',
] as const;

export const SOFT_LAUNCH_CORE_NON_GOALS = [
  'No new gameplay engine.',
  'No new monetization system.',
  'No real AI advisor integration.',
  'No Remote Config runtime.',
  'No Live-Ops system.',
  'No Story Chain Persistent Runtime.',
  'No District Operation Actions Persistence.',
  'No Container Network Runtime.',
  'No Vehicle Maintenance Runtime.',
  'No Team Specialization Runtime.',
  'No Seasonal Challenge System.',
  'No SAVE_VERSION increase.',
  'No persist schema change.',
  'No navigation route addition.',
  'No large UI redesign.',
  'No event generation rewrite.',
  'No dayPipeline or applyDecision core logic change.',
] as const;

export const SOFT_LAUNCH_CORE_LAUNCH_BLOCKERS = [
  'RevenueCat public keys missing.',
  'App Store product missing.',
  'Play Console product missing.',
  'IAP sandbox purchase test not completed.',
  'IAP restore test not completed.',
  'Real device playtest not completed.',
  'Privacy URL placeholder.',
  'Screenshots pending.',
  'Metadata console entry pending.',
] as const;

export const SOFT_LAUNCH_CORE_BASE_PRELAUNCH_PASSES = [
  {
    name: 'Decision Impact Explanation Pass',
    priority: 'must',
    reason: 'Decision result currently needs stronger cause/effect readability across result, report, and next-day surfaces.',
    suggestedPromptName: 'Decision Impact Explanation Pass',
  },
  {
    name: 'Tomorrow Risk Card + One More Day CTA Pass',
    priority: 'must',
    reason: 'Retention motivation needs a clearer tomorrow risk promise without FOMO language.',
    suggestedPromptName: 'Tomorrow Risk Card and One More Day CTA Pass',
  },
  {
    name: 'Ece / Social / Report Echo Binding Pass',
    priority: 'must',
    reason: 'The same event should echo consistently through advisor, social pulse, and report surfaces.',
    suggestedPromptName: 'Ece Social Report Echo Binding Pass',
  },
  {
    name: 'Day 8+ Main Operation Feel Pass',
    priority: 'must',
    reason: 'Post-pilot light/full framing must feel like a started main operation, not just continuation copy.',
    suggestedPromptName: 'Day 8 Main Operation Feel Pass',
  },
  {
    name: 'Content Pack Runtime Activation Lite',
    priority: 'must',
    reason: 'Authored content packs need visible safe activation without breaking event caps or duplicate guards.',
    suggestedPromptName: 'Content Pack Runtime Activation Lite',
  },
  {
    name: 'Offline / Resume Robustness Pass',
    priority: 'should',
    reason: 'Critical resume states need a targeted manual and automated pass before public soft launch.',
    suggestedPromptName: 'Offline Resume Robustness Pass',
  },
  {
    name: 'Crash / Performance SDK Integration',
    priority: 'should',
    reason: 'Telemetry and crash visibility are required before broad external traffic.',
    suggestedPromptName: 'Release Candidate Audit',
  },
  {
    name: 'Localization EN/TR Polish',
    priority: 'should',
    reason: 'Player-facing copy needs final Turkish/English polish and large text review.',
    suggestedPromptName: 'Accessibility / Large Text Pass',
  },
  {
    name: 'Accessibility / Large Text Pass',
    priority: 'should',
    reason: 'Dense Hub/Report/Event cards need final accessibility and large text checks.',
    suggestedPromptName: 'Accessibility / Large Text Pass',
  },
  {
    name: 'Mahalle Karnesi Lite Review',
    priority: 'optional',
    reason: 'District meaning can improve retention, but full history is not required for the first soft-launch candidate.',
    suggestedPromptName: 'Mahalle Karnesi Lite Review',
  },
  {
    name: 'Dynamic Map Reaction Lite Review',
    priority: 'optional',
    reason: 'Map reactions can improve city feel after the must-pass feedback surfaces are closed.',
    suggestedPromptName: 'Dynamic Map Reaction Lite Review',
  },
  {
    name: 'Release Candidate Audit',
    priority: 'must',
    reason: 'Launch candidate must stay blocked until IAP/store/manual blockers are closed.',
    suggestedPromptName: 'Release Candidate Audit',
  },
] as const satisfies readonly SoftLaunchCorePreLaunchPass[];

export const SOFT_LAUNCH_CORE_DEFERRED_V11_SYSTEMS = [
  'Mahalle Karnesi Lite expansion: last 3 events, player style, citizen tone.',
  'Şehir Günlüğü Lite if soft-launch telemetry shows memory demand.',
  'Style badges for fast responder, social trust, resource saver, route balancer.',
  'Deterministic weekly municipality bulletin.',
  'Dynamic map reaction lite polish after completion pass.',
] as const;

export const SOFT_LAUNCH_CORE_DEFERRED_V2_SYSTEMS = [
  'AI-supported weekly bulletin.',
  'Full living map layers: vehicle route drawing, container fill animation, full reaction layer.',
  'Persistent story chain runtime.',
  'Container Network Runtime.',
  'Vehicle Maintenance Runtime.',
  'Team Specialization Runtime.',
  'Seasonal Challenge System.',
] as const;

export const SOFT_LAUNCH_CORE_AUDIT_AREAS: SoftLaunchCoreAuditArea[] = [
  {
    id: 'first_10_minutes',
    title: 'First 10 Minutes Completeness',
    category: 'first_session',
    status: 'PASS',
    severity: 'low',
    summary: 'Day 1 progressive reveal and the Hub to report chain are structurally understandable.',
    evidence: [
      'verify:first-10-minutes already covers Day 1 progressive reveal.',
      'Existing flow guards keep advanced systems hidden early.',
      'Ece/advisor onboarding is present, but still needs real-device comprehension validation.',
    ],
    playerRisk: 'Low automated risk, medium manual comprehension risk until real-device first-session notes exist.',
    recommendedAction: 'Run real-device first 10 minutes playtest and keep Day 1 surfaces compact.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: false,
    relatedSystems: ['firstTenMinutesPresentation', 'Hub', 'Event flow', 'Daily report', 'Ece'],
    suggestedPromptName: 'First 10 Minutes Device Playtest Review',
  },
  {
    id: 'pilot_loop_day_1_7',
    title: 'Day 1-7 Pilot Loop Completeness',
    category: 'pilot_loop',
    status: 'PASS',
    severity: 'low',
    summary: 'The seven-day pilot loop has simulation coverage and a Day 7 transition path.',
    evidence: [
      'verify:full-loop covers seven-day scenarios and pilot completion.',
      'Decision result, report, and Hub return are wired in the existing UX flow.',
      'Authority/badge/progression systems are present but should stay low-density in early days.',
    ],
    playerRisk: 'The loop is technically complete; risk is presentation overload rather than missing runtime.',
    recommendedAction: 'Keep pilot days differentiated through copy, report emphasis, and visible consequences.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: false,
    relatedSystems: ['pilot loop', 'daily report', 'authority', 'badges', 'full-loop simulation'],
    suggestedPromptName: 'Pilot Day 1-7 Differentiation Polish',
  },
  {
    id: 'day_8_main_operation_feel',
    title: 'Day 8+ Main Operation Feel',
    category: 'main_operation',
    status: 'WARN',
    severity: 'high',
    summary: 'Main operation foundations exist, but Day 8+ can still feel preview/light unless Hub, Map, and Report reinforce it together.',
    evidence: [
      'Post-pilot light main operation and full foundation exist.',
      'Operation era/runtime preview and post-pilot systems are partly preview/review-oriented.',
      'Player-facing distinction between light and full main operation needs stronger surface consistency.',
    ],
    playerRisk: 'Player may feel the game empties out after the pilot or repeats familiar cards.',
    recommendedAction: 'Add a Day 8 Main Operation Feel Pass focused on Hub/Map/Report framing only.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: true,
    relatedSystems: ['postPilotOperation', 'Hub open-ended card', 'Map', 'Report systems integration'],
    suggestedPromptName: 'Day 8 Main Operation Feel Pass',
  },
  {
    id: 'decision_impact_chain',
    title: 'Decision Impact Chain',
    category: 'decision_impact',
    status: 'WARN',
    severity: 'high',
    summary: 'Decision effects are technically wired, but cause/effect and tradeoff explanation need a focused player-facing pass.',
    evidence: [
      'applyDecision and result systems exist and full UX verifies no regression.',
      'Event result systems echo model exists.',
      'Tradeoff language needs to follow decisions into result, Hub, Map, and report more explicitly.',
    ],
    playerRisk: 'Player may interpret outcomes as score changes instead of systemic city reaction.',
    recommendedAction: 'Implement Decision Impact Explanation Pass without changing applyDecision or dayPipeline.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: true,
    relatedSystems: ['Decision result', 'event result systems echo', 'daily report', 'carry-over memory'],
    suggestedPromptName: 'Decision Impact Explanation Pass',
  },
  {
    id: 'tomorrow_risk_one_more_day',
    title: 'Tomorrow Risk / One More Day Motivation',
    category: 'retention',
    status: 'WARN',
    severity: 'medium',
    summary: 'Tomorrow preview and carry-over systems exist, but the report-ending retention promise needs stronger visibility.',
    evidence: [
      'report tomorrow preview and carry-over memory systems exist.',
      'Daily report can imply tomorrow risk.',
      'Need a clearer non-FOMO “city prepares for tomorrow” tone and CTA.',
    ],
    playerRisk: 'End-of-day may not create enough “one more day” motivation.',
    recommendedAction: 'Add Tomorrow Risk Card + One More Day CTA Pass in report/end-of-day surfaces.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: true,
    relatedSystems: ['reportTomorrowPreview', 'carryOverMemory', 'daily report'],
    suggestedPromptName: 'Tomorrow Risk Card and One More Day CTA Pass',
  },
  {
    id: 'ece_social_report_echo_binding',
    title: 'Ece / Social Pulse / Report Echo Binding',
    category: 'echo_binding',
    status: 'WARN',
    severity: 'high',
    summary: 'Echo templates and surfaces exist, but a single player decision should read as one coherent story across Ece, Social Pulse, and Report.',
    evidence: [
      'Event echo templates and social pulse systems exist.',
      'Advisor presentation can reference operation signals.',
      'Need deterministic echo binding review to avoid generic or duplicate-feeling text.',
    ],
    playerRisk: 'Ece may feel generic and Social/Report may feel disconnected from the player decision.',
    recommendedAction: 'Implement Ece Social Report Echo Binding Pass using existing deterministic echo data.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: true,
    relatedSystems: ['Ece/advisor', 'Social Pulse', 'event echo templates', 'report systems integration'],
    suggestedPromptName: 'Ece Social Report Echo Binding Pass',
  },
  {
    id: 'city_memory_archive_lite',
    title: 'City Memory / Operation Archive Lite Readiness',
    category: 'city_memory',
    status: 'WARN',
    severity: 'medium',
    summary: 'A city diary lite can be derived from current reports, carry-over, district memory, and story hints without new persistence, but it is not mandatory for the first completion pass.',
    evidence: [
      'dailyReport and carryOverMemory exist.',
      'districtMemory runtime exists.',
      'story chain presentation/runtime hints exist but persistent runtime is intentionally not open.',
    ],
    playerRisk: 'Past decisions may not feel archived unless reports/carry-over do enough work.',
    recommendedAction: 'Review Şehir Günlüğü Lite as V1.1 or optional post-soft-launch unless playtests show memory confusion.',
    recommendedTiming: 'v1_1',
    isImplementationRequiredBeforeSoftLaunch: false,
    relatedSystems: ['dailyReport', 'carryOverMemory', 'districtMemoryRuntime', 'storyChainRuntimeHints'],
    suggestedPromptName: 'Şehir Günlüğü Lite Review',
  },
  {
    id: 'district_report_card_lite',
    title: 'District Report Card / Mahalle Karnesi Lite Readiness',
    category: 'district_meaning',
    status: 'WARN',
    severity: 'medium',
    summary: 'Current district trust, memory, operations, and map intelligence are enough for a lite mahalle card, but full history can wait.',
    evidence: [
      'districtTrustRuntime, districtMemoryRuntime, districtOperationsRuntime exist.',
      'mapDistrictIntelligence exists.',
      'Lite content can include trust band, dominant problem, recent effect, and one Ece line.',
    ],
    playerRisk: 'Districts may feel like labels rather than meaningful places.',
    recommendedAction: 'Review Mahalle Karnesi Lite after the main completion pass; defer deeper district history to V1.1.',
    recommendedTiming: 'v1_1',
    isImplementationRequiredBeforeSoftLaunch: false,
    relatedSystems: ['districtTrustRuntime', 'districtMemoryRuntime', 'districtOperationsRuntime', 'mapDistrictIntelligence'],
    suggestedPromptName: 'Mahalle Karnesi Lite Review',
  },
  {
    id: 'content_variety_visibility',
    title: 'Content Variety Visibility',
    category: 'content_visibility',
    status: 'WARN',
    severity: 'high',
    summary: 'Multiple content packs exist, but authored/review content needs runtime activation lite so variety is visible to early players.',
    evidence: [
      'District, vehicle/route, container/environment, social trust, and crisis-adjacent packs exist.',
      'Some pack work is authoring/review-oriented.',
      'Activation must preserve Day 1/Day 7 safety, event caps, freshness, and duplicate guards.',
    ],
    playerRisk: 'The game can look content-rich on paper while players see repeated familiar cards.',
    recommendedAction: 'Implement Content Pack Runtime Activation Lite with strict event-selection guards.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: true,
    relatedSystems: ['content packs', 'event selection', 'event freshness', 'duplicate guards'],
    suggestedPromptName: 'Content Pack Runtime Activation Lite',
  },
  {
    id: 'map_as_living_city',
    title: 'Map as Living City',
    category: 'map_feedback',
    status: 'WARN',
    severity: 'medium',
    summary: 'Map intelligence exists, but the map should communicate city reaction more visibly before full living-map layers are opened.',
    evidence: [
      'mapDistrictIntelligence and map UI systems exist.',
      'Lite reactions can be selected district glow, amber risk ring, social bubble, and short result pulse.',
      'Full route drawing/container fill animation should stay deferred.',
    ],
    playerRisk: 'Map may feel like navigation instead of a city feedback surface.',
    recommendedAction: 'Review Dynamic Map Reaction Lite after decision impact and echo binding passes.',
    recommendedTiming: 'post_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: false,
    relatedSystems: ['Map', 'district intelligence', 'operation signals', 'social mentions'],
    suggestedPromptName: 'Dynamic Map Reaction Lite Review',
  },
  {
    id: 'player_style_recognition',
    title: 'Player Style Recognition',
    category: 'player_identity',
    status: 'WARN',
    severity: 'low',
    summary: 'Player style can be derived from existing decisions, badges, and authority signals, but style badges should wait.',
    evidence: [
      'Badge and authority systems exist.',
      'Decision history can imply fast responder, social trust, resource saver, or route balancer.',
      'No new identity runtime is needed before soft launch.',
    ],
    playerRisk: 'Player may not feel personally recognized beyond badges.',
    recommendedAction: 'Defer style badges to V1.1; use Ece/report copy to softly acknowledge patterns now.',
    recommendedTiming: 'v1_1',
    isImplementationRequiredBeforeSoftLaunch: false,
    relatedSystems: ['decisionHistory', 'badges', 'authority', 'advisor'],
    suggestedPromptName: 'Player Style Recognition Review',
  },
  {
    id: 'weekly_bulletin_season_summary',
    title: 'Weekly Bulletin / Season Summary Readiness',
    category: 'summary_readiness',
    status: 'WARN',
    severity: 'low',
    summary: 'A deterministic weekly bulletin is possible from existing daily reports, but it should be documented rather than opened now.',
    evidence: [
      'Daily reports and pilot completion summary exist.',
      'AI-supported bulletin is explicitly deferred.',
      'Deterministic mini weekly summary is a V1.1 candidate.',
    ],
    playerRisk: 'Low for soft launch core; useful for longer retention later.',
    recommendedAction: 'Document deterministic weekly summary for V1.1 and keep AI bulletin for V2.',
    recommendedTiming: 'v1_1',
    isImplementationRequiredBeforeSoftLaunch: false,
    relatedSystems: ['dailyReport', 'pilot completion', 'report systems integration'],
    suggestedPromptName: 'Weekly Bulletin Review',
  },
  {
    id: 'offline_resume_continuity',
    title: 'Offline / Resume / Continuity Risk',
    category: 'continuity',
    status: 'WARN',
    severity: 'high',
    summary: 'Save migration should not be changed now, but half-finished flows and session-only systems need a robustness pass.',
    evidence: [
      'Current instruction explicitly avoids SAVE_VERSION and persist shape changes.',
      'District operation actions are intentionally runtime/session-only.',
      'Story chain persistent runtime remains non-goal.',
    ],
    playerRisk: 'Resume after app close may lose some presentation-only context or confuse active flow recovery.',
    recommendedAction: 'Run Offline / Resume Robustness Pass without adding persistence unless a blocker is proven.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: true,
    relatedSystems: ['gamePersist', 'event workflow', 'report phase', 'post-pilot state', 'districtOperationActions'],
    suggestedPromptName: 'Offline Resume Robustness Pass',
  },
  {
    id: 'performance_selector_ui_density',
    title: 'Performance / Selector / UI Density Risk',
    category: 'performance',
    status: 'WARN',
    severity: 'medium',
    summary: 'Selector/performance verifiers exist, but dense Hub, Report, Map, and Event surfaces need final mobile density review.',
    evidence: [
      'performance selector pass-two verifier exists.',
      'Large text and compact card rules are repeatedly needed across surfaces.',
      'Completion pass should prioritize compact/hide/priority rules rather than new systems.',
    ],
    playerRisk: 'Mobile players can feel overloaded or see clipped dense cards.',
    recommendedAction: 'Run Accessibility / Large Text Pass and keep cards prioritized by day/context.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: false,
    relatedSystems: ['HubScreen', 'ReportScreen', 'MapScreen', 'Event flow', 'selectors'],
    suggestedPromptName: 'Accessibility / Large Text Pass',
  },
  {
    id: 'monetization_iap_store_blockers',
    title: 'Monetization / IAP / Store Blocker Awareness',
    category: 'launch_blockers',
    status: 'BLOCKER',
    severity: 'blocker',
    summary: 'Launch candidate remains blocked until IAP, store, privacy, screenshots, metadata, and manual test blockers close.',
    evidence: [...SOFT_LAUNCH_CORE_LAUNCH_BLOCKERS],
    playerRisk: 'Public launch cannot proceed safely without purchase, restore, store, privacy, and real-device validation.',
    recommendedAction: 'Keep launch_candidate BLOCKED; proceed only with internal device test until blockers close.',
    recommendedTiming: 'pre_soft_launch',
    isImplementationRequiredBeforeSoftLaunch: true,
    relatedSystems: ['RevenueCat', 'App Store Connect', 'Play Console', 'privacy policy', 'screenshots', 'real device playtest'],
    suggestedPromptName: 'Release Candidate Audit',
  },
];
