/** Olaylar harita + bottom-sheet UI — referans palet. */
export const olaylar = {
  green: '#064E45',
  greenDark: '#063F39',
  tealDeep: '#022C29',
  bg: '#F8FAF8',
  card: '#FFFFFF',
  successBg: '#EAF8F1',
  success: '#22C55E',
  critical: '#EF4444',
  criticalBg: '#FFF1F1',
  urgent: '#F59E0B',
  xp: '#7C3AED',
  xpBg: '#F1EAFE',
  text: '#102A2A',
  textMuted: '#64748B',
  border: '#E5E7EB',
  screenPadding: 20,
  radiusHero: 22,
  radiusCard: 20,
  radiusChip: 20,
  radiusStat: 16,
  radiusSheet: 28,
  mapHeight: 220,
  sheetOverlap: -18,
  scrollBottomPad: 16,
  sheetElevation: {
    shadowColor: '#022C29',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 8,
  },
  shadow: {
    shadowColor: '#022C29',
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  shadowSoft: {
    shadowColor: '#022C29',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
} as const;
