import type { TeamSpecializationDefinition } from './teamSpecializationTypes';

export const TEAM_SPECIALIZATION_CATALOG: readonly TeamSpecializationDefinition[] = [
  {
    id: 'field_team_fast_response',
    groupId: 'field_team',
    title: 'Saha Ekibi',
    shortLabel: 'Saha Müdahale',
    description:
      'Hızlı müdahale, saha uygulaması ve genel operasyon akışında güçlü uzmanlık.',
    primaryDomains: ['container', 'district_balance', 'generic_operation'],
    secondaryDomains: ['personnel', 'resource_recovery'],
    capabilities: ['fast_response', 'field_execution', 'recovery_support'],
    preferredDistrictOperationKinds: [
      'visible_service',
      'resource_balance',
      'district_memory_response',
    ],
    preferredEventFamilyDomains: ['container', 'generic_operation', 'district_balance'],
    preferredRouteDomains: ['container', 'generic', 'district_balance'],
    preferredImpactDomains: ['container', 'personnel', 'generic_operation'],
    weaknessDomains: ['vehicle_route', 'social'],
    unlockPermissionId: 'assignment_fit_preview',
    minDay: 2,
    isFutureOnly: false,
    playerFacingPriority: 90,
    iconKey: 'walk-outline',
  },
  {
    id: 'technical_team_preventive_maintenance',
    groupId: 'technical_team',
    title: 'Teknik Ekip',
    shortLabel: 'Teknik Bakım',
    description:
      'Bakım, konteyner ağı ve kaynak toparlanmasında güçlü teknik uzmanlık.',
    primaryDomains: ['vehicle_route', 'container', 'resource_recovery'],
    secondaryDomains: ['personnel', 'environmental_care'],
    capabilities: [
      'preventive_maintenance',
      'container_network_support',
      'recovery_support',
    ],
    preferredDistrictOperationKinds: [
      'container_network',
      'resource_balance',
      'environmental_care',
    ],
    preferredEventFamilyDomains: ['container', 'vehicle_route', 'resource_recovery'],
    preferredRouteDomains: ['vehicle_route', 'container'],
    preferredImpactDomains: ['container', 'vehicle_route', 'resource_recovery'],
    weaknessDomains: ['social', 'public_trust'],
    unlockPermissionId: 'assignment_fit_preview',
    minDay: 2,
    isFutureOnly: false,
    playerFacingPriority: 88,
    iconKey: 'construct-outline',
  },
  {
    id: 'public_communication_trust',
    groupId: 'public_communication_team',
    title: 'Halk İletişim Ekibi',
    shortLabel: 'Halk İletişimi',
    description:
      'Sosyal güven, mahalle algısı ve halk iletişiminde uzman ekip profili.',
    primaryDomains: ['social', 'public_trust', 'district_balance'],
    secondaryDomains: ['resource_recovery', 'generic_operation'],
    capabilities: [
      'public_communication',
      'morale_stabilization',
      'district_memory_response',
    ],
    preferredDistrictOperationKinds: ['public_trust', 'recovery_focus', 'visible_service'],
    preferredEventFamilyDomains: ['social', 'district_balance', 'resource_recovery'],
    preferredRouteDomains: ['social', 'district_balance'],
    preferredImpactDomains: ['social', 'public_trust', 'district_balance'],
    weaknessDomains: ['vehicle_route', 'container'],
    unlockPermissionId: 'district_specific_operations_preview',
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 87,
    iconKey: 'megaphone-outline',
  },
  {
    id: 'route_support_discipline',
    groupId: 'route_support_team',
    title: 'Rota Destek Ekibi',
    shortLabel: 'Rota Disiplini',
    description:
      'Rota disiplini, aktif görev rotası ve geçiş bölgelerinde güçlü destek.',
    primaryDomains: ['vehicle_route', 'district_balance', 'resource_recovery'],
    secondaryDomains: ['personnel', 'generic_operation'],
    capabilities: ['route_discipline', 'preventive_maintenance', 'field_execution'],
    preferredDistrictOperationKinds: ['route_discipline', 'resource_balance', 'crisis_prevention'],
    preferredEventFamilyDomains: ['vehicle_route', 'district_balance', 'generic_operation'],
    preferredRouteDomains: ['vehicle_route', 'personnel', 'generic'],
    preferredImpactDomains: ['vehicle_route', 'personnel', 'district_balance'],
    weaknessDomains: ['social', 'public_trust'],
    unlockPermissionId: 'assignment_fit_preview',
    minDay: 3,
    isFutureOnly: false,
    playerFacingPriority: 91,
    iconKey: 'git-branch-outline',
  },
  {
    id: 'crisis_support_recovery',
    groupId: 'crisis_support_team',
    title: 'Kriz Destek Ekibi',
    shortLabel: 'Kriz Destek',
    description:
      'Kriz eşiği, toparlanma ve kaynak dengelemede koordinasyon odaklı uzmanlık.',
    primaryDomains: ['crisis', 'resource_recovery', 'district_balance'],
    secondaryDomains: ['social', 'personnel'],
    capabilities: ['crisis_coordination', 'recovery_support', 'public_communication'],
    preferredDistrictOperationKinds: ['crisis_prevention', 'recovery_focus', 'resource_balance'],
    preferredEventFamilyDomains: ['crisis_adjacent', 'resource_recovery', 'social'],
    preferredRouteDomains: ['crisis', 'vehicle_route', 'social'],
    preferredImpactDomains: ['crisis', 'resource_recovery', 'social'],
    weaknessDomains: ['environmental_care', 'generic_operation'],
    unlockPermissionId: 'resource_pressure_summary',
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 89,
    iconKey: 'shield-checkmark-outline',
  },
  {
    id: 'container_network_unit',
    groupId: 'technical_team',
    title: 'Konteyner Ağı Ekibi',
    shortLabel: 'Konteyner Ağı',
    description:
      'Konteyner ağı, çevre hassasiyeti ve saha uygulamasında odaklı birim.',
    primaryDomains: ['container', 'environmental_care', 'district_balance'],
    secondaryDomains: ['resource_recovery', 'generic_operation'],
    capabilities: ['container_network_support', 'field_execution', 'recovery_support'],
    preferredDistrictOperationKinds: ['container_network', 'environmental_care', 'recovery_focus'],
    preferredEventFamilyDomains: ['container', 'district_balance', 'resource_recovery'],
    preferredRouteDomains: ['container', 'district_balance'],
    preferredImpactDomains: ['container', 'environmental_care', 'district_balance'],
    weaknessDomains: ['social', 'crisis'],
    unlockPermissionId: 'container_network_upgrade_preview',
    minDay: 5,
    isFutureOnly: false,
    playerFacingPriority: 84,
    iconKey: 'cube-outline',
  },
] as const;

export function getSpecializationsForGroupFromCatalog(
  groupId: string,
): readonly TeamSpecializationDefinition[] {
  return TEAM_SPECIALIZATION_CATALOG.filter((definition) => definition.groupId === groupId);
}
