import type {
  CreviaEventVariantDefinition,
  CreviaEventVariantKind,
  CreviaEventVariantSurface,
} from './eventVariantTypes';

export const EVENT_VARIANT_KINDS: readonly CreviaEventVariantKind[] = [
  'normal',
  'improved',
  'worsened',
  'carry_over',
  'reward',
  'comeback',
  'resource_fatigue',
  'district_trust',
  'crisis_adjacent',
  'operation_era',
] as const;

export const EVENT_VARIANT_SURFACES: readonly CreviaEventVariantSurface[] = [
  'event_card',
  'inspect',
  'plan',
  'dispatch',
  'field',
  'result',
  'report',
  'social',
  'advisor',
  'map',
  'tomorrow_preview',
] as const;

export const EVENT_VARIANT_FORBIDDEN_COPY_TERMS: readonly string[] = [
  '14 günlük sezon',
  'sezon sonu',
  'sezon finali',
  'oyun bitti',
  'oyun sonu',
  'yeni sezona başla',
  'premium al',
  'paywall',
  'panik',
  'felaket',
  'çöküş',
  'kaos',
] as const;

export const EVENT_VARIANT_PANIC_TERMS: readonly string[] = [
  'panik',
  'felaket',
  'çöküş',
  'kaos',
  'umutsuz',
  'bedava',
  'bedelsiz',
] as const;

export const EVENT_VARIANT_GENERIC_SPAM_TERMS: readonly string[] = [
  'durum takip ediliyor',
  'durum izleniyor',
  'gelişmeler takip ediliyor',
] as const;

export const EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH = 96;
export const EVENT_VARIANT_MOBILE_MAX_COPY_LENGTH = 72;
export const EVENT_VARIANT_TUTORIAL_MAX_DAY = 1;

export const EVENT_VARIANT_TUTORIAL_BLOCKED_KINDS: readonly CreviaEventVariantKind[] = [
  'worsened',
  'crisis_adjacent',
  'operation_era',
] as const;

export const EVENT_VARIANT_RISKY_KINDS: readonly CreviaEventVariantKind[] = [
  'worsened',
  'crisis_adjacent',
] as const;

export const EVENT_VARIANT_ALL_SURFACES: readonly CreviaEventVariantSurface[] = EVENT_VARIANT_SURFACES;

const BASE_SURFACES: readonly CreviaEventVariantSurface[] = [
  'event_card',
  'inspect',
  'plan',
  'dispatch',
  'field',
  'result',
  'report',
  'social',
  'advisor',
  'map',
  'tomorrow_preview',
];

const ECHO_SURFACES: readonly CreviaEventVariantSurface[] = [
  'report',
  'social',
  'advisor',
  'map',
  'tomorrow_preview',
  'result',
];

export const EVENT_VARIANT_DEFINITIONS: Record<CreviaEventVariantKind, CreviaEventVariantDefinition> = {
  normal: {
    kind: 'normal',
    label: 'Normal Operasyon',
    shortLabel: 'Normal',
    tone: 'neutral',
    priority: 10,
    allowedSurfaces: BASE_SURFACES,
    forbiddenTerms: EVENT_VARIANT_FORBIDDEN_COPY_TERMS,
    maxCopyLength: EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: false,
    isRecovery: false,
    isRisky: false,
    isProgressionRelevant: false,
    defaultEchoIntent: 'Günlük operasyon akışını sürdür.',
    isContextOnly: false,
  },
  improved: {
    kind: 'improved',
    label: 'İyileşmiş Koşul',
    shortLabel: 'İyileşmiş',
    tone: 'encouraging',
    priority: 20,
    allowedSurfaces: BASE_SURFACES,
    forbiddenTerms: EVENT_VARIANT_FORBIDDEN_COPY_TERMS,
    maxCopyLength: EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: true,
    isRecovery: false,
    isRisky: false,
    isProgressionRelevant: true,
    defaultEchoIntent: 'Önceki adımlar operasyonu hafifletiyor.',
    isContextOnly: false,
  },
  worsened: {
    kind: 'worsened',
    label: 'Zorlaşan Koşul',
    shortLabel: 'Zorlaşmış',
    tone: 'cautious',
    priority: 15,
    allowedSurfaces: BASE_SURFACES,
    forbiddenTerms: [...EVENT_VARIANT_FORBIDDEN_COPY_TERMS, 'umutsuz', 'ceza'],
    maxCopyLength: EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: false,
    isRecovery: false,
    isRisky: true,
    isProgressionRelevant: false,
    defaultEchoIntent: 'Baskı arttı; kontrollü yönetim gerekiyor.',
    isContextOnly: false,
  },
  carry_over: {
    kind: 'carry_over',
    label: 'Devam Eden Etki',
    shortLabel: 'Devam',
    tone: 'contextual',
    priority: 25,
    allowedSurfaces: BASE_SURFACES,
    forbiddenTerms: EVENT_VARIANT_FORBIDDEN_COPY_TERMS,
    maxCopyLength: EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: false,
    isRecovery: false,
    isRisky: false,
    isProgressionRelevant: true,
    defaultEchoIntent: 'Önceki günün tercihi bugünü şekillendiriyor.',
    isContextOnly: false,
  },
  reward: {
    kind: 'reward',
    label: 'Olumlu Geri Bildirim',
    shortLabel: 'Ödül',
    tone: 'reward',
    priority: 30,
    allowedSurfaces: BASE_SURFACES,
    forbiddenTerms: [...EVENT_VARIANT_FORBIDDEN_COPY_TERMS, 'bedava', 'bedelsiz'],
    maxCopyLength: EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: true,
    isRecovery: false,
    isRisky: false,
    isProgressionRelevant: true,
    defaultEchoIntent: 'Önceki karar görünür rahatlama yarattı.',
    isContextOnly: false,
  },
  comeback: {
    kind: 'comeback',
    label: 'Toparlanma Fırsatı',
    shortLabel: 'Toparlanma',
    tone: 'recovery',
    priority: 28,
    allowedSurfaces: BASE_SURFACES,
    forbiddenTerms: [...EVENT_VARIANT_FORBIDDEN_COPY_TERMS, 'bedava', 'bedelsiz', 'kurtarma garantisi'],
    maxCopyLength: EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: false,
    isRecovery: true,
    isRisky: false,
    isProgressionRelevant: true,
    defaultEchoIntent: 'Toparlanma fırsatı var; kaynak baskısı yönetilmeli.',
    isContextOnly: false,
  },
  resource_fatigue: {
    kind: 'resource_fatigue',
    label: 'Kaynak Yorgunluğu',
    shortLabel: 'Yorgunluk',
    tone: 'operational',
    priority: 22,
    allowedSurfaces: BASE_SURFACES,
    forbiddenTerms: EVENT_VARIANT_FORBIDDEN_COPY_TERMS,
    maxCopyLength: EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: false,
    isRecovery: false,
    isRisky: false,
    isProgressionRelevant: true,
    defaultEchoIntent: 'Kaynak yorgunluğu bu kararda daha görünür.',
    isContextOnly: false,
  },
  district_trust: {
    kind: 'district_trust',
    label: 'Mahalle Güveni',
    shortLabel: 'Güven',
    tone: 'contextual',
    priority: 24,
    allowedSurfaces: BASE_SURFACES,
    forbiddenTerms: EVENT_VARIANT_FORBIDDEN_COPY_TERMS,
    maxCopyLength: EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: false,
    isRecovery: true,
    isRisky: false,
    isProgressionRelevant: true,
    defaultEchoIntent: 'Mahalle güveni operasyon tonunu değiştiriyor.',
    isContextOnly: false,
  },
  crisis_adjacent: {
    kind: 'crisis_adjacent',
    label: 'Kriz Eşiği',
    shortLabel: 'Kriz Eşiği',
    tone: 'cautious',
    priority: 26,
    allowedSurfaces: ECHO_SURFACES,
    forbiddenTerms: [...EVENT_VARIANT_FORBIDDEN_COPY_TERMS, ...EVENT_VARIANT_PANIC_TERMS],
    maxCopyLength: EVENT_VARIANT_MOBILE_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: false,
    isRecovery: false,
    isRisky: true,
    isProgressionRelevant: false,
    defaultEchoIntent: 'Risk büyümeden kontrol penceresi açıldı.',
    isContextOnly: false,
  },
  operation_era: {
    kind: 'operation_era',
    label: 'Operasyon Dönemi',
    shortLabel: 'Dönem',
    tone: 'contextual',
    priority: 18,
    allowedSurfaces: ECHO_SURFACES,
    forbiddenTerms: EVENT_VARIANT_FORBIDDEN_COPY_TERMS,
    maxCopyLength: EVENT_VARIANT_DEFAULT_MAX_COPY_LENGTH,
    shouldAvoidPanicLanguage: true,
    isPositive: false,
    isRecovery: false,
    isRisky: false,
    isProgressionRelevant: true,
    defaultEchoIntent: 'Operasyon mevcut dönem temasına bağlanıyor.',
    isContextOnly: true,
  },
};

export function getEventVariantDefinition(kind: CreviaEventVariantKind): CreviaEventVariantDefinition {
  return EVENT_VARIANT_DEFINITIONS[kind];
}
