import type { AnalyticsEventName } from './analyticsTypes';

export const ANALYTICS_SCHEMA_VERSION = 1;

export const FORBIDDEN_ANALYTICS_PAYLOAD_KEYS = [
  'name',
  'firstName',
  'lastName',
  'email',
  'phone',
  'address',
  'rawText',
  'reportText',
  'freeText',
  'saveState',
  'deviceId',
  'idfa',
  'idfv',
  'advertisingId',
  'ipAddress',
  'locationLat',
  'locationLng',
] as const;

export const ALLOWED_GENERIC_PAYLOAD_KEYS = [
  'eventName',
  'surface',
  'day',
  'pilotDay',
  'seasonDay',
  'accessMode',
  'districtId',
  'eventType',
  'eventCategory',
  'decisionType',
  'optionId',
  'assignmentFitBand',
  'resourceStatusBand',
  'crisisRiskBand',
  'ratingBand',
  'resultBand',
  'ctaId',
  'tabId',
  'source',
  'isFirstSession',
  'isTutorial',
  'hasCrisisAction',
  'hasSeasonEnd',
  'schemaVersion',
  'timestampMs',
] as const;

export const FREE_TEXT_LIKE_PAYLOAD_KEY_SUFFIXES = [
  'Text',
  'summary',
  'description',
  'reportLine',
  'advisorLine',
  'message',
  'body',
] as const;

export const BASE_REQUIRED_PAYLOAD_KEYS = [
  'eventName',
  'surface',
  'schemaVersion',
] as const;

/** All event names in schema — used for uniqueness checks. */
export const ALL_ANALYTICS_EVENT_NAMES: readonly AnalyticsEventName[] = [
  'app_opened',
  'session_started',
  'day_started',
  'first_guide_seen',
  'advisor_hint_requested',
  'daily_plan_seen',
  'daily_plan_confirmed',
  'first_event_opened',
  'decision_selected',
  'assignment_seen',
  'assignment_confirmed',
  'field_phase_started',
  'event_completed',
  'report_opened',
  'hub_returned',
  'pilot_day_started',
  'pilot_day_completed',
  'day7_report_opened',
  'pilot_completion_seen',
  'post_pilot_offer_opened',
  'post_pilot_offer_primary_cta_pressed',
  'limited_continue_selected',
  'main_operation_mock_purchase_started',
  'main_operation_mock_purchase_completed',
  'access_restore_pressed',
  'iap_product_list_loaded',
  'iap_purchase_started',
  'iap_purchase_completed',
  'iap_purchase_failed',
  'iap_restore_started',
  'iap_restore_completed',
  'iap_restore_not_found',
  'main_operation_day_started',
  'season_goal_card_seen',
  'season_goal_detail_opened',
  'operational_resources_card_seen',
  'operational_resources_detail_opened',
  'map_resource_overlay_seen',
  'map_crisis_overlay_seen',
  'micro_decision_seen',
  'micro_decision_resolved',
  'crisis_desk_seen',
  'crisis_action_sheet_opened',
  'crisis_action_selected',
  'crisis_action_processed',
  'season_end_seen',
  'season_end_detail_opened',
  'report_primary_impact_seen',
  'report_daily_plan_seen',
  'report_assignment_seen',
  'report_resources_seen',
  'report_crisis_seen',
  'report_micro_decision_seen',
  'report_main_operation_seen',
  'report_season_end_seen',
  'tab_changed',
  'map_opened',
  'social_pulse_opened',
  'profile_opened',
  'leaderboard_opened',
] as const;
