import type {
  CreviaTelemetryAlertThreshold,
  CreviaTelemetryDashboardCard,
  CreviaTelemetryFunnelDefinition,
  CreviaTelemetryKpiDefinition,
  CreviaTelemetryKpiGroupId,
  CreviaTelemetryReviewQuestion,
} from './postLaunchTelemetryReadinessTypes';
import type { AnalyticsEventName } from './analyticsTypes';

export const POST_LAUNCH_TELEMETRY_READINESS_DOCS_PATH =
  'docs/crevia-post-launch-telemetry-readiness.md';

export const POST_LAUNCH_TELEMETRY_MIN_KPI_GROUPS = 8;
export const POST_LAUNCH_TELEMETRY_MIN_FUNNELS = 5;
export const POST_LAUNCH_TELEMETRY_MIN_DASHBOARD_CARDS = 10;
export const POST_LAUNCH_TELEMETRY_MIN_REVIEW_QUESTIONS = 20;

export const POST_LAUNCH_TELEMETRY_KPI_GROUP_LABELS: Record<
  CreviaTelemetryKpiGroupId,
  string
> = {
  first_session: 'A. First Session',
  day_1_funnel: 'B. Day 1 Funnel',
  pilot_1_7_progression: 'C. Pilot 1–7 Progression',
  day_8_open_ended: 'D. Day 8+ Open-Ended Operation',
  map_route_engagement: 'E. Map / Route Engagement',
  result_report_engagement: 'F. Result / Report Engagement',
  iap_monetization: 'G. IAP / Monetization Funnel',
  technical_quality: 'H. Technical / Quality',
};

/** KPI → mevcut schema event eşlemesi (yeni event eklenmez). */
export const POST_LAUNCH_TELEMETRY_KPI_DEFINITIONS: CreviaTelemetryKpiDefinition[] = [
  {
    id: 'kpi.app_open',
    groupId: 'first_session',
    label: 'app_open',
    description: 'Uygulama açılışı.',
    sourceEvent: 'app_opened',
  },
  {
    id: 'kpi.first_hub_view',
    groupId: 'first_session',
    label: 'first hub view',
    description: 'İlk hub oturumu (session_started proxy).',
    sourceEvent: 'session_started',
    segmentNote: 'isFirstSession=true',
  },
  {
    id: 'kpi.first_event_inspect',
    groupId: 'first_session',
    label: 'first event inspect',
    description: 'İlk olay kartı açılışı.',
    sourceEvent: 'first_event_opened',
  },
  {
    id: 'kpi.first_plan',
    groupId: 'first_session',
    label: 'first plan',
    description: 'İlk günlük plan onayı.',
    sourceEvent: 'daily_plan_confirmed',
  },
  {
    id: 'kpi.first_dispatch',
    groupId: 'first_session',
    label: 'first dispatch',
    description: 'İlk saha ataması onayı.',
    sourceEvent: 'assignment_confirmed',
  },
  {
    id: 'kpi.first_result',
    groupId: 'first_session',
    label: 'first result',
    description: 'İlk olay tamamlanması.',
    sourceEvent: 'event_completed',
  },
  {
    id: 'kpi.first_report',
    groupId: 'first_session',
    label: 'first report',
    description: 'İlk gün sonu raporu.',
    sourceEvent: 'report_opened',
  },
  {
    id: 'kpi.first_session_completion',
    groupId: 'first_session',
    label: 'first session completion',
    description: 'Rapor sonrası hub dönüşü.',
    sourceEvent: 'hub_returned',
  },
  {
    id: 'kpi.day_1_start',
    groupId: 'day_1_funnel',
    label: 'Day 1 start',
    description: 'Gün 1 başlangıcı.',
    sourceEvent: 'day_started',
    segmentNote: 'day=1',
  },
  {
    id: 'kpi.day_1_first_event_completed',
    groupId: 'day_1_funnel',
    label: 'first event completed',
    description: 'Gün 1 ilk olay tamamlanması.',
    sourceEvent: 'event_completed',
    segmentNote: 'day=1',
  },
  {
    id: 'kpi.day_1_report_viewed',
    groupId: 'day_1_funnel',
    label: 'first report viewed',
    description: 'Gün 1 rapor açılışı.',
    sourceEvent: 'report_opened',
    segmentNote: 'day=1',
  },
  {
    id: 'kpi.day_2_reached',
    groupId: 'day_1_funnel',
    label: 'Day 2 reached',
    description: 'Gün 2 başlangıcı.',
    sourceEvent: 'pilot_day_started',
    segmentNote: 'pilotDay=2',
  },
  {
    id: 'kpi.pilot_daily_completion',
    groupId: 'pilot_1_7_progression',
    label: 'daily completion rate',
    description: 'Pilot gün tamamlanma oranı.',
    sourceEvent: 'pilot_day_completed',
  },
  {
    id: 'kpi.pilot_day_3',
    groupId: 'pilot_1_7_progression',
    label: 'Day 3 reached',
    description: 'Pilot gün 3 başlangıcı.',
    sourceEvent: 'pilot_day_started',
    segmentNote: 'pilotDay=3',
  },
  {
    id: 'kpi.pilot_day_7',
    groupId: 'pilot_1_7_progression',
    label: 'Day 7 reached',
    description: 'Gün 7 rapor / pilot kapanışı.',
    sourceEvent: 'day7_report_opened',
  },
  {
    id: 'kpi.pilot_completed',
    groupId: 'pilot_1_7_progression',
    label: 'pilot completed',
    description: 'Pilot tamamlanma kartı.',
    sourceEvent: 'pilot_completion_seen',
  },
  {
    id: 'kpi.post_pilot_offer_viewed',
    groupId: 'pilot_1_7_progression',
    label: 'post-pilot offer viewed',
    description: 'Post-pilot teklif ekranı.',
    sourceEvent: 'post_pilot_offer_opened',
  },
  {
    id: 'kpi.day_8_reached',
    groupId: 'day_8_open_ended',
    label: 'Day 8 reached',
    description: 'Ana operasyon gün 8 başlangıcı.',
    sourceEvent: 'main_operation_day_started',
    segmentNote: 'day>=8',
  },
  {
    id: 'kpi.hub_open_ended_card',
    groupId: 'day_8_open_ended',
    label: 'hub open-ended card viewed',
    description: 'Hub open-ended kartı.',
    sourceEvent: 'hub_open_ended_card_viewed',
  },
  {
    id: 'kpi.operation_era_line',
    groupId: 'day_8_open_ended',
    label: 'operation era line viewed',
    description: 'Operasyon dönemi satırı (şema event yok — hub focus proxy).',
    sourceEvent: 'hub_open_ended_focus_line_viewed',
    segmentNote: 'lineKind=operation_era',
    optional: true,
  },
  {
    id: 'kpi.district_operation_action',
    groupId: 'day_8_open_ended',
    label: 'district operation action viewed / selected',
    description: 'Mahalle operasyon ipucu (seçim eventi yok).',
    sourceEvent: 'map_district_operation_hint_viewed',
    optional: true,
  },
  {
    id: 'kpi.story_chain_hint',
    groupId: 'day_8_open_ended',
    label: 'story chain hint viewed',
    description: 'Hikâye zinciri ipucu — şema event yok.',
    sourceEvent: 'manual_proxy',
    optional: true,
  },
  {
    id: 'kpi.profile_career_showcase',
    groupId: 'day_8_open_ended',
    label: 'profile career showcase viewed',
    description: 'Profil kariyer vitrini.',
    sourceEvent: 'profile_career_showcase_viewed',
  },
  {
    id: 'kpi.map_district_intelligence',
    groupId: 'map_route_engagement',
    label: 'map district intelligence viewed',
    description: 'Harita mahalle intelligence bloğu.',
    sourceEvent: 'map_district_intelligence_viewed',
  },
  {
    id: 'kpi.active_route_preview',
    groupId: 'map_route_engagement',
    label: 'active route preview viewed',
    description: 'Aktif rota önizlemesi.',
    sourceEvent: 'active_route_preview_viewed',
  },
  {
    id: 'kpi.route_phase',
    groupId: 'map_route_engagement',
    label: 'route phase viewed',
    description: 'Aktif rota faz satırı.',
    sourceEvent: 'active_route_phase_viewed',
  },
  {
    id: 'kpi.route_resource_warning',
    groupId: 'map_route_engagement',
    label: 'route/resource warning viewed',
    description: 'Rota kaynak uyarısı.',
    sourceEvent: 'active_route_resource_warning_viewed',
  },
  {
    id: 'kpi.result_systems_echo',
    groupId: 'result_report_engagement',
    label: 'result systems echo viewed',
    description: 'Sonuç sistem yankı kartı.',
    sourceEvent: 'result_systems_echo_viewed',
  },
  {
    id: 'kpi.report_systems_card',
    groupId: 'result_report_engagement',
    label: 'report systems card viewed',
    description: 'Rapor sistem entegrasyon kartı.',
    sourceEvent: 'report_systems_card_viewed',
  },
  {
    id: 'kpi.tomorrow_carryover',
    groupId: 'result_report_engagement',
    label: 'tomorrow/carry-over line viewed',
    description: 'Yarın taşıma satırı.',
    sourceEvent: 'report_tomorrow_carryover_line_viewed',
  },
  {
    id: 'kpi.advisor_comment',
    groupId: 'result_report_engagement',
    label: 'advisor comment viewed',
    description: 'Danışman ipucu isteği proxy.',
    sourceEvent: 'advisor_hint_requested',
    optional: true,
  },
  {
    id: 'kpi.iap_offer_viewed',
    groupId: 'iap_monetization',
    label: 'post-pilot offer viewed',
    description: 'Post-pilot teklif ekranı.',
    sourceEvent: 'post_pilot_offer_opened',
  },
  {
    id: 'kpi.iap_product_loaded',
    groupId: 'iap_monetization',
    label: 'product loaded',
    description: 'Mağaza ürün listesi yüklendi.',
    sourceEvent: 'iap_product_list_loaded',
  },
  {
    id: 'kpi.iap_purchase_started',
    groupId: 'iap_monetization',
    label: 'purchase started',
    description: 'IAP satın alma başladı.',
    sourceEvent: 'iap_purchase_started',
  },
  {
    id: 'kpi.iap_purchase_cancelled',
    groupId: 'iap_monetization',
    label: 'purchase cancelled',
    description: 'İptal eventi şemada yok — store/RevenueCat funnel gap.',
    sourceEvent: 'manual_proxy',
    optional: true,
  },
  {
    id: 'kpi.iap_purchase_failed',
    groupId: 'iap_monetization',
    label: 'purchase failed',
    description: 'IAP satın alma başarısız.',
    sourceEvent: 'iap_purchase_failed',
  },
  {
    id: 'kpi.iap_purchase_completed',
    groupId: 'iap_monetization',
    label: 'purchase completed',
    description: 'IAP satın alma tamamlandı.',
    sourceEvent: 'iap_purchase_completed',
  },
  {
    id: 'kpi.iap_restore_started',
    groupId: 'iap_monetization',
    label: 'restore started',
    description: 'Geri yükleme başladı.',
    sourceEvent: 'iap_restore_started',
  },
  {
    id: 'kpi.iap_restore_completed',
    groupId: 'iap_monetization',
    label: 'restore completed',
    description: 'Geri yükleme tamamlandı.',
    sourceEvent: 'iap_restore_completed',
  },
  {
    id: 'kpi.entitlement_active',
    groupId: 'iap_monetization',
    label: 'entitlement active',
    description: 'Entitlement aktif — doğrudan event yok; purchase completed proxy.',
    sourceEvent: 'iap_purchase_completed',
    segmentNote: 'resultBand=success + accessMode transition',
    optional: true,
  },
  {
    id: 'kpi.crash_rate',
    groupId: 'technical_quality',
    label: 'crash rate placeholder',
    description: 'Crash SDK entegrasyonu öncesi manuel placeholder.',
    sourceEvent: 'placeholder',
  },
  {
    id: 'kpi.app_restart_after_report',
    groupId: 'technical_quality',
    label: 'app restart after report',
    description: 'Rapor sonrası hub dönüşü / oturum devamı proxy.',
    sourceEvent: 'hub_returned',
  },
  {
    id: 'kpi.offline_graceful',
    groupId: 'technical_quality',
    label: 'offline graceful handling',
    description: 'Offline davranış — manuel QA proxy.',
    sourceEvent: 'manual_proxy',
  },
  {
    id: 'kpi.performance_warning',
    groupId: 'technical_quality',
    label: 'performance warning manual proxy',
    description: 'Performans uyarıları — quality audit manuel.',
    sourceEvent: 'manual_proxy',
  },
  {
    id: 'kpi.smoke_test_status',
    groupId: 'technical_quality',
    label: 'smoke test status',
    description: 'IAP sandbox smoke execution durumu.',
    sourceEvent: 'manual_proxy',
  },
];

export const POST_LAUNCH_TELEMETRY_FUNNEL_DEFINITIONS: CreviaTelemetryFunnelDefinition[] = [
  {
    id: 'first_session_funnel',
    title: 'First Session Funnel',
    description:
      'app_open → hub_view → event_inspect → plan → dispatch → result → report',
    orderedSteps: [
      { stepId: 'app_open', label: 'app_open', sourceEvent: 'app_opened' },
      { stepId: 'hub_view', label: 'hub_view', sourceEvent: 'session_started', segmentNote: 'isFirstSession' },
      { stepId: 'event_inspect', label: 'event_inspect', sourceEvent: 'first_event_opened' },
      { stepId: 'plan', label: 'plan', sourceEvent: 'daily_plan_confirmed' },
      { stepId: 'dispatch', label: 'dispatch', sourceEvent: 'assignment_confirmed' },
      { stepId: 'result', label: 'result', sourceEvent: 'event_completed' },
      { stepId: 'report', label: 'report', sourceEvent: 'report_opened' },
    ],
    successEvent: 'report_opened',
    dropoffNotes: [
      'Plan onayı öncesi çıkış',
      'Atama panelinde tereddüt',
      'Rapor açılmadan çıkış',
    ],
  },
  {
    id: 'day_1_completion_funnel',
    title: 'Day 1 Completion Funnel',
    description: 'day_start → event_completed → report_viewed → next_day_started',
    orderedSteps: [
      { stepId: 'day_start', label: 'day_start', sourceEvent: 'day_started', segmentNote: 'day=1' },
      { stepId: 'event_completed', label: 'event_completed', sourceEvent: 'event_completed', segmentNote: 'day=1' },
      { stepId: 'report_viewed', label: 'report_viewed', sourceEvent: 'report_opened', segmentNote: 'day=1' },
      { stepId: 'next_day_started', label: 'next_day_started', sourceEvent: 'pilot_day_started', segmentNote: 'pilotDay=2' },
    ],
    successEvent: 'pilot_day_started',
    dropoffNotes: ['Gün 1 olay tamamlanmadan çıkış', 'Rapor atlanması', 'Gün 2 başlamadan churn'],
  },
  {
    id: 'pilot_completion_funnel',
    title: 'Pilot Completion Funnel',
    description:
      'day_1_started → day_3_reached → day_7_reached → pilot_completed → post_pilot_offer_viewed',
    orderedSteps: [
      { stepId: 'day_1_started', label: 'day_1_started', sourceEvent: 'pilot_day_started', segmentNote: 'pilotDay=1' },
      { stepId: 'day_3_reached', label: 'day_3_reached', sourceEvent: 'pilot_day_started', segmentNote: 'pilotDay=3' },
      { stepId: 'day_7_reached', label: 'day_7_reached', sourceEvent: 'day7_report_opened' },
      { stepId: 'pilot_completed', label: 'pilot_completed', sourceEvent: 'pilot_completion_seen' },
      { stepId: 'post_pilot_offer_viewed', label: 'post_pilot_offer_viewed', sourceEvent: 'post_pilot_offer_opened' },
    ],
    successEvent: 'post_pilot_offer_opened',
    dropoffNotes: ['Gün 3 pacing düşüşü', 'Gün 7 raporu atlanması', 'Teklif ekranına ulaşamama'],
  },
  {
    id: 'open_ended_engagement_funnel',
    title: 'Open-Ended Engagement Funnel',
    description:
      'day_8_reached → hub_open_ended_viewed → map_intelligence_viewed → district_action_selected → report_systems_viewed',
    orderedSteps: [
      { stepId: 'day_8_reached', label: 'day_8_reached', sourceEvent: 'main_operation_day_started', segmentNote: 'day>=8' },
      { stepId: 'hub_open_ended_viewed', label: 'hub_open_ended_viewed', sourceEvent: 'hub_open_ended_card_viewed' },
      { stepId: 'map_intelligence_viewed', label: 'map_intelligence_viewed', sourceEvent: 'map_district_intelligence_viewed' },
      {
        stepId: 'district_action_selected',
        label: 'district_action_selected',
        sourceEvent: 'map_district_operation_hint_viewed',
        segmentNote: 'selection event yok — hint proxy',
      },
      { stepId: 'report_systems_viewed', label: 'report_systems_viewed', sourceEvent: 'report_systems_card_viewed' },
    ],
    successEvent: 'report_systems_card_viewed',
    dropoffNotes: ['Day 8 değer algısı düşük', 'Map CTA keşfedilemiyor', 'Report yoğunluğu'],
  },
  {
    id: 'iap_funnel',
    title: 'IAP Funnel',
    description:
      'offer_viewed → product_loaded → purchase_started → purchase_completed → entitlement_active',
    orderedSteps: [
      { stepId: 'offer_viewed', label: 'offer_viewed', sourceEvent: 'post_pilot_offer_opened' },
      { stepId: 'product_loaded', label: 'product_loaded', sourceEvent: 'iap_product_list_loaded' },
      { stepId: 'purchase_started', label: 'purchase_started', sourceEvent: 'iap_purchase_started' },
      { stepId: 'purchase_completed', label: 'purchase_completed', sourceEvent: 'iap_purchase_completed' },
      {
        stepId: 'entitlement_active',
        label: 'entitlement_active',
        sourceEvent: 'iap_purchase_completed',
        segmentNote: 'entitlement event yok — purchase proxy',
      },
    ],
    successEvent: 'iap_purchase_completed',
    dropoffNotes: [
      'Ürün yükleme hatası',
      'Store sheet iptali (cancel event eksik)',
      'Entitlement senkron gecikmesi',
    ],
  },
];

export const POST_LAUNCH_TELEMETRY_DASHBOARD_CARDS: CreviaTelemetryDashboardCard[] = [
  {
    id: 'dash.first_session_completion',
    title: 'First session completion',
    questionAnswered: 'İlk oturumda rapora kadar kaç oyuncu geliyor?',
    sourceEvents: ['app_opened', 'session_started', 'report_opened', 'hub_returned'],
    segment: 'isFirstSession=true; day=1',
    recommendedChartType: 'funnel',
    alertThresholdId: 'thresh.first_event_completion',
    owner: 'product',
    status: 'pending_sdk',
  },
  {
    id: 'dash.day_1_dropoff',
    title: 'Day 1 drop-off',
    questionAnswered: 'Gün 1 hangi adımda oyuncu kaybediliyor?',
    sourceEvents: ['day_started', 'event_completed', 'report_opened', 'pilot_day_started'],
    segment: 'day=1',
    recommendedChartType: 'funnel',
    alertThresholdId: 'thresh.day_1_completion',
    owner: 'product',
    status: 'pending_sdk',
  },
  {
    id: 'dash.pilot_day_progression',
    title: 'Pilot day progression',
    questionAnswered: 'Pilot gün 1–7 ilerleme eğrisi nasıl?',
    sourceEvents: ['pilot_day_started', 'pilot_day_completed', 'day7_report_opened'],
    segment: 'pilotDay=1..7',
    recommendedChartType: 'line',
    alertThresholdId: 'thresh.day_7_reach',
    owner: 'product',
    status: 'pending_sdk',
  },
  {
    id: 'dash.day_8_reached',
    title: 'Day 8 reached',
    questionAnswered: 'Pilot sonrası Day 8+ operasyona kaç oyuncu ulaşıyor?',
    sourceEvents: ['main_operation_day_started', 'hub_open_ended_card_viewed'],
    segment: 'day>=8',
    recommendedChartType: 'bar',
    alertThresholdId: 'thresh.day_8_reach',
    owner: 'product',
    status: 'pending_sdk',
  },
  {
    id: 'dash.post_pilot_offer_view',
    title: 'Post-pilot offer view',
    questionAnswered: 'Pilot tamamlayanların kaçı teklif ekranını görüyor?',
    sourceEvents: ['pilot_completion_seen', 'post_pilot_offer_opened'],
    segment: 'post-pilot cohort',
    recommendedChartType: 'funnel',
    owner: 'monetization',
    status: 'pending_sdk',
  },
  {
    id: 'dash.purchase_funnel',
    title: 'Purchase funnel',
    questionAnswered: 'Satın alma hunisinde nerede düşüş var?',
    sourceEvents: [
      'post_pilot_offer_opened',
      'iap_product_list_loaded',
      'iap_purchase_started',
      'iap_purchase_completed',
    ],
    segment: 'iap cohort',
    recommendedChartType: 'funnel',
    alertThresholdId: 'thresh.purchase_start_low',
    owner: 'monetization',
    status: 'pending_sdk',
  },
  {
    id: 'dash.map_engagement',
    title: 'Map engagement',
    questionAnswered: 'Harita intelligence ve rota önizlemesi kullanılıyor mu?',
    sourceEvents: [
      'map_opened',
      'map_district_intelligence_viewed',
      'active_route_preview_viewed',
      'active_route_phase_viewed',
    ],
    segment: 'day>=2',
    recommendedChartType: 'bar',
    alertThresholdId: 'thresh.map_view_low',
    owner: 'product',
    status: 'pending_sdk',
  },
  {
    id: 'dash.report_engagement',
    title: 'Report engagement',
    questionAnswered: 'Rapor sistem kartları ve carry-over satırları okunuyor mu?',
    sourceEvents: [
      'report_opened',
      'report_systems_card_viewed',
      'report_tomorrow_carryover_line_viewed',
    ],
    segment: 'all days',
    recommendedChartType: 'bar',
    alertThresholdId: 'thresh.report_view_low',
    owner: 'product',
    status: 'pending_sdk',
  },
  {
    id: 'dash.profile_career_engagement',
    title: 'Profile career engagement',
    questionAnswered: 'Profil kariyer vitrini açılıyor mu?',
    sourceEvents: ['profile_opened', 'profile_career_showcase_viewed'],
    segment: 'day>=3',
    recommendedChartType: 'bar',
    owner: 'product',
    status: 'pending_sdk',
  },
  {
    id: 'dash.iap_smoke_status',
    title: 'IAP smoke status',
    questionAnswered: 'Sandbox smoke testleri geçti mi?',
    sourceEvents: ['manual_proxy'],
    segment: 'qa manual',
    recommendedChartType: 'status_badge',
    owner: 'qa',
    status: 'manual_only',
  },
  {
    id: 'dash.crash_performance_placeholder',
    title: 'Crash/performance placeholder',
    questionAnswered: 'Crash ve performans sinyalleri (SDK öncesi manuel).',
    sourceEvents: ['placeholder'],
    segment: 'technical',
    recommendedChartType: 'table',
    owner: 'engineering',
    status: 'manual_only',
  },
  {
    id: 'dash.manual_blocker_status',
    title: 'Manual blocker status',
    questionAnswered: 'Soft launch review manuel blocker durumu.',
    sourceEvents: ['manual_proxy'],
    segment: 'release readiness',
    recommendedChartType: 'status_badge',
    owner: 'release',
    status: 'manual_only',
  },
];

export const POST_LAUNCH_TELEMETRY_ALERT_THRESHOLDS: CreviaTelemetryAlertThreshold[] = [
  {
    id: 'thresh.day_1_completion',
    metricLabel: 'Day 1 completion rate',
    condition: 'below',
    thresholdValue: '50%',
    severity: 'investigate',
    recommendedAction: 'Day 1 funnel adımlarını incele; tutorial ve plan yoğunluğunu gözden geçir.',
    note: 'Review threshold — hard-coded business truth değil.',
  },
  {
    id: 'thresh.first_event_completion',
    metricLabel: 'First event completion rate',
    condition: 'below',
    thresholdValue: '60%',
    severity: 'high_risk',
    recommendedAction: 'İlk olay keşfi ve plan→dispatch geçişini incele.',
    note: 'Review threshold — hard-coded business truth değil.',
  },
  {
    id: 'thresh.day_7_reach',
    metricLabel: 'Day 7 reach rate',
    condition: 'below',
    thresholdValue: '20%',
    severity: 'review',
    recommendedAction: 'Pilot pacing ve gün yoğunluğunu gözden geçir.',
    note: 'Review threshold — hard-coded business truth değil.',
  },
  {
    id: 'thresh.day_8_reach',
    metricLabel: 'Day 8 reach rate',
    condition: 'below',
    thresholdValue: '10%',
    severity: 'review',
    recommendedAction: 'Post-pilot değer önerisi ve Day 8 onboarding incele.',
    note: 'Review threshold — hard-coded business truth değil.',
  },
  {
    id: 'thresh.offer_high_purchase_start_low',
    metricLabel: 'Offer view vs purchase start gap',
    condition: 'gap_high',
    thresholdValue: 'offer_view >> purchase_start',
    severity: 'investigate',
    recommendedAction: 'IAP copy ve ürün sunumu incele.',
    note: 'Review threshold — hard-coded business truth değil.',
  },
  {
    id: 'thresh.purchase_start_low',
    metricLabel: 'Purchase start vs completion gap',
    condition: 'gap_high',
    thresholdValue: 'purchase_started >> purchase_completed',
    severity: 'investigate',
    recommendedAction: 'Store/RevenueCat/IAP sandbox sorunlarını incele.',
    note: 'Review threshold — hard-coded business truth değil.',
  },
  {
    id: 'thresh.report_view_low',
    metricLabel: 'Report view rate',
    condition: 'below',
    thresholdValue: 'benchmark TBD',
    severity: 'review',
    recommendedAction: 'Rapor yoğunluğu ve carry-over tekrarını incele.',
    note: 'Review threshold — hard-coded business truth değil.',
  },
  {
    id: 'thresh.map_view_low',
    metricLabel: 'Map intelligence view rate',
    condition: 'below',
    thresholdValue: 'benchmark TBD',
    severity: 'review',
    recommendedAction: 'Map CTA ve keşfedilebilirlik incele.',
    note: 'Review threshold — hard-coded business truth değil.',
  },
];

export const POST_LAUNCH_TELEMETRY_REVIEW_QUESTIONS: CreviaTelemetryReviewQuestion[] = [
  {
    id: 'q.first_event_reach',
    question: 'Oyuncular ilk event\'e ulaşıyor mu?',
    relatedKpiIds: ['kpi.first_event_inspect'],
    relatedFunnelIds: ['first_session_funnel'],
    dataSource: 'first_event_opened / first_session_funnel',
    owner: 'product',
  },
  {
    id: 'q.first_report_seen',
    question: 'İlk raporu görüyor mu?',
    relatedKpiIds: ['kpi.first_report'],
    relatedFunnelIds: ['first_session_funnel', 'day_1_completion_funnel'],
    dataSource: 'report_opened day=1',
    owner: 'product',
  },
  {
    id: 'q.day_2_transition',
    question: 'Day 2\'ye geçiyor mu?',
    relatedKpiIds: ['kpi.day_2_reached'],
    relatedFunnelIds: ['day_1_completion_funnel'],
    dataSource: 'pilot_day_started pilotDay=2',
    owner: 'product',
  },
  {
    id: 'q.day_7_reach',
    question: 'Day 7\'ye ulaşıyor mu?',
    relatedKpiIds: ['kpi.pilot_day_7'],
    relatedFunnelIds: ['pilot_completion_funnel'],
    dataSource: 'day7_report_opened',
    owner: 'product',
  },
  {
    id: 'q.day_8_offer',
    question: 'Day 8 teklifini görüyor mu?',
    relatedKpiIds: ['kpi.post_pilot_offer_viewed', 'kpi.day_8_reached'],
    relatedFunnelIds: ['pilot_completion_funnel', 'open_ended_engagement_funnel'],
    dataSource: 'post_pilot_offer_opened + main_operation_day_started',
    owner: 'monetization',
  },
  {
    id: 'q.hub_open_ended',
    question: 'Hub open-ended card işe yarıyor mu?',
    relatedKpiIds: ['kpi.hub_open_ended_card'],
    relatedFunnelIds: ['open_ended_engagement_funnel'],
    dataSource: 'hub_open_ended_card_viewed',
    owner: 'product',
  },
  {
    id: 'q.map_intelligence',
    question: 'Map intelligence kullanılıyor mu?',
    relatedKpiIds: ['kpi.map_district_intelligence'],
    relatedFunnelIds: ['open_ended_engagement_funnel'],
    dataSource: 'map_district_intelligence_viewed',
    owner: 'product',
  },
  {
    id: 'q.report_density',
    question: 'Report çok ağır mı?',
    relatedKpiIds: ['kpi.report_systems_card', 'kpi.tomorrow_carryover'],
    relatedFunnelIds: [],
    dataSource: 'report_systems_card_viewed + session length proxy',
    owner: 'product',
  },
  {
    id: 'q.profile_career',
    question: 'Profile career showcase açılıyor mu?',
    relatedKpiIds: ['kpi.profile_career_showcase'],
    relatedFunnelIds: [],
    dataSource: 'profile_career_showcase_viewed',
    owner: 'product',
  },
  {
    id: 'q.iap_offer_view',
    question: 'IAP offer görüntüleniyor mu?',
    relatedKpiIds: ['kpi.iap_offer_viewed'],
    relatedFunnelIds: ['iap_funnel'],
    dataSource: 'post_pilot_offer_opened',
    owner: 'monetization',
  },
  {
    id: 'q.purchase_dropoff',
    question: 'Purchase flow nerede düşüyor?',
    relatedKpiIds: ['kpi.iap_purchase_started', 'kpi.iap_purchase_completed'],
    relatedFunnelIds: ['iap_funnel'],
    dataSource: 'iap_* funnel steps',
    owner: 'monetization',
  },
  {
    id: 'q.restore_usage',
    question: 'Restore kullanılıyor mu?',
    relatedKpiIds: ['kpi.iap_restore_started', 'kpi.iap_restore_completed'],
    relatedFunnelIds: ['iap_funnel'],
    dataSource: 'iap_restore_*',
    owner: 'monetization',
  },
  {
    id: 'q.district_action',
    question: 'District operation action seçiliyor mu?',
    relatedKpiIds: ['kpi.district_operation_action'],
    relatedFunnelIds: ['open_ended_engagement_funnel'],
    dataSource: 'map_district_operation_hint_viewed (selection gap)',
    owner: 'product',
  },
  {
    id: 'q.story_chain_hints',
    question: 'Story chain hints okunuyor mu?',
    relatedKpiIds: ['kpi.story_chain_hint'],
    relatedFunnelIds: [],
    dataSource: 'manual — event schema gap',
    owner: 'product',
  },
  {
    id: 'q.operation_era',
    question: 'Operation era preview fark ediliyor mu?',
    relatedKpiIds: ['kpi.operation_era_line'],
    relatedFunnelIds: [],
    dataSource: 'hub_open_ended_focus_line_viewed proxy',
    owner: 'product',
  },
  {
    id: 'q.resource_fatigue',
    question: 'Resource fatigue oyuncuyu kaçırıyor mu?',
    relatedKpiIds: ['kpi.route_resource_warning'],
    relatedFunnelIds: [],
    dataSource: 'active_route_resource_warning_viewed + churn cohort',
    owner: 'product',
  },
  {
    id: 'q.crash',
    question: 'Crash var mı?',
    relatedKpiIds: ['kpi.crash_rate'],
    relatedFunnelIds: [],
    dataSource: 'crash SDK placeholder / manual reports',
    owner: 'engineering',
  },
  {
    id: 'q.offline',
    question: 'Offline davranış sorunlu mu?',
    relatedKpiIds: ['kpi.offline_graceful'],
    relatedFunnelIds: [],
    dataSource: 'manual QA + iap offline cases',
    owner: 'engineering',
  },
  {
    id: 'q.platform_split',
    question: 'Android/iOS farkı var mı?',
    relatedKpiIds: [],
    relatedFunnelIds: ['first_session_funnel', 'iap_funnel'],
    dataSource: 'platform segment (SDK sonrası)',
    owner: 'product',
  },
  {
    id: 'q.small_screen',
    question: 'Küçük ekranlarda drop-off artıyor mu?',
    relatedKpiIds: [],
    relatedFunnelIds: ['first_session_funnel'],
    dataSource: 'screen size segment (SDK sonrası) + playtest notes',
    owner: 'product',
  },
];

/** Funnel/KPI için şema doğrulamasında taranan event adları. */
export function collectPostLaunchTelemetryRequiredEvents(): AnalyticsEventName[] {
  const names = new Set<AnalyticsEventName>();

  for (const kpi of POST_LAUNCH_TELEMETRY_KPI_DEFINITIONS) {
    if (
      kpi.sourceEvent !== 'manual_proxy' &&
      kpi.sourceEvent !== 'placeholder'
    ) {
      names.add(kpi.sourceEvent);
    }
  }

  for (const funnel of POST_LAUNCH_TELEMETRY_FUNNEL_DEFINITIONS) {
    for (const step of funnel.orderedSteps) {
      if (step.sourceEvent !== 'manual_proxy') {
        names.add(step.sourceEvent);
      }
    }
    if (funnel.successEvent !== 'manual_proxy') {
      names.add(funnel.successEvent);
    }
  }

  for (const card of POST_LAUNCH_TELEMETRY_DASHBOARD_CARDS) {
    for (const ev of card.sourceEvents) {
      if (ev !== 'manual_proxy' && ev !== 'placeholder') {
        names.add(ev);
      }
    }
  }

  return [...names];
}
