import type {
  CreviaMapLayerCategory,
  CreviaMapLayerDefinition,
  CreviaMapLayerId,
  CreviaMapLayerStatus,
  CreviaMapLayerUnlockAxis,
} from './mapLayerTypes';

export const CREVIA_MAP_LAYER_REQUIRED_IDS: readonly CreviaMapLayerId[] = [
  'base_districts',
  'district_identity',
  'resource_pressure',
  'resource_fatigue',
  'social_pulse',
  'crisis_watch',
  'district_trust',
  'district_memory',
  'active_task_route',
  'event_family_signal',
  'operation_era',
  'city_development',
] as const;

export const CREVIA_MAP_LAYER_CATEGORIES: readonly CreviaMapLayerCategory[] = [
  'base',
  'resource',
  'social',
  'crisis',
  'district',
  'route',
  'event_content',
  'progression',
  'city_growth',
] as const;

export const CREVIA_MAP_LAYER_UNLOCK_AXES: readonly CreviaMapLayerUnlockAxis[] = [
  'day',
  'rank_permission',
  'authority',
  'xp',
  'district_trust',
  'resource_stability',
  'crisis_state',
  'operation_era',
  'future_system',
] as const;

export const CREVIA_MAP_LAYER_DEFINITIONS: readonly CreviaMapLayerDefinition[] = [
  {
    id: 'base_districts',
    title: 'Temel Mahalle Görünümü',
    shortLabel: 'Mahalleler',
    description: 'Şehir haritasındaki temel mahalle görünümünü gösterir.',
    category: 'base',
    unlockAxis: 'day',
    minDay: 1,
    isFutureOnly: false,
    playerFacingPriority: 10,
    iconKey: 'map-outline',
    tone: 'neutral',
  },
  {
    id: 'district_identity',
    title: 'Mahalle Kimliği',
    shortLabel: 'Kimlik',
    description: 'Mahalle karakteri ve risk odağını harita bağlamına taşır.',
    category: 'district',
    unlockAxis: 'day',
    minDay: 1,
    isFutureOnly: false,
    playerFacingPriority: 20,
    iconKey: 'location-outline',
    tone: 'neutral',
  },
  {
    id: 'resource_pressure',
    title: 'Kaynak Baskısı',
    shortLabel: 'Kaynak',
    description: 'Araç, personel ve konteyner baskısını harita odağına taşır.',
    category: 'resource',
    unlockAxis: 'rank_permission',
    requiredPermissionId: 'map_resource_layer',
    minDay: 3,
    isFutureOnly: false,
    playerFacingPriority: 30,
    iconKey: 'construct-outline',
    tone: 'warning',
  },
  {
    id: 'resource_fatigue',
    title: 'Kaynak Yorgunluğu',
    shortLabel: 'Yorgunluk',
    description: 'Kaynak yorgunluğu ve bakım sinyallerini harita katmanı olarak hazırlar.',
    category: 'resource',
    unlockAxis: 'resource_stability',
    requiredPermissionId: 'resource_pressure_summary',
    minDay: 3,
    isFutureOnly: false,
    playerFacingPriority: 35,
    iconKey: 'battery-half-outline',
    tone: 'warning',
  },
  {
    id: 'social_pulse',
    title: 'Sosyal Nabız',
    shortLabel: 'Sosyal',
    description: 'Sosyal nabız ve mahalle algısını haritada özetler.',
    category: 'social',
    unlockAxis: 'rank_permission',
    requiredPermissionId: 'map_social_layer',
    minDay: 4,
    isFutureOnly: false,
    playerFacingPriority: 40,
    iconKey: 'chatbubble-ellipses-outline',
    tone: 'neutral',
  },
  {
    id: 'crisis_watch',
    title: 'Kriz İzleme',
    shortLabel: 'Kriz',
    description: 'Kriz izleme sinyallerini harita önceliği olarak gösterir.',
    category: 'crisis',
    unlockAxis: 'crisis_state',
    requiredPermissionId: 'map_crisis_layer',
    minDay: 5,
    requiresCrisisState: true,
    isFutureOnly: false,
    playerFacingPriority: 50,
    iconKey: 'warning-outline',
    tone: 'warning',
  },
  {
    id: 'district_trust',
    title: 'Mahalle Güveni',
    shortLabel: 'Güven',
    description: 'Mahalle güveni ve uzun vadeli ilişki trendini harita katmanı olarak hazırlar.',
    category: 'district',
    unlockAxis: 'district_trust',
    requiredPermissionId: 'district_trust_preview',
    minDay: 4,
    requiresDistrictTrust: true,
    isFutureOnly: false,
    playerFacingPriority: 60,
    iconKey: 'heart-outline',
    tone: 'positive',
  },
  {
    id: 'district_memory',
    title: 'Mahalle Hafıza İzi',
    shortLabel: 'Hafıza',
    description: 'Önceki karar izlerini mahalle hafızası olarak harita bağlamına hazırlar.',
    category: 'district',
    unlockAxis: 'district_trust',
    requiredPermissionId: 'district_memory_trace_preview',
    minDay: 4,
    requiresDistrictTrust: true,
    isFutureOnly: false,
    playerFacingPriority: 65,
    iconKey: 'time-outline',
    tone: 'neutral',
  },
  {
    id: 'active_task_route',
    title: 'Aktif Görev Rotası',
    shortLabel: 'Rota',
    description: 'Seçili operasyonun saha yönünü route foundation olarak hazırlar.',
    category: 'route',
    unlockAxis: 'rank_permission',
    requiredPermissionId: 'assignment_fit_preview',
    minDay: 3,
    isFutureOnly: false,
    playerFacingPriority: 70,
    iconKey: 'git-branch-outline',
    tone: 'neutral',
  },
  {
    id: 'event_family_signal',
    title: 'Olay Ailesi Sinyali',
    shortLabel: 'Olay Ailesi',
    description: 'Event family foundation sinyallerini harita bağlamına hazırlayan preview katmanı.',
    category: 'event_content',
    unlockAxis: 'rank_permission',
    requiredPermissionId: 'event_family_rotation_preview',
    minDay: 8,
    isFutureOnly: false,
    playerFacingPriority: 80,
    iconKey: 'repeat-outline',
    tone: 'neutral',
  },
  {
    id: 'operation_era',
    title: 'Operasyon Dönemi',
    shortLabel: 'Dönem',
    description: 'Operation era temasını harita katmanı olarak ileride görünür kılar.',
    category: 'progression',
    unlockAxis: 'operation_era',
    requiredPermissionId: 'operation_era_preview',
    minDay: 8,
    isFutureOnly: false,
    playerFacingPriority: 90,
    iconKey: 'compass-outline',
    tone: 'positive',
  },
  {
    id: 'city_development',
    title: 'Şehir Gelişimi',
    shortLabel: 'Şehir',
    description: 'Şehir gelişimi katmanı ilerleyen sistemler için future foundation olarak tutulur.',
    category: 'city_growth',
    unlockAxis: 'future_system',
    requiredPermissionId: 'city_development_preview',
    isFutureOnly: true,
    playerFacingPriority: 100,
    iconKey: 'business-outline',
    tone: 'positive',
  },
] as const;

export const CREVIA_MAP_LAYER_DEFAULT_ORDER: readonly CreviaMapLayerId[] =
  CREVIA_MAP_LAYER_REQUIRED_IDS;

export const CREVIA_MAP_LAYER_FORBIDDEN_COPY_TERMS: readonly string[] = [
  '14 günlük sezon',
  'sezon sonu',
  'sezon finali',
  'yeni sezona başla',
  'premium al',
  'paywall',
  'panik',
  'felaket',
  'çöküş',
] as const;

export const CREVIA_MAP_LAYER_MAX_VISIBLE_CHIPS = 4;

export const CREVIA_MAP_LAYER_DAY_VISIBILITY_RULES = {
  day1: ['base_districts', 'district_identity'],
  day2Preview: ['resource_pressure'],
  day3: ['resource_pressure', 'resource_fatigue', 'active_task_route'],
  day4: ['social_pulse', 'district_trust', 'district_memory'],
  day5: ['crisis_watch'],
  day8: ['event_family_signal', 'operation_era'],
} as const;

export const CREVIA_MAP_LAYER_SAFE_DEFAULT_LAYER_ID: CreviaMapLayerId = 'base_districts';

export const CREVIA_MAP_LAYER_STATUS_LABELS: Record<CreviaMapLayerStatus, string> = {
  active: 'Aktif',
  available: 'Açık',
  preview: 'Sırada',
  locked_by_rank: 'Yetkiyle açılır',
  hidden: 'Gizli',
  future: 'İleride',
};

export const CREVIA_MAP_LAYER_CATEGORY_LABELS: Record<CreviaMapLayerCategory, string> = {
  base: 'Temel',
  resource: 'Kaynak',
  social: 'Sosyal',
  crisis: 'Kriz',
  district: 'Mahalle',
  route: 'Rota',
  event_content: 'Olay İçeriği',
  progression: 'Progression',
  city_growth: 'Şehir Gelişimi',
};

export const CREVIA_MAP_LAYER_PERMISSION_IDS = [
  'map_resource_layer',
  'map_social_layer',
  'map_crisis_layer',
  'map_trust_layer',
  'district_trust_preview',
  'district_memory_trace_preview',
  'assignment_fit_preview',
  'event_family_rotation_preview',
  'operation_era_preview',
  'city_development_preview',
] as const;
