import type { EceStrategyContentLine } from './eceStrategyLineContentPack';

export const ECE_STRATEGY_LINE_CONTENT_PACK_EXPANSION: EceStrategyContentLine[] = [
  {
    id: 'expansion-day-start-1',
    kind: 'day_start_briefing',
    tone: 'calm',
    text: 'Yeni fazda sakin acilis: once tabloyu oku, sonra tek bir net oncelik sec.',
  },
  {
    id: 'expansion-day-start-2',
    kind: 'day_start_briefing',
    tone: 'strategic',
    text: 'Ileri fazda ritim netlesiyor; bugun guvenle tek odaga odaklanabilirsin.',
  },
  {
    id: 'expansion-day-start-3',
    kind: 'day_start_briefing',
    tone: 'mentor',
    text: 'Sabah notu: acele etmeden en gorunur sinyali sec, gerisini takibe birak.',
  },
  {
    id: 'expansion-day-start-4',
    kind: 'day_start_briefing',
    tone: 'calm',
    text: 'Yeni fazda ilk adim sakin okuma; buyuk hamle bugun sart degil.',
  },
  {
    id: 'expansion-day-start-5',
    kind: 'day_start_briefing',
    tone: 'strategic',
    text: 'Ileri fazda tablo daha okunur; stratejik oncelik secimi artik daha guvenli.',
  },
  {
    id: 'expansion-day-start-6',
    kind: 'day_start_briefing',
    tone: 'calm',
    text: 'Gunun basinda kapasiteyi koru; net sinyal gelene kadar izleme yeterli.',
  },
  {
    id: 'expansion-hub-1',
    kind: 'hub_strategy_hint',
    tone: 'strategic',
    text: 'Merkezdeki tablo netlesmeden kaynak harcama; once sinyali sabitle.',
  },
  {
    id: 'expansion-hub-2',
    kind: 'hub_strategy_hint',
    tone: 'calm',
    text: 'Yeni fazda merkezinde sakin tempo iyi; her kart operasyon istemiyor.',
  },
  {
    id: 'expansion-hub-3',
    kind: 'hub_strategy_hint',
    tone: 'mentor',
    text: 'Iyi hamle buyuk olmak zorunda degil; dogru yerde kucuk secim yeter.',
  },
  {
    id: 'expansion-hub-4',
    kind: 'hub_strategy_hint',
    tone: 'strategic',
    text: 'Ileri fazda merkez daha guven veriyor; oncelik secimi netlesiyor.',
  },
  {
    id: 'expansion-hub-5',
    kind: 'hub_strategy_hint',
    tone: 'calm',
    text: 'Once baskiyi oku, sonra operasyonu sec; bugun bu sira daha temiz sonuc verir.',
  },
  {
    id: 'expansion-hub-6',
    kind: 'hub_strategy_hint',
    tone: 'strategic',
    text: 'Stratejik guven artti; bugun tek odak secimi daha rahat yapilabilir.',
  },
  {
    id: 'expansion-portfolio-1',
    kind: 'portfolio_tradeoff',
    tone: 'strategic',
    text: 'Secmedigin isler de hafizada kalir; portfoy dengesi yarin baskisini belirler.',
  },
  {
    id: 'expansion-portfolio-2',
    kind: 'portfolio_tradeoff',
    tone: 'cautious',
    text: 'Ayni anda her seyi cozme; ertelenen riski gorunur tutmak daha saglam.',
  },
  {
    id: 'expansion-portfolio-3',
    kind: 'portfolio_tradeoff',
    tone: 'mentor',
    text: 'Iyi portfoy karari, secileni ve beklemeye alinani birlikte acik tutar.',
  },
  {
    id: 'expansion-portfolio-4',
    kind: 'portfolio_tradeoff',
    tone: 'strategic',
    text: 'Ileri fazda portfoy okumasi daha net; tradeoff secimi guvenle yapilabilir.',
  },
  {
    id: 'expansion-portfolio-5',
    kind: 'portfolio_tradeoff',
    tone: 'calm',
    text: 'Yeni fazda portfoyunde sakin secim; kapasiteyi dagitmadan bir iz birak.',
  },
  {
    id: 'expansion-portfolio-6',
    kind: 'portfolio_tradeoff',
    tone: 'strategic',
    text: 'Bu plan kaynaklari dagitmiyor; sonraki hamle icin okunabilir iz birakiyor.',
  },
  {
    id: 'expansion-defer-1',
    kind: 'defer_follow_up',
    tone: 'cautious',
    text: 'Erteledigimiz sinyal kapanmadi; dogru zamanda bakilmak uzere bekliyor.',
  },
  {
    id: 'expansion-defer-2',
    kind: 'defer_follow_up',
    tone: 'strategic',
    text: 'Bugun dokunmadigin baski, yarin plan yaparken ilk kontrol noktasi olabilir.',
  },
  {
    id: 'expansion-defer-3',
    kind: 'defer_follow_up',
    tone: 'mentor',
    text: 'Ertelemek vazgecmek degil; izi kaybetmeden siraya almak daha iyi tercih.',
  },
  {
    id: 'expansion-defer-4',
    kind: 'defer_follow_up',
    tone: 'warning',
    text: 'Erteledigin takip notu kaybolmaz; dogru anda geri donmek yeterli olabilir.',
  },
  {
    id: 'expansion-defer-5',
    kind: 'defer_follow_up',
    tone: 'calm',
    text: 'Yeni fazda erteleme notu sakin tutulmali; iz kaybolmadan beklemeye al.',
  },
  {
    id: 'expansion-defer-6',
    kind: 'defer_follow_up',
    tone: 'strategic',
    text: 'Ileri fazda erteleme maliyeti daha okunur; takip notu kritik.',
  },
  {
    id: 'expansion-resource-1',
    kind: 'resource_pressure',
    tone: 'warning',
    text: 'Kaynak baskisi artmadan once tek hedefe odaklanmak daha guvenli.',
  },
  {
    id: 'expansion-resource-2',
    kind: 'resource_pressure',
    tone: 'cautious',
    text: 'Ekip ve butce ayni anda yoruluyorsa bugun daha kisa hamle sec.',
  },
  {
    id: 'expansion-resource-3',
    kind: 'resource_pressure',
    tone: 'strategic',
    text: 'Kaynak sikisikligi dogru siralama ister; once en cok etki veren isi al.',
  },
  {
    id: 'expansion-resource-4',
    kind: 'resource_pressure',
    tone: 'mentor',
    text: 'Kapasite daraldiginda az is secip tamamlamak bazen en iyi yonetimdir.',
  },
  {
    id: 'expansion-resource-5',
    kind: 'resource_pressure',
    tone: 'calm',
    text: 'Yeni fazda kaynak tablosu sakin; kapasiteyi koruyarak tek oncelik sec.',
  },
  {
    id: 'expansion-resource-6',
    kind: 'resource_pressure',
    tone: 'strategic',
    text: 'Ileri fazda kaynak okumasi guvenli; maliyet secimi daha net.',
  },
  {
    id: 'expansion-style-1',
    kind: 'player_style_reflection',
    tone: 'mentor',
    text: 'Karar tarzinda sakin takip gucleniyor; bu ritmi bugunku plana tasiyabilirsin.',
  },
  {
    id: 'expansion-style-2',
    kind: 'player_style_reflection',
    tone: 'positive',
    text: 'Son secimler acele etmeden okudugunu gosteriyor; sehir icin iyi aliskanlik.',
  },
  {
    id: 'expansion-style-3',
    kind: 'player_style_reflection',
    tone: 'strategic',
    text: 'Son gunlerde riski onceleyip etkiyi sonra buyutmen okunakli bir ritim veriyor.',
  },
  {
    id: 'expansion-style-4',
    kind: 'player_style_reflection',
    tone: 'calm',
    text: 'Sakin karar ritmini korursan merkez daha okunabilir hale gelir.',
  },
  {
    id: 'expansion-style-5',
    kind: 'player_style_reflection',
    tone: 'strategic',
    text: 'Ileri fazda tarz sinyali guclu; stratejik guvenle devam edebilirsin.',
  },
  {
    id: 'expansion-style-6',
    kind: 'player_style_reflection',
    tone: 'mentor',
    text: 'Yeni fazda tarz okumasi sakin; aliskanlik henuz olusuyor, acele etme.',
  },
  {
    id: 'expansion-recovery-1',
    kind: 'recovery_opportunity',
    tone: 'positive',
    text: 'Toparlanma penceresi acik; kucuk hamle buyuk mudahaleden once degerli.',
  },
  {
    id: 'expansion-recovery-2',
    kind: 'recovery_opportunity',
    tone: 'strategic',
    text: 'Iyilesme sinyali dusuk maliyetle korunabilir; firsati not al.',
  },
  {
    id: 'expansion-recovery-3',
    kind: 'recovery_opportunity',
    tone: 'calm',
    text: 'Yeni fazda toparlanma sinyali sakin; kucuk takip yeterli olabilir.',
  },
  {
    id: 'expansion-recovery-4',
    kind: 'recovery_opportunity',
    tone: 'positive',
    text: 'Olumlu donus izi gorunur; devam hamlesi momentumu korur.',
  },
  {
    id: 'expansion-recovery-5',
    kind: 'recovery_opportunity',
    tone: 'strategic',
    text: 'Ileri fazda toparlanma okumasi guvenli; firsat secimi netlesiyor.',
  },
  {
    id: 'expansion-recovery-6',
    kind: 'recovery_opportunity',
    tone: 'mentor',
    text: 'Risk kadar firsati da oku; kucuk iyilesme yarin yuku azaltir.',
  },
  {
    id: 'expansion-warning-1',
    kind: 'warning_caution',
    tone: 'warning',
    text: 'Baski sessizce buyuyebilir; erken not almak maliyeti dusurur.',
  },
  {
    id: 'expansion-warning-2',
    kind: 'warning_caution',
    tone: 'cautious',
    text: 'Ayni bolgeyi uzun pas gecmek yarin onceligi degistirebilir.',
  },
  {
    id: 'expansion-warning-3',
    kind: 'warning_caution',
    tone: 'warning',
    text: 'Kaynak ve ekip ayni anda zorlaniyorsa bugun sinirli kal.',
  },
  {
    id: 'expansion-warning-4',
    kind: 'warning_caution',
    tone: 'cautious',
    text: 'Sosyal sinyal gec okunursa iletisim maliyeti artabilir.',
  },
  {
    id: 'expansion-warning-5',
    kind: 'warning_caution',
    tone: 'warning',
    text: 'Erteleme notu kaybolursa ayni baski tekrar tabloya gelir.',
  },
  {
    id: 'expansion-warning-6',
    kind: 'warning_caution',
    tone: 'cautious',
    text: 'Yeni fazda dikkat: dusuk veriyle agresif secim riskli olabilir.',
  },
  {
    id: 'expansion-positive-1',
    kind: 'positive_reinforcement',
    tone: 'positive',
    text: 'Son hamle olumlu iz birakti; ayni hatta kucuk devam etkisi buyutebilir.',
  },
  {
    id: 'expansion-positive-2',
    kind: 'positive_reinforcement',
    tone: 'positive',
    text: 'Sakin tempo ise yariyor; bugun de ayni ritmi koruyabilirsin.',
  },
  {
    id: 'expansion-positive-3',
    kind: 'positive_reinforcement',
    tone: 'positive',
    text: 'Kucuk kazanim gorunur; momentumu korumak dusuk maliyetli.',
  },
  {
    id: 'expansion-positive-4',
    kind: 'positive_reinforcement',
    tone: 'mentor',
    text: 'Iyi okuma aliskanligi olusuyor; sehir bunu zamanla daha net gosterir.',
  },
  {
    id: 'expansion-positive-5',
    kind: 'positive_reinforcement',
    tone: 'positive',
    text: 'Ileri fazda ilerleme okunur; stratejik guvenle devam et.',
  },
  {
    id: 'expansion-positive-6',
    kind: 'positive_reinforcement',
    tone: 'calm',
    text: 'Yeni fazda sakin ilerleme de degerli; tablo zamanla netlesiyor.',
  },
  {
    id: 'expansion-consequence-1',
    kind: 'decision_consequence',
    tone: 'strategic',
    text: 'Onceki karar iz birakti; bugunku secim o izi guclendirir ya da yumusatir.',
  },
  {
    id: 'expansion-consequence-2',
    kind: 'decision_consequence',
    tone: 'cautious',
    text: 'Bu etki tek gunde kapanmaz; sakin takip hamlesi gerekir.',
  },
  {
    id: 'expansion-consequence-3',
    kind: 'decision_consequence',
    tone: 'mentor',
    text: 'Karar zincirini goruyorsun; iyi strateji bu baglantiyi okumak.',
  },
  {
    id: 'expansion-consequence-4',
    kind: 'decision_consequence',
    tone: 'positive',
    text: 'Dunku hamle bugun ise yariyor; kucuk devam etkisi buyutebilir.',
  },
  {
    id: 'expansion-consequence-5',
    kind: 'decision_consequence',
    tone: 'strategic',
    text: 'Ileri fazda etki zinciri daha okunur; sonucu guvenle takip et.',
  },
  {
    id: 'expansion-consequence-6',
    kind: 'decision_consequence',
    tone: 'calm',
    text: 'Yeni fazda etki okumasi sakin; iz zamanla netlesir.',
  },
  {
    id: 'expansion-map-1',
    kind: 'map_priority',
    tone: 'strategic',
    text: 'Haritadaki yogunluk tek noktada; once orayi sakinlestirmek verimli.',
  },
  {
    id: 'expansion-map-2',
    kind: 'map_priority',
    tone: 'cautious',
    text: 'Rota baskisi dagilmadan kaynaklari yorma; en yakin net sinyale odaklan.',
  },
  {
    id: 'expansion-map-3',
    kind: 'map_priority',
    tone: 'mentor',
    text: 'Harita sadece yer gostermez; hangi karar gec kalmadan alinmali onu anlatir.',
  },
  {
    id: 'expansion-map-4',
    kind: 'map_priority',
    tone: 'positive',
    text: 'Dogru rota secimi bugunku operasyonu kisaltir, ekibi dengeli tutar.',
  },
  {
    id: 'expansion-map-5',
    kind: 'map_priority',
    tone: 'strategic',
    text: 'Ileri fazda harita okumasi guvenli; oncelik secimi netlesiyor.',
  },
  {
    id: 'expansion-map-6',
    kind: 'map_priority',
    tone: 'calm',
    text: 'Yeni fazda haritasi sakin; tek noktaya odaklan, gerisini izlemeye birak.',
  },
];
