import type {
  CreviaFreezeAllowedScope,
  CreviaFreezeForbiddenScope,
  CreviaFreezeManualBlocker,
  CreviaFreezePromptGuardItem,
} from './noNewSystemFreezeTypes';

export const NO_NEW_SYSTEM_FREEZE_DOCS_PATH = 'docs/crevia-no-new-system-freeze.md';

export const NO_NEW_SYSTEM_FREEZE_EXPECTED_SAVE_VERSION = 25;

export const NO_NEW_SYSTEM_FREEZE_ALLOWED_SCOPES: readonly CreviaFreezeAllowedScope[] = [
  'bugfix',
  'crash_fix',
  'layout_overflow_fix',
  'typo_copy_fix',
  'false_claim_copy_fix',
  'secret_hygiene_fix',
  'privacy_store_fix',
  'iap_setup_tracker_update',
  'iap_smoke_result_update',
  'real_device_playtest_result_update',
  'store_metadata_update',
  'screenshot_capture_status_update',
  'performance_selector_fix',
  'release_candidate_audit',
  'verification_only',
  'documentation_only',
] as const;

export const NO_NEW_SYSTEM_FREEZE_FORBIDDEN_SCOPES: readonly CreviaFreezeForbiddenScope[] = [
  'new_gameplay_system',
  'new_content_pack',
  'new_runtime_activation',
  'new_progression_system',
  'new_map_layer',
  'new_profile_system',
  'new_report_system',
  'new_hub_card_system',
  'new_analytics_event_schema',
  'save_version_bump',
  'persist_shape_change',
  'event_generation_rewrite',
  'applyDecision_rewrite',
  'dayPipeline_rewrite',
  'iap_purchase_flow_rewrite',
  'new_screen_or_route',
  'large_ui_redesign',
  'new_ai_runtime_feature',
  'remote_config_activation',
  'live_ops_calendar',
] as const;

export const NO_NEW_SYSTEM_FREEZE_MANUAL_BLOCKERS: readonly CreviaFreezeManualBlocker[] = [
  {
    id: 'manual.real_device_playtest_pending',
    title: 'Real device playtest pending',
    status: 'pending',
    drivesFreeze: true,
  },
  {
    id: 'manual.iap_sandbox_smoke_pending',
    title: 'IAP sandbox smoke pending',
    status: 'pending',
    drivesFreeze: true,
  },
  {
    id: 'manual.revenuecat_keys_pending',
    title: 'RevenueCat keys pending',
    status: 'pending',
    drivesFreeze: true,
  },
  {
    id: 'manual.app_store_product_pending',
    title: 'App Store product pending',
    status: 'pending',
    drivesFreeze: true,
  },
  {
    id: 'manual.play_console_product_pending',
    title: 'Play Console product pending',
    status: 'pending',
    drivesFreeze: true,
  },
  {
    id: 'manual.eas_secrets_pending',
    title: 'EAS secrets pending',
    status: 'pending',
    drivesFreeze: true,
  },
  {
    id: 'manual.privacy_url_placeholder',
    title: 'Privacy URL placeholder',
    status: 'pending',
    drivesFreeze: true,
  },
  {
    id: 'manual.screenshots_pending',
    title: 'Screenshots pending',
    status: 'pending',
    drivesFreeze: true,
  },
  {
    id: 'manual.metadata_console_entry_pending',
    title: 'Metadata console entry pending',
    status: 'pending',
    drivesFreeze: true,
  },
] as const;

export const NO_NEW_SYSTEM_FREEZE_PROMPT_GUARD: readonly CreviaFreezePromptGuardItem[] = [
  {
    id: 'guard.new_gameplay_system',
    question: 'Bu prompt yeni gameplay sistemi ekliyor mu?',
    rejectIfYes: true,
  },
  {
    id: 'guard.save_version_bump',
    question: 'Bu prompt SAVE_VERSION artırıyor mu?',
    rejectIfYes: true,
  },
  {
    id: 'guard.event_generation',
    question: 'Bu prompt runtime event generation değiştiriyor mu?',
    rejectIfYes: true,
  },
  {
    id: 'guard.apply_decision_day_pipeline',
    question: 'Bu prompt applyDecision/dayPipeline değiştiriyor mu?',
    rejectIfYes: true,
  },
  {
    id: 'guard.new_content_pack',
    question: 'Bu prompt yeni content pack ekliyor mu?',
    rejectIfYes: true,
  },
  {
    id: 'guard.release_blocker',
    question: 'Bu prompt release blocker kapatıyor mu?',
    rejectIfYes: false,
  },
  {
    id: 'guard.fix_only',
    question: 'Bu prompt sadece bugfix/readiness/polish mi?',
    rejectIfYes: false,
  },
  {
    id: 'guard.reject_policy',
    question: 'Cevap hayırsa prompt freeze sonrası reddedilmeli mi?',
    rejectIfYes: false,
  },
] as const;

export const NO_NEW_SYSTEM_FREEZE_REGISTERED_CONTENT_PACK_FILES = [
  'districtPackOne.ts',
  'vehicleRoutePackOne.ts',
  'containerEnvironmentPackOne.ts',
  'socialTrustPackOne.ts',
  'crisisAdjacentPackOne.ts',
] as const;

export const NO_NEW_SYSTEM_FREEZE_BASELINE_CORE_DIRS = [
  'src/core/activeTaskRoutes',
  'src/core/advisors',
  'src/core/advisorRelationship',
  'src/core/analytics',
  'src/core/animations',
  'src/core/assets',
  'src/core/assignments',
  'src/core/authority',
  'src/core/badges',
  'src/core/balance',
  'src/core/brand',
  'src/core/carryOver',
  'src/core/cityEchoBinding',
  'src/core/cityArchive',
  'src/core/cityArchivePlanning',
  'src/core/cityJournal',
  'src/core/crashPerformance',
  'src/core/containerNetwork',
  'src/core/containers',
  'src/core/content',
  'src/core/contentPacks',
  'src/core/contentProduction',
  'src/core/contentQuality',
  'src/core/contentRuntimeActivation',
  'src/core/crisis',
  'src/core/crisisActions',
  'src/core/dailyGoals',
  'src/core/dailyPlanning',
  'src/core/dailyPriority',
  'src/core/dayPipeline',
  'src/core/decisionImpactExplanation',
  'src/core/districtMemoryRuntime',
  'src/core/districtOperationActions',
  'src/core/districtOperations',
  'src/core/districtOperationsRuntime',
  'src/core/districtReportCard',
  'src/core/districts',
  'src/core/districtTrust',
  'src/core/districtTrustRuntime',
  'src/core/economy',
  'src/core/eventFamilies',
  'src/core/eventFreshness',
  'src/core/events',
  'src/core/eventSelection',
  'src/core/eventVariants',
  'src/core/feedback',
  'src/core/fullLoop',
  'src/core/game',
  'src/core/hub',
  'src/core/hubQuickActions',
  'src/core/iap',
  'src/core/iapQa',
  'src/core/leaderboard',
  'src/core/liveFlow',
  'src/core/mainOperation',
  'src/core/mainOperationFeel',
  'src/core/map',
  'src/core/mapLayers',
  'src/core/mapPresence',
  'src/core/mapReactions',
  'src/core/mapReactionsMotion',
  'src/core/metaProgression',
  'src/core/microDecisions',
  'src/core/models',
  'src/core/motion',
  'src/core/monetization',
  'src/core/neighborhoodIdentity',
  'src/core/offlineResume',
  'src/core/onboarding',
  'src/core/openEndedProgression',
  'src/core/operationalResourcePresence',
  'src/core/operationalResources',
  'src/core/operationEra',
  'src/core/operations',
  'src/core/personnel',
  'src/core/pilotCompletion',
  'src/core/pilotRhythm',
  'src/core/playerStyle',
  'src/core/playtest',
  'src/core/postPilot',
  'src/core/presentation',
  'src/core/profile',
  'src/core/progression',
  'src/core/quality',
  'src/core/rankPermissions',
  'src/core/rewardComeback',
  'src/core/releaseReadiness',
  'src/core/reports',
  'src/core/resources',
  'src/core/seasonEnd',
  'src/core/security',
  'src/core/simulation',
  'src/core/social',
  'src/core/socialEcho',
  'src/core/softLaunchCoreCompleteness',
  'src/core/softLaunchRegressionCleanup',
  'src/core/manualLaunchTracker',
  'src/core/releaseCandidate',
  'src/core/releaseCandidatePolish',
  'src/core/storeScreenshotNarrative',
  'src/core/storeMetadataCopy',
  'src/core/privacyPolicyText',
  'src/core/iapProductCopy',
  'src/core/storyChains',
  'src/core/teamSpecialization',
  'src/core/tomorrowRisk',
  'src/core/uiDensity',
  'src/core/utils',
  'src/core/ux',
  'src/core/vehicleMaintenance',
  'src/core/vehicles',
  'src/core/xp',
] as const;

export const NO_NEW_SYSTEM_FREEZE_PROTECTED_RUNTIME_FILES = [
  'src/core/game/ensureDailyEventsForDay.ts',
  'src/core/game/applyDecision.ts',
  'src/core/dayPipeline/dayPipelineOrchestrator.ts',
  'src/store/gamePersist.ts',
] as const;

export const NO_NEW_SYSTEM_FREEZE_REGISTERED_APP_ROUTES = [
  'src/app/index.tsx',
  'src/app/_layout.tsx',
  'src/app/profile.tsx',
  'src/app/leaderboard.tsx',
  'src/app/post-pilot-offer.tsx',
  'src/app/events/index.tsx',
  'src/app/events/[id].tsx',
  'src/app/events/decision-result.tsx',
  'src/app/events/pilot-final-report.tsx',
  'src/app/events/main-operation-preview.tsx',
  'src/app/events/_layout.tsx',
  'src/app/reports/index.tsx',
  'src/app/reports/_layout.tsx',
  'src/app/social/index.tsx',
  'src/app/social/mentions.tsx',
  'src/app/social/outcome-history.tsx',
  'src/app/social/_layout.tsx',
  'src/app/risks/index.tsx',
  'src/app/risks/_layout.tsx',
  'src/app/progression/index.tsx',
  'src/app/progression/_layout.tsx',
] as const;

export const NO_NEW_SYSTEM_FREEZE_REGISTERED_CORE_DIRS = NO_NEW_SYSTEM_FREEZE_BASELINE_CORE_DIRS;

export const NO_NEW_SYSTEM_FREEZE_IAP_FLOW_FILES = [
  'src/core/iap/iapRuntimeService.ts',
  'src/core/iap/revenueCatIapAdapter.ts',
  'src/core/iap/iapOfferPresentation.ts',
] as const;

export const NO_NEW_SYSTEM_FREEZE_ANALYTICS_EVENT_REGISTRY = [
  'day_started',
  'decision_made',
  'event_resolved',
  'iap_offer_shown',
  'iap_purchase_started',
  'iap_purchase_completed',
  'iap_restore_started',
  'iap_restore_completed',
  'session_start',
  'session_end',
] as const;

export const NO_NEW_SYSTEM_FREEZE_FORBIDDEN_COPY_PATTERNS = [
  /14\s*g[üu]nl[üu]k\s*sezon/i,
  /sezon\s*finali/i,
  /oyun\s*bitti/i,
  /ger[çc]ek\s*zamanl[ıi]\s*gps/i,
  /resmi\s*kurum\s*onay/i,
] as const;

export const NO_NEW_SYSTEM_FREEZE_V11_BACKLOG = [
  'Yeni gameplay sistemi veya content pack',
  'Yeni progression veya profile sistemi',
  'Yeni hub card veya report sistemi',
  'Büyük UI redesign',
  'Remote config / live ops aktivasyonu',
  'Analytics event schema genişletmesi',
  'SAVE_VERSION bump ve persist shape değişikliği',
] as const;
