import type {
  CreviaAppStorePrivacyAnswerDraft,
  CreviaGooglePlayDataSafetyAnswerDraft,
  CreviaPrivacyDataCategory,
  CreviaPrivacyPolicySection,
  CreviaPrivacyThirdPartyProcessor,
} from './privacyPolicyReadinessTypes';

export const PRIVACY_POLICY_DRAFT_DOCS_PATH = 'docs/crevia-privacy-policy-draft.md';
export const DATA_SAFETY_DRAFT_DOCS_PATH = 'docs/crevia-data-safety-draft.md';

export const PRIVACY_POLICY_MIN_DATA_CATEGORIES = 10;

export const PRIVACY_POLICY_PUBLISHED_URL_PLACEHOLDER =
  'https://PENDING_PLACEHOLDER.crevia.app/privacy';

export const PRIVACY_POLICY_RISKY_WORDING_PATTERNS = [
  'resmi belediye uygulaması',
  'gerçek zamanlı gps',
  'canlı takip',
  'gerçek şehir verisi',
  'hiçbir veri toplamıyoruz',
  'kişisel veri toplamıyoruz',
  'tam anonim',
  'kvkk/gdpr tamamen uyumlu',
  'gdpr fully compliant',
  'we collect no data',
  'we do not collect any personal data',
  'completely anonymous',
] as const;

export const PRIVACY_POLICY_SECTIONS: CreviaPrivacyPolicySection[] = [
  {
    id: 'introduction',
    titleTr: 'Giriş',
    titleEn: 'Introduction',
    summaryTr: 'Bu taslak Crevia mobil oyunu için geçerlidir; hukuki danışmanlık yerine geçmez.',
    summaryEn: 'Draft for the Crevia mobile game; not legal advice.',
  },
  {
    id: 'what_crevia_is',
    titleTr: 'Crevia Nedir',
    titleEn: 'What Crevia Is',
    summaryTr: 'Kurgusal mahalle operasyon simülasyonu; resmi kurum veya canlı konum servisi değildir.',
    summaryEn: 'Fictional neighborhood operations simulation; not an official agency or live location app.',
  },
  {
    id: 'data_we_collect',
    titleTr: 'Topladığımız Veriler',
    titleEn: 'Data We Collect',
    summaryTr: 'Yapılandırılmış analitik, satın alma/entitlement durumu, sınırlı teknik veriler.',
    summaryEn: 'Structured analytics, purchase/entitlement status, limited technical data.',
  },
  {
    id: 'data_we_do_not_collect',
    titleTr: 'Toplamadığımız Veriler',
    titleEn: 'Data We Do Not Collect',
    summaryTr: 'Ham metin, save dump, hesap verisi, hassas konum, reklam kimliği toplanmaz.',
    summaryEn: 'No raw text, save dumps, account data, precise location, or ad IDs.',
  },
  {
    id: 'analytics_data',
    titleTr: 'Analitik Kullanımı',
    titleEn: 'Analytics',
    summaryTr: 'Structured event payloads; raw copy yok; SDK entegrasyonu doğrulanmalı.',
    summaryEn: 'Structured event payloads; no raw copy; SDK behavior must be confirmed.',
  },
  {
    id: 'purchase_payment_data',
    titleTr: 'Satın Alma ve RevenueCat',
    titleEn: 'Purchases and RevenueCat',
    summaryTr: 'Ödeme Apple/Google üzerinden; entitlement RevenueCat ile senkronize edilebilir.',
    summaryEn: 'Payments via Apple/Google; entitlement may sync via RevenueCat.',
  },
  {
    id: 'crash_logging_data',
    titleTr: 'Çökme / Tanılama Verileri',
    titleEn: 'Crash and Diagnostic Data',
    summaryTr: 'Sentry kod entegrasyonu hazır; DSN/dashboard smoke pending. PII/raw save gönderilmez.',
    summaryEn: 'Sentry code integration ready; DSN/dashboard smoke pending. No PII/raw save sent.',
  },
  {
    id: 'device_technical_data',
    titleTr: 'Cihaz / Uygulama Teknik Verileri',
    titleEn: 'Device and App Technical Data',
    summaryTr: 'Oturum kapsamlı teknik bağlam; reklam/izleme kimliği kullanılmaz.',
    summaryEn: 'Session-scoped technical context; no ad/tracking identifiers.',
  },
  {
    id: 'how_data_is_used',
    titleTr: 'Verilerin Kullanımı',
    titleEn: 'How Data Is Used',
    summaryTr: 'Ürün iyileştirme, erişim doğrulama, kararlılık (crash SDK sonrası).',
    summaryEn: 'Product improvement, access verification, stability (after crash SDK).',
  },
  {
    id: 'third_party_services',
    titleTr: 'Üçüncü Taraf Hizmetler',
    titleEn: 'Third-Party Services',
    summaryTr: 'RevenueCat, Apple StoreKit, Google Play Billing; crash/analytics provider pending.',
    summaryEn: 'RevenueCat, Apple StoreKit, Google Play Billing; crash/analytics provider pending.',
  },
  {
    id: 'data_sharing',
    titleTr: 'Verilerin Paylaşımı',
    titleEn: 'Data Sharing',
    summaryTr: 'Yalnızca işlev için gerekli processor’lar; ham metin paylaşılmaz.',
    summaryEn: 'Only processors required for functionality; no raw text shared.',
  },
  {
    id: 'data_retention',
    titleTr: 'Saklama Süresi',
    titleEn: 'Retention',
    summaryTr: 'Analitik ve satın alma saklama süreleri provider politikalarına bağlı.',
    summaryEn: 'Analytics and purchase retention follow provider policies.',
  },
  {
    id: 'children_privacy',
    titleTr: 'Çocukların Gizliliği',
    titleEn: "Children's Privacy",
    summaryTr: 'Çocuklara yönelik bilinçli veri toplama yok; yaş derecelendirmesi store formlarında.',
    summaryEn: 'No intentional collection from children; age rating via store forms.',
  },
  {
    id: 'user_rights_contact',
    titleTr: 'Haklarınız ve İletişim',
    titleEn: 'Your Rights and Contact',
    summaryTr: 'Destek e-postası üzerinden talep; yerel kayıt cihazda silinebilir.',
    summaryEn: 'Requests via support email; local save deletable on device.',
  },
  {
    id: 'international_note',
    titleTr: 'Uluslararası Erişim',
    titleEn: 'International Availability',
    summaryTr: 'Veri işleme ülkeye göre değişebilir; hukuki inceleme önerilir.',
    summaryEn: 'Processing may vary by region; legal review recommended.',
  },
  {
    id: 'policy_changes',
    titleTr: 'Politika Değişiklikleri',
    titleEn: 'Changes',
    summaryTr: 'Güncellemeler yayınlandığında bildirim veya store notu ile duyurulabilir.',
    summaryEn: 'Updates may be announced via publication or store notice.',
  },
  {
    id: 'contact_support',
    titleTr: 'İletişim',
    titleEn: 'Contact',
    summaryTr: 'support@PENDING_PLACEHOLDER.crevia.app — placeholder.',
    summaryEn: 'support@PENDING_PLACEHOLDER.crevia.app — placeholder.',
  },
];

export const PRIVACY_DATA_CATEGORY_MATRIX: CreviaPrivacyDataCategory[] = [
  {
    id: 'analytics_events',
    label: 'Analytics events',
    collected: 'yes',
    source: 'In-app structured analytics (no-op / future SDK)',
    purpose: 'Product improvement, funnel understanding',
    linkedToUser: false,
    usedForTracking: false,
    sharedWithThirdParty: 'pending',
    thirdPartyProcessor: 'Analytics provider placeholder',
    retentionNote: 'Per analytics provider policy when SDK wired',
    disclosureNote: 'No raw event copy or free text in payloads',
    confidence: 'medium',
    actionNeeded: 'Confirm SDK behavior before App Store / Play forms',
  },
  {
    id: 'app_interactions',
    label: 'App interactions',
    collected: 'yes',
    source: 'Structured screen/event impressions',
    purpose: 'Understand feature usage',
    linkedToUser: false,
    usedForTracking: false,
    sharedWithThirdParty: 'pending',
    thirdPartyProcessor: 'Analytics provider placeholder',
    retentionNote: 'Session-scoped in verify; provider TBD',
    disclosureNote: 'Allowlisted keys only',
    confidence: 'medium',
    actionNeeded: 'Map to App Store “App Interactions”',
  },
  {
    id: 'purchase_status',
    label: 'Purchase status',
    collected: 'yes',
    source: 'Apple StoreKit / Google Play Billing',
    purpose: 'Process one-time unlock',
    linkedToUser: 'pending',
    usedForTracking: false,
    sharedWithThirdParty: true,
    thirdPartyProcessor: 'Apple / Google',
    retentionNote: 'Per store policies',
    disclosureNote: 'No card data in app',
    confidence: 'high',
    actionNeeded: 'Complete sandbox smoke before launch',
  },
  {
    id: 'entitlement_status',
    label: 'Product / entitlement status',
    collected: 'yes',
    source: 'RevenueCat CustomerInfo sync',
    purpose: 'Unlock full Main Operation access',
    linkedToUser: 'pending',
    usedForTracking: false,
    sharedWithThirdParty: true,
    thirdPartyProcessor: 'RevenueCat',
    retentionNote: 'Per RevenueCat dashboard settings',
    disclosureNote: 'Entitlement id main_operation_full_access',
    confidence: 'medium',
    actionNeeded: 'Confirm RC data processing terms',
  },
  {
    id: 'crash_diagnostics',
    label: 'Crash diagnostics',
    collected: 'pending',
    source: 'Sentry SDK (code ready; env/dashboard pending)',
    purpose: 'Stability monitoring',
    linkedToUser: 'pending',
    usedForTracking: false,
    sharedWithThirdParty: 'pending',
    thirdPartyProcessor: 'Sentry (crash reporting)',
    retentionNote: 'Per Sentry project settings after activation',
    disclosureNote: 'Code integrated; declare pending until DSN + smoke on internal build',
    confidence: 'medium',
    actionNeeded: 'Set EXPO_PUBLIC_SENTRY_DSN and complete dashboard smoke',
  },
  {
    id: 'device_technical',
    label: 'Device / app technical info',
    collected: 'yes',
    source: 'App runtime / analytics base payload',
    purpose: 'Diagnostics context (day, access mode, surface)',
    linkedToUser: false,
    usedForTracking: false,
    sharedWithThirdParty: 'pending',
    thirdPartyProcessor: 'Analytics provider placeholder',
    retentionNote: 'Non-persistent session context in verify',
    disclosureNote: 'No advertising ID',
    confidence: 'medium',
    actionNeeded: 'Confirm device fields when SDK enabled',
  },
  {
    id: 'user_identifiers',
    label: 'User identifiers',
    collected: 'no',
    source: 'No login / no account system',
    purpose: 'N/A',
    linkedToUser: false,
    usedForTracking: false,
    sharedWithThirdParty: false,
    thirdPartyProcessor: 'None',
    retentionNote: 'N/A',
    disclosureNote: 'RevenueCat may assign anonymous customer id when IAP enabled',
    confidence: 'medium',
    actionNeeded: 'Confirm RC anonymous id disclosure',
  },
  {
    id: 'location_data',
    label: 'Location data',
    collected: 'no',
    source: 'Not collected — map is fictional simulation',
    purpose: 'N/A',
    linkedToUser: false,
    usedForTracking: false,
    sharedWithThirdParty: false,
    thirdPartyProcessor: 'None',
    retentionNote: 'N/A',
    disclosureNote: 'No precise GPS; in-game map is not live location',
    confidence: 'high',
    actionNeeded: 'None',
  },
  {
    id: 'raw_text_content',
    label: 'Raw text / content',
    collected: 'no',
    source: 'Explicitly excluded',
    purpose: 'N/A',
    linkedToUser: false,
    usedForTracking: false,
    sharedWithThirdParty: false,
    thirdPartyProcessor: 'None',
    retentionNote: 'N/A',
    disclosureNote: 'Analytics forbidden keys block raw copy',
    confidence: 'high',
    actionNeeded: 'None',
  },
  {
    id: 'save_data',
    label: 'Save data',
    collected: 'no',
    source: 'Local device only (AsyncStorage)',
    purpose: 'Gameplay progress on device',
    linkedToUser: false,
    usedForTracking: false,
    sharedWithThirdParty: false,
    thirdPartyProcessor: 'None',
    retentionNote: 'Until app uninstall / clear data',
    disclosureNote: 'Save dump not sent to analytics',
    confidence: 'high',
    actionNeeded: 'None',
  },
  {
    id: 'contact_support_email',
    label: 'Contact / support email',
    collected: 'pending',
    source: 'User-initiated email to support',
    purpose: 'Support requests only',
    linkedToUser: 'pending',
    usedForTracking: false,
    sharedWithThirdParty: false,
    thirdPartyProcessor: 'Email provider (manual)',
    retentionNote: 'Per support process',
    disclosureNote: 'Only if user contacts support',
    confidence: 'low',
    actionNeeded: 'Define support inbox retention policy',
  },
];

export const PRIVACY_THIRD_PARTY_PROCESSORS: CreviaPrivacyThirdPartyProcessor[] = [
  {
    id: 'revenuecat',
    name: 'RevenueCat',
    role: 'IAP entitlement sync',
    status: 'pending',
    dataTypes: ['Purchase status', 'Entitlement status', 'Anonymous customer id'],
    notes: 'Active when public SDK keys configured; no secret keys in client.',
  },
  {
    id: 'apple_storekit',
    name: 'Apple App Store / StoreKit',
    role: 'iOS purchase processing',
    status: 'pending',
    dataTypes: ['Purchase transactions'],
    notes: 'Sandbox/production via App Store Connect.',
  },
  {
    id: 'google_play_billing',
    name: 'Google Play Billing',
    role: 'Android purchase processing',
    status: 'pending',
    dataTypes: ['Purchase transactions'],
    notes: 'Sandbox/production via Play Console.',
  },
  {
    id: 'analytics_provider',
    name: 'Analytics provider',
    role: 'Structured event delivery',
    status: 'pending',
    dataTypes: ['App interactions', 'Analytics events'],
    notes: 'Current verify uses no-op tracker; real SDK TBD.',
  },
  {
    id: 'crash_reporting',
    name: 'Sentry (crash reporting)',
    role: 'Crash diagnostics',
    status: 'pending',
    dataTypes: ['Crash logs', 'Device technical context'],
    notes:
      'Code integration ready (@sentry/react-native); DSN/env + dashboard smoke pending. No PII/raw save/event body.',
  },
  {
    id: 'openai_external_ai',
    name: 'OpenAI / external AI',
    role: 'Runtime AI inference',
    status: 'not_used',
    dataTypes: [],
    notes: 'Not used in runtime unless explicitly integrated later.',
  },
];

export const APP_STORE_PRIVACY_ANSWER_DRAFTS: CreviaAppStorePrivacyAnswerDraft[] = [
  {
    dataCategory: 'Purchases',
    collected: 'yes',
    linkedToUser: 'pending',
    usedForTracking: false,
    purpose: 'App functionality — unlock full operation',
    notes: 'Via StoreKit / Play Billing + RevenueCat when IAP enabled',
    confidence: 'medium',
    needsManualConfirmation: true,
  },
  {
    dataCategory: 'App Interactions / Analytics',
    collected: 'yes',
    linkedToUser: false,
    usedForTracking: false,
    purpose: 'Analytics — product improvement',
    notes: 'Structured events only; no raw text',
    confidence: 'medium',
    needsManualConfirmation: true,
  },
  {
    dataCategory: 'Crash Data',
    collected: 'pending',
    linkedToUser: 'pending',
    usedForTracking: false,
    purpose: 'Diagnostics',
    notes: 'Crash SDK not integrated — answer pending or no',
    confidence: 'pending',
    needsManualConfirmation: true,
  },
  {
    dataCategory: 'Precise Location',
    collected: 'no',
    linkedToUser: false,
    usedForTracking: false,
    purpose: 'N/A',
    notes: 'In-game map is fictional; no GPS',
    confidence: 'high',
    needsManualConfirmation: false,
  },
  {
    dataCategory: 'User Content',
    collected: 'no',
    linkedToUser: false,
    usedForTracking: false,
    purpose: 'N/A',
    notes: 'No UGC / raw text collection',
    confidence: 'high',
    needsManualConfirmation: false,
  },
  {
    dataCategory: 'Identifiers',
    collected: 'pending',
    linkedToUser: 'pending',
    usedForTracking: false,
    purpose: 'Analytics / purchase restore',
    notes: 'Confirm RevenueCat anonymous id + analytics SDK fields',
    confidence: 'low',
    needsManualConfirmation: true,
  },
  {
    dataCategory: 'Diagnostics',
    collected: 'pending',
    linkedToUser: 'pending',
    usedForTracking: false,
    purpose: 'App functionality / analytics',
    notes: 'Device technical context; crash pending',
    confidence: 'pending',
    needsManualConfirmation: true,
  },
];

export const GOOGLE_PLAY_DATA_SAFETY_ANSWER_DRAFTS: CreviaGooglePlayDataSafetyAnswerDraft[] = [
  {
    dataType: 'Purchase history / in-app purchases',
    collected: 'yes',
    shared: true,
    processedEphemerally: false,
    requiredOrOptional: 'optional',
    purpose: 'App functionality',
    encryptedInTransit: true,
    userCanRequestDeletion: 'pending',
    notes: 'Google Play Billing + RevenueCat',
    needsManualConfirmation: true,
  },
  {
    dataType: 'App interactions / analytics',
    collected: 'yes',
    shared: 'pending',
    processedEphemerally: 'pending',
    requiredOrOptional: 'optional',
    purpose: 'Analytics',
    encryptedInTransit: true,
    userCanRequestDeletion: 'pending',
    notes: 'Structured events when SDK enabled',
    needsManualConfirmation: true,
  },
  {
    dataType: 'Crash logs',
    collected: 'pending',
    shared: 'pending',
    processedEphemerally: 'pending',
    requiredOrOptional: 'not_applicable',
    purpose: 'Diagnostics',
    encryptedInTransit: 'pending',
    userCanRequestDeletion: 'pending',
    notes: 'Only if crash SDK integrated',
    needsManualConfirmation: true,
  },
  {
    dataType: 'Precise location',
    collected: 'no',
    shared: false,
    processedEphemerally: 'not_applicable',
    requiredOrOptional: 'not_applicable',
    purpose: 'N/A',
    encryptedInTransit: 'not_applicable',
    userCanRequestDeletion: false,
    notes: 'Not collected',
    needsManualConfirmation: false,
  },
  {
    dataType: 'Contacts',
    collected: 'no',
    shared: false,
    processedEphemerally: 'not_applicable',
    requiredOrOptional: 'not_applicable',
    purpose: 'N/A',
    encryptedInTransit: 'not_applicable',
    userCanRequestDeletion: false,
    notes: 'Not collected',
    needsManualConfirmation: false,
  },
  {
    dataType: 'Photos / videos / files',
    collected: 'no',
    shared: false,
    processedEphemerally: 'not_applicable',
    requiredOrOptional: 'not_applicable',
    purpose: 'N/A',
    encryptedInTransit: 'not_applicable',
    userCanRequestDeletion: false,
    notes: 'Not collected',
    needsManualConfirmation: false,
  },
  {
    dataType: 'Health data',
    collected: 'no',
    shared: false,
    processedEphemerally: 'not_applicable',
    requiredOrOptional: 'not_applicable',
    purpose: 'N/A',
    encryptedInTransit: 'not_applicable',
    userCanRequestDeletion: false,
    notes: 'Not collected',
    needsManualConfirmation: false,
  },
  {
    dataType: 'Financial info (in-app)',
    collected: 'yes',
    shared: true,
    processedEphemerally: false,
    requiredOrOptional: 'optional',
    purpose: 'App functionality',
    encryptedInTransit: true,
    userCanRequestDeletion: 'pending',
    notes: 'Store-handled payment; app sees entitlement status only',
    needsManualConfirmation: true,
  },
];
