import type {
  SoftLaunchReadinessArea,
  SoftLaunchReadinessChecklistItem,
} from './softLaunchReadinessTypes';

export const SOFT_LAUNCH_READINESS_DOCS_PATH = 'docs/crevia-soft-launch-readiness.md';

export const SOFT_LAUNCH_PLAYER_FLOW_DOCS_PATH =
  'docs/crevia-player-flow-playtest-checklist.md';

export const SOFT_LAUNCH_IAP_DOCS_PATH = 'docs/crevia-iap-product-design.md';

export const SOFT_LAUNCH_ANALYTICS_DOCS_PATH = 'docs/crevia-analytics-event-schema.md';

export const SOFT_LAUNCH_FORBIDDEN_COPY_WORDS = [
  'premium',
  'satın al',
  'kilitli',
  'paywall',
  'ödeme yap',
  'reklamsız',
  'zorunlu',
] as const;

export const SOFT_LAUNCH_READINESS_AREAS: readonly SoftLaunchReadinessArea[] = [
  'save_migration',
  'first_session',
  'core_gameplay_loop',
  'post_pilot_offer',
  'full_main_operation',
  'season_end',
  'monetization_iap',
  'analytics',
  'performance',
  'qa_playtest',
  'store_review_copy',
  'debug_tools',
  'release_blockers',
] as const;

export const SOFT_LAUNCH_AREA_LABELS: Record<SoftLaunchReadinessArea, string> = {
  save_migration: 'Kayıt & migration',
  first_session: 'İlk oturum (Gün 1)',
  core_gameplay_loop: 'Çekirdek oyun döngüsü',
  post_pilot_offer: 'Post-pilot teklif',
  full_main_operation: 'Tam Ana Operasyon',
  season_end: 'Sezon sonu',
  monetization_iap: 'Monetization & IAP tasarımı',
  analytics: 'Analytics şeması',
  performance: 'Performans & selector',
  qa_playtest: 'QA & playtest',
  store_review_copy: 'Store review copy',
  debug_tools: 'Debug / dev araçları',
  release_blockers: 'Release blocker özeti',
};

export const SOFT_LAUNCH_EXPECTED_WARNS = [
  'real IAP SDK pending',
  'runtime analytics instrumentation pending',
  'manual playtest pending',
  'performance selector WARN',
  'pricing/store product IDs pending',
  'season 2 restart pending',
] as const;

export const SOFT_LAUNCH_PRE_SDK_CHECKLIST_IDS = [
  'pre_sdk.typecheck',
  'pre_sdk.full_loop',
  'pre_sdk.monetization_gate',
  'pre_sdk.iap_product_design',
  'pre_sdk.analytics_schema',
  'pre_sdk.no_blockers',
] as const;

export const SOFT_LAUNCH_PUBLIC_LAUNCH_CHECKLIST_IDS = [
  'launch.iap_sdk',
  'launch.analytics_instrumentation',
  'launch.manual_playtest',
  'launch.store_product_ids',
  'launch.pricing',
  'launch.release_smoke',
  'launch.dev_tools_hidden',
  'launch.privacy_copy',
] as const;

export const SOFT_LAUNCH_READINESS_CHECKLIST: SoftLaunchReadinessChecklistItem[] = [
  {
    id: 'save.save_version_23',
    area: 'save_migration',
    title: 'SAVE_VERSION 23',
    passCriteria: 'SAVE_VERSION sabit 23; typecheck ve full-loop uyumlu.',
    failSignal: 'SAVE_VERSION uyumsuz veya migration kırık.',
    manual: false,
  },
  {
    id: 'save.hydrate_v22',
    area: 'save_migration',
    title: 'v22/v23 hydrate',
    passCriteria: 'normalizePersistedSave eski sürümleri onarır.',
    failSignal: 'Hydrate null veya eksik monetization/advisor alanları.',
    manual: false,
  },
  {
    id: 'save.no_new_persist',
    area: 'save_migration',
    title: 'Yeni persist anahtarı yok',
    passCriteria: 'Bu patch persist şeması değiştirmez.',
    failSignal: 'Beklenmeyen yeni persist alanı.',
    manual: false,
  },
  {
    id: 'save.dev_reset_hidden',
    area: 'save_migration',
    title: 'Dev reset üretimde gizli',
    passCriteria: 'HubDevTools / PostPilotDevTools __DEV__ guard.',
    failSignal: 'Dev reset production build’de görünür.',
    manual: false,
  },
  {
    id: 'first.verify_first_10',
    area: 'first_session',
    title: 'verify:first-10-minutes PASS',
    passCriteria: 'Gün 1 hub sade; gelişmiş sistemler gizli.',
    failSignal: 'First 10 minutes verify FAIL.',
    manual: false,
  },
  {
    id: 'first.day1_hub_cards',
    area: 'first_session',
    title: 'Gün 1 hub yoğunluğu',
    passCriteria: 'En fazla 2 featured kart; kriz/micro/main op gizli.',
    failSignal: 'Gün 1 hub aşırı kalabalık.',
    manual: false,
  },
  {
    id: 'first.day1_report_short',
    area: 'first_session',
    title: 'Gün 1 rapor kısa',
    passCriteria: 'Report guard compact mod.',
    failSignal: 'Gün 1 rapor aşırı uzun.',
    manual: false,
  },
  {
    id: 'first.manual_playtest',
    area: 'first_session',
    title: 'Gün 1 insan playtest',
    passCriteria: 'Manuel checklist tamamlandı.',
    failSignal: 'Playtest yapılmadı.',
    manual: true,
  },
  {
    id: 'core.full_loop',
    area: 'core_gameplay_loop',
    title: 'verify:full-loop PASS',
    passCriteria: '7 günlük pilot simülasyonu crash/duplicate yok.',
    failSignal: 'Full loop FAIL.',
    manual: false,
  },
  {
    id: 'core.day_pipeline',
    area: 'core_gameplay_loop',
    title: 'Day pipeline FAIL yok',
    passCriteria: 'verify:day-pipeline PASS.',
    failSignal: 'Pipeline audit FAIL.',
    manual: false,
  },
  {
    id: 'core.assignment_layer',
    area: 'core_gameplay_loop',
    title: 'Assignment layer PASS',
    passCriteria: 'verify:assignment-layer PASS.',
    failSignal: 'Assignment verify FAIL.',
    manual: false,
  },
  {
    id: 'core.daily_planning',
    area: 'core_gameplay_loop',
    title: 'Daily planning PASS',
    passCriteria: 'verify:daily-planning PASS.',
    failSignal: 'Daily planning FAIL.',
    manual: false,
  },
  {
    id: 'core.operation_signals',
    area: 'core_gameplay_loop',
    title: 'Operation signals PASS',
    passCriteria: 'verify:operation-signals PASS.',
    failSignal: 'Signals verify FAIL.',
    manual: false,
  },
  {
    id: 'core.advisor',
    area: 'core_gameplay_loop',
    title: 'Advisor PASS',
    passCriteria: 'verify:advisor PASS.',
    failSignal: 'Advisor verify FAIL.',
    manual: false,
  },
  {
    id: 'offer.day7_route',
    area: 'post_pilot_offer',
    title: 'Gün 7 → post-pilot offer',
    passCriteria: 'Pilot tamamlanınca teklif rotası.',
    failSignal: 'Offer routing kırık.',
    manual: false,
  },
  {
    id: 'offer.limited_continue',
    area: 'post_pilot_offer',
    title: 'Sınırlı gündem',
    passCriteria: 'selectLimitedContinue limited access.',
    failSignal: 'Limited flow kırık.',
    manual: false,
  },
  {
    id: 'offer.mock_full',
    area: 'post_pilot_offer',
    title: 'Mock full access',
    passCriteria: 'mockPurchaseMainOperationPack full erişim.',
    failSignal: 'Mock purchase kırık.',
    manual: false,
  },
  {
    id: 'offer.monetization_gate',
    area: 'post_pilot_offer',
    title: 'verify:monetization-gate PASS',
    passCriteria: 'Monetization gate verify PASS.',
    failSignal: 'Monetization gate FAIL.',
    manual: false,
  },
  {
    id: 'offer.restore_cta',
    area: 'post_pilot_offer',
    title: 'Restore CTA',
    passCriteria: 'Erişimi Geri Yükle etiketi.',
    failSignal: 'Restore CTA uyumsuz.',
    manual: false,
  },
  {
    id: 'full.main_operation_full',
    area: 'full_main_operation',
    title: 'main_operation_full fazı',
    passCriteria: 'Full access ile tam operasyon.',
    failSignal: 'Full phase açılmıyor.',
    manual: false,
  },
  {
    id: 'full.limited_split',
    area: 'full_main_operation',
    title: 'Full / limited ayrımı',
    passCriteria: 'Limited ve full farklı yoğunluk.',
    failSignal: 'Ayrım oyuncuya görünmüyor.',
    manual: false,
  },
  {
    id: 'full.season_goals',
    area: 'full_main_operation',
    title: 'Sezon hedefleri',
    passCriteria: 'Full modda season goals aktif.',
    failSignal: 'Goals limited’de görünüyor.',
    manual: false,
  },
  {
    id: 'full.crisis_resources',
    area: 'full_main_operation',
    title: 'Kriz & saha kaynakları',
    passCriteria: 'Crisis desk, resources, micro decisions full’de.',
    failSignal: 'Sistemler full’de eksik.',
    manual: false,
  },
  {
    id: 'full.season_sim',
    area: 'full_main_operation',
    title: 'Full season simulation',
    passCriteria: 'WARN kabul; FAIL yok.',
    failSignal: 'Full season sim FAIL.',
    manual: false,
  },
  {
    id: 'season.verify_season_end',
    area: 'season_end',
    title: 'verify:season-end PASS',
    passCriteria: 'Sezon sonu değerlendirme modeli.',
    failSignal: 'Season end verify FAIL.',
    manual: false,
  },
  {
    id: 'season.report_card',
    area: 'season_end',
    title: 'Rapor kartı full’de',
    passCriteria: 'Full erişimde season end card.',
    failSignal: 'Kart görünmüyor.',
    manual: false,
  },
  {
    id: 'season.limited_hidden',
    area: 'season_end',
    title: 'Limited/pilot gizli',
    passCriteria: 'Pilot/limited’de season end yok.',
    failSignal: 'Yanlış modda kart.',
    manual: false,
  },
  {
    id: 'season.season2_restart',
    area: 'season_end',
    title: 'Sezon 2 restart',
    passCriteria: 'Henüz yok — WARN, blocker değil.',
    failSignal: 'N/A',
    manual: false,
  },
  {
    id: 'iap.product_design',
    area: 'monetization_iap',
    title: 'verify:iap-product-design PASS',
    passCriteria: 'One-time unlock ürün modeli hazır.',
    failSignal: 'IAP design FAIL.',
    manual: false,
  },
  {
    id: 'iap.entitlement_mapping',
    area: 'monetization_iap',
    title: 'Entitlement mapping',
    passCriteria: 'main_operation_full_access → full access.',
    failSignal: 'Mapping audit FAIL.',
    manual: false,
  },
  {
    id: 'iap.real_sdk',
    area: 'monetization_iap',
    title: 'Gerçek IAP SDK',
    passCriteria: 'Aşama 2 entegrasyonu tamamlandı.',
    failSignal: 'SDK yok (pre-SDK: WARN).',
    manual: false,
  },
  {
    id: 'iap.store_ids',
    area: 'monetization_iap',
    title: 'Store product ID',
    passCriteria: 'App Store / Play Console’da oluşturuldu.',
    failSignal: 'ID’ler sadece dokümanda.',
    manual: true,
  },
  {
    id: 'iap.pricing',
    area: 'monetization_iap',
    title: 'Fiyatlandırma',
    passCriteria: 'Fiyat finalize edildi.',
    failSignal: 'Fiyat bekliyor.',
    manual: true,
  },
  {
    id: 'analytics.schema',
    area: 'analytics',
    title: 'verify:analytics-events PASS',
    passCriteria: '60 event, 9 funnel, privacy PASS.',
    failSignal: 'Analytics schema FAIL.',
    manual: false,
  },
  {
    id: 'analytics.instrumentation',
    area: 'analytics',
    title: 'Runtime instrumentation',
    passCriteria: 'trackAnalyticsEvent UI’da bağlı.',
    failSignal: 'Instrumentation yok (WARN).',
    manual: false,
  },
  {
    id: 'analytics.dashboard',
    area: 'analytics',
    title: 'Analytics dashboard',
    passCriteria: 'Amplitude/Firebase/PostHog bağlı.',
    failSignal: 'Dashboard yok (WARN).',
    manual: false,
  },
  {
    id: 'perf.selectors',
    area: 'performance',
    title: 'verify:performance-selectors',
    passCriteria: 'FAIL yok; WARN izlenir.',
    failSignal: 'Selector audit FAIL.',
    manual: false,
  },
  {
    id: 'perf.low_end_device',
    area: 'performance',
    title: 'Düşük cihaz testi',
    passCriteria: 'Gerçek cihazda hub/report akıcı.',
    failSignal: 'Ciddi jank veya crash.',
    manual: true,
  },
  {
    id: 'qa.playtest_doc',
    area: 'qa_playtest',
    title: 'Playtest checklist dokümanı',
    passCriteria: 'crevia-player-flow-playtest-checklist.md mevcut.',
    failSignal: 'Doküman eksik.',
    manual: false,
  },
  {
    id: 'qa.manual_playtest',
    area: 'qa_playtest',
    title: 'Manuel playtest',
    passCriteria: '4 profil + gerçek cihaz tamamlandı.',
    failSignal: 'Playtest pending (WARN).',
    manual: true,
  },
  {
    id: 'qa.device_matrix',
    area: 'qa_playtest',
    title: 'Cihaz matrisi',
    passCriteria: 'iOS + Android smoke.',
    failSignal: 'Cihaz testi yok.',
    manual: true,
  },
  {
    id: 'copy.forbidden_words',
    area: 'store_review_copy',
    title: 'Yasak kelimeler',
    passCriteria: 'Oyuncu metinlerinde premium/satın al/kilitli yok.',
    failSignal: 'Yasak kelime bulundu.',
    manual: false,
  },
  {
    id: 'copy.offer_soft',
    area: 'store_review_copy',
    title: 'Offer copy yumuşak',
    passCriteria: 'Ana Operasyonu Aç / Sınırlı Gündem.',
    failSignal: 'Agresif paywall dili.',
    manual: false,
  },
  {
    id: 'copy.mock_hidden',
    area: 'store_review_copy',
    title: 'Mock/dev copy gizli',
    passCriteria: 'Production’da mock purchase görünmez.',
    failSignal: 'Dev copy sızıntısı.',
    manual: false,
  },
  {
    id: 'debug.hub_dev_guard',
    area: 'debug_tools',
    title: 'HubDevTools guard',
    passCriteria: '__DEV__ guard.',
    failSignal: 'Production’da görünür.',
    manual: false,
  },
  {
    id: 'debug.post_pilot_dev_guard',
    area: 'debug_tools',
    title: 'PostPilotDevTools guard',
    passCriteria: '__DEV__ guard.',
    failSignal: 'Production’da görünür.',
    manual: false,
  },
  {
    id: 'debug.mock_purchase_prod',
    area: 'debug_tools',
    title: 'Mock purchase production',
    passCriteria: 'Yalnızca dev/test.',
    failSignal: 'Store build’de mock CTA.',
    manual: false,
  },
  {
    id: 'blocker.typecheck',
    area: 'release_blockers',
    title: 'Typecheck',
    passCriteria: 'tsc --noEmit PASS.',
    failSignal: 'Typecheck FAIL → blocker.',
    manual: false,
  },
  {
    id: 'blocker.full_loop',
    area: 'release_blockers',
    title: 'Full loop',
    passCriteria: 'Pilot loop PASS.',
    failSignal: 'Full loop FAIL → blocker.',
    manual: false,
  },
  {
    id: 'blocker.privacy',
    area: 'release_blockers',
    title: 'Analytics privacy',
    passCriteria: 'Privacy audit PASS.',
    failSignal: 'Privacy FAIL → blocker.',
    manual: false,
  },
  {
    id: 'pre_sdk.typecheck',
    area: 'release_blockers',
    title: 'Pre-SDK: typecheck',
    passCriteria: 'npm run typecheck PASS.',
    failSignal: 'Typecheck fail.',
    manual: false,
  },
  {
    id: 'pre_sdk.full_loop',
    area: 'release_blockers',
    title: 'Pre-SDK: full-loop',
    passCriteria: 'verify:full-loop PASS.',
    failSignal: 'Loop fail.',
    manual: false,
  },
  {
    id: 'pre_sdk.monetization_gate',
    area: 'release_blockers',
    title: 'Pre-SDK: monetization-gate',
    passCriteria: 'verify:monetization-gate PASS.',
    failSignal: 'Gate fail.',
    manual: false,
  },
  {
    id: 'pre_sdk.iap_product_design',
    area: 'release_blockers',
    title: 'Pre-SDK: iap-product-design',
    passCriteria: 'verify:iap-product-design PASS.',
    failSignal: 'IAP design fail.',
    manual: false,
  },
  {
    id: 'pre_sdk.analytics_schema',
    area: 'release_blockers',
    title: 'Pre-SDK: analytics-events',
    passCriteria: 'verify:analytics-events PASS.',
    failSignal: 'Schema fail.',
    manual: false,
  },
  {
    id: 'launch.iap_sdk',
    area: 'release_blockers',
    title: 'Launch: IAP SDK',
    passCriteria: 'StoreKit/Billing/RevenueCat entegre.',
    failSignal: 'SDK eksik → launch blocker.',
    manual: false,
  },
  {
    id: 'launch.analytics_instrumentation',
    area: 'release_blockers',
    title: 'Launch: analytics instrumentation',
    passCriteria: 'Runtime event tracking aktif.',
    failSignal: 'Instrumentation yok → launch blocker.',
    manual: false,
  },
  {
    id: 'launch.manual_playtest',
    area: 'release_blockers',
    title: 'Launch: manual playtest',
    passCriteria: 'Checklist tamamlandı.',
    failSignal: 'Playtest yok → launch blocker.',
    manual: false,
  },
  {
    id: 'launch.store_product_ids',
    area: 'release_blockers',
    title: 'Launch: store product IDs',
    passCriteria: 'Console’da ürünler oluşturuldu.',
    failSignal: 'ID eksik.',
    manual: true,
  },
  {
    id: 'launch.pricing',
    area: 'release_blockers',
    title: 'Launch: pricing',
    passCriteria: 'Fiyat onaylandı.',
    failSignal: 'Fiyat yok.',
    manual: true,
  },
  {
    id: 'launch.release_smoke',
    area: 'release_blockers',
    title: 'Launch: release smoke',
    passCriteria: 'Release build smoke test PASS.',
    failSignal: 'Smoke fail.',
    manual: true,
  },
  {
    id: 'launch.dev_tools_hidden',
    area: 'release_blockers',
    title: 'Launch: dev tools hidden',
    passCriteria: 'Dev UI production’da yok.',
    failSignal: 'Dev tools görünür.',
    manual: false,
  },
  {
    id: 'launch.privacy_copy',
    area: 'release_blockers',
    title: 'Launch: privacy copy',
    passCriteria: 'Gizlilik metni gözden geçirildi.',
    failSignal: 'Privacy copy eksik.',
    manual: true,
  },
];
