import type {
  CreviaStoreScreenshotAssetRequirement,
  CreviaStoreScreenshotDeviceProfile,
  CreviaStoreScreenshotRequirement,
} from './storeScreenshotReadinessTypes';

export const STORE_SCREENSHOT_READINESS_DOCS_PATH = 'docs/crevia-store-screenshot-capture-plan.md';

export const STORE_SCREENSHOT_MIN_COUNT = 8;

export const STORE_SCREENSHOT_FALSE_CLAIM_PATTERNS = [
  'resmi belediye uygulaması',
  'gerçek şehir verisi',
  'gerçek zamanlı gps',
  'canlı takip',
  'kesin rota',
  'kesin çözüm',
  'para kazan',
  'garantili sonuç',
  'premium ile kazan',
  'satın almazsan oynayamazsın',
  'sezon finali',
  '14 gün bitti',
  'oyun sonu',
  'official municipality app',
  'real city data',
  'real-time gps',
  'live tracking',
  'exact route',
  'exact solution',
  'earn money',
  'guaranteed result',
  'win with premium',
  'can not play without purchase',
  'season finale',
  '14 days over',
  'game over',
] as const;

export const STORE_SCREENSHOT_PAYWALL_PRESSURE_PATTERNS = [
  'satın almazsan oynayamazsın',
  'hemen satın al yoksa',
  'son şans',
  'süren doluyor',
  'kaçırma',
  'zorunlu satın alma',
  'can not play without purchase',
  'buy now or else',
  'last chance',
  'time running out',
  'mandatory purchase',
] as const;

export const STORE_SCREENSHOT_GPS_CLAIM_PATTERNS = [
  'canlı gps',
  'gerçek zamanlı konum',
  'canlı navigasyon',
  'live gps',
  'real-time location',
  'live navigation',
  'gerçek zamanlı gps',
  'real-time gps',
] as const;

export const STORE_SCREENSHOT_OFFICIAL_CLAIM_PATTERNS = [
  'resmi belediye',
  'resmi kurum',
  'official municipality',
  'official agency',
  'government app',
] as const;

export const STORE_SCREENSHOT_OLD_SEASON_PATTERNS = [
  'sezon finali',
  'sezon sonu',
  '14 gün bitti',
  'oyun sonu',
  'season finale',
  'season end',
  '14 days over',
  'game over',
] as const;

export const STORE_SCREENSHOT_DEVICE_PROFILES: CreviaStoreScreenshotDeviceProfile[] = [
  {
    id: 'ios_small_phone',
    label: 'iPhone SE / iPhone 8 (4.7")',
    platform: 'ios',
    category: 'small_phone',
    storeSizePendingManualConfirmation: true,
    notes: 'App Store 4.7" set — confirm required sizes in App Store Connect.',
  },
  {
    id: 'ios_large_phone',
    label: 'iPhone 15 Pro Max / 16 Pro Max (6.7")',
    platform: 'ios',
    category: 'large_phone',
    storeSizePendingManualConfirmation: true,
    notes: 'App Store 6.7" set — required for all new submissions.',
  },
  {
    id: 'android_small_phone',
    label: 'Android compact (~5.4–5.8")',
    platform: 'android',
    category: 'small_phone',
    storeSizePendingManualConfirmation: true,
    notes: 'Play Store phone screenshots — confirm minimum resolution in Play Console.',
  },
  {
    id: 'android_medium_phone',
    label: 'Android standard (~6.1–6.5")',
    platform: 'android',
    category: 'medium_phone',
    storeSizePendingManualConfirmation: true,
    notes: 'Play Store phone screenshots — primary device profile.',
  },
  {
    id: 'android_low_mid_device',
    label: 'Android low-mid (~5.5–6.0" / lower RAM)',
    platform: 'android',
    category: 'low_mid_device',
    storeSizePendingManualConfirmation: true,
    notes: 'Performance baseline — verify UI renders without layout overflow.',
  },
  {
    id: 'tablet_optional',
    label: 'iPad / Android tablet (optional)',
    platform: 'ios',
    category: 'tablet',
    storeSizePendingManualConfirmation: true,
    notes: 'Optional for soft launch; recommended for full launch listing.',
  },
];

export const STORE_SCREENSHOT_REQUIREMENTS: CreviaStoreScreenshotRequirement[] = [
  {
    id: 'ss_hub',
    screenName: 'Hub / Merkez',
    platform: 'both',
    deviceProfile: 'ios_large_phone',
    targetDay: 'Day 4 or Day 8+',
    gameStateRequirement: 'Hub open-ended card visible; no carry-over duplicate; no crowded crisis/devtools state',
    requiredVisibleCards: ['daily_plan_card', 'hub_open_ended_card'],
    forbiddenVisibleCards: ['devtools_panel', 'crisis_overload_overlay'],
    capturePurpose: 'Show main operational hub and daily planning entry',
    copyOverlayAllowed: true,
    overlayCopyDraft: 'Mahalle operasyon merkezi',
    riskNotes: 'No official municipality logo or agency claim',
    status: 'pending',
    blockerIfMissing: true,
  },
  {
    id: 'ss_event_inspect',
    screenName: 'Event inspect + plan',
    platform: 'both',
    deviceProfile: 'ios_large_phone',
    targetDay: 'Day 3+',
    gameStateRequirement: 'Active event inspect/plan flow; CTA visible; no text overflow; decision card premium visible',
    requiredVisibleCards: ['event_detail_card', 'decision_cta'],
    forbiddenVisibleCards: ['devtools_panel'],
    capturePurpose: 'Demonstrate event inspection and planning phase',
    copyOverlayAllowed: true,
    overlayCopyDraft: 'Olay inceleme ve planlama',
    riskNotes: 'No exaggerated outcome promises in overlay',
    status: 'pending',
    blockerIfMissing: true,
  },
  {
    id: 'ss_dispatch',
    screenName: 'Dispatch / active route',
    platform: 'both',
    deviceProfile: 'ios_large_phone',
    targetDay: 'Day 3+',
    gameStateRequirement: 'Team/vehicle selection visible; active route strip visible; no GPS/live tracking claim',
    requiredVisibleCards: ['dispatch_team_selection', 'active_route_strip'],
    forbiddenVisibleCards: ['gps_navigation_overlay'],
    capturePurpose: 'Show field dispatch and operational route preview',
    copyOverlayAllowed: true,
    overlayCopyDraft: 'Saha yönlendirme',
    riskNotes: 'No GPS / live navigation claim — simulation only',
    status: 'pending',
    blockerIfMissing: true,
  },
  {
    id: 'ss_map_district',
    screenName: 'Map district intelligence',
    platform: 'both',
    deviceProfile: 'ios_large_phone',
    targetDay: 'Day 4+',
    gameStateRequirement: 'Selected district; trust/memory/operation intelligence at reasonable density; route accent optional; crisis overlay simple if present',
    requiredVisibleCards: ['map_district_overlay', 'intelligence_strip'],
    forbiddenVisibleCards: ['real_map_data_overlay'],
    capturePurpose: 'Show map-based district intelligence and neighborhood view',
    copyOverlayAllowed: true,
    overlayCopyDraft: 'Mahalle istihbarat haritası',
    riskNotes: 'No real map data or live traffic claim',
    status: 'pending',
    blockerIfMissing: true,
  },
  {
    id: 'ss_operation_result',
    screenName: 'Operation result',
    platform: 'both',
    deviceProfile: 'ios_large_phone',
    targetDay: 'Day 3+',
    gameStateRequirement: 'Result hero visible; systems echo strip; map before/after impact; tomorrow/carry-over hint',
    requiredVisibleCards: ['result_hero_card', 'systems_echo_strip'],
    forbiddenVisibleCards: ['devtools_panel'],
    capturePurpose: 'Show operation outcome and system feedback',
    copyOverlayAllowed: true,
    overlayCopyDraft: 'Operasyon sonucu',
    riskNotes: 'No guaranteed result / exact solution claim',
    status: 'pending',
    blockerIfMissing: true,
  },
  {
    id: 'ss_end_of_day_report',
    screenName: 'End-of-day report',
    platform: 'both',
    deviceProfile: 'ios_large_phone',
    targetDay: 'Day 3+',
    gameStateRequirement: 'Report hero; systems integration card; tomorrow preview; advisor comment; watch for scroll overflow at top',
    requiredVisibleCards: ['report_hero', 'systems_integration_card', 'tomorrow_preview'],
    forbiddenVisibleCards: ['devtools_panel'],
    capturePurpose: 'Show daily report summary and systems integration',
    copyOverlayAllowed: true,
    overlayCopyDraft: 'Gün sonu raporu',
    riskNotes: 'Avoid overly long scroll start — capture top portion cleanly',
    status: 'pending',
    blockerIfMissing: true,
  },
  {
    id: 'ss_profile_career',
    screenName: 'Profile / career',
    platform: 'both',
    deviceProfile: 'ios_large_phone',
    targetDay: 'Day 4+',
    gameStateRequirement: 'Authority card; career showcase; badge showcase; next unlock / permission chip',
    requiredVisibleCards: ['authority_card', 'career_showcase', 'badge_section'],
    forbiddenVisibleCards: ['devtools_panel'],
    capturePurpose: 'Show career progression and badge/authority system',
    copyOverlayAllowed: true,
    overlayCopyDraft: 'Kariyer vitrini',
    riskNotes: 'No real profession certification claim',
    status: 'pending',
    blockerIfMissing: true,
  },
  {
    id: 'ss_post_pilot_offer',
    screenName: 'Post-pilot offer / main operation preview',
    platform: 'both',
    deviceProfile: 'ios_large_phone',
    targetDay: 'Day 8+',
    gameStateRequirement: 'Day 8+ value proposition; no pushy paywall language; IAP product price must be real or screenshot rejected',
    requiredVisibleCards: ['post_pilot_value_card'],
    forbiddenVisibleCards: ['placeholder_price_tag', 'aggressive_paywall_cta'],
    capturePurpose: 'Show post-pilot offer and full operation value preview',
    copyOverlayAllowed: false,
    riskNotes: 'IAP price must come from store; if placeholder shown, capture must be rejected. No paywall pressure language.',
    status: 'pending',
    blockerIfMissing: true,
  },
];

export const STORE_SCREENSHOT_ASSET_CHECKLIST: CreviaStoreScreenshotAssetRequirement[] = [
  {
    id: 'asset_app_icon',
    assetType: 'App icon (1024×1024 master)',
    requiredFor: 'both',
    status: 'pending',
    sourceFile: 'assets/images/icon.png',
    exportStatus: 'pending',
    manualConfirmationNeeded: true,
    blockerIfMissing: true,
  },
  {
    id: 'asset_adaptive_android_icon',
    assetType: 'Adaptive Android icon (foreground + background)',
    requiredFor: 'android',
    status: 'pending',
    sourceFile: 'assets/images/adaptive-icon.png',
    exportStatus: 'pending',
    manualConfirmationNeeded: true,
    blockerIfMissing: true,
  },
  {
    id: 'asset_ios_icon_source',
    assetType: 'iOS icon source (App Store Connect)',
    requiredFor: 'ios',
    status: 'pending',
    sourceFile: 'assets/images/icon.png',
    exportStatus: 'pending',
    manualConfirmationNeeded: true,
    blockerIfMissing: true,
  },
  {
    id: 'asset_feature_graphic',
    assetType: 'Play Store feature graphic (1024×500)',
    requiredFor: 'android',
    status: 'pending',
    sourceFile: '',
    exportStatus: 'pending',
    manualConfirmationNeeded: true,
    blockerIfMissing: true,
  },
  {
    id: 'asset_ios_screenshots',
    assetType: 'App Store screenshots',
    requiredFor: 'ios',
    status: 'pending',
    sourceFile: '',
    exportStatus: 'pending',
    manualConfirmationNeeded: true,
    blockerIfMissing: true,
  },
  {
    id: 'asset_play_screenshots',
    assetType: 'Play Store screenshots',
    requiredFor: 'android',
    status: 'pending',
    sourceFile: '',
    exportStatus: 'pending',
    manualConfirmationNeeded: true,
    blockerIfMissing: true,
  },
  {
    id: 'asset_promo_graphic',
    assetType: 'Optional promo graphic',
    requiredFor: 'android',
    status: 'not_applicable',
    sourceFile: '',
    exportStatus: 'not_applicable',
    manualConfirmationNeeded: false,
    blockerIfMissing: false,
  },
  {
    id: 'asset_tablet_screenshots',
    assetType: 'Optional tablet screenshots',
    requiredFor: 'both',
    status: 'not_applicable',
    sourceFile: '',
    exportStatus: 'not_applicable',
    manualConfirmationNeeded: false,
    blockerIfMissing: false,
  },
  {
    id: 'asset_screenshot_state_docs',
    assetType: 'Screenshot source state documentation',
    requiredFor: 'both',
    status: 'pending',
    sourceFile: STORE_SCREENSHOT_READINESS_DOCS_PATH,
    exportStatus: 'pending',
    manualConfirmationNeeded: false,
    blockerIfMissing: false,
  },
  {
    id: 'asset_export_folder',
    assetType: 'Asset export folder placeholder',
    requiredFor: 'both',
    status: 'pending',
    sourceFile: '',
    exportStatus: 'pending',
    manualConfirmationNeeded: true,
    blockerIfMissing: false,
  },
];

